### ISSUE TITLE
Gradle - Stack level too deep (SystemStackError)

### ISSUE THREAD

**Issue by wartingep** [dependabot/dependabot-core#10125]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

gradle

### dependabot.yml content

version: 2
registries:
  drivers-android-mono:
    type: maven-repository
    url: https://maven.pkg.github.com/foo/bar1
    username: ep-productivity-robot
    password: ${{secrets.xxx}}
  rally-android:
    type: maven-repository
    url: https://maven.pkg.github.com/foo/bar2
    username: ep-productivity-robot
    password: ${{secrets.xxx}}
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Stockholm"
    open-pull-requests-limit: 10
    registries: "*"
  - package-ecosystem: "gradle"
    directory: "foo/bar"
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Stockholm"
    registries: "*"
  - package-ecosystem: "github-actions"
    directory: ""
    schedule:
      interval: "weekly"
      time: "05:00"
      timezone: "Europe/Stockholm"
    registries: "*"
    open-pull-requests-limit: 10

### What you expected to see, versus what you actually saw

Expected to see pr updates but receive "Dependabot encountered an unknown error"

updater | 
  proxy | 2024/07/02 06:50:32 [002] GET https://github.com:443/foo/bar/info/refs?service=git-upload-pack
  proxy | 2024/07/02 06:50:32 [002] * authenticating git server request (host: github.com)
  proxy | 2024/07/02 06:50:33 [002] 200 https://github.com:443/foo/bar/info/refs?service=git-upload-pack
  proxy | 2024/07/02 06:50:33 [004] POST https://github.com:443/foo/bar/git-upload-pack
  proxy | 2024/07/02 06:50:33 [004] * authenticating git server request (host: github.com)
  proxy | 2024/07/02 06:50:33 [004] 200 https://github.com:443/foo/bar/git-upload-pack
  proxy | 2024/07/02 06:50:33 [006] POST https://github.com:443/foo/bar/git-upload-pack
  proxy | 2024/07/02 06:50:33 [006] * authenticating git server request (host: github.com)
  proxy | 2024/07/02 06:50:33 [006] 200 https://github.com:443/foo/bar/git-upload-pack
updater | /usr/local/lib/ruby/3.3.0/pathname.rb:51:in `chop_basename': stack level too deep (SystemStackError)
updater | 	from /usr/local/lib/ruby/3.3.0/pathname.rb:110:in `cleanpath_aggressive'
updater | 	from /usr/local/lib/ruby/3.3.0/pathname.rb:98:in `cleanpath'
updater | 	from /home/dependabot/gradle/lib/dependabot/gradle/file_fetcher.rb:73:in `clean_join'
updater | 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:968:in `bind_call'
updater | 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:968:in `block in create_validator_method_medium1'
updater | 	from /home/dependabot/gradle/lib/dependabot/gradle/file_fetcher.rb:149:in `block in find_first'
updater | 	from /home/dependabot/gradle/lib/dependabot/gradle/file_fetcher.rb:149:in `map'
updater | 	from /home/dependabot/gradle/lib/dependabot/gradle/file_fetcher.rb:149:in `find_first'
updater | 	 ... 9350 levels...
updater | 	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:22:in `perform_job'
updater | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 	from bin/fetch_files.rb:37:in `<main>'
updater | time="2024-07-02T06:50:41Z" level=info msg="task complete" container_id=job-850370462-file-fetcher exit_code=1 job_id=850370462 step=fetcher
updater | time="2024-07-02T06:50:42Z" level=warning msg="updater container failed" error="waiting for fetcher: bad response from container: 1" exit_code=1 job_id=850370462

**Comment by jacobhampel** [comment]
Is there an expected timeline availble when this issue will be fixed?

**Comment by embeddedeml** [comment]
+1

**Comment by jacobhampel** [comment]
I double checked our stacktrace.
It looks a bit different but very similar:

```
updater | /home/dependabot/common/lib/dependabot/dependency_file.rb:131:in `path': stack level too deep (SystemStackError)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
	from /home/dependabot/common/lib/dependabot/dependency_file.rb:136:in `realpath'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
	from /home/dependabot/common/lib/dependabot/dependency_file.rb:100:in `initialize'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:167:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
	 ... 93[47](https://github1.vg.vector.int/xnb/vcharm-backend/actions/runs/3191098/job/9991913#step:4:49) levels...
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.4.0/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:22:in `perform_job'
	from /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
	from bin/fetch_files.rb:37:in `<main>'
```

**Comment by Siedlerchr** [comment]
We got the same now in JabRef with a multi-module project.

Edit// 
Workaround, we explicitly specified the subdirectories for our dependencies :
https://github.com/JabRef/jabref/blob/main/.github/dependabot.yml


```
 updater | 2025/06/02 18:58:48 INFO <job_1026613264> Started process PID: 1342 with command: {} git rev-parse HEAD {}
updater | 2025/06/02 18:58:48 INFO <job_1026613264> Process PID: 1342 completed with status: pid 1342 exit 0
2025/06/02 18:58:48 INFO <job_1026613264> Total execution time: 0.0 seconds
updater | /home/dependabot/common/lib/dependabot/errors.rb:410:in `filter_sensitive_data': stack level too deep (SystemStackError)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:108:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:108:in `block in create_validator_method_fast1'
	from /home/dependabot/common/lib/dependabot/errors.rb:405:in `sanitize_message'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:968:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:968:in `block in create_validator_method_medium1'
	from /home/dependabot/common/lib/dependabot/errors.rb:391:in `initialize'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:179:in `bind_call'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:179:in `validate_call_skip_block_type'
	 ... 9348 levels...
	from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:22:in `perform_job'
	from /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
	from bin/fetch_files.rb:35:in `<main>'
Failure running container 7ef6fa6bdca3c8158513b9e2af345e4668efb2333b712069ee95c5de2b100f71
Cleaned up container 7ef6fa6bdca3c8158513b9e2af345e4668efb2333b712069ee95c5de2b100f71
  proxy | 2025/06/02 18:58:52 0/12 calls cached (0%)
2025/06/02 18:58:52 Posting metrics to remote API endpoint
```

**Comment by v-thavaahariharangit** [comment]
I attempted to recreate the problem

`.github/dependabot.yml`
```
version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/artifactory/"
    schedule:
      interval: "weekly"
    registries: "*"
  - package-ecosystem: "gradle" # See documentation for possible values
    directory: "/git/" # Location of package manifests
    schedule:
      interval: "weekly"
    registries: "*"

registries: 
  maven-artifactory:
      type: "maven-repository"
      url: "https://jfrogghdemo.jfrog.io/artifactory/e2e-tests-dependabot-maven-repo/"
      username: "thavaahariharangit@github.com"  # Store username in GitHub Secrets
      password: "${{ secrets.JFROG_TOKEN }}"
  github:
    type: "maven-repository"
    url: "https://maven.pkg.github.com/dsp-testing/maven-repo-to-publish"
    username: "x-access-token"
    password: "${{secrets.GIT_TOKEN}}"
```

### Contents of `artifactory` folder
`artifactory/build.gradle`
```
dependencies {
    implementation("commons-logging:commons-logging:1.0")
}
```
`artifactory/settings.xml`
```
dependencyResolutionManagement {
    repositories {
        maven {
            url = uri("https://jfrogghdemo.jfrog.io/artifactory/e2e-tests-dependabot-maven-repo/")
            credentials {
                username = "thavaahariharangit@github.com"
                password = "${{ secrets.JFROG_TOKEN }}"
            }
        }
    }
}
```

### Contents of `git` folder
`git/build.gradle`
```
dependencies {
    implementation("com.dsp.testing:maven-repo-to-publish:1.0.1")
}
```
`git/settings.xml`
```
dependencyResolutionManagement {
    repositories {
        maven {
            url = uri("https://maven.pkg.github.com/dsp-testing/maven-repo-to-publish")
            credentials {
                username = "thavaahariharangit@github.com"
                password = "${{ secrets.GIT_TOKEN }}"
            }
        }
    }
}
```

PR's generated as expected
<img width="1623" height="493" alt="Image" src="https://github.com/user-attachments/assets/849afc81-eadf-455d-976c-50f4f081baec" />

With this note (unable to create the issue with the description provided on the issue.) I am closing this ticket. 

Please feel free to reopen with the steps to reproduce.
