### ISSUE TITLE
Azure Service principal Access token fails where PAT works

### ISSUE THREAD

**Issue by JaeTLDR** [dependabot/dependabot-core#10238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### What you expected to see, versus what you actually saw

When running the Docker image (generated with dependabot-script) with a pat token PR s are generated against the repo, however when running with a Service principal Access Token the dependabot responds with invalid  repository.  

 expected output (using PAT)
 ```
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:44: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/response/raise_error.rb:14:in `on_complete': GET https://api.github.com/repos/twbs/bootstrap/contents/: 403 - API rate limit exceeded for 20.28.19.185. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting (Octokit::TooManyRequests)
	from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/middleware.rb:18:in `block in call'
	from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/response.rb:42:in `on_complete'
	from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/middleware.rb:17:in `call'
	from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
	from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
	from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/rack_builder.rb:153:in `build_response'
	from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/connection.rb:445:in `run_request'
	from /home/dependabot/dependabot-script/.bundle/gems/faraday-2.3.0/lib/faraday/connection.rb:200:in `get'
	from /home/dependabot/dependabot-script/.bundle/gems/sawyer-0.9.2/lib/sawyer/agent.rb:99:in `call'
	from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/connection.rb:156:in `request'
	from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/connection.rb:19:in `get'
	from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/client/contents.rb:40:in `contents'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:101:in `public_send'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:101:in `block in method_missing'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:121:in `retry_connection_failures'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:98:in `method_missing'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:239:in `fetch_github_file_list'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:220:in `fetch_dependency_file_list'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:215:in `dependency_file_list'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:113:in `changelog_from_ref'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:101:in `default_branch_changelog'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:64:in `changelog'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base/changelog_finder.rb:33:in `changelog_url'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/metadata_finders/base.rb:40:in `changelog_url'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:341:in `changelog_url'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:306:in `metadata_links_for_dep'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:293:in `metadata_links'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator/message_builder.rb:56:in `commit_message'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator.rb:172:in `azure_creator'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/pull_request_creator.rb:104:in `create'
	from ./generic-update-script.rb:233:in `block in <main>'
	from ./generic-update-script.rb:176:in `each'
	from ./generic-update-script.rb:176:in `<main>'
Running with options: {}
Fetching nuget dependency files for <ORGANISATION>/<PROJECT>/_git/<REPO>
Parsing dependencies information
  - Updating AspNet.ScriptManager.bootstrap (from 3.4.1)… submitted
  - Updating AspNet.ScriptManager.jQuery (from 3.4.1)… submitted
  - Updating bootstrap (from 3.4.1)…
```
Actual output (using service principal Access Token)
```
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:29: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:35: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:44: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
/usr/local/lib/ruby/gems/3.1.0/gems/bundler-1.17.3/lib/bundler/shared_helpers.rb:118: warning: Pathname#untaint is deprecated and will be removed in Ruby 3.2.
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
/home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/repository.rb:92:in `raise_invalid_repository!': "<ORGANISATION>/<PROJECT>/_git/<REPO>" is invalid as a repository identifier. Use the user/repo (String) format, or the repository ID (Integer), or a hash containing :repo and :user keys. (Octokit::InvalidRepository)
	from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/repository.rb:36:in `initialize'
	from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/repository.rb:58:in `new'
	from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/repository.rb:58:in `path'
	from /home/dependabot/dependabot-script/.bundle/gems/octokit-5.2.0/lib/octokit/client/repositories.rb:27:in `repository'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:101:in `public_send'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:101:in `block in method_missing'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:121:in `retry_connection_failures'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:98:in `method_missing'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/clients/github_with_retries.rb:72:in `fetch_default_branch'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/file_fetchers/base.rb:478:in `default_branch_for_repo'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/file_fetchers/base.rb:74:in `commit'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/file_fetchers/base.rb:389:in `_full_specification_for'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/file_fetchers/base.rb:179:in `_fetch_repo_contents'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/file_fetchers/base.rb:166:in `repo_contents'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-nuget-0.209.0/lib/dependabot/nuget/file_fetcher.rb:184:in `csproj_file'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-nuget-0.209.0/lib/dependabot/nuget/file_fetcher.rb:55:in `project_files'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-nuget-0.209.0/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
	from /home/dependabot/dependabot-script/.bundle/gems/dependabot-common-0.209.0/lib/dependabot/file_fetchers/base.rb:68:in `files'
	from ./generic-update-script.rb:160:in `<main>'
Running with options: {}
Fetching nuget dependency files for <ORGANISATION>/<PROJECT>/_git/<REPO>
```

**Comment by abdulapopoola** [comment]
@JaeTLDR ; Dependabot doesn't currently support Azure service principal access tokens. Can you please file a new feature request with the requisite details so we can take a look at it?
