### ISSUE TITLE
Dependabot not handling environment variables with yarn

### ISSUE THREAD

**Issue by bbangert** [dependabot/dependabot-core#10244]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

3.3.0

### dependabot.yml content

https://github.com/mozilla/fxa/blob/main/.github/dependabot.yml

### Updated dependency

Any of them

### What you expected to see, versus what you actually saw

Expected to see updates get processed, instead I see this issue:
```

Dependabot could not run Invalid .yarnrc.yml file to update your dependencies due to a configuration error

Please review your Invalid .yarnrc.yml file setup. Dependabot encountered the following error when running it:

Internal Error: Invalid value, expected one of classic, hardlinks-local, hardlinks-global in [38;5;170m/home/dependabot/dependabot-updater/repo/.yarnrc.yml[39m (in [38;5;170m/home/dependabot/dependabot-updater/repo/.yarnrc.yml[39m)
    at jk (/home/dependabot/.cache/node/corepack/yarn/3.3.0/yarn.js:391:17670)
    at Vk (/home/dependabot/.cache/node/corepack/yarn/3.3.0/yarn.js:391:16917)
    at Ga.use (/home/dependabot/.cache/node/corepack/yarn/3.3.0/yarn.js:391:24982)
    at Ga.useWithSource (/home/dependabot/.cache/node/corepack/yarn/3.3.0/yarn.js:391:24229)
    at Ga.find (/home/dependabot/.cache/node/corepack/yarn/3.3.0/yarn.js:391:22355)
    at async i (/home/dependabot/.cache/node/corepack/yarn/3.3.0/yarn.js:446:10711)
    at async i (/home/dependabot/.cache/node/corepack/yarn/3.3.0/yarn.js:446:11098)
    at async t (/home/dependabot/.cache/node/corepack/yarn/3.3.0/yarn.js:446:10278)

```

This file is using an environment variable with fallback, which works when running this version of yarn locally. I'm unable to run yarn in a manner that reproduces this error.

### Native package manager behavior

yarn runs as expected

### Smallest manifest that reproduces the issue

.yarnrc file is here:
https://github.com/mozilla/fxa/blob/main/.yarnrc.yml

**Comment by mrginglymus** [comment]
This (env var with fallback) was working for me on `dependabot-updater-npm:v2.0.20231208161417`, but stopped working on `dependabot-updater-npm:v2.0.20240628234530`

**Comment by dariodevito** [comment]
I am seeing the same issue.

```
updater | 2024/12/02 16:00:20 INFO <job_925975210> Running package manager command: corepack yarn --version
updater | 2024/12/02 16:00:20 ERROR <job_925975210> Error running package manager command: corepack yarn --version, Error: Usage Error: Environment variable not found ({redacted}) in /home/dependabot/dependabot-updater/repo/.yarnrc.yml (in /home/dependabot/dependabot-updater/repo/.yarnrc.yml)

Yarn Package Manager - 3.8.3
```

I am unable to work around the issue as the secret that I am trying to inject is a PAT token used by yarn to authenticate with a private registry.

**Comment by mattwebbio** [comment]
We're also seeing this behavior:
> Dependabot could not run Invalid .yarnrc.yml file to update your dependencies due to a configuration error. Because of this, Dependabot cannot update this pull request.

Our `.yarnrc.yml` includes the following:
```
...
nmHoistingLimits: "${YARN_NM_HOISTING_LIMITS:-workspaces}"
nmMode: "${YARN_NM_MODE:-hardlinks-global}"
...
```

**Comment by dariodevito** [comment]
Any update on this?

I know we can set yarn private registry details in `dependabot.yaml` but it's common to use yarnrc files outside of dependabot workflows. (Other CI/CD workflows, local, etc).
