### ISSUE TITLE
version is nil, crashes humanized_version

### ISSUE THREAD

**Issue by bmulholland** [dependabot/dependabot-core#10312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pnpm, **just switched from yarn**

### Manifest location and content before the Dependabot update

package.json

### What you expected to see, versus what you actually saw

 updater | 2024/07/30 09:54:19 INFO <job_862454551> Creating a pull request for 'all-packages'
  proxy | 2024/07/30 09:54:19 [739] POST /update_jobs/862454551/record_update_job_unknown_error
  proxy | 2024/07/30 09:54:19 [739] 204 /update_jobs/862454551/record_update_job_unknown_error
  proxy | 2024/07/30 09:54:19 [741] POST /update_jobs/862454551/record_update_job_error
  proxy | 2024/07/30 09:54:19 [741] 204 /update_jobs/862454551/record_update_job_error
  proxy | 2024/07/30 09:54:19 [743] POST /update_jobs/862454551/increment_metric
  proxy | 2024/07/30 09:54:19 [743] 204 /update_jobs/862454551/increment_metric
  proxy | 2024/07/30 09:54:19 [745] POST /update_jobs/862454551/record_update_job_unknown_error
  proxy | 2024/07/30 09:54:20 [745] 204 /update_jobs/862454551/record_update_job_unknown_error
updater | 2024/07/30 09:54:20 ERROR <job_862454551> Error processing job (TypeError)
2024/07/30 09:54:20 ERROR <job_862454551> Passed `nil` into T.must
2024/07/30 09:54:20 ERROR <job_862454551> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/_types.rb:222:in `must'
2024/07/30 09:54:20 ERROR <job_862454551> /home/dependabot/common/lib/dependabot/dependency.rb:231:in `humanized_version'
2024/07/30 09:54:20 ERROR <job_862454551> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'
2024/07/30 09:54:20 ERROR <job_862454551> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `block in create_validator_method_medium0'

This line, from the logs above, looks suspicious:

`updater | 2024/07/30 09:54:16 INFO <job_862454551> Skipping vue-infinite-loading as it has already been updated to `

(I didn't cut that off, that's the end of the line)

package.json for that is
    "vue-infinite-loading": "github:nvitius/vue-infinite-loading#next",

### Images of the diff or a link to the PR, issue, or logs

https://github.com/recitalsoftware/recital-frontend/actions/runs/10160118930/job/28095785090

**Comment by bmulholland** [comment]
Confirmed it was `"vue-infinite-loading": "github:nvitius/vue-infinite-loading#next",`

I changed to the published version `next` and that fixed dependabot. So the above is a reliable repro.

**Comment by bmulholland** [comment]
Personally I've solved the problem as mentioned. Behaviour-wise, I think anything other than "doesn't crash" is probably good enough :)
