### ISSUE TITLE
Updates to dotnet-tools.json with white-space lines cause "Passed `nil` into T.must" errors

### ISSUE THREAD

**Issue by rhyskoedijk** [dependabot/dependabot-core#10323]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Package manager version

v0.267.0

### Manifest location and content before the Dependabot update

https://github.com/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test/blob/main/DotNetTools/.config/dotnet-tools.json

### dependabot.yml content

N/A, updated using dry-run.rb

### Updated dependency

dotnet-ef from 7.0.8 to 8.0.7

### What you expected to see, versus what you actually saw

**Expected:**
dotnet-ef should be updated to 8.0.7 in dotnet-tools.json.

**Actual:**
Error is thrown, dependency is not updated.
```log
=== dotnet-ef (7.0.8)
 => checking for updates 2/2
🌍 --> GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/index.json
🌍 <-- 200 https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/index.json
🌍 --> GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/0.0.1-alpha/3.1.28.json
🌍 <-- 200 https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/0.0.1-alpha/3.1.28.json
🌍 --> GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/3.1.29/6.0.23.json
🌍 <-- 200 https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/3.1.29/6.0.23.json
🌍 --> GET https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/6.0.24/9.0.0-preview.6.24327.4.json
🌍 <-- 200 https://api.nuget.org/v3/registration5-gz-semver2/dotnet-ef/page/6.0.24/9.0.0-preview.6.24327.4.json
I, [2024-07-31T11:39:30.550657 #4598]  INFO -- : Filtered out 59 pre-release versions
🌍 --> GET https://api.nuget.org/v3-flatcontainer/dotnet-ef/7.0.8/dotnet-ef.nuspec
🌍 <-- 200 https://api.nuget.org/v3-flatcontainer/dotnet-ef/7.0.8/dotnet-ef.nuspec
🌍 --> GET https://api.nuget.org/v3-flatcontainer/dotnet-ef/8.0.7/dotnet-ef.nuspec
🌍 <-- 200 https://api.nuget.org/v3-flatcontainer/dotnet-ef/8.0.7/dotnet-ef.nuspec
 => latest available version is 8.0.7
 => latest allowed version is 7.0.8
 => requirements to unlock: all
 => requirements update strategy: 
Finding updated dependencies for dotnet-ef.
🌍 --> GET https://api.nuget.org/v3-flatcontainer/dotnet-ef/8.0.7/dotnet-ef.nuspec
🌍 <-- 200 https://api.nuget.org/v3-flatcontainer/dotnet-ef/8.0.7/dotnet-ef.nuspec
running NuGet updater:
/opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/tmp/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test --solution-or-project /home/dependabot/tmp/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test/DotNetTools/CaseManagement/Common/Common.csproj --dependency dotnet-ef --new-version 8.0.7 --previous-version 7.0.8 --result-output-path /tmp/update-result.json --verbose
  Updating [DotNetTools/.config/dotnet-tools.json] file.
    Saved [DotNetTools/.config/dotnet-tools.json].
  No global.json file found.
Running for project file [DotNetTools/CaseManagement/Common/Common.csproj]
Updating project [/home/dependabot/tmp/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test/DotNetTools/CaseManagement/Common/Common.csproj]
  Running for SDK-style project
    Package [dotnet-ef] Does not exist as a dependency in [/home/dependabot/tmp/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test/DotNetTools/CaseManagement/Common/Common.csproj].
Update complete.
  Writing update result to [/tmp/update-result.json].
I, [2024-07-31T11:39:33.925840 #4598]  INFO -- : update result: {
  "ErrorType": null,
  "ErrorDetails": null
}
Fixing mismatched Windows line endings for [.config/dotnet-tools.json].
/home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/_types.rb:222:in `must': Passed `nil` into T.must (TypeError)

      raise TypeError.new("Passed `nil` into T.must")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        from /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:285:in `pr_name_directory'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:185:in `solo_pr_name'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:115:in `pr_name'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:174:in `message'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
        from /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
        from bin/dry-run.rb:728:in `block in <main>'
        from bin/dry-run.rb:620:in `each'
        from bin/dry-run.rb:620:in `<main>'
```

### Smallest manifest that reproduces the issue

Repo:
https://github.com/rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test/tree/main/DotNetTools

Dry run command:
```bash
bin/dry-run.rb nuget rhyskoedijk/dependabot-nuget-webconfig-assembly-binding-test --dir="/DotNetTools"
```

**Comment by rhyskoedijk** [comment]
It appears this broke after https://github.com/dependabot/dependabot-core/pull/9162

This function doesn't behave as expected; If a file is modified in a way that both modifies and deletes lines, the function incorrectly returns `true` suggesting **only** lines were deleted by the change.
https://github.com/dependabot/dependabot-core/blob/8296fc29ba5ca1a7dbe628d56e457f2e438e3da3/nuget/lib/dependabot/nuget/file_updater.rb#L222-L227

If a user has a badly formatted json file (e.g. empty trailing line), `only_deleted_lines?` will return `true` and skip the file change. This bubbles up the call chain eventually resulting in no file changes being detected when building the PR message.

```diff
± DotNetTools/.config/dotnet-tools.json
~~~
--- /tmp/original20240731-5014-nuvtde       2024-07-31 11:53:07.151638184 +0000
+++ /tmp/updated20240731-5014-ub4pae        2024-07-31 11:53:07.151638184 +0000
@@ -1,13 +1,12 @@
 {
-    "version": 1,
-    "isRoot": true,
-    "tools": {
-      "dotnet-ef": {
-        "version": "7.0.8",
-        "commands": [
-          "dotnet-ef"
-        ]
-      }
+  "version": 1,
+  "isRoot": true,
+  "tools": {
+    "dotnet-ef": {
+      "version": "8.0.7",
+      "commands": [
+        "dotnet-ef"
+      ]
     }
   }
-  
\ No newline at end of file
+}
\ No newline at end of file
~~~
10 insertions (+), 11 deletions (-)
```

If I modify `only_deleted_lines?` to ignore whitespace changes, it the update works as expected without errors.
