### ISSUE TITLE
Rust: "Dependabot can't parse your Cargo.toml" error triggered by Cargo `[lints]` table

### ISSUE THREAD

**Issue by kpreid** [dependabot/dependabot-core#10453]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Cargo

### Package manager version

cargo 1.80.1 (376290515 2024-07-16)

### Language version

rustc 1.80.1 (3f5fd8dd4 2024-08-06)

### Manifest location and content before the Dependabot update

Reduced `Cargo.toml` test case, tested at the root of a repo:
```toml
[package]
name = "problem"

[lints]
clippy.should_panic_without_expect = "deny"
clippy.pedantic = { level = "warn", priority = -1 }
```
I uploaded this to <https://github.com/kpreid/dependabot-investigation>.

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "17:00"
      timezone: "America/Los_Angeles"
    versioning-strategy: "auto"
```

### What you expected to see, versus what you actually saw

Dependabot fails to parse the file. It gives no line number in the log, only:

```
updater | 2024/08/16 04:52:09 ERROR <job_870136100> Error during file fetching; aborting: /Cargo.toml not parseable
  proxy | 2024/08/16 04:52:10 [008] POST /update_jobs/870136100/record_update_job_error
  proxy | 2024/08/16 04:52:10 [008] 204 /update_jobs/870136100/record_update_job_error
  proxy | 2024/08/16 04:52:10 [010] PATCH /update_jobs/870136100/mark_as_processed
  proxy | 2024/08/16 04:52:10 [010] 204 /update_jobs/870136100/mark_as_processed
updater | 2024/08/16 04:52:10 INFO <job_870136100> Finished job processing
updater | 2024/08/16 04:52:10 INFO Results:
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+-------------------------------+
|            Errors             |
+-------------------------------+
| dependency_file_not_parseable |
+-------------------------------+
```

### Native package manager behavior

The problem is not with updating, but with reading the file at all. Cargo accepts this `Cargo.toml` file.

**Comment by Jefffrey** [comment]
Bug in upstream toml-rb parser: https://github.com/emancu/toml-rb/issues/151

**Comment by 4br3mm0rd** [comment]
Hey! From what I understand with the issue in toml-rb, and from what I tested, you can fix your toml file like the following (in the meantime, until they fix the issue):
```
[package]
name = "problem"

[lints]
clippy.pedantic = { level = "warn", priority = -1 }
clippy.should_panic_without_expect = "deny"
```

**Comment by latk** [comment]
This also affects the Python ecosystem. In the `pyproject.toml` file, it's somewhat common to configure linters with TOML tables that have dotted keys, e.g.:

```toml
[tool.ruff]
lint.select = ["E", "F", "W"]
lint.ignore = ["E501"]
```

Dependabot doesn't show the stack trace with the toml-rb error, so it was really difficult to figure out what was happening. The error that I saw in the logs was:

```
 Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+-------------------------------------------------------------------------------+
|                                    Errors                                     |
+-------------------------------+-----------------------------------------------+
| Type                          | Details                                       |
+-------------------------------+-----------------------------------------------+
| dependency_file_not_parseable | {                                             |
|                               |   "message": "/pyproject.toml not parseable", |
|                               |   "file-path": "/pyproject.toml"              |
|                               | }                                             |
+-------------------------------+-----------------------------------------------+
```

Investigating this further, I see that the upstream toml-rb issues have been solved as of version 4.1 (released in Oct 2025):

* https://github.com/emancu/toml-rb/issues/151
* https://github.com/emancu/toml-rb/issues/155
* https://github.com/emancu/toml-rb/pull/157
* v4.1.0 changelog: https://github.com/emancu/toml-rb/releases/tag/v4.1.0

I have confirmed that my `pyproject.toml` file fails when parsed with toml-rb 4.0, but succeeds with toml-rb 4.1. Here's the error when trying to load my file with 4.0:

```
irb(main):001> require 'toml-rb'
=> true
irb(main):002> TomlRB.load_file("/pyproject.toml")
/usr/local/bundle/gems/toml-rb-4.0.0/lib/toml-rb/keyvalue.rb:21:in 'block in TomlRB::Keyvalue#assign': Key "lint" is defined more than once (TomlRB::ValueOverwriteError)
        from /usr/local/bundle/gems/toml-rb-4.0.0/lib/toml-rb/keyvalue.rb:21:in 'Hash#merge!'
        from /usr/local/bundle/gems/toml-rb-4.0.0/lib/toml-rb/keyvalue.rb:21:in 'TomlRB::Keyvalue#assign'
        from /usr/local/bundle/gems/toml-rb-4.0.0/lib/toml-rb/parser.rb:36:in 'TomlRB::Parser#visit_keyvalue'
        from /usr/local/bundle/gems/toml-rb-4.0.0/lib/toml-rb/keyvalue.rb:40:in 'TomlRB::Keyvalue#accept_visitor'
        from /usr/local/bundle/gems/toml-rb-4.0.0/lib/toml-rb/parser.rb:14:in 'block in TomlRB::Parser#initialize'
        from /usr/local/bundle/gems/toml-rb-4.0.0/lib/toml-rb/parser.rb:14:in 'Array#each'
        from /usr/local/bundle/gems/toml-rb-4.0.0/lib/toml-rb/parser.rb:14:in 'TomlRB::Parser#initialize'
        from /usr/local/bundle/gems/toml-rb-4.0.0/lib/toml-rb.rb:46:in 'TomlRB.parse'
        from /usr/local/bundle/gems/toml-rb-4.0.0/lib/toml-rb.rb:70:in 'TomlRB.load_file'
        from (irb):2:in '<main>'
        from /usr/local/lib/ruby/gems/4.0.0/gems/irb-1.16.0/exe/irb:9:in '<top (required)>'
        from /usr/local/lib/ruby/4.0.0/rubygems.rb:303:in 'Kernel#load'
        from /usr/local/lib/ruby/4.0.0/rubygems.rb:303:in 'Gem.activate_and_load_bin_path'
        from /usr/local/bin/irb:25:in '<main>'
```

I am not familiar with Ruby, but I think this issue can be resolved by updating the dependency here?

https://github.com/dependabot/dependabot-core/blob/3f8820c82f64140c5a36fea15cf60151067bbe49/common/dependabot-common.gemspec#L49

There is an open Dependabot PR for Dependabot (Nov 2025) that would include the toml-rb 4.1 update, but there seem to be tons of unrelated CI failures:

* https://github.com/dependabot/dependabot-core/pull/13455
