### ISSUE TITLE
Updating more than one cargo create with the same name results in an error

### ISSUE THREAD

**Issue by NicoSchmidt1703** [dependabot/dependabot-core#10507]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Cargo

### Manifest location and content before the Dependabot update

```
[package]
name = "yy"
version = "0.1.0"
edition = "2021"

[dependencies]
utils = { git = "ssh://git@github.com/{repo}.git", tag = "0.0.1"] }

[dev-dependencies]
utils = { git = "ssh://git@github.com/{repo}.git", tag = "0.0.1", features = ["testing"] }
```

### dependabot.yml content

```
# Dependabot config
version: 2
registries:
  github:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.FKT_USER_TOKEN}}

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      my-dependencies:
        patterns:
          - "utils"
```

### Updated dependency

`utils` from `0.0.1` to `0.0.2`

### What you expected to see, versus what you actually saw

Both dependencies are updated at the same time. 

The cargo error message, shown below, also occurs, when I update one version and run `cargo build` locally. Therefore, I think the grouping does not work correctly.

### Native package manager behavior

updater | 2024/08/27 11:54:03 ERROR <job_xx> Error processing utils (Dependabot::SharedHelpers::HelperSubprocessFailed)
2024/08/27 11:54:03 ERROR <job_xx> error: failed to parse manifest at `dependabot_tmp_dir/Cargo.toml`

Caused by:
  Dependency 'utils' has different source paths depending on the build target. Each dependency must have a single canonical source path irrespective of build target.

### Images of the diff or a link to the PR, issue, or logs

> updater | 2024/08/27 11:53:47 INFO <job_xx> Starting update group for 'my-dependencies'
updater | 2024/08/27 11:53:47 INFO <job_xx> Updating the / directory.
updater | 2024/08/27 11:53:48 INFO <job_xx> Checking if utils 272a28dd4874233ac95205e13669757971397bd2 needs updating
  proxy | 2024/08/27 11:53:48 [019] GET [https://github.com:443/{repo}.git/info/refs?service=git-upload-pack](https://github.com/{repo}..git/info/refs?service=git-upload-pack)
  proxy | 2024/08/27 11:53:48 [019] * authenticating git server request (host: github.com)
  proxy | 2024/08/27 11:53:48 [019] 200 [https://github.com:443/{repo}.git/info/refs?service=git-upload-pack](https://github.com/{repo}..git/info/refs?service=git-upload-pack)
updater | 2024/08/27 11:53:48 INFO <job_xx> Latest version is 1b9de7023b12f4c6d40dace3dad9fe1e5af92e3d

...

> updater | 2024/08/27 11:54:01 INFO <job_xx> Requirements to unlock own
2024/08/27 11:54:01 INFO <job_xx> Requirements update strategy bump_versions
updater | 2024/08/27 11:54:01 INFO <job_xx> Updating utils from 272a28dd4874233ac95205e13669757[971](https://github.com/{current_repo}/actions/runs/xx/job/yy#step:3:973)397bd2 to 1b9de7023b12f4c6d40dace3dad9fe1e5af92e3d
  proxy | 2024/08/27 11:54:03 [917] POST /update_jobs/xx/record_update_job_unknown_error
  proxy | 2024/08/27 11:54:03 [917] 204 /update_jobs/xx/record_update_job_unknown_error
  proxy | 2024/08/27 11:54:03 [919] POST /update_jobs/xx/record_update_job_error
  proxy | 2024/08/27 11:54:03 [919] 204 /update_jobs/xx/record_update_job_error
  proxy | 2024/08/27 11:54:03 [921] POST /update_jobs/xx/increment_metric
  proxy | 2024/08/27 11:54:03 [921] 204 /update_jobs/xx/increment_metric
  proxy | 2024/08/27 11:54:03 [923] POST /update_jobs/xx/record_update_job_unknown_error
  proxy | 2024/08/27 11:54:03 [923] 204 /update_jobs/xx/record_update_job_unknown_error
updater | 2024/08/27 11:54:03 ERROR <job_xx> Error processing utils (Dependabot::SharedHelpers::HelperSubprocessFailed)
2024/08/27 11:54:03 ERROR <job_xx> error: failed to parse manifest at `dependabot_tmp_dir/Cargo.toml`

> Caused by:
  Dependency 'utils' has different source paths depending on the build target. Each dependency must have a single canonical source path irrespective of build target.
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb:168:in `run_cargo_command'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb:37:in `block (2 levels) in updated_lockfile_content'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/common/lib/dependabot/shared_helpers.rb:290:in `with_git_configured'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:191:in `block in create_validator_slow'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb:34:in `block in updated_lockfile_content'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/common/lib/dependabot/shared_helpers.rb:81:in `block in in_a_temporary_directory'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/common/lib/dependabot/shared_helpers.rb:81:in `chdir'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/common/lib/dependabot/shared_helpers.rb:81:in `in_a_temporary_directory'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:191:in `block in create_validator_slow'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/cargo/lib/dependabot/cargo/file_updater/lockfile_updater.rb:31:in `updated_lockfile_content'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/cargo/lib/dependabot/cargo/file_updater.rb:67:in `updated_lockfile_content'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/cargo/lib/dependabot/cargo/file_updater.rb:38:in `updated_dependency_files'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:143:in `generate_dependency_files'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:72:in `run'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:44:in `create_from'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:170:in `create_change_for'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:99:in `block in compile_all_dependency_changes_for'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:61:in `each'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:61:in `compile_all_dependency_changes_for'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:968:in `bind_call'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:968:in `block in create_validator_method_medium1'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:97:in `dependency_change'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `block in create_validator_method_medium0'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:61:in `perform'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `block in create_validator_method_medium0'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:117:in `run_grouped_update_for'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:968:in `bind_call'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:968:in `block in create_validator_method_medium1'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:103:in `block in run_grouped_dependency_updates'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:102:in `each'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:102:in `run_grouped_dependency_updates'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:64:in `perform'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:44:in `block in perform_job'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `block in with_span'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/context.rb:87:in `with_value'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `with_span'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:18:in `perform_job'
2024/08/27 11:54:03 ERROR <job_xx> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
2024/08/27 11:54:03 ERROR <job_xx> bin/update_files.rb:46:in `<main>'
updater | 2024/08/27 11:54:17 INFO <job_xx> Nothing to update for Dependency Group: 'my-dependencies'

...

>  proxy | 2024/08/27 11:54:23 [859] PATCH /update_jobs/xx/mark_as_processed
  proxy | 2024/08/27 11:54:23 [859] 204 /update_jobs/xx/mark_as_processed
updater | 2024/08/27 11:54:23 INFO <job_xx> Finished job processing
updater | 2024/08/27 11:54:23 INFO Results:
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+-------------------------------+
| Dependencies failed to update |
+---------------+---------------+
| utils         | unknown_error |
+---------------+---------------+
Failure running container 5e82b28da78dde4d118f71db31441c691df0b856b7541a3cae23054f637c1193
Cleaned up container 5e82b28da78dde4d118f71db31441c691df0b856b7541a3cae23054f637c1193
  proxy | 2024/08/27 11:54:23 10/924 calls cached (1%)
2024/08/27 11:54:23 Posting metrics to remote API endpoint
  proxy | 2024/08/27 11:54:23 Successfully posted metrics data via api client
Error: Dependabot encountered an error performing the update

**Comment by v-thavaahariharangit** [comment]
@NicoSchmidt1703 

Updating more than one cargo crate with the same name is working as expected.
Ex: https://github.com/dsp-testing/cargo-private-registry-issues-10507

In your `dependabot.yml`, you missed configuring the registry details in ecosystem update step
```
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    groups:
      my-dependencies:
        patterns:
          - "utils"
```
