### ISSUE TITLE
dependabot errors with "file_fetcher_error" when running for cargo ecosystem

### ISSUE THREAD

**Issue by alex** [dependabot/dependabot-core#10596]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

cargo

### Manifest location and content before the Dependabot update

https://github.com/pyca/cryptography this fails when running on this repo

### dependabot.yml content

https://github.com/pyca/cryptography/blob/main/.github/dependabot.yml

```
  - package-ecosystem: cargo
    directory: "/src/rust/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "America/New_York"
    allow:
      # Also update indirect dependencies
      - dependency-type: all
    open-pull-requests-limit: 1024
```

### What you expected to see, versus what you actually saw

The error I'm seeing in the logs is:

```
updater | 2024/09/12 10:18:14 ERROR <job_883663713> Error during file fetching; aborting: Could not resolve workspace root for path dependency /src/rust/cryptography-cffi/Cargo.toml of /src/rust/Cargo.toml
updater | 2024/09/12 10:18:14 ERROR <job_883663713> Could not resolve workspace root for path dependency /src/rust/cryptography-cffi/Cargo.toml of /src/rust/Cargo.toml
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/cargo/lib/dependabot/cargo/file_fetcher.rb:282:in `find_workspace_root'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/cargo/lib/dependabot/cargo/file_fetcher.rb:153:in `block in fetch_path_dependency_files'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/cargo/lib/dependabot/cargo/file_fetcher.rb:134:in `each'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/cargo/lib/dependabot/cargo/file_fetcher.rb:134:in `flat_map'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/cargo/lib/dependabot/cargo/file_fetcher.rb:134:in `fetch_path_dependency_files'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/cargo/lib/dependabot/cargo/file_fetcher.rb:90:in `block in path_dependency_files'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/cargo/lib/dependabot/cargo/file_fetcher.rb:88:in `each'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/cargo/lib/dependabot/cargo/file_fetcher.rb:88:in `path_dependency_files'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/cargo/lib/dependabot/cargo/file_fetcher.rb:63:in `fetch_path_dependency_and_workspace_files'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/cargo/lib/dependabot/cargo/file_fetcher.rb:54:in `fetch_files'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/common/lib/dependabot/file_fetchers/base.rb:135:in `files'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:144:in `block in dependency_files'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:162:in `with_retries'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:144:in `dependency_files'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:36:in `block in perform_job'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `block in with_span'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/context.rb:87:in `with_value'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `with_span'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:22:in `perform_job'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/09/12 10:18:14 ERROR <job_883663713> bin/fetch_files.rb:37:in `<main>'
updater | 2024/09/12 10:18:14 INFO <job_883663713> Finished job processing
updater | 2024/09/12 10:18:14 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------+
updater | |       Errors       |
updater | +--------------------+
updater | | file_fetcher_error |
updater | +--------------------+
```

### Images of the diff or a link to the PR, issue, or logs

https://github.com/pyca/cryptography/network/updates/883663713

**Comment by alex** [comment]
I'm not sure why this was triaged as go:modules or ruby:bundler, this reproducer only involves cargo.

**Comment by rdipardo** [comment]
Duplicate of #10584 ?

**Comment by alex** [comment]
Looks like it
