### ISSUE TITLE
Dependabot creates incompatible upgrade for pip-compile project

### ISSUE THREAD

**Issue by jprestel-rue** [dependabot/dependabot-core#10661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

pip-tools 7.4.1; pip 24.2

### Language version

python 3.12

## `/requirements.txt`

```pip-requirements
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile --strip-extras pyproject.toml
#
attrs==23.2.0
    # via
    #   cattrs
    #   jsii
aws-cdk-asset-awscli-v1==2.2.202
    # via aws-cdk-lib
aws-cdk-asset-kubectl-v20==2.1.2
    # via aws-cdk-lib
aws-cdk-asset-node-proxy-agent-v6==2.0.3
    # via aws-cdk-lib
aws-cdk-lib==2.153.0
    # via foo (pyproject.toml)
cattrs==23.2.3
    # via jsii
constructs==10.3.0
    # via
    #   aws-cdk-lib
    #   foo (pyproject.toml)
importlib-resources==6.4.3
    # via jsii
jsii==1.102.0
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-lib
    #   constructs
publication==0.0.3
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-lib
    #   constructs
    #   jsii
python-dateutil==2.9.0.post0
    # via jsii
six==1.16.0
    # via python-dateutil
typeguard==2.13.3
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-lib
    #   constructs
    #   jsii
typing-extensions==4.12.2
    # via jsii
```

# `/pyproject.toml`
```toml
[project]
name = "foo"
dynamic = ["version"]
requires-python = ">=3.12,<3.13"
dependencies = [
    "aws-cdk-lib>=2.153.0,<3.0.0",
    "constructs>=10.3.0,<11.0.0",
]

[build-system]
requires = ["hatchling>=1.25.0,<2.0.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "foo/__about__.py"
```

### dependabot.yml content

```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: /
    schedule:
      interval: "weekly"
    groups:
      dev-dependencies:
        applies-to: version-updates
        dependency-type: development
      prod-dependencies:
        applies-to: version-updates
        dependency-type: production
```

### Updated dependency

# Unexpected upgrades
dependabot made these additional upgrades, which were not included by the native package manager
* `cattrs` 23.2.3 -> 24.1.2
* `typeguard` 2.13.3 -> 4.3.0

# Missing dependency
dependabot failed to add the following transitive dependency, which the native package manager added:
* `aws-cdk-cloud-assembly-schema==36.3.0`
    * Via upgrade to `aws-cdk-lib`

### What you expected to see, versus what you actually saw

Dependabot created dependency conflict by including an upgrade to `cattrs` and `typeguard` libraries:

When running `pip-sync requirements.txt` I get the following error:

```
ERROR: Cannot install -r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 7) and cattrs==24.1.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested cattrs==24.1.2
    jsii 1.103.1 depends on cattrs<23.3 and >=1.8

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

## Full output of `pip-sync requirements.txt`
```
pip-sync requirements.txt
Found existing installation: cfgv 3.4.0
Uninstalling cfgv-3.4.0:
  Successfully uninstalled cfgv-3.4.0
Found existing installation: distlib 0.3.8
Uninstalling distlib-0.3.8:
  Successfully uninstalled distlib-0.3.8
Found existing installation: filelock 3.16.0
Uninstalling filelock-3.16.0:
  Successfully uninstalled filelock-3.16.0
Found existing installation: identify 2.6.0
Uninstalling identify-2.6.0:
  Successfully uninstalled identify-2.6.0
Found existing installation: iniconfig 2.0.0
Uninstalling iniconfig-2.0.0:
  Successfully uninstalled iniconfig-2.0.0
Found existing installation: mypy 1.11.2
Uninstalling mypy-1.11.2:
  Successfully uninstalled mypy-1.11.2
Found existing installation: mypy-extensions 1.0.0
Uninstalling mypy-extensions-1.0.0:
  Successfully uninstalled mypy-extensions-1.0.0
Found existing installation: nodeenv 1.9.1
Uninstalling nodeenv-1.9.1:
  Successfully uninstalled nodeenv-1.9.1
Found existing installation: platformdirs 4.3.2
Uninstalling platformdirs-4.3.2:
  Successfully uninstalled platformdirs-4.3.2
Found existing installation: pluggy 1.5.0
Uninstalling pluggy-1.5.0:
  Successfully uninstalled pluggy-1.5.0
Found existing installation: pre-commit 3.8.0
Uninstalling pre-commit-3.8.0:
  Successfully uninstalled pre-commit-3.8.0
Found existing installation: pytest 8.3.2
Uninstalling pytest-8.3.2:
  Successfully uninstalled pytest-8.3.2
Found existing installation: PyYAML 6.0.2
Uninstalling PyYAML-6.0.2:
  Successfully uninstalled PyYAML-6.0.2
Found existing installation: ruff 0.6.4
Uninstalling ruff-0.6.4:
  Successfully uninstalled ruff-0.6.4
Found existing installation: virtualenv 20.26.4
Uninstalling virtualenv-20.26.4:
  Successfully uninstalled virtualenv-20.26.4
Collecting attrs==24.2.0 (from -r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 1))
  Using cached attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting aws-cdk-asset-awscli-v1==2.2.204 (from -r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 2))
  Downloading aws_cdk.asset_awscli_v1-2.2.204-py3-none-any.whl.metadata (1.1 kB)
Collecting aws-cdk-asset-node-proxy-agent-v6==2.1.0 (from -r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 3))
  Using cached aws_cdk.asset_node_proxy_agent_v6-2.1.0-py3-none-any.whl.metadata (1.1 kB)
Collecting aws-cdk-lib==2.159.1 (from -r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 4))
  Downloading aws_cdk_lib-2.159.1-py3-none-any.whl.metadata (59 kB)
Collecting cattrs==24.1.2 (from -r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 5))
  Downloading cattrs-24.1.2-py3-none-any.whl.metadata (8.4 kB)
Collecting importlib-resources==6.4.5 (from -r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 6))
  Using cached importlib_resources-6.4.5-py3-none-any.whl.metadata (4.0 kB)
Collecting jsii==1.103.1 (from -r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 7))
  Using cached jsii-1.103.1-py3-none-any.whl.metadata (79 kB)
Collecting typeguard==4.3.0 (from -r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 8))
  Using cached typeguard-4.3.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: publication>=0.0.3 in /Users/jprestel/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from aws-cdk-asset-awscli-v1==2.2.204->-r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 2)) (0.0.3)
Requirement already satisfied: aws-cdk.asset-kubectl-v20<3.0.0,>=2.1.2 in /Users/jprestel/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from aws-cdk-lib==2.159.1->-r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 4)) (2.1.2)
Collecting aws-cdk.cloud-assembly-schema<37.0.0,>=36.0.24 (from aws-cdk-lib==2.159.1->-r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 4))
  Downloading aws_cdk.cloud_assembly_schema-36.3.0-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: constructs<11.0.0,>=10.0.0 in /Users/jprestel/.pyenv/versions/3.12.4/lib/python3.12/site-packages (from aws-cdk-lib==2.159.1->-r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 4)) (10.3.0)
INFO: pip is looking at multiple versions of jsii to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r /var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk (line 7) and cattrs==24.1.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested cattrs==24.1.2
    jsii 1.103.1 depends on cattrs<23.3 and >=1.8

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
Traceback (most recent call last):
  File "/Users/jprestel/.pyenv/versions/3.12.4/bin/pip-sync", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/jprestel/.pyenv/versions/3.12.4/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jprestel/.pyenv/versions/3.12.4/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/jprestel/.pyenv/versions/3.12.4/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jprestel/.pyenv/versions/3.12.4/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jprestel/.pyenv/versions/3.12.4/lib/python3.12/site-packages/piptools/scripts/sync.py", line 145, in cli
    sync.sync(
  File "/Users/jprestel/.pyenv/versions/3.12.4/lib/python3.12/site-packages/piptools/sync.py", line 263, in sync
    run(  # nosec
  File "/Users/jprestel/.pyenv/versions/3.12.4/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/jprestel/.pyenv/versions/3.12.4/bin/python3.12', '-m', 'pip', 'install', '-r', '/var/folders/vw/6x775j054cg2z84cr4q2cq55ghvmww/T/tmp22vzx3dk']' returned non-zero exit status 1.
```

## Diff of dependabot vs native package manager
```diff
diff --git a/requirements.txt b/requirements.txt
index ea95ec4..762c56a 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -14,11 +14,9 @@ aws-cdk-asset-kubectl-v20==2.1.2
     # via aws-cdk-lib
 aws-cdk-asset-node-proxy-agent-v6==2.1.0
     # via aws-cdk-lib
-aws-cdk-cloud-assembly-schema==36.3.0
-    # via aws-cdk-lib
 aws-cdk-lib==2.159.1
     # via foo (pyproject.toml)
-cattrs==23.2.3
+cattrs==24.1.2
     # via jsii
 constructs==10.3.0
     # via
@@ -31,7 +29,6 @@ jsii==1.103.1
     #   aws-cdk-asset-awscli-v1
     #   aws-cdk-asset-kubectl-v20
     #   aws-cdk-asset-node-proxy-agent-v6
-    #   aws-cdk-cloud-assembly-schema
     #   aws-cdk-lib
     #   constructs
 publication==0.0.3
@@ -39,7 +36,6 @@ publication==0.0.3
     #   aws-cdk-asset-awscli-v1
     #   aws-cdk-asset-kubectl-v20
     #   aws-cdk-asset-node-proxy-agent-v6
-    #   aws-cdk-cloud-assembly-schema
     #   aws-cdk-lib
     #   constructs
     #   jsii
@@ -47,12 +43,11 @@ python-dateutil==2.9.0.post0
     # via jsii
 six==1.16.0
     # via python-dateutil
-typeguard==2.13.3
+typeguard==4.3.0
     # via
     #   aws-cdk-asset-awscli-v1
     #   aws-cdk-asset-kubectl-v20
     #   aws-cdk-asset-node-proxy-agent-v6
-    #   aws-cdk-cloud-assembly-schema
     #   aws-cdk-lib
     #   constructs
     #   jsii
```

### Native package manager behavior

# Upgrade procedure
```sh
rm requirements.txt
pip-compile --strip-extras pyproject.toml
```
# Resulting `/requirements.txt`
```pip-requirements
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile --strip-extras pyproject.toml
#
attrs==24.2.0
    # via
    #   cattrs
    #   jsii
aws-cdk-asset-awscli-v1==2.2.204
    # via aws-cdk-lib
aws-cdk-asset-kubectl-v20==2.1.2
    # via aws-cdk-lib
aws-cdk-asset-node-proxy-agent-v6==2.1.0
    # via aws-cdk-lib
aws-cdk-cloud-assembly-schema==36.3.0
    # via aws-cdk-lib
aws-cdk-lib==2.159.1
    # via foo (pyproject.toml)
cattrs==23.2.3
    # via jsii
constructs==10.3.0
    # via
    #   aws-cdk-lib
    #   foo (pyproject.toml)
importlib-resources==6.4.5
    # via jsii
jsii==1.103.1
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-cloud-assembly-schema
    #   aws-cdk-lib
    #   constructs
publication==0.0.3
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-cloud-assembly-schema
    #   aws-cdk-lib
    #   constructs
    #   jsii
python-dateutil==2.9.0.post0
    # via jsii
six==1.16.0
    # via python-dateutil
typeguard==2.13.3
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-cloud-assembly-schema
    #   aws-cdk-lib
    #   constructs
    #   jsii
typing-extensions==4.12.2
    # via jsii
```

# Diff versus previous:
```diff
diff --git a/requirements.txt b/requirements.txt
index eac943b..ea95ec4 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -4,17 +4,19 @@
 #
 #    pip-compile --strip-extras pyproject.toml
 #
-attrs==23.2.0
+attrs==24.2.0
     # via
     #   cattrs
     #   jsii
-aws-cdk-asset-awscli-v1==2.2.202
+aws-cdk-asset-awscli-v1==2.2.204
     # via aws-cdk-lib
 aws-cdk-asset-kubectl-v20==2.1.2
     # via aws-cdk-lib
-aws-cdk-asset-node-proxy-agent-v6==2.0.3
+aws-cdk-asset-node-proxy-agent-v6==2.1.0
     # via aws-cdk-lib
-aws-cdk-lib==2.153.0
+aws-cdk-cloud-assembly-schema==36.3.0
+    # via aws-cdk-lib
+aws-cdk-lib==2.159.1
     # via foo (pyproject.toml)
 cattrs==23.2.3
     # via jsii
@@ -22,13 +24,14 @@ constructs==10.3.0
     # via
     #   aws-cdk-lib
     #   foo (pyproject.toml)
-importlib-resources==6.4.3
+importlib-resources==6.4.5
     # via jsii
-jsii==1.102.0
+jsii==1.103.1
     # via
     #   aws-cdk-asset-awscli-v1
     #   aws-cdk-asset-kubectl-v20
     #   aws-cdk-asset-node-proxy-agent-v6
+    #   aws-cdk-cloud-assembly-schema
     #   aws-cdk-lib
     #   constructs
 publication==0.0.3
@@ -36,6 +39,7 @@ publication==0.0.3
     #   aws-cdk-asset-awscli-v1
     #   aws-cdk-asset-kubectl-v20
     #   aws-cdk-asset-node-proxy-agent-v6
+    #   aws-cdk-cloud-assembly-schema
     #   aws-cdk-lib
     #   constructs
     #   jsii
@@ -48,6 +52,7 @@ typeguard==2.13.3
     #   aws-cdk-asset-awscli-v1
     #   aws-cdk-asset-kubectl-v20
     #   aws-cdk-asset-node-proxy-agent-v6
+    #   aws-cdk-cloud-assembly-schema
     #   aws-cdk-lib
     #   constructs
     #   jsii
```

### Images of the diff or a link to the PR, issue, or logs

# Diff created by dependabot
```diff
diff --git a/requirements.txt b/requirements.txt
index eac943b..762c56a 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -4,27 +4,27 @@
 #
 #    pip-compile --strip-extras pyproject.toml
 #
-attrs==23.2.0
+attrs==24.2.0
     # via
     #   cattrs
     #   jsii
-aws-cdk-asset-awscli-v1==2.2.202
+aws-cdk-asset-awscli-v1==2.2.204
     # via aws-cdk-lib
 aws-cdk-asset-kubectl-v20==2.1.2
     # via aws-cdk-lib
-aws-cdk-asset-node-proxy-agent-v6==2.0.3
+aws-cdk-asset-node-proxy-agent-v6==2.1.0
     # via aws-cdk-lib
-aws-cdk-lib==2.153.0
+aws-cdk-lib==2.159.1
     # via foo (pyproject.toml)
-cattrs==23.2.3
+cattrs==24.1.2
     # via jsii
 constructs==10.3.0
     # via
     #   aws-cdk-lib
     #   foo (pyproject.toml)
-importlib-resources==6.4.3
+importlib-resources==6.4.5
     # via jsii
-jsii==1.102.0
+jsii==1.103.1
     # via
     #   aws-cdk-asset-awscli-v1
     #   aws-cdk-asset-kubectl-v20
@@ -43,7 +43,7 @@ python-dateutil==2.9.0.post0
     # via jsii
 six==1.16.0
     # via python-dateutil
-typeguard==2.13.3
+typeguard==4.3.0
     # via
     #   aws-cdk-asset-awscli-v1
     #   aws-cdk-asset-kubectl-v20
```

# Full resulting `/requirements.txt` from dependabot
```pip-requirements
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile --strip-extras pyproject.toml
#
attrs==24.2.0
    # via
    #   cattrs
    #   jsii
aws-cdk-asset-awscli-v1==2.2.204
    # via aws-cdk-lib
aws-cdk-asset-kubectl-v20==2.1.2
    # via aws-cdk-lib
aws-cdk-asset-node-proxy-agent-v6==2.1.0
    # via aws-cdk-lib
aws-cdk-lib==2.159.1
    # via foo (pyproject.toml)
cattrs==24.1.2
    # via jsii
constructs==10.3.0
    # via
    #   aws-cdk-lib
    #   foo (pyproject.toml)
importlib-resources==6.4.5
    # via jsii
jsii==1.103.1
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-lib
    #   constructs
publication==0.0.3
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-lib
    #   constructs
    #   jsii
python-dateutil==2.9.0.post0
    # via jsii
six==1.16.0
    # via python-dateutil
typeguard==4.3.0
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-lib
    #   constructs
    #   jsii
typing-extensions==4.12.2
    # via jsii
```

### Smallest manifest that reproduces the issue

# `pyproject.toml`
```toml
[project]
name = "foo"
dynamic = ["version"]
requires-python = ">=3.12,<3.13"
dependencies = [
    "aws-cdk-lib>=2.153.0,<3.0.0",
    "constructs>=10.3.0,<11.0.0",
]

[build-system]
requires = ["hatchling>=1.25.0,<2.0.0"]
build-backend = "hatchling.build"

[tool.hatch.version]
path = "foo/__about__.py"

```

# And initial `/requirements.txt`
```python
#
# This file is autogenerated by pip-compile with Python 3.12
# by the following command:
#
#    pip-compile --strip-extras pyproject.toml
#
attrs==23.2.0
    # via
    #   cattrs
    #   jsii
aws-cdk-asset-awscli-v1==2.2.202
    # via aws-cdk-lib
aws-cdk-asset-kubectl-v20==2.1.2
    # via aws-cdk-lib
aws-cdk-asset-node-proxy-agent-v6==2.0.3
    # via aws-cdk-lib
aws-cdk-lib==2.153.0
    # via foo (pyproject.toml)
cattrs==23.2.3
    # via jsii
constructs==10.3.0
    # via
    #   aws-cdk-lib
    #   foo (pyproject.toml)
importlib-resources==6.4.3
    # via jsii
jsii==1.102.0
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-lib
    #   constructs
publication==0.0.3
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-lib
    #   constructs
    #   jsii
python-dateutil==2.9.0.post0
    # via jsii
six==1.16.0
    # via python-dateutil
typeguard==2.13.3
    # via
    #   aws-cdk-asset-awscli-v1
    #   aws-cdk-asset-kubectl-v20
    #   aws-cdk-asset-node-proxy-agent-v6
    #   aws-cdk-lib
    #   constructs
    #   jsii
typing-extensions==4.12.2
    # via jsii
```

**Comment by Crosswind** [comment]
I think, we have a similar case here. I have created a repository that showcases this: https://github.com/Crosswind/dependabot-pip-bug-showcase
Our dependency node2vec requires numpy<2.0.0 and yet we receive a PR from dependabot stating that we should upgrade to numpy>2. I have set up an action which tries to do a simple pip install which fails. The PR with the failed pipeline run that's triggered on PR creation: https://github.com/Crosswind/dependabot-pip-bug-showcase/pull/1

@jprestel-rue Do you think this is the same issue or should I rather open a separate one? I am not familiar with pip-compile. We only use basic pip.

**Comment by jprestel-rue** [comment]
> @jprestel-rue Do you think this is the same issue or should I rather open a separate one? I am not familiar with pip-compile. We only use basic pip.

I couldn't say if it's the same issue exactly, but, at the very least, it's the same sort of symptom.

**Comment by Crosswind** [comment]
Thank you! I'll leave it here for now and in case someone at GitHub decides to want this tracked separately, I'll happily create an issue for it.
