### ISSUE TITLE
NuGet fails to update implicitly added dependency with `Update` attribute.

### ISSUE THREAD

**Issue by brettfo** [dependabot/dependabot-core#10883]
F# projects get an implicit reference to `FSharp.Core` added.  The initial `<PackageReferene Include...` line comes from the SDK and is not in the user's source.  If a newer version is requested, the project file will contain only the following line:

`example.fsproj`:

``` xml
...
<PackageReference Update="FSharp.Core" Version="[some-newer-version]" />
...
```

Currently trying to make that update results in `Package [FSharp.Core] does not exist as a dependency in [example.csproj].` which ultimately turns into an `update_not_possible` error.

**Comment by goswinr** [comment]
the exception is:
```log
2024-11-19T22:24:53.5239790Z updater | running NuGet updater:
2024-11-19T22:24:53.5244152Z /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --job-path /home/dependabot/dependabot-updater/job.json --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/DependabotTest.fsproj --dependency FSharp.Core --new-version 9.0.100 --previous-version 6.0.7 --result-output-path /tmp/update-result.json
2024-11-19T22:24:55.2303528Z updater | 2024/11/19 22:24:53 INFO Error deserializing job file: System.Text.Json.JsonException: The JSON value could not be converted to System.Boolean. Path: $.job.debug | LineNumber: 0 | BytePositionInLine: 958.
2024-11-19T22:24:55.2306393Z  ---> System.InvalidOperationException: Cannot get the value of a token type 'Null' as a boolean.
2024-11-19T22:24:55.2307480Z    at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_ExpectedBoolean(JsonTokenType tokenType)
2024-11-19T22:24:55.2308500Z    at System.Text.Json.Utf8JsonReader.GetBoolean()
2024-11-19T22:24:55.2309476Z    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
2024-11-19T22:24:55.2311074Z    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
2024-11-19T22:24:55.2312887Z    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
2024-11-19T22:24:55.2314448Z    at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
2024-11-19T22:24:55.2315986Z    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
2024-11-19T22:24:55.2318046Z    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
2024-11-19T22:24:55.2319597Z    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
2024-11-19T22:24:55.2320669Z    --- End of inner exception stack trace ---
2024-11-19T22:24:55.2321450Z    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
2024-11-19T22:24:55.2322649Z    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
2024-11-19T22:24:55.2323934Z    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
2024-11-19T22:24:55.2325160Z    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
2024-11-19T22:24:55.2326340Z    at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
2024-11-19T22:24:55.2327615Z    at NuGetUpdater.Core.Run.RunWorker.Deserialize(String json) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Run/RunWorker.cs:line 381
2024-11-19T22:24:55.2339533Z    at NuGetUpdater.Core.ExperimentsManager.FromJobFileAsync(String jobFilePath, ILogger logger) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/ExperimentsManager.cs:line 24: {"base64_dependency_files":[{"name":"DependabotTest.fsproj","content":"77u/PFByb2plY3QgU2RrPSJNaWNyb3NvZnQuTkVULlNkayI+CgogIDxQcm9w\nZXJ0eUdyb3VwPgogICAgPFRhcmdldEZyYW1ld29yaz5uZXQ4LjA8L1Rhcmdl\ndEZyYW1ld29yaz4KICAgIDxHZW5lcmF0ZURvY3VtZW50YXRpb25GaWxlPnRy\ndWU8L0dlbmVyYXRlRG9jdW1lbnRhdGlvbkZpbGU+CiAgPC9Qcm9wZXJ0eUdy\nb3VwPgoKICA8SXRlbUdyb3VwPgogICAgPFBhY2thZ2VSZWZlcmVuY2UgVXBk\nYXRlPSJGU2hhcnAuQ29yZSIgVmVyc2lvbj0iNi4wLjciIC8+CiAgICA8Q29t\ncGlsZSBJbmNsdWRlPSJMaWJyYXJ5LmZzIiAvPgogIDwvSXRlbUdyb3VwPgoK\nPC9Qcm9qZWN0Pgo=\n","directory":"/","type":"file","support_file":false,"content_encoding":"utf-8","deleted":false,"operation":"update","mode":null}],"base_commit_sha":"1aef41cb7d3b6daa1472f2870fef3b7493d82f67","job":{"allowed-updates":[{"dependency-type":"direct","update-type":"all"}],"commit-message-options":{"prefix":null,"prefix-development":null,"include-scope":null},"credentials-metadata":[{"type":"git_source","host":"github.com"}],"debug":null,"dependencies":null,"dependency-groups":[],"dependency-group-to-refresh":null,"existing-pull-requests":[],"existing-group-pull-requests":[],"experiments":{"record-ecosystem-versions":true,"record-update-job-unknown-error":true,"proxy-cached":true,"move-job-token":true,"dependency-change-validation":true,"nuget-native-analysis":true,"composer-v1-deprecation-warning":true,"composer-v1-unsupported-error":true,"lead-security-dependency":true,"enable-record-ecosystem-meta":true,"enable-corepack-for-npm-and-yarn":true},"ignore-conditions":[],"lockfile-only":false,"max-updater-run-time":2700,"package-manager":"nuget","proxy-log-response-body-on-auth-failure":true,"requirements-update-strategy":null,"reject-external-code":false,"security-advisories":[],"security-updates-only":false,"source":{"provider":"github","repo":"goswinr/DependabotTest","branch":null,"directory":"/.","api-endpoint":"https://api.github.com/","hostname":"github.com"},"updating-a-pull-request":false,"update-subdependencies":false,"vendor-dependencies":false,"repo-private":false}}
2024-11-19T22:24:55.2350664Z   No dotnet-tools.json file found.
2024-11-19T22:24:55.2351131Z   No global.json file found.
2024-11-19T22:24:55.2351669Z Running for project file [DependabotTest.fsproj]
2024-11-19T22:24:55.2352433Z Updating project [/home/dependabot/dependabot-updater/repo/DependabotTest.fsproj]
2024-11-19T22:24:55.2353195Z   Running 'PackageReference' project direct XML update
2024-11-19T22:24:55.2354453Z     Package [FSharp.Core] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/DependabotTest.fsproj].
```

**Comment by brettfo** [comment]
@goswinr The stack trace listed is from a separate area of the code and not the F# update, but I'm interested in it.  The failure was parsing the `job.json` file, but I'm not sure why it failed.  At the top of the log, do you see a line that looks like this:

```
updater | 2024/11/12 23:02:14 INFO Job definition: { /* some big JSON object */ }
```

That's the file that we failed to parse.  Could you paste the value?  If you don't want that file to be public, you can also email it directly to me and I'll delete it as soon as I figure out why it failed to parse.  `brettfo@microsoft.com`

**Comment by goswinr** [comment]
@brettfo thanks for fixing it. I saw it's already merged. How can I see if it is deployed? To test it.

**Comment by brettfo** [comment]
@goswinr The fix for the error you were seeing has been deployed.  The next update run on your repo will have the fix.

**Comment by goswinr** [comment]
@brettfo unfortunately Dependabot still fails with:
`Package [FSharp.Core] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/DependabotTest.fsproj].`
You can find the full log here in the README:
https://github.com/goswinr/DependabotTest

**Comment by goswinr** [comment]
A workaround is to use `Include` instead of `Update` : 
```xml
<DisableImplicitFSharpCoreReference>true</DisableImplicitFSharpCoreReference>

...
<PackageReference Include="FSharp.Core" Version="6.0.7" />
```
 you can see that it worked here: 
https://github.com/goswinr/DependabotTest2/pull/1

**Comment by JamieMagee** [comment]
Fixed. The updater now handles the `Update` attribute on `<PackageReference>` for implicit dependencies like `FSharp.Core`. `ProjectBuildFile.cs` detects it and `XmlFileWriter.cs` uses the right attribute when writing updates.

**Comment by goswinr** [comment]
Thank you @JamieMagee
