### ISSUE TITLE
Metadata Fetch Fails When Creating PR For Github Enterprise

### ISSUE THREAD

**Issue by asummers** [dependabot/dependabot-core#1154]
Using `dependabot-script`, it successfully reads my repo, recognizes a dependency to update and goes to attempt the PR, where it fails to fetch the `ref_names`. It seems to be trying to access `https://github.com/$REPO` instead of the provided `GITHUB_ENTERPRISE_HOSTNAME`  used when fetching the project originally.  

```
Traceback (most recent call last):
	8: from generic-update-script.rb:119:in `<main>'
	7: from generic-update-script.rb:119:in `each'
	6: from generic-update-script.rb:171:in `block in <main>'
	5: from /usr/local/lib/ruby/gems/2.6.0/gems/dependabot-common-0.107.5/lib/dependabot/pull_request_creator.rb:66:in `create'
	4: from /usr/local/lib/ruby/gems/2.6.0/gems/dependabot-common-0.107.5/lib/dependabot/pull_request_creator/github.rb:39:in `create'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/dependabot-common-0.107.5/lib/dependabot/pull_request_creator/github.rb:66:in `branch_exists?'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/dependabot-common-0.107.5/lib/dependabot/git_metadata_fetcher.rb:27:in `ref_names'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/dependabot-common-0.107.5/lib/dependabot/git_metadata_fetcher.rb:16:in `upload_pack'
/usr/local/lib/ruby/gems/2.6.0/gems/dependabot-common-0.107.5/lib/dependabot/git_metadata_fetcher.rb:51:in `fetch_upload_pack_for': The following git URLs could not be retrieved: https://github.com/$REPO(Dependabot::GitDependenciesNotReachable)
	6: from generic-update-script.rb:119:in `<main>'
	5: from generic-update-script.rb:119:in `each'
	4: from generic-update-script.rb:171:in `block in <main>'
	3: from /usr/local/lib/ruby/gems/2.6.0/gems/dependabot-common-0.107.5/lib/dependabot/pull_request_creator.rb:66:in `create'
	2: from /usr/local/lib/ruby/gems/2.6.0/gems/dependabot-common-0.107.5/lib/dependabot/pull_request_creator/github.rb:39:in `create'
	1: from /usr/local/lib/ruby/gems/2.6.0/gems/dependabot-common-0.107.5/lib/dependabot/pull_request_creator/github.rb:65:in `branch_exists?'
/usr/local/lib/ruby/gems/2.6.0/gems/dependabot-common-0.107.5/lib/dependabot/pull_request_creator/github.rb:68:in `rescue in branch_exists?': Unexpected git error! (RuntimeError)
```

Notice the line `URLs could not be retrieved: https://github.com/$REPO`

Debugging from `dependabot-script`, all the information (including `@files`) looks correct in the object created [here](https://github.com/dependabot/dependabot-script/blob/master/generic-update-script.rb#L158) but it fails to use the enterprise repo [here](https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/git_metadata_fetcher.rb#L39) 

Is there something I should be doing differently to get it past this point?

**Comment by asummers** [comment]
Note: this seems to be a recent-ish regression. It broke somewhere between `0.106.30` and `0.106.47`

**Comment by greysteil** [comment]
Fixed in https://github.com/dependabot/dependabot-core/commit/83adb157ef2ac70d737794679c0f3ff69e479c13. Thanks for the heads up!
