### ISSUE TITLE
Support setting default NPM repo when no npmrc is present

### ISSUE THREAD

**Issue by keirlawson** [dependabot/dependabot-core#1231]
It appears that dependabot-core keeps the public NPM registry as the default in the case that there is no npmrc present in the repository in question, even when additional repos are specified via credentials.  This is causing dependabot-core to fail with a 404 when attempting to detect upgrades for internal libraries in our projects, which make the assumption that the default registry has been set to our internal one by the user/build environment.  I note that for python registries there is an option `replaces-base` to allow for setting the default registry, is there an equivalent for NPM registries? If not would you accept a PR for this functionality?

**Comment by greysteil** [comment]
This sounds like something we should be able to fix without requiring configuration. Can you @-mention Dependabot in a PR or issue that it's creating? That will help me replicate and fix.

**Comment by keirlawson** [comment]
Unfortunately I can't link to a PR as this was using dependabot-core on our internal Github Enterprise installation, any other way I can help investigate?

**Comment by greysteil** [comment]
Ah, OK.

My first hunch here is that adding a `.npmrc` file or `.yarnrc` file that declared a global registry (with or without credentials) would stop this behaviour, as it's likely coming from the `RegistryFinder#global_registry` method. Do you have one committed?

**Comment by keirlawson** [comment]
yes, adding such a `.npmrc` does indeed resolve the issue, the problem with this is I suspect we have a lot of repos that don't have this file.  We could of course do an exercise to add it to each of them, but I was wondering if it would be possible to set the default when invoking dependabot to avoid needing to do that.

**Comment by greysteil** [comment]
Hmmm, Dependabot shouldn't be falling back to registry.npmjs.org anywhere else unless it can't find details of the dependency anywhere else. What line are you seeing the error from?

**Comment by greysteil** [comment]
(I presume you're using the latest version of Dependabot Core, by the way?)

**Comment by keirlawson** [comment]
I've been using the dependabot-core docker image, pulled 7 days ago and invoked via dependabot-script with our NPM repo added to the credentials block. The error is:

```
  - Updating debug (from )…Traceback (most recent call last):
	23: from ./generic-update-script.rb:126:in `<main>'
	22: from ./generic-update-script.rb:126:in `each'
	21: from ./generic-update-script.rb:164:in `block in <main>'
	20: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:39:in `updated_dependency_files'
	19: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `updated_lockfiles'
	18: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `each'
	17: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:149:in `block in updated_lockfiles'
	16: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:120:in `package_lock_changed?'
	15: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:187:in `updated_package_lock_content'
	14: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:30:in `updated_lockfile_content'
	13: from /workspace/vendor/ruby/2.6.0/gems/dependabot-common-0.108.15/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
	12: from /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	11: from /workspace/vendor/ruby/2.6.0/gems/dependabot-common-0.108.15/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
	10: from /workspace/vendor/ruby/2.6.0/gems/dependabot-common-0.108.15/lib/dependabot/shared_helpers.rb:37:in `chdir'
	 9: from /workspace/vendor/ruby/2.6.0/gems/dependabot-common-0.108.15/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
	 8: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:34:in `block in updated_lockfile_content'
	 7: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:34:in `chdir'
	 6: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:35:in `block (2 levels) in updated_lockfile_content'
	 5: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:115:in `run_current_npm_update'
	 4: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:137:in `run_npm_updater'
	 3: from /workspace/vendor/ruby/2.6.0/gems/dependabot-common-0.108.15/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
	 2: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:139:in `block in run_npm_updater'
	 1: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:151:in `run_npm_top_level_updater'
/workspace/vendor/ruby/2.6.0/gems/dependabot-common-0.108.15/lib/dependabot/shared_helpers.rb:112:in `run_helper_subprocess': 404 Not Found - GET https://registry.npmjs.org/mshell-node-metrics - Not found (Dependabot::SharedHelpers::HelperSubprocessFailed)
	12: from ./generic-update-script.rb:126:in `<main>'
	11: from ./generic-update-script.rb:126:in `each'
	10: from ./generic-update-script.rb:164:in `block in <main>'
	 9: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:39:in `updated_dependency_files'
	 8: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `updated_lockfiles'
	 7: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `each'
	 6: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:149:in `block in updated_lockfiles'
	 5: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:120:in `package_lock_changed?'
	 4: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater.rb:187:in `updated_package_lock_content'
	 3: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:24:in `updated_lockfile_content'
	 2: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:41:in `rescue in updated_lockfile_content'
	 1: from /workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:181:in `handle_npm_updater_error'
/workspace/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.108.15/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:320:in `handle_missing_package': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): artifactory.skyscannertools.net/artifactory/api/npm/npm/ (Dependabot::PrivateSourceAuthenticationFailure)
```

The exact same setup correctly raises PRs when I add an npmrc to the repo in question specifying the default.

**Comment by greysteil** [comment]
Honestly, I don't have many leads on this one, and without the ability to replicate it's going to take me many hours to try to MacGyver it out. If you want to debug locally I'd suggest walking through in a script and when you get to the file updater stage inspecting the `.npmrc` that Dependabot is generating (`file_updater.send(:npm_lockfile_updater).send(:npmrc_content)` should get it for you). My guess is that something is going wrong in generating that, and we can adjust the logic in `NpmrcBuilder` to fix that, but I can't help much more than that without a reproduction case.

**Comment by greysteil** [comment]
OK, in that case the issue is almost certainly in [here](https://github.com/dependabot/dependabot-core/blob/master/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npmrc_builder.rb#L47-L62). That code takes all of the registries you've specified in credentials and loops through them, looking for any unscoped packages that use that registry. If it finds any then it declares it global.

For some reason that line isn't determining that any of the registries you're providing in your credentials are used globally. Hard to figure out why without looking through your lockfile, but making that check more robust is what will fix this.

**Comment by keirlawson** [comment]
We've been looking at fixing this, however we are now unable to recreate, so closing this issue.
