### ISSUE TITLE
Dependabot failing commitlint 

### ISSUE THREAD

**Issue by localredhead** [dependabot/dependabot-core#1357]
Hello.   We have a repository that has been recently converted to use semantic-release.  After we started using semantic release with commitlint dependabot's PRs fail CI checks.

I saw a few other issues related to this that lead me to believe dependabot should be checking and using semantic release if it detects it.

Is there some way to configure it?

Thanks in advance

```Running sanity check... ok
semantic-commitlint: local
😞   Errors found with commit
💬   Bump eslint-utils from 1.3.1 to 1.4.2

Bumps [eslint-utils](https://github.com/mysticatea/eslint-utils) from 1.3.1 to 1.4.2.
- [Release notes](https://github.com/mysticatea/eslint-utils/releases)
- [Commits](https://github.com/mysticatea/eslint-utils/compare/v1.3.1...v1.4.2)

Signed-off-by: dependabot[bot] <support@github.com>

✖   message may not be empty [subject-empty]
✖   type may not be empty [type-empty]
✖   found 2 problems, 0 warnings
{ SemanticReleaseError: The commit message is not formatted correctly
    at /home/circleci/.npm/_npx/3944/lib/node_modules/semantic-commitlint/dist/lint-commits.plugin.js:100:31
    at step (/home/circleci/.npm/_npx/3944/lib/node_modules/semantic-commitlint/dist/lint-commits.plugin.js:32:23)
    at Object.next (/home/circleci/.npm/_npx/3944/lib/node_modules/semantic-commitlint/dist/lint-commits.plugin.js:13:53)
    at fulfilled (/home/circleci/.npm/_npx/3944/lib/node_modules/semantic-commitlint/dist/lint-commits.plugin.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  name: 'SemanticReleaseError',
  code: 'EINVALIDCOMMIT',
  details: undefined,
  semanticRelease: true }
Exited with code 1```

**Comment by greysteil** [comment]
Yes! You can configure from within a config file - the docs are [here](https://dependabot.com/docs/config-file/#commit_message).

**Comment by greysteil** [comment]
Awesome. Automated detection only happens when you first start using Dependabot on a repo, so that makes sense (it keeps  the same style from then on for consistency).
