### ISSUE TITLE
Unexpected git error

### ISSUE THREAD

**Issue by juanjoqmelian** [dependabot/dependabot-core#1373]
We're trying to use `dependabot-core` to update the dependencies in one of our repos and we get an `Unexpected git error!`. It seems that it fails trying to create the pull request, a bit hard to understand the reason from the logs.

```
warning: parser/current is loading parser/ruby26, which recognizes
warning: 2.6.4-compliant syntax, but you are running 2.6.2.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/pull_request_creator/github.rb:64:in `rescue in branch_exists?': Unexpected git error! (RuntimeError)
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/pull_request_creator/github.rb:56:in `branch_exists?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/pull_request_creator/github.rb:42:in `create'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/pull_request_creator.rb:71:in `create'
	from ./my-update-script.rb:147:in `block in <main>'
	from ./my-update-script.rb:95:in `each'
	from ./my-update-script.rb:95:in `<main>'
/home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/git_metadata_fetcher.rb:57:in `fetch_upload_pack_for': The following git URLs could not be retrieved: https://github.mycompany.org/Organisation/Project (Dependabot::GitDependenciesNotReachable)
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/git_metadata_fetcher.rb:16:in `upload_pack'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/git_metadata_fetcher.rb:114:in `parse_refs_for_upload_pack'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/git_metadata_fetcher.rb:108:in `refs_for_upload_pack'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/git_metadata_fetcher.rb:28:in `ref_names'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/pull_request_creator/github.rb:57:in `branch_exists?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/pull_request_creator/github.rb:42:in `create'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.112.32/lib/dependabot/pull_request_creator.rb:71:in `create'
	from ./my-update-script.rb:147:in `block in <main>'
	from ./my-update-script.rb:95:in `each'
	from ./my-update-script.rb:95:in `<main>'
Fetching gradle dependency files for Organisation/Project
Parsing dependencies information
  - Updating pl.allegro.tech.build:axion-release-plugin (from 1.8.1)…%
```

I can see that is reading one of the dependencies in our gradle file, so it seems to be able to access the repository.

**Comment by greysteil** [comment]
Not all of the classes in  Dependabot Core are robust to any input, so if you're using it with Dependabot Script or your own logic you'll need to debug issues yourself. I've added some extra details to the error in [this commit](https://github.com/dependabot/dependabot-core/commit/d27aa5b4067fde0940b45b38668178d9e89b09af) that should help, though.
