### ISSUE TITLE
Error with gitlab file type "commit"

### ISSUE THREAD

**Issue by RodrigoPetter** [dependabot/dependabot-core#1484]
When I try to use dependabot with a Gitlab project that has a submodule I receive the following error:

```
Traceback (most recent call last):
        13: from manual-update-script.rb:5:in `<main>'
        12: from /home/4243730/Documents/dpe-dependabot/dependabot-script.rb:49:in `execute'
        11: from /home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/dependabot-common-0.113.17/lib/dependabot/file_fetchers/base.rb:55:in `files'
        10: from /home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/dependabot-docker-0.113.17/lib/dependabot/docker/file_fetcher.rb:21:in `fetch_files'
         9: from /home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/dependabot-docker-0.113.17/lib/dependabot/docker/file_fetcher.rb:46:in `correctly_encoded_dockerfiles'
         8: from /home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/dependabot-docker-0.113.17/lib/dependabot/docker/file_fetcher.rb:40:in `dockerfiles'
         7: from /home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/dependabot-common-0.113.17/lib/dependabot/file_fetchers/base.rb:110:in `repo_contents'
         6: from /home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/dependabot-common-0.113.17/lib/dependabot/file_fetchers/base.rb:128:in `_fetch_repo_contents'
         5: from /home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/dependabot-common-0.113.17/lib/dependabot/file_fetchers/base.rb:155:in `_fetch_repo_contents_fully_specified'
         4: from /home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/dependabot-common-0.113.17/lib/dependabot/file_fetchers/base.rb:214:in `_gitlab_repo_contents'
         3: from /home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/gitlab-4.12.0/lib/gitlab/paginated_response.rb:22:in `method_missing'
         2: from /home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/gitlab-4.12.0/lib/gitlab/paginated_response.rb:22:in `map'
         1: from /home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/dependabot-common-0.113.17/lib/dependabot/file_fetchers/base.rb:220:in `block in _gitlab_repo_contents'
/home/4243730/Documents/dpe-dependabot/vendor/ruby/2.5.0/gems/gitlab-4.12.0/lib/gitlab/objectified_hash.rb:27:in `method_missing': wrong number of arguments (given 2, expected 1) (ArgumentEr
```

After adding some log to `base.rb` I got the following:
```
file.name: .gitignore
file.type: blob
file.name: .gitlab-ci.yml
file.type: blob
file.name: .gitmodules
file.type: blob
file.name: Dockerfile
file.type: blob
file.name: Readme.md
file.type: blob
file.name: deploy-module
file.type: commit
Traceback (most recent call last):
...
```

My repository structure:
![image](https://user-images.githubusercontent.com/24530396/68030514-6ae2fc80-fc98-11e9-88b2-0fbbf4c638ac.png)

If I make the following addition to the `base.rb` file, everything start to work as expected:
![image](https://user-images.githubusercontent.com/24530396/68030635-ad0c3e00-fc98-11e9-91fd-3c01da6c6969.png)

I'm using GitLab 12.4.0-ee.

**Comment by rebelagentm** [comment]
👋 Thanks for submitting this!  The team is pretty swamped at the moment, so it may be some time before we can look into exactly what's happening here.  However, it seems you may have figured out how to fix this, so if you'd like to submit your code change as a PR, we can review it as soon as we get a chance.  That could definitely help speed things up for us. 😄

**Comment by RodrigoPetter** [comment]
I'll try.

I just think maybe the Gitlab "commit" file type should be translated to "submodule" so the output of `_gitlab_repo_contents` match the output of `_github_repo_contents`.

https://developer.github.com/v3/repos/contents/#response-if-content-is-a-submodule

**Comment by feelepxyz** [comment]
Fixed in https://github.com/dependabot/dependabot-core/pull/1501
