### ISSUE TITLE
Poetry version support

### ISSUE THREAD

**Issue by ulgens** [dependabot/dependabot-core#1556]
Dependabot supports Poetry but it doesn't use given version in pyproject.toml file. When i use any version newer than 1.0.0a1, update check fails because of changed lock file syntax.

**Comment by tommilligan** [comment]
Would also be interested in this. Just upgraded to the newly released poetry v1 and getting the error:

```log
updater | ERROR <job_17789943> Error processing tld (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_17789943>                                   
updater | <job_17789943> [NonExistentKey]   
updater | <job_17789943> 'Key "hashes" does not exist.'  
updater | <job_17789943>                                   
updater | <job_17789943> update [--no-dev] [--dry-run] [--lock] [--] [<packages>]...
updater | <job_17789943> 
```

**Comment by sobolevn** [comment]
I am all in into this change! 

Repo that has this problem: https://github.com/wemake-services/wemake-python-styleguide/blob/master/pyproject.toml

Poetry version is specified in the build file:

```
[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
```

But, it does not work. What website says:
<img width="670" alt="Снимок экрана 2019-12-18 в 11 27 18" src="https://user-images.githubusercontent.com/4660275/71069269-6bbce880-2189-11ea-9b06-268b693da59b.png">

Logs:

```
updater | ERROR <job_18040832> Error processing astboom (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_18040832>                                   
updater | <job_18040832> [NonExistentKey]   
updater | <job_18040832> 'Key "hashes" does not exist.'  
updater | <job_18040832>                                   
updater | <job_18040832> update [--no-dev] [--dry-run] [--lock] [--] [<packages>]...
updater | <job_18040832> 
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/poetry_version_resolver.rb:319:in `run_poetry_command'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/poetry_version_resolver.rb:85:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/shared_helpers.rb:143:in `with_git_configured'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/poetry_version_resolver.rb:73:in `block in fetch_latest_resolvable_version_string'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/shared_helpers.rb:37:in `chdir'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
updater | ERROR <job_18040832> /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/poetry_version_resolver.rb:72:in `fetch_latest_resolvable_version_string'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/poetry_version_resolver.rb:42:in `latest_resolvable_version'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker.rb:43:in `latest_resolvable_version'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:70:in `preferred_resolvable_version'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:233:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:225:in `numeric_version_can_update?'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:175:in `version_can_update?'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:38:in `can_update?'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:208:in `requirements_to_unlock'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:159:in `check_and_create_pull_request'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:62:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:48:in `block in run'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:48:in `each'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:48:in `run'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_18040832> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_18040832> bin/update_files.rb:21:in `<main>'
```

In case making a support for several versions is a hard thing, then I suggest to drop `poetry@0.x` support in favour of `poetry@1.x` support. Because update process is easy for developers.

**Comment by sobolevn** [comment]
At this point I have upgraded almost all my packages to `poetry@1.0` and dependabot almost stoped working to me 😞

**Comment by m-aciek** [comment]
Related pull request: #1571. Related issue on feedback repo: https://github.com/dependabot/feedback/issues/798.

**Comment by gabor-boros** [comment]
Any update on this?

**Comment by cjolowicz** [comment]
The automated pull request for Poetry 1.0.3 is here: https://github.com/dependabot/dependabot-core/pull/1667

**Comment by ulgens** [comment]
https://github.com/dependabot/dependabot-core/pull/1710 

Does anyone have any idea why this test fails?

**Comment by sobolevn** [comment]
dependendabot is not working for me for almost 4 month now. Sadly, but there's nothing I can do about it.

**Comment by tommilligan** [comment]
@ulgens I've submitted PR #1739, which fixes the failing tests you mentioned. The fix is only in the tests themselves, so hopefully should be a quick review.

**Comment by tetienne** [comment]
Issue is now solved.

**Comment by sobolevn** [comment]
Not fully. There are several issues:

1. I got a lot of spam like this: https://github.com/wemake-services/wemake-python-styleguide/issues?q=is%3Aissue+author%3Aapp%2Fdependabot-preview+is%3Aclosed
2. Every dependency update has merge conflicts. Because of the `[metadata].content-hash` field:  https://github.com/wemake-services/wemake-python-styleguide/pull/1287/files#diff-41fe8bebc1a2a52eb5321b759e40b3a8R1627 Now all merge must be done like: merge first -> rebase second -> merge second. I guess it is a problem with `poetry`. Here's the upstream issue: https://github.com/python-poetry/poetry/issues/496 

There's a workaround for the second problem: https://pypi.org/project/poetry-merge-lock/

**Comment by sobolevn** [comment]
Also dependabot cannot update my deps, here's what it says: https://github.com/wemake-services/wemake-python-styleguide/pull/1286#issuecomment-604388383

**Comment by donbowman** [comment]
> Not fully. There are several issues:
> 
> 1. I got a lot of spam like this: https://github.com/wemake-services/wemake-python-styleguide/issues?q=is%3Aissue+author%3Aapp%2Fdependabot-preview+is%3Aclosed
> 2. Every dependency update has merge conflicts. Because of the `[metadata].content-hash` field:  https://github.com/wemake-services/wemake-python-styleguide/pull/1287/files#diff-41fe8bebc1a2a52eb5321b759e40b3a8R1627 Now all merge must be done like: merge first -> rebase second -> merge second. I guess it is a problem with `poetry`. Here's the upstream issue: [python-poetry/poetry#496](https://github.com/python-poetry/poetry/issues/496)
> 
> There's a workaround for the second problem: https://pypi.org/project/poetry-merge-lock/

https://github.com/python-poetry/poetry/pull/2654 is my PR to poetry to try and resolve this issue upstream. It seeks to make content-hash omitted, so no merge conflict.

**Comment by chbndrhnns** [comment]
https://pypi.org/project/poetry-merge-lock/ seems archived now.
Are other known workarounds to this issue?

**Comment by cjolowicz** [comment]
@chbndrhnns These days I use a small shell script with these commands:

```sh
git restore --worktree --staged poetry.lock
poetry lock --no-update
git add poetry.lock
```

See [this comment](https://github.com/python-poetry/poetry/issues/496#issuecomment-738680177) for more details.

**Comment by cjolowicz** [comment]
See also https://github.com/dependabot/dependabot-core/issues/4435

**Comment by jeffwidman** [comment]
I think this can be closed now as similar issues report that Dependabot / poetry seem to play nicely together:
* https://github.com/dependabot/dependabot-core/issues/5554
* https://github.com/dependabot/dependabot-core/issues/4435

There are some further improvements that could be done to to `poetry` itself, but those are outside the scope of this repo and already tracked upstream in https://github.com/python-poetry/poetry/issues/496.

**Comment by ulgens** [comment]
@jeffwidman I don't think those issues solve the problem here. I may be okay with "not planned" but the issue still exists and it got even worse with Poetry 1.2.0. 

During that major update, there were some ordering, capitalization and "-" vs "_" changes in the lock file. We were having issues like these for months: 

* The latest version is X, dependabot is using X - 1. X is generating package names as "Django," as they come from the PyPI API, but X-1 was converting them to "django", all lower case. If someone in the team makes a change in the lock file locally, dependabot was  generating diff with hundreds of lines, just because it's using the old version. At that point, what we need is to tell Dependabot to use X version of the poetry, not the predefined one.

* Latest is X, dependabot is X-1. Lock files have a big difference and dependabot is going slow with the version update, so we as a team a decide use version X-1 too. Then boom, one night dependabot updates itself to use X, without giving any chance to continue with X-1, and the next day we have to tell everyone to update their local version but just a day ago we were telling them not to, please imagine the mess.

**Comment by jeffwidman** [comment]
Thanks for the feedback, it's thanksgiving here so I don't have time to look at this in detail as about to head to family gathering, but re-opening so we don't lose track of this.

**Comment by edgarrmondragon** [comment]
Bump for this. Poetry 1.3 has [a new lock `poetry.lock` format](https://github.com/python-poetry/poetry/pull/6393), so dependabot rewriting the file with the old format 😕

**Comment by phillipuniverse** [comment]
@edgarrmondragon the Poetry 1.3 update in dependabot is at #6302

**Comment by deivid-rodriguez** [comment]
I agree we should do something about this, but it's tricky.

As per https://github.com/python-poetry/poetry/issues/3316, the `poetry-core` version information in the `[build-system]` table in `pyproject.toml` is currently ignored by Poetry, so that does not seem the way to go.

There's a `lock-version` field in the `[metadata]` table, which tells us the format of the lockfile that we should generate, but that's not enough to figure out which version of poetry we should use to generate that format. So the only idea I can think of is the we keep this mapping ourselves, which I guess would work but feels not great.

Just to define what needs to be done here. The right way to figure out the Poetry version to use is to use what's specified in `requires` in the `[build-system]` table, right? So if we have

```
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

```

**Comment by jeffwidman** [comment]
I'm pretty hesitant to get into the business of storing state ourselves on this. Much prefer we wait for `poetry` itself to add support for specifying the minimum working version... Looking at the discussion in https://github.com/python-poetry/poetry/issues/3316, it seems the poetry maintainers are open to the idea, just no one has worked on it yet.

**Comment by deivid-rodriguez** [comment]
I agree with you, I was just sharing the only workaround on our side that I could think of at the moment that does not involve poetry itself recording the version/requirement somehow.

**Comment by xmnlab** [comment]
hi everyone! is this issue still a problem or was it already fixed?

**Comment by deivid-rodriguez** [comment]
Still a problem I think. There's been no movement here, so I don't expect this to have been fixed.

**Comment by xmnlab** [comment]
@deivid-rodriguez, thanks for the quick response!

**Comment by d3QUone** [comment]
Hi team! Any updates here?

**Comment by deivid-rodriguez** [comment]
No news @d3QUone. I will post an update when there's something to share.

**Comment by tianhuil** [comment]
Any updates here?

**Comment by denys-marichev-sumup** [comment]
> Any updates here? Dependabot's commits aren't honoring the python patch version specified in `pyproject.toml`. They consistently replace it in `poetry.lock` with a tilde version specification, causing build failures.

Same problem :smiling_face_with_tear:

**Comment by naglalakk** [comment]
Hi. I don't know anything but just throwing this out there. I was dealing with multiple poetry versions the other day and one answer I came across was to use pipx to install different poetry versions and then label them with the version number. 

If you specify support for certain versions, they could then be picked up from the config and run as such:
https://github.com/orgs/python-poetry/discussions/7866

could something similar be achieved with dependabot?

**Comment by jeffwidman** [comment]
☝️ sounds like a specific bug that isn't related to this general thread of "support multiple versions of poetry/`poetry.lock`"...

Can you spin that off as a specific issue? I can't guarantee that we'll get to it (in fact a PR would be most welcome!) but it should be a _lot_ more tractable to say "retain specific python pin from `pyproject.toml` to `poetry.lock` than it is to say "run with my desired poetry version"... because we should be retaining specific python pins no matter whether we stick with a single poetry version or mutliple.

**Comment by cedric-spinergie** [comment]
Hello!  
My team and I just stumbled upon this but in the opposite direction: we need to stay on `poetry` `1.5.1` while the one used by dependabot is `1.8.3`.  

Would a "quickfix" like specifying the `poetry` version inside the `dependabot.yml` be feasible? Or maybe some place else like in the `pyproject.toml`.

**Comment by saada** [comment]
Even when using 1.8.3, we started getting 1.8.5 changes. I'm assuming dependabot just bumped their version again

**Comment by ulgens** [comment]
It's been 5 years, and the same issue happens between 1.8.5 and 2.0.1 now. Therhas e been a major version update and the lock file has a new version now. Github tries to revert it with each Dependabot run.

**Comment by OldSneerJaw** [comment]
Our build process requires the `poetry export` command, but it has been moved into an optional dependency in Poetry v2 (see [here](https://python-poetry.org/docs/cli#export)). There is a new `tool.poetry.requires-plugins` config option in v2 that lets you set your project's Poetry plugins declaratively, but because Dependabot still uses Poetry 1.8, it considers the configuration file invalid. The solution is to add plugins imperatively ([instructions](https://python-poetry.org/docs/1.8/plugins#using-plugins)), but that's a nuisance because every user that needs to run that command now has to manually install the plugin.

**Comment by d33bs** [comment]
Just a bump to mention I ran into the same as above; using Poetry 2.x configurations (with `requires-plugins` config) causes Dependabot to fail. Hoping we can get a fix for this, thanks in advance!

**Comment by d33bs** [comment]
This issue could possibly be closed through #11642 (and more specific issues moving forward).

**Comment by ulgens** [comment]
@d33bs Issues like #11642 solves a different problem. Having the latest version active is important, but now there won't be a chance to a pre-v2.0.0 version with Github and the projects that stuck with a later version won't be able to update dependabot.

**Comment by edgarrmondragon** [comment]
At least starting with Poetry 2, dependabot should be able to use [`requires-poetry`](https://python-poetry.org/docs/pyproject/#requires-poetry) if available to install a custom Poetry version.

**Comment by ulgens** [comment]
@edgarrmondragon I'm not sure that parameter installs a custom Poetry version. AFAIK,  it only raises an error if the requirement is not met.

**Comment by edgarrmondragon** [comment]
> [@edgarrmondragon](https://github.com/edgarrmondragon) I'm not sure that parameter installs a custom Poetry version. AFAIK, it only raises an error if the requirement is not met.

I know, but Dependabot could use that constraint to install at runtime a Poetry version the project supports.

**Comment by robaiken** [comment]
Closing this for now as we've improved our support for Poetry and Poetry v2. If anyone is still running into issues, [please open a bug report](https://github.com/dependabot/dependabot-core/issues/new?template=bug-report.yml)
