### ISSUE TITLE
Docker: Fails to bump dependency when Dockerfile has multiple images

### ISSUE THREAD

**Issue by felipefill** [dependabot/dependabot-core#1609]
I noticed that dependabot fails to bump a dependency when Dockerfile uses the same image multiple times and one of them is in the latest version. It raises a `No files changed!` exception.

From what I could gather it understands that requirements haven't changed since the previous ones already had the newest version.

e.g.
```
FROM python:3.7.5
FROM python:3.7.6
```

`3.7.6` being the latest version

**Comment by stephenmontgomery** [comment]
Yeah getting here too:

```
updater | INFO <job_600866772> Checking if convictional/trigger-workflow-and-wait 1.6.1 needs updating
  proxy | 2023/02/09 15:47:45 [056] GET https://github.com:443/convictional/trigger-workflow-and-wait.git/info/refs?service=git-upload-pack
  proxy | 2023/02/09 15:47:45 [056] * authenticating git server request (host: github.com)
  proxy | 2023/02/09 15:47:45 [056] 200 https://github.com:443/convictional/trigger-workflow-and-wait.git/info/refs?service=git-upload-pack
updater | INFO <job_600866772> Latest version is 1.6.5
updater | INFO <job_600866772> Requirements to unlock own
updater | INFO <job_600866772> Requirements update strategy 
updater | INFO <job_600866772> Updating convictional/trigger-workflow-and-wait from 1.6.1 to 1.6.5
updater | I, [2023-02-09T15:47:45.974200 #7]  INFO -- sentry: ** [Raven] Sending event 742e87bbac8f494baea9a5f72594757a to Sentry
  proxy | 2023/02/09 15:47:46 [058] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/02/09 15:47:46 [058] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_600866772> Error processing convictional/trigger-workflow-and-wait (RuntimeError)
updater | ERROR <job_600866772> No files changed!
updater | ERROR <job_600866772> /home/dependabot/github_actions/lib/dependabot/github_actions/file_updater.rb:28:in `updated_dependency_files'
updater | ERROR <job_600866772> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:747:in `generate_dependency_files_for'
updater | ERROR <job_600866772> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:311:in `check_and_create_pull_request'
updater | ERROR <job_600866772> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:109:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_600866772> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `block in run'
updater | ERROR <job_600866772> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `each'
updater | ERROR <job_600866772> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `run'
updater | ERROR <job_600866772> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_600866772> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_600866772> bin/update_files.rb:23:in `<main>'
```

Another workflow GH file had already been updated convictional/trigger-workflow-and-wait to 1.6.5.

DP never fixes itself: 
<img width="976" alt="image" src="https://user-images.githubusercontent.com/5411859/217870292-372bdde2-09dd-4567-ada2-c25769d94d9a.png">

**Comment by stephenmontgomery** [comment]
> Your seems like an issue with GitHub Actions while this one was with docker, right?
> 
> I did check that the original issue in here is fixed, so can you report a fresh issue, possibly with a link to a public repository that shows the problem? Thanks!

Ok @deivid-rodriguez raised https://github.com/dependabot/dependabot-core/issues/6634 for it - the same behaviour is observed and pointed me in the right direction as manually updating the dependency and merging fixed DP GitHub checking task. The DP GH task (like all GH actions) runs GH docker image anyway so similar behaviour observed.
