### ISSUE TITLE
Dependabot-bundler error on Ruby 2.7.0: Could not find gem 'Ruby (~> 2.7.0.0)' in the local ruby installation.

### ISSUE THREAD

**Issue by martijnversluis** [dependabot/dependabot-core#1644]
We recently updated our Rails application to Ruby 2.7, but now `dependabot-bundler` is failing with the message `Could not find gem 'Ruby (~> 2.7.0.0)' in the local ruby installation`:

```
Fetching gem metadata from https://rubygems.org/.........
Fetching source index from https://rubygems.org/
/data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-bundler-0.116.3/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb:133:in `handle_bundler_errors': Bundler::GemNotFound with message: Could not find gem 'Ruby (~> 2.7.0.0)' in the local ruby installation. (Dependabot::DependencyFileNotResolvable)
The source contains 'Ruby' at: 2.6.5.114
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-bundler-0.116.3/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb:63:in `rescue in in_a_temporary_bundler_context'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-bundler-0.116.3/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb:38:in `in_a_temporary_bundler_context'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-bundler-0.116.3/lib/dependabot/bundler/update_checker/version_resolver.rb:78:in `block in fetch_latest_resolvable_version_details'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-bundler-0.116.3/lib/dependabot/bundler/update_checker/version_resolver.rb:77:in `fetch_latest_resolvable_version_details'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-bundler-0.116.3/lib/dependabot/bundler/update_checker/version_resolver.rb:43:in `latest_resolvable_version_details'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-bundler-0.116.3/lib/dependabot/bundler/update_checker.rb:189:in `latest_resolvable_version_details'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-bundler-0.116.3/lib/dependabot/bundler/update_checker.rb:26:in `latest_resolvable_version'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/update_checkers/base.rb:70:in `preferred_resolvable_version'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/update_checkers/base.rb:233:in `preferred_version_resolvable_with_unlock?'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/update_checkers/base.rb:225:in `numeric_version_can_update?'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/update_checkers/base.rb:175:in `version_can_update?'
	from /data/gitlab-builds/NMS/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/update_checkers/base.rb:38:in `can_update?'
	from ./gitlab-update-script.rb:108:in `block in <main>'
	from ./gitlab-update-script.rb:91:in `each'
	from ./gitlab-update-script.rb:91:in `<main>'
```

I'm assuming the Ruby version of the application it tries to update the dependencies for, should not affect the working on Dependabot because it runs in its own container using its own Ruby version. Am I missing something?

Thanks in advance for checking!

**Comment by deivid-rodriguez** [comment]
Sorry @martijnversluis for not replying to this ticket earlier. Are you still having this issue? I have not seen this error for a long time so I believe it's actually fixed!
