### ISSUE TITLE
 Seeing error "comparison of String with Dependabot::GoModules::Version failed (ArgumentError)"

### ISSUE THREAD

**Issue by elptacek** [dependabot/dependabot-core#1649]
When I run the dry_run.rb script in the dependabot docker dev shell to check one dependency in the kubernetes/kubernetes go.mod file, I see an error as follows

> dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb go_modules kubernetes/kubernetes --dep "cloud.google.com/go"
> => fetching dependency files
> => dumping fetched dependency files: ./dry-run/kubernetes/kubernetes/
> => parsing dependency files
> => updating 1 dependencies
> 
> === cloud.google.com/go (0.38.0)
>  => checking for updates
>  => latest version from registry is 0.38.0
>  => latest resolvable version is 0.38.0
> Traceback (most recent call last):
> 	6: from bin/dry-run.rb:402:in `<main>'
> 	5: from bin/dry-run.rb:402:in `each'
> 	4: from bin/dry-run.rb:410:in `block in <main>'
> 	3: from /home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:27:in `up_to_date?'
> 	2: from /home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:165:in `version_up_to_date?'
> 	1: from /home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:214:in `numeric_version_up_to_date?'
/home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:214:in `<=': comparison of String with Dependabot::GoModules::Version failed (ArgumentError)

I modified my local copy of dependabot core at line 214 of common/lib/dependabot/update_checkers/base.rb (https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/update_checkers/base.rb#L214) to append the .version method at the end of version_class.new(dependency.version) and ran the same command again:

> [dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb go_modules kubernetes/kubernetes --dep "cloud.google.com/go"
> => fetching dependency files
> => dumping fetched dependency files: ./dry-run/kubernetes/kubernetes/
> => parsing dependency files
> => updating 1 dependencies
> 
> === cloud.google.com/go (0.38.0)
>  => checking for updates
>  => latest version from registry is 0.38.0
>  => latest resolvable version is 0.38.0
>     (no update needed)

This time, successful. Maybe this is a bug? I see this same line of code in a few other places in the update_checkers/base.rb file, but I've not successfully triggered those conditions.

**Comment by elptacek** [comment]
Seems to be only for that one dependency? 

> [dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb go_modules kubernetes/kubernetes --dep github.com/Azure/azure-sdk-for-go
> => fetching dependency files
> => dumping fetched dependency files: ./dry-run/kubernetes/kubernetes/
> => parsing dependency files
> => updating 1 dependencies
> 
> === github.com/Azure/azure-sdk-for-go (35.0.0+incompatible)
>  => checking for updates
>  => latest version from registry is 35.1.0+incompatible
>  => latest resolvable version is 35.1.0+incompatible
> Dependabot::GoModules::Version
> Dependabot::GoModules::Version
> Dependabot::GoModules::Version
> Dependabot::GoModules::Version
>  => requirements to unlock: own
>  => requirements update strategy: 
> Dependabot::GoModules::Version
> Dependabot::GoModules::Version
> Dependabot::GoModules::Version
> Dependabot::GoModules::Version
>  => updating github.com/Azure/azure-sdk-for-go from 35.0.0+incompatible to 35.1.0+incompatible
> 
>     ± go.mod
>     ~~~
>     11c11
>     < 	github.com/Azure/azure-sdk-for-go v35.0.0+incompatible
>     ---
>     > 	github.com/Azure/azure-sdk-for-go v35.1.0+incompatible
>     ~~~
> [dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb go_modules kubernetes/kubernetes --dep cloud.google.com/go
> => fetching dependency files
> => dumping fetched dependency files: ./dry-run/kubernetes/kubernetes/
> => parsing dependency files
> => updating 1 dependencies
> 
> === cloud.google.com/go (0.38.0)
>  => checking for updates
>  => latest version from registry is 0.38.0
>  => latest resolvable version is 0.38.0
> Dependabot::GoModules::Version
> String
> Traceback (most recent call last):
> 	6: from bin/dry-run.rb:401:in `<main>'
> 	5: from bin/dry-run.rb:401:in `each'
> 	4: from bin/dry-run.rb:409:in `block in <main>'
> 	3: from /home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:27:in `up_to_date?'
> 	2: from /home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:165:in `version_up_to_date?'
> 	1: from /home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:217:in `numeric_version_up_to_date?'
> /home/dependabot/dependabot-core/common/lib/dependabot/update_checkers/base.rb:217:in `<=': comparison of String with Dependabot::GoModules::Version failed (ArgumentError)

**Comment by elptacek** [comment]
This is the last comment I will leave for a while, because I need to move on with what I am working on, but from what I'm seeing, some dependencies hit this line of code 

https://github.com/dependabot/dependabot-core/blob/master/go_modules/lib/dependabot/go_modules/update_checker.rb#L19

Where if the dependency has no requirements, it doesn't pass the dependency.top_level? check. The comments in this function make me wonder if this is because dependencies without requirements are "indirect dependencies"; I don't exactly understand what this means. In the case of cloud.google.com/go, the requirements array is empty, which triggers this condition and the function returns a String instead of a Dependabot::GoModules::Version object. But if I run the find_latest_resolvable_version function against the cloud.google.com/go dependency, it shows me that the latest version is v0.52.0 (the version in the go.mod file is 0.38.0. 

Even though I have to move on, I'm eventually going to have to circle back and get this working. I'd be curious to know what's going on here.
