### ISSUE TITLE
Azure DevOps build fails and only a few PRs are created (Octokit::TooManyRequests)

### ISSUE THREAD

**Issue by Bertk** [dependabot/dependabot-core#1651]
Hi, Is it possible to reduce number of PRs or enable caching to reduce the amount of request?

I created a Azure DevOps build pipeline which creates PRs to update nuget packages and this pipeline only works for some small projects. 

gem: dependabot-omnibus 0.116.3

```
2020-01-26T09:38:44.4604666Z /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/octokit-4.15.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/fluentassertions/fluentassertions/commits?sha=5.9.0: 403 - API rate limit exceeded for 104.45.91.43. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting (Octokit::TooManyRequests)
2020-01-26T09:38:44.4605680Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/faraday-1.0.0/lib/faraday/response.rb:12:in `block in call'
2020-01-26T09:38:44.4606211Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/faraday-1.0.0/lib/faraday/response.rb:62:in `on_complete'
2020-01-26T09:38:44.4606672Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/faraday-1.0.0/lib/faraday/response.rb:11:in `call'
2020-01-26T09:38:44.4607251Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/octokit-4.15.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
2020-01-26T09:38:44.4607742Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/octokit-4.15.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
2020-01-26T09:38:44.4608260Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/faraday-1.0.0/lib/faraday/request/retry.rb:148:in `call'
2020-01-26T09:38:44.4609142Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/faraday-1.0.0/lib/faraday/rack_builder.rb:153:in `build_response'
2020-01-26T09:38:44.4609610Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/faraday-1.0.0/lib/faraday/connection.rb:492:in `run_request'
2020-01-26T09:38:44.4610112Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/faraday-1.0.0/lib/faraday/connection.rb:198:in `get'
2020-01-26T09:38:44.4610546Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
2020-01-26T09:38:44.4611065Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/octokit-4.15.0/lib/octokit/connection.rb:156:in `request'
2020-01-26T09:38:44.4611568Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/octokit-4.15.0/lib/octokit/connection.rb:84:in `paginate'
2020-01-26T09:38:44.4612026Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/octokit-4.15.0/lib/octokit/client/commits.rb:29:in `commits'
2020-01-26T09:38:44.4612595Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/clients/github_with_retries.rb:95:in `public_send'
2020-01-26T09:38:44.4613124Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/clients/github_with_retries.rb:95:in `block in method_missing'
2020-01-26T09:38:44.4613761Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/clients/github_with_retries.rb:115:in `retry_connection_failures'
2020-01-26T09:38:44.4614494Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/clients/github_with_retries.rb:92:in `method_missing'
2020-01-26T09:38:44.4615041Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/metadata_finders/base/commits_finder.rb:240:in `fetch_github_commits'
2020-01-26T09:38:44.4615627Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/metadata_finders/base/commits_finder.rb:43:in `commits'
2020-01-26T09:38:44.4616126Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/metadata_finders/base.rb:106:in `commits'
2020-01-26T09:38:44.4617346Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/pull_request_creator/message_builder.rb:520:in `commits'
2020-01-26T09:38:44.4617982Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/pull_request_creator/message_builder.rb:411:in `commits_cascade'
2020-01-26T09:38:44.4618539Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/pull_request_creator/message_builder.rb:311:in `metadata_cascades_for_dep'
2020-01-26T09:38:44.4619134Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/pull_request_creator/message_builder.rb:288:in `metadata_cascades'
2020-01-26T09:38:44.4619724Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/pull_request_creator/message_builder.rb:47:in `pr_message'
2020-01-26T09:38:44.4620234Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/pull_request_creator.rb:142:in `azure_creator'
2020-01-26T09:38:44.4620789Z 	from /opt/hostedtoolcache/Ruby/2.6.5/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.116.3/lib/dependabot/pull_request_creator.rb:75:in `create'
2020-01-26T09:38:44.4621139Z 	from ./update.rb:105:in `block in <main>'
2020-01-26T09:38:44.4621483Z 	from ./update.rb:53:in `each'
2020-01-26T09:38:44.4621768Z 	from ./update.rb:53:in `<main>'
```

**Comment by Bertk** [comment]
Found the solution here #942 and solved it.

```
credentials = [{
  "type" => "git_source",
  "host" => "dev.azure.com",
  "username" => "",
  "password" => ENV["SYSTEM_ACCESSTOKEN"]
},{
  "type" => "git_source",
  "host" => "github.com",
  "username" => "x-access-token",
  "password" => ENV["GITHUB_ACCESS_TOKEN"] # A GitHub access token with read access to public repos
},{ ...
```
