### ISSUE TITLE
JavaScript yarn/npm updates timing out with missing keyword: security_updates_only

### ISSUE THREAD

**Issue by dpraul** [dependabot/dependabot-core#1672]
This is happening across multiple repos in `fintechstudios`.

```
  proxy | time="2020-02-03T13:53:04Z" level=info msg="proxy starting" commit=c112a5a5cd86983046156e55becbc0d14ef9cb3e
  proxy | 2020/02/03 13:53:04 Listening (:1080)
fetcher | yarn config v1.21.1
fetcher | success Set "cafile" to "/etc/ssl/certs/ca-certificates.crt".
fetcher | Done in 0.03s.
fetcher | INFO <job_22309353> Starting job processing
fetcher | ERROR <job_22309353> Error during file fetching; aborting
fetcher | ERROR <job_22309353> missing keyword: security_updates_only
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/job.rb:13:in `initialize'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `new'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `job'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:73:in `file_fetcher'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:63:in `base_commit_sha'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:11:in `perform_job'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
fetcher | ERROR <job_22309353> bin/fetch_files.rb:21:in `<main>'
fetcher | ERROR <job_22309353> missing keyword: security_updates_only
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/job.rb:13:in `initialize'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `new'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `job'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:94:in `raven_context'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:122:in `handle_file_fetcher_error'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:15:in `rescue in perform_job'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:10:in `perform_job'
fetcher | ERROR <job_22309353> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
fetcher | ERROR <job_22309353> bin/fetch_files.rb:21:in `<main>'
fetcher | /home/dependabot/dependabot-updater/lib/dependabot/job.rb:13:in `initialize': missing keyword: security_updates_only (ArgumentError)
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `new'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:94:in `raven_context'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:40:in `handle_exception'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:32:in `rescue in run'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:27:in `run'
fetcher | 	from bin/fetch_files.rb:21:in `<main>'
fetcher | /home/dependabot/dependabot-updater/lib/dependabot/job.rb:13:in `initialize': missing keyword: security_updates_only (ArgumentError)
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `new'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:94:in `raven_context'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:122:in `handle_file_fetcher_error'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:15:in `rescue in perform_job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:10:in `perform_job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
fetcher | 	from bin/fetch_files.rb:21:in `<main>'
fetcher | /home/dependabot/dependabot-updater/lib/dependabot/job.rb:13:in `initialize': missing keyword: security_updates_only (ArgumentError)
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `new'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:59:in `job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:73:in `file_fetcher'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:63:in `base_commit_sha'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:11:in `perform_job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
fetcher | 	from bin/fetch_files.rb:21:in `<main>'
```

**Comment by feelepxyz** [comment]
@dpraul thanks for reporting. Working on a fix 👍

**Comment by feelepxyz** [comment]
@dpraul just deployed a fix for the above. Thanks again for reporting 🙇

**Comment by dpraul** [comment]
Appears to be working!
