### ISSUE TITLE
Don't fail in air-gapped environments

### ISSUE THREAD

**Issue by augi** [dependabot/dependabot-core#1696]
I'm running Dependabot via [dependabot-script](https://github.com/dependabot/dependabot-script) in air-gapped environment, it means that even github.com cannot be accessed.

Now, Depedabot correctly finds a new version (e.g. wants to upgrade junit from 4.12 to 4.13) because it correctly reads address of our internal repositories (from `build.gradle`) but then fails when constructing PR message because it cannot fetch information about the new release from github.com

It would be great if a new PR were created even in case of a connection failure. The body of the PR could contain just link to the GitHub page instead.

```
 /usr/lib/ruby/2.6.0/net/http.rb:947:in `initialize': execution expired (Net::OpenTimeout)
 	from /usr/lib/ruby/2.6.0/net/http.rb:947:in `open'
 	from /usr/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
 	from /usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
 	from /usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
 	from /usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
 	from /usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
 	from /usr/lib/ruby/2.6.0/net/http.rb:1470:in `request'
 	from /usr/lib/ruby/2.6.0/net/http.rb:1228:in `get'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:85:in `perform_request'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:43:in `block in call'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-0.17.1/lib/faraday/adapter/net_http.rb:38:in `call'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-0.17.1/lib/faraday/response.rb:8:in `call'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-0.17.1/lib/faraday/response.rb:8:in `call'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-0.17.1/lib/faraday/request/retry.rb:131:in `call'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-0.17.1/lib/faraday/rack_builder.rb:143:in `build_response'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-0.17.1/lib/faraday/connection.rb:387:in `run_request'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/faraday-0.17.1/lib/faraday/connection.rb:138:in `get'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.14.0/lib/octokit/connection.rb:156:in `request'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.14.0/lib/octokit/connection.rb:19:in `get'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.14.0/lib/octokit/client/contents.rb:36:in `contents'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/clients/github_with_retries.rb:95:in `public_send'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/clients/github_with_retries.rb:95:in `block in method_missing'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/clients/github_with_retries.rb:115:in `retry_connection_failures'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/clients/github_with_retries.rb:92:in `method_missing'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/metadata_finders/base/changelog_finder.rb:263:in `fetch_github_file_list'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/metadata_finders/base/changelog_finder.rb:245:in `fetch_dependency_file_list'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/metadata_finders/base/changelog_finder.rb:240:in `dependency_file_list'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/metadata_finders/base/changelog_finder.rb:141:in `changelog_from_ref'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/metadata_finders/base/changelog_finder.rb:129:in `default_branch_changelog'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/metadata_finders/base/changelog_finder.rb:89:in `changelog'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/metadata_finders/base/changelog_finder.rb:36:in `changelog_url'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/metadata_finders/base.rb:40:in `changelog_url'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/pull_request_creator/message_builder.rb:503:in `changelog_url'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/pull_request_creator/message_builder.rb:283:in `metadata_links_for_dep'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/pull_request_creator/message_builder.rb:270:in `metadata_links'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/pull_request_creator/message_builder.rb:53:in `commit_message'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/pull_request_creator.rb:102:in `github_creator'
 	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/pull_request_creator.rb:73:in `create'
 	from ./generic-update-script.rb:182:in `block in <main>'
 	from ./generic-update-script.rb:130:in `each'
 	from ./generic-update-script.rb:130:in `<main>'
```

**Comment by augi** [comment]
This is still desired improvement.

**Comment by jurre** [comment]
Dependabot is pretty dependant on GitHub, the vast majority of the time it runs with access to the internet. We don't have the capacity to add support for air-gapped environment support, so I'm going to close out this issue.
