### ISSUE TITLE
Dependabot failing in Azure Repos

### ISSUE THREAD

**Issue by EwanNoble** [dependabot/dependabot-core#1723]
Hi there, I'm currently trying and failing to run dependabot within Azure Repos, it is always failing on this particular line after it's first PR per repo:
https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L378

Error message: `undefined method 'message' `

Backtrace: 
```
["/var/lib/gems/2.6.0/gems/dependabot-common-0.117.1/lib/dependabot/pull_request_creator/pr_name_prefixer.rb:378:in `last_azure_dependabot_commit_message'", "/var/lib/gems/2.6.0/gems/dependabot-common-0.117.1/lib/dependabot/pull_request_creator/pr_name_prefixer.rb:340:in `last_dependabot_commit_message'", "/var/lib/gems/2.6.0/gems/dependabot-common-0.117.1/lib/dependabot/pull_request_creator/pr_name_prefixer.rb:162:in `last_dependabot_commit_style'", "/var/lib/gems/2.6.0/gems/dependabot-common-0.117.1/lib/dependabot/pull_request_creator/pr_name_prefixer.rb:72:in `commit_prefix'", "/var/lib/gems/2.6.0/gems/dependabot-common-0.117.1/lib/dependabot/pull_request_creator/pr_name_prefixer.rb:39:in `pr_name_prefix'", "/var/lib/gems/2.6.0/gems/dependabot-common-0.117.1/lib/dependabot/pull_request_creator/message_builder.rb:38:in `pr_name'", "/var/lib/gems/2.6.0/gems/dependabot-common-0.117.1/lib/dependabot/pull_request_creator/message_builder.rb:104:in `commit_subject'", "/var/lib/gems/2.6.0/gems/dependabot-common-0.117.1/lib/dependabot/pull_request_creator/message_builder.rb:51:in `commit_message'", "/var/lib/gems/2.6.0/gems/dependabot-common-0.117.1/lib/dependabot/pull_request_creator.rb:141:in `azure_creator'", "/var/lib/gems/2.6.0/gems/dependabot-common-0.117.1/lib/dependabot/pull_request_creator.rb:75:in `create'", "/home/dependabot/azure_processor.rb:291:in `block in process_dependency'", "/home/dependabot/azure_processor.rb:234:in `each'", "/home/dependabot/azure_processor.rb:234:in `process_dependency'", "/home/dependabot/azure_processor.rb:58:in `block in process_repo'", "/home/dependabot/azure_processor.rb:58:in `each'", "/home/dependabot/azure_processor.rb:58:in `process_repo'", "/home/dependabot/azure_processor.rb:47:in `block in process_project'", "/home/dependabot/azure_processor.rb:47:in `each'", "/home/dependabot/azure_processor.rb:47:in `process_project'", "/home/dependabot/azure_processor.rb:32:in `block in process'", "/home/dependabot/azure_processor.rb:32:in `each'", "/home/dependabot/azure_processor.rb:32:in `process'", "run.rb:18:in `<main>'"]
```

Unfortunately I'm not too clued up on Ruby but I'm wondering if this should be `.comment` rather than `.message`  as it is on these lines https://github.com/dependabot/dependabot-core/blob/master/common/lib/dependabot/pull_request_creator/pr_name_prefixer.rb#L318-L319 
(message isn't a property on the returned object: https://docs.microsoft.com/en-us/rest/api/azure/devops/git/commits/get%20commits?view=azure-devops-rest-5.1#gitcommitref )

Any help here would be appreciated!

**Comment by GiriB** [comment]
@EwanNoble  did you ever find a fix for this?

**Comment by jurre** [comment]
I'm going to close this issue because it does not seem like an issue on the Dependabot side but rather in third-party code that uses the library
