### ISSUE TITLE
Dependabot encountered an unknown error

### ISSUE THREAD

**Issue by FabianKoestring** [dependabot/dependabot-core#1759]
see #1730 

Hey there,

we currently getting dependabot exceptions for our php projects. Is there a problem with our project or is this a bug? Yesterday everything worked as expected.

> Dependabot encountered an unknown error.
> We've been notified of the problem, and are working to fix it.

```console
updater | ERROR <job_27354177> Error processing knplabs/github-api (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_27354177> syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST)
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.117.3/lib/dependabot/shared_helpers.rb:111:in `run_helper_subprocess'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.117.3/lib/dependabot/composer/file_updater/lockfile_updater.rb:93:in `block in run_update_helper'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.117.3/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.117.3/lib/dependabot/composer/file_updater/lockfile_updater.rb:92:in `run_update_helper'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.117.3/lib/dependabot/composer/file_updater/lockfile_updater.rb:65:in `block in generate_updated_lockfile_content'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.117.3/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.117.3/lib/dependabot/shared_helpers.rb:37:in `chdir'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.117.3/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
updater | ERROR <job_27354177> /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.117.3/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.117.3/lib/dependabot/composer/file_updater/lockfile_updater.rb:62:in `generate_updated_lockfile_content'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.117.3/lib/dependabot/composer/file_updater/lockfile_updater.rb:46:in `updated_lockfile_content'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.117.3/lib/dependabot/composer/file_updater.rb:64:in `updated_lockfile_content'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-composer-0.117.3/lib/dependabot/composer/file_updater.rb:34:in `updated_dependency_files'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:418:in `generate_dependency_files_for'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:216:in `check_and_create_pull_request'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:62:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:48:in `block in run'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:48:in `each'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:48:in `run'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_27354177> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_27354177> bin/update_files.rb:21:in `<main>'
```

**Comment by jurre** [comment]
I believe this is resolved by #1730, lmk if it isn't
