### ISSUE TITLE
PrivateSourceAuthenticationFailure : Accessing a private pypi with env variables in extra-index-url

### ISSUE THREAD

**Issue by SVilgelm** [dependabot/dependabot-core#1772]
Hi,

I faced an issue with a private pypi repo. The extra-index-url is configured in the requirements.txt file:

```pip
requirements.txt 
--extra-index-url https://${PYPI_USER}:${PYPI_PASSWORD}@artifactory.<....>/artifactory/api/pypi/<....>/simple/

Flask==0.12.2
Flask-Cors==3.0.8
cb-common==1.10.0
...
```
As you can see it uses env variables `PYPI_USER` and `PYPI_PASSWORD`

I passed these variables to the dependabot-script docker container:

```bash
docker run --rm \
-v "$(pwd):/home/dependabot/dependabot-script" \
-w /home/dependabot/dependabot-script \
-e PACKAGE_MANAGER="pip" \
-e PROJECT_PATH="$1" \
-e GITHUB_ENTERPRISE_ACCESS_TOKEN="${GHE_TOKEN}" \
-e GITHUB_ENTERPRISE_HOSTNAME="..." \
-e PYPI_USER="${PYPI_USER}" \
-e PYPI_PASSWORD="${PYPI_PASSWORD}" \
dependabot/dependabot-core \
bundle exec ruby ./generic-update-script.rb
```

but it fails with:

```
% ./run_py.sh <.....>
NOTE: Inheriting Faraday::Error::ClientError is deprecated; use Faraday::ClientError instead. It will be removed in or after version 1.0
Faraday::Error::ClientError.inherited called from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/octokit-4.14.0/lib/octokit/middleware/follow_redirects.rb:14.
Fetching pip dependency files for <....>
Parsing dependencies information
/home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/index_finder.rb:179:in `clean_check_and_remove_environment_variables': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): https://${PYPI_USER}:${PYPI_PASSWORD}@artifactory.<....>/artifactory/api/pypi/<....>/simple/ (Dependabot::PrivateSourceAuthenticationFailure)
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/index_finder.rb:28:in `block in index_urls'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/index_finder.rb:27:in `map'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/index_finder.rb:27:in `index_urls'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/latest_version_finder.rb:203:in `index_urls'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/latest_version_finder.rb:139:in `available_versions'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/latest_version_finder.rb:49:in `fetch_latest_version'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker/latest_version_finder.rb:30:in `latest_version'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker.rb:256:in `fetch_latest_version'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-python-0.113.28/lib/dependabot/python/update_checker.rb:32:in `latest_version'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:207:in `numeric_version_up_to_date?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:165:in `version_up_to_date?'
	from /home/dependabot/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:27:in `up_to_date?'
	from ./generic-update-script.rb:140:in `block in <main>'
	from ./generic-update-script.rb:130:in `each'
	from ./generic-update-script.rb:130:in `<main>'
```

**Comment by SVilgelm** [comment]
Looks like it's a dup of #1681
