### ISSUE TITLE
Error start_with invalid byte sequence in latest_version_finder

### ISSUE THREAD

**Issue by laurieplo** [dependabot/dependabot-core#1800]
Got the following error on a yarn dependabot job : 
```
/usr/local/bundle/gems/dependabot-npm_and_yarn-0.117.6/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:339:in `start_with?': invalid byte sequence in US-ASCII (ArgumentError)
```

I experienced the same issue with a PHP package few months ago but upgrading dependabot-core fixed the issue. Now I reproduce the problem on a yarn package.

```
Traceback (most recent call last):
	14: from main.rb:101:in `<main>'
	13: from main.rb:101:in `each'
	12: from main.rb:111:in `block in <main>'
	11: from /usr/local/bundle/gems/dependabot-common-0.117.6/lib/dependabot/update_checkers/base.rb:27:in `up_to_date?'
	10: from /usr/local/bundle/gems/dependabot-common-0.117.6/lib/dependabot/update_checkers/base.rb:165:in `version_up_to_date?'
	 9: from /usr/local/bundle/gems/dependabot-common-0.117.6/lib/dependabot/update_checkers/base.rb:207:in `numeric_version_up_to_date?'
	 8: from /usr/local/bundle/gems/dependabot-npm_and_yarn-0.117.6/lib/dependabot/npm_and_yarn/update_checker.rb:22:in `latest_version'
	 7: from /usr/local/bundle/gems/dependabot-npm_and_yarn-0.117.6/lib/dependabot/npm_and_yarn/update_checker.rb:197:in `latest_version_details'
	 6: from /usr/local/bundle/gems/dependabot-npm_and_yarn-0.117.6/lib/dependabot/npm_and_yarn/update_checker.rb:170:in `latest_released_version'
	 5: from /usr/local/bundle/gems/dependabot-npm_and_yarn-0.117.6/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:33:in `latest_version_from_registry'
	 4: from /usr/local/bundle/gems/dependabot-npm_and_yarn-0.117.6/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:99:in `valid_npm_details?'
	 3: from /usr/local/bundle/gems/dependabot-npm_and_yarn-0.117.6/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:271:in `npm_details'
	 2: from /usr/local/bundle/gems/dependabot-npm_and_yarn-0.117.6/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:316:in `check_npm_response'
	 1: from /usr/local/bundle/gems/dependabot-npm_and_yarn-0.117.6/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:339:in `private_dependency_not_reachable?'
/usr/local/bundle/gems/dependabot-npm_and_yarn-0.117.6/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:339:in `start_with?': invalid byte sequence in US-ASCII (ArgumentError)
```

**Comment by fatroom** [comment]
For me it helped to set the proper locale on the host where dependabot runs.
As example following helped to solve this problem:

    ENV LANG C.UTF-8

**Comment by mattt** [comment]
Hi @laurieplo. I think @fatroom's advice to set a UTF-8 locale in your runner environment should fix your issue. You may also try [this solution by @wengjq](https://github.com/dependabot/dependabot-core/issues/3869#issuecomment-868146517):

```shell
export RUBYOPT="-KU -E utf-8:utf-8"
```
