### ISSUE TITLE
Rights access issue on private dependency

### ISSUE THREAD

**Issue by laurieplo** [dependabot/dependabot-core#1811]
I have this error message since 0.112.0 that was not there before. It is on a composer private repository dependency.

```
/usr/local/bundle/gems/dependabot-common-0.113.28/lib/dependabot/git_metadata_fetcher.rb:57:in `fetch_upload_pack_for': The following git URLs could not be retrieved: XXX (Dependabot::GitDependenciesNotReachable)
 	from /usr/local/bundle/gems/dependabot-common-0.113.28/lib/dependabot/git_metadata_fetcher.rb:16:in `upload_pack'
 	from /usr/local/bundle/gems/dependabot-common-0.113.28/lib/dependabot/git_metadata_fetcher.rb:114:in `parse_refs_for_upload_pack'
 	from /usr/local/bundle/gems/dependabot-common-0.113.28/lib/dependabot/git_metadata_fetcher.rb:108:in `refs_for_upload_pack'
 	from /usr/local/bundle/gems/dependabot-common-0.113.28/lib/dependabot/git_metadata_fetcher.rb:41:in `head_commit_for_ref'
 	from /usr/local/bundle/gems/dependabot-common-0.113.28/lib/dependabot/git_commit_checker.rb:83:in `head_commit_for_current_branch'
 	from /usr/local/bundle/gems/dependabot-composer-0.113.28/lib/dependabot/composer/update_checker.rb:148:in `latest_version_for_git_dependency'
 	from /usr/local/bundle/gems/dependabot-composer-0.113.28/lib/dependabot/composer/update_checker.rb:18:in `latest_version'
 	from /usr/local/bundle/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:187:in `sha1_version_up_to_date?'
 	from /usr/local/bundle/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:163:in `version_up_to_date?'
 	from /usr/local/bundle/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:27:in `up_to_date?'
 	from main.rb:111:in `block in <main>'
 	from main.rb:101:in `each'
 	from main.rb:101:in `<main>'
`
``

**Comment by jeffwidman** [comment]
This is an ancient ticket, from before Dependabot ran on GitHub native... so our code and security access patterns/authorization requirements have changed a lot since then. So I'm going to close.

If this is still an issue please comment and we can re-open.

Possibly related:
* https://github.com/dependabot/dependabot-core/issues/3628
