### ISSUE TITLE
Checking golang dependencies error

### ISSUE THREAD

**Issue by michaellihs** [dependabot/dependabot-core#1870]
**Package manage/ecosystem**
bundler
**Manifest contents prior to update**
```
module abdc

go 1.12

require github.com/go-playground/log v6.3.0+incompatible
```
**Updated dependency**
```
github.com/go-playground/log v6.3.0+incompatible
```
**What you expected to see, versus what you actually saw**
Expect to either see a pull request being created or dependabot exiting peacefully.
Instead, I see the following error:

```
Parsing dependencies information
Traceback (most recent call last):
	21: from ./update.rb:93:in `<main>'
	20: from ./update.rb:93:in `each'
	19: from ./update.rb:103:in `block in <main>'
	18: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:27:in `up_to_date?'
	17: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:165:in `version_up_to_date?'
	16: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:207:in `numeric_version_up_to_date?'
	15: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-go_modules-0.113.28/lib/dependabot/go_modules/update_checker.rb:22:in `latest_version'
	14: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-go_modules-0.113.28/lib/dependabot/go_modules/update_checker.rb:15:in `latest_resolvable_version'
	13: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-go_modules-0.113.28/lib/dependabot/go_modules/update_checker.rb:39:in `find_latest_resolvable_version'
	12: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
	11: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	10: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
	 9: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/shared_helpers.rb:37:in `chdir'
	 8: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
	 7: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-go_modules-0.113.28/lib/dependabot/go_modules/update_checker.rb:40:in `block in find_latest_resolvable_version'
	 6: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/shared_helpers.rb:143:in `with_git_configured'
	 5: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-go_modules-0.113.28/lib/dependabot/go_modules/update_checker.rb:47:in `block (2 levels) in find_latest_resolvable_version'
	 4: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/shared_helpers.rb:92:in `run_helper_subprocess'
	 3: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/2.6.0/open3.rb:281:in `capture3'
	 2: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/2.6.0/open3.rb:101:in `popen3'
	 1: from /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/2.6.0/open3.rb:213:in `popen_run'
/Users/mimi/.rbenv/versions/2.6.5/lib/ruby/2.6.0/open3.rb:213:in `spawn': No such file or directory - /Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-go_modules-0.113.28/helpers/install-dir/go_modules/bin/helper (Errno::ENOENT)
```

I can see that dependabot tries to run `/Users/mimi/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/dependabot-go_modules-0.113.28/helpers/install-dir/go_modules/bin/helper` but there is no `install-dir` within this gem. Do I miss an installation step?

**Comment by michaellihs** [comment]
Since this might be helpful for others who run into the same issue, here is the solution to the problem above:

Make sure to read the [README for the go_modules](https://github.com/dependabot/dependabot-core/blob/master/go_modules/README.md) that provides the command for installing the go helpers:

```bash
helpers/build "$(pwd)/helpers/install-dir/go_modules"
```

To add this to your build pipeline, you can run the following commands:

```bash
gem install bundler
bundle install --retry=3 --jobs=4
# see https://github.com/dependabot/dependabot-core/blob/master/go_modules/README.md
cd $(gem environment gemdir)/gems/dependabot-go_modules-0.113.28 && helpers/build "$(pwd)/helpers/install-dir/go_modules"
```
