### ISSUE TITLE
Exhaustive list of package-ecosystem values is not documented

### ISSUE THREAD

**Issue by lexicalunit** [dependabot/dependabot-core#1925]
According to https://dependabot.com/blog/announcing-poetry-support/ dependabot has supported Poetry since 2018. However I don't see `poetry` as an option documented for `package-ecosystem` here: https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem

Is `poetry` not the correct value to use for `package-ecosystem` in the configuration for dependabot? Where is the complete list of supported values documented? If it's only the values shown in the page I linked, then does that mean Poetry support has been dropped recently?

It's just not very clear. I'd like to see some documentation on the supported values for `package-ecosystem` or some documentation on how to enable Poetry support.

**Comment by feelepxyz** [comment]
> According to https://dependabot.com/blog/announcing-poetry-support/ dependabot has supported Poetry since 2018. However I don't see `poetry` as an option documented for `package-ecosystem` here: https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates#package-ecosystem

Yeah sorry about the confusion here, you can specify `pip` which will also work for poetry. Currently, all python package managers supported by dependabot are in a shared codebase. We're planning to split these out in future which is why we opted for pip as the most common one.

**Comment by lexicalunit** [comment]
I tried using `pip` here: https://github.com/lexicalunit/spellbot/blob/master/.github/dependabot.yml -- but I got a ton of errors that look like:

```
updater | ERROR <job_40324635> Error processing pytest-freezegun (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_40324635> pyenv: version `3.8.3' is not installed (set by /home/dependabot/dependabot-updater/tmp/dependabot_20200728-73-1gd5ulc/.python-version)
updater | 
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:317:in `run_poetry_command'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:84:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:72:in `block in fetch_latest_resolvable_version_string'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:37:in `chdir'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
updater | ERROR <job_40324635> /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:71:in `fetch_latest_resolvable_version_string'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker/poetry_version_resolver.rb:42:in `latest_resolvable_version'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.118.7/lib/dependabot/python/update_checker.rb:43:in `latest_resolvable_version'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:72:in `preferred_resolvable_version'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:235:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:227:in `numeric_version_can_update?'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:177:in `version_can_update?'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/update_checkers/base.rb:40:in `can_update?'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:250:in `requirements_to_unlock'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:186:in `check_and_create_pull_request'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:65:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `block in run'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `each'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `run'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_40324635> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_40324635> bin/update_files.rb:21:in `<main>'
```

**Comment by feelepxyz** [comment]
@lexicalunit we just fixed a bug with the installed python versions. Could you try triggering a new update for your repo? You can get to it from the repository > Insights > Dependency Graph > Dependabot > last checked ...

**Comment by lexicalunit** [comment]
It works! 🎉

**Comment by mdesta** [comment]
Hei,
How about package-ecosystem for javascript? I dint see it in the list and I was wondering if it is still supported in v2

**Comment by feelepxyz** [comment]
> How about package-ecosystem for javascript? I dint see it in the list and I was wondering if it is still supported in v2

@mdesta `npm` supports both yarn and npm, we're planning on splitting these out in future.
