### ISSUE TITLE
Using Harbor container image registry

### ISSUE THREAD

**Issue by DhruvM1994** [dependabot/dependabot-core#2026]
I am trying to use dependabot for verfying docker images. Thereby, the images are located in a private 
Harbor registry. I adjusted the "update-script.rb" and "generic-update-script.rb" from dependabot-script as follows:
```
credentials = [
  {
    "type" => "git_source",
    "host" => "github.com",
    "username" => "x-access-token",
    "password" => ENV["GITHUB_ACCESS_TOKEN"] # A GitHub access token with read access to public repos
  },
  {
    "type"=>"docker_registry",
    "registry"=>"https://<harbor_url>",
    "password" => "",
    "username" => ""
  }]
```

The above adjustment led to the following output:
```
/builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:206:in `rescue in tags_from_registry': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): registry.hub.docker.com (Dependabot::PrivateSourceAuthenticationFailure)
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:192:in `tags_from_registry'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:138:in `comparable_tags_from_registry'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:111:in `fetch_latest_version'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:30:in `latest_version'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:81:in `version_tag_up_to_date?'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:70:in `version_up_to_date?'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:27:in `up_to_date?'
	from ./generic-update-script.rb:145:in `block in <main>'
	from ./generic-update-script.rb:135:in `each'
	from ./generic-update-script.rb:135:in `<main>'
/builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/docker_registry2-1.9.0/lib/registry/registry.rb:325:in `rescue in do_bearer_req': DockerRegistry2::RegistryAuthenticationException (DockerRegistry2::RegistryAuthenticationException)
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/docker_registry2-1.9.0/lib/registry/registry.rb:307:in `do_bearer_req'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/docker_registry2-1.9.0/lib/registry/registry.rb:267:in `rescue in doreq'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/docker_registry2-1.9.0/lib/registry/registry.rb:241:in `doreq'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/docker_registry2-1.9.0/lib/registry/registry.rb:22:in `doget'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/docker_registry2-1.9.0/lib/registry/registry.rb:61:in `tags'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:196:in `tags_from_registry'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:138:in `comparable_tags_from_registry'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:111:in `fetch_latest_version'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:30:in `latest_version'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:81:in `version_tag_up_to_date?'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-docker-0.113.28/lib/dependabot/docker/update_checker.rb:70:in `version_up_to_date?'
	from /builds/<user_name>/dependabot-script/vendor/ruby/2.6.0/gems/dependabot-common-0.113.28/lib/dependabot/update_checkers/base.rb:27:in `up_to_date?'
	from ./generic-update-script.rb:145:in `block in <main>'
	from ./generic-update-script.rb:135:in `each'
	from ./generic-update-script.rb:135:in `<main>'
```
It seems that the script attempts to access the docker hub registry instead of the private one.
Therefore, I would like to know whether further adjustments are necessary.

**Comment by jurre** [comment]
It's not possible for us to provide support for running dependabot as a standalone script, as the environment it's running in differs so wildly between implementations. That said, is the docker image itself set up with the harbor host name? If not, Docker will always attempt to go to docker hub.
