### ISSUE TITLE
Dependabot fails for `pip-tools` Python projects

### ISSUE THREAD

**Issue by AdamHillier** [dependabot/dependabot-core#2043]
I work on a Python project which uses [`pip-tools`/`pip-compile`](https://dependabot.com/blog/dependabot-now-supports-pip-compile/) for dependency management.

When Dependabot runs update checks for our repo, it fails.

Although the project is private, I've created a public repo which has just the requirements files and reproduced the Dependabot error: [AdamHillier/test-pip-tools](https://github.com/AdamHillier/test-pip-tools).

Below is a snippet of the Dependabot logs containing the error messages (for the public repo):

```
updater | ERROR <job_21993930> Error processing tensorflow-addons (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_21993930> Killed
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.116.4/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:187:in `run_command'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.116.4/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:224:in `run_pip_compile_command'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.116.4/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:76:in `block (3 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.116.4/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:73:in `each'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.116.4/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:73:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.116.4/lib/dependabot/shared_helpers.rb:141:in `with_git_configured'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.116.4/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:69:in `block in fetch_latest_resolvable_version_string'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.116.4/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.116.4/lib/dependabot/shared_helpers.rb:37:in `chdir'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.116.4/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
updater | ERROR <job_21993930> /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.116.4/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.116.4/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:68:in `fetch_latest_resolvable_version_string'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.116.4/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:43:in `latest_resolvable_version'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.116.4/lib/dependabot/python/update_checker.rb:47:in `latest_resolvable_version'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.116.4/lib/dependabot/update_checkers/base.rb:70:in `preferred_resolvable_version'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.116.4/lib/dependabot/update_checkers/base.rb:233:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.116.4/lib/dependabot/update_checkers/base.rb:225:in `numeric_version_can_update?'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.116.4/lib/dependabot/update_checkers/base.rb:175:in `version_can_update?'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.116.4/lib/dependabot/update_checkers/base.rb:38:in `can_update?'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:208:in `requirements_to_unlock'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:159:in `check_and_create_pull_request'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:62:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:48:in `block in run'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:48:in `each'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:48:in `run'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_21993930> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_21993930> bin/update_files.rb:21:in `<main>'
```

Dependabot apparently fails when processing `tensorflow-addons`.

Although the error can't be seen in the logs snippet above, I've also seen Dependabot update logs with the error message `OSError: [Errno 28] No space left on device`.

Within this public repo, running `pip-compile --upgrade requirements.in && pip-compile --upgrade dev-requirements.in` locally successfully updates the `requirements.txt` file with upgraded dependencies, so Dependabot shouldn't have any issues.

**Comment by jurre** [comment]
It looks like this issue has been open for a while and we’ve made a bunch of improvements to Dependabot since, is this still happening, or has this problem been resolved and can we close this issue?

**Comment by AdamHillier** [comment]
Hey, yes you're right I haven't encountered issues recently so I'll close this.
