### ISSUE TITLE
Dependabot is failing when installing rtree because missing libspatialindex

### ISSUE THREAD

**Issue by bryanculbertson** [dependabot/dependabot-core#2071]
> OSError: libspatialindex_c.so: cannot open shared object file: No such file or directory

```
updater | ERROR <job_17271076> Command errored out with exit status 1:
updater | <job_17271076>  command: /usr/local/.pyenv/versions/3.7.5/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/tmp4gluod60build/rtree/setup.py'"'"'; __file__='"'"'/tmp/tmp4gluod60build/rtree/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/tmp4gluod60build/rtree/pip-egg-info
updater | <job_17271076>      cwd: /tmp/tmp4gluod60build/rtree/
updater | <job_17271076> Complete output (13 lines):
updater | <job_17271076> Traceback (most recent call last):
updater | <job_17271076>   File "<string>", line 1, in <module>
updater | <job_17271076>   File "/tmp/tmp4gluod60build/rtree/setup.py", line 3, in <module>
updater | <job_17271076>     import rtree
updater | <job_17271076>   File "/tmp/tmp4gluod60build/rtree/rtree/__init__.py", line 1, in <module>
updater | <job_17271076>     from .index import Rtree
updater | <job_17271076>   File "/tmp/tmp4gluod60build/rtree/rtree/index.py", line 6, in <module>
updater | <job_17271076>     from . import core
updater | <job_17271076>   File "/tmp/tmp4gluod60build/rtree/rtree/core.py", line 107, in <module>
updater | <job_17271076>     rt = ctypes.CDLL(lib_name)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/ctypes/__init__.py", line 364, in __init__
updater | <job_17271076>     self._handle = _dlopen(self._name, mode)
updater | <job_17271076> OSError: libspatialindex_c.so: cannot open shared object file: No such file or directory
updater | <job_17271076> ----------------------------------------
updater | <job_17271076> Traceback (most recent call last):
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/bin/pip-compile", line 10, in <module>
updater | <job_17271076>     sys.exit(cli())
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 764, in __call__
updater | <job_17271076>     return self.main(*args, **kwargs)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 717, in main
updater | <job_17271076>     rv = self.invoke(ctx)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 956, in invoke
updater | <job_17271076>     return ctx.invoke(self.callback, **ctx.params)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/core.py", line 555, in invoke
updater | <job_17271076>     return callback(*args, **kwargs)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
updater | <job_17271076>     return f(get_current_context(), *args, **kwargs)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/scripts/compile.py", line 359, in cli
updater | <job_17271076>     results = resolver.resolve(max_rounds=max_rounds)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/resolver.py", line 168, in resolve
updater | <job_17271076>     has_changed, best_matches = self._resolve_one_round()
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/resolver.py", line 263, in _resolve_one_round
updater | <job_17271076>     their_constraints.extend(self._iter_dependencies(best_match))
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/resolver.py", line 358, in _iter_dependencies
updater | <job_17271076>     dependencies = self.repository.get_dependencies(ireq)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/repositories/local.py", line 70, in get_dependencies
updater | <job_17271076>     return self.repository.get_dependencies(ireq)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 269, in get_dependencies
updater | <job_17271076>     download_dir, ireq, wheel_cache
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/piptools/repositories/pypi.py", line 225, in resolve_reqs
updater | <job_17271076>     results = resolver._resolve_one(reqset, ireq)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 365, in _resolve_one
updater | <job_17271076>     abstract_dist = self._get_abstract_dist_for(req_to_install)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/legacy_resolve.py", line 313, in _get_abstract_dist_for
updater | <job_17271076>     req, self.session, self.finder, self.require_hashes
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 224, in prepare_linked_requirement
updater | <job_17271076>     req, self.req_tracker, finder, self.build_isolation,
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 49, in _get_prepared_distribution
updater | <job_17271076>     abstract_dist.prepare_distribution_metadata(finder, build_isolation)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/distributions/source/legacy.py", line 39, in prepare_distribution_metadata
updater | <job_17271076>     self.req.prepare_metadata()
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/req/req_install.py", line 563, in prepare_metadata
updater | <job_17271076>     self.metadata_directory = metadata_generator(self)
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/operations/generate_metadata.py", line 124, in _generate_metadata_legacy
updater | <job_17271076>     command_desc='python setup.py egg_info',
updater | <job_17271076>   File "/usr/local/.pyenv/versions/3.7.5/lib/python3.7/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
updater | <job_17271076>     raise InstallationError(exc_msg)
updater | <job_17271076> pip._internal.exceptions.InstallationError: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by infin8x** [comment]
Can you provide more context around what's happening here and how to reproduce the issue?

**Comment by bryanculbertson** [comment]
@infin8x The root of the problem is that `rtree` doesn't have a wheel with `libspatialindex` so you can only install `rtree` if the system has `libspatialindex` installed already.

Dependabot doesn't run on a system with `libspatialindex`, therefore `rtree` cannot be install to check dependancies. This means that if `rtree` is in your dependency tree then Dependabot doesn't work at all.

Context here:
- https://github.com/Toblerity/rtree/issues/114
- https://github.com/Toblerity/rtree/issues/147

This is really an issue for `rtree` to improve but if Dependabot team figured out a workaround that would be helpful.

Possible fixes:
1. Install `libspatialindex` on the system used to check dependancies.
2. Allow skipping requirements that cannot be pip installed.
3. Provide assistance to `rtree` to produce wheels like `shapely` does: https://github.com/shapely/shapely-wheels

**Comment by infin8x** [comment]
Got it, thanks.

**Comment by jeffwidman** [comment]
👋 Hey there! Sorry for the glacially slow response... we've been a bit buried the past few years, and only just now starting to dig through some of our backlog.

Reading through this, it looks like the root problem is that `rtree` doesn't produce wheels. Technically that's allowable, but the Python ecosystem has strongly moved toward wheels. So I just don't see us investing time into workarounds for packages that aren't following idiomatic behavior for their ecosystems. So I'm going to close as not-planned.
