### ISSUE TITLE
Go dep ssh urls not parsed properly

### ISSUE THREAD

**Issue by tnsardesai** [dependabot/dependabot-core#2278]
**Package manage/ecosystem**

Go dep

**Manifest contents prior to update**

`Gopkg.toml` contents had
```
[[constraint]]
  name = "github.com/<org>/<repo>"
  source = "git@github.com:<org>/<repo>.git"
  version = "1.34.0"
```

**Updated dependency**

Failed to update

**What you expected to see, versus what you actually saw**
```
[[constraint]]
  name = "github.com/<org>/<repo>"
  source = "git@github.com:<org>/<repo>.git"
  version = "1.35.0"
```

**Images of the diff or a link to the PR, issue or logs**

log excerpts 
```
updater | INFO <job_38871549> Starting job processing
updater | INFO <job_38871549> Starting update job for <org>/<current_repo>
updater | ERROR <job_38871549> parse https://git@github.com:<org>/<repo>.git: invalid port ":<org>" after host
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.118.7/lib/dependabot/shared_helpers.rb:111:in `run_helper_subprocess'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-dep-0.118.7/lib/dependabot/dep/path_converter.rb:17:in `git_url_for_path'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-dep-0.118.7/lib/dependabot/dep/file_parser.rb:140:in `git_source'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-dep-0.118.7/lib/dependabot/dep/file_parser.rb:91:in `source_from_declaration'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-dep-0.118.7/lib/dependabot/dep/file_parser.rb:115:in `version_from_declaration'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-dep-0.118.7/lib/dependabot/dep/file_parser.rb:44:in `block (2 levels) in manifest_dependencies'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-dep-0.118.7/lib/dependabot/dep/file_parser.rb:38:in `each'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-dep-0.118.7/lib/dependabot/dep/file_parser.rb:38:in `block in manifest_dependencies'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-dep-0.118.7/lib/dependabot/dep/file_parser.rb:37:in `each'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-dep-0.118.7/lib/dependabot/dep/file_parser.rb:37:in `manifest_dependencies'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-dep-0.118.7/lib/dependabot/dep/file_parser.rb:27:in `parse'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:336:in `dependencies'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:51:in `run'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:16:in `perform_job'
updater | ERROR <job_38871549> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_38871549> bin/update_files.rb:21:in `<main>'
updater | INFO <job_38871549> Finished job processing
```

I believe the bug is that ssh links are formatted as https without validating. I don't know ruby at all but skimming through the code base I think the bug lies at https://github.com/dependabot/dependabot-core/blob/9f7b26453519e1b2a2db21d19078d4a65755bf6d/dep/lib/dependabot/dep/path_converter.rb#L35

**Comment by jeffwidman** [comment]
Can this be closed now that `go dep` is deprecated in favor of `go mod`?

**Comment by jurre** [comment]
Yeah I think that's the right thing to do, `dep` support is also deprecated in dependabot so we won't be making investments in it.
