### ISSUE TITLE
Fix flaky bundler specs

### ISSUE THREAD

**Issue by feelepxyz** [dependabot/dependabot-core#2364]
We're seeing the following flaky tests for bundler:

- [ ] rspec ./spec/dependabot/bundler/update_checker/version_resolver_spec.rb:150
- [ ] rspec ./spec/dependabot/bundler/update_checker/version_resolver_spec.rb:122
- [ ] rspec ./spec/dependabot/bundler/update_checker/version_resolver_spec.rb:434
- [ ] rspec ./spec/dependabot/bundler/file_updater_spec.rb:858
- [ ] rspec ./spec/dependabot/bundler/update_checker/force_updater_spec.rb:190

I can't seem to reproduce these locally with or without docker.

Example errors:

```
# Dependabot::SharedHelpers::ChildProcessFailed:
#   Child process raised Bundler::VersionConflict with message: Bundler could not find compatible versions for gem "activemodel":
#     In Gemfile:
#       activerecord (= 6.0.0.beta1) was resolved to 6.0.0.beta1, which depends on
#         activemodel (= 6.0.0.beta1)
#
#   Could not find gem 'activemodel (= 6.0.0.beta1)', which is required by gem 'activerecord (= 6.0.0.beta1)', in any of the sources.
#   ./lib/dependabot/bundler/update_checker/version_resolver.rb:163:in `dependency_from_definition'
```

```
# Dependabot::SharedHelpers::ChildProcessFailed:
#   Child process raised Bundler::VersionConflict with message: Bundler could not find compatible versions for gem "nokogiri":
#     In Gemfile:
#       roar (= 1.0.0.beta2) was resolved to 1.0.0.beta2, which depends on
#         representable (>= 2.0.1, <= 3.0.0) was resolved to 2.2.3, which depends on
#           nokogiri
#
#   Could not find gem 'nokogiri', which is required by gem 'representable (>= 2.0.1, <= 3.0.0)', in any of the sources.
#   ./lib/dependabot/bundler/update_checker/version_resolver.rb:163:in `dependency_from_definition'
```

```
# Dependabot::SharedHelpers::ChildProcessFailed:
#   Child process raised Bundler::VersionConflict with message: Bundler could not find compatible versions for gem "rake":
#     In Gemfile:
#       appraisal was resolved to 2.2.0, which depends on
#         rake
#
#   Could not find gem 'rake', which is required by gem 'appraisal', in any of the sources.
#   ./lib/dependabot/bundler/update_checker/version_resolver.rb:163:in `dependency_from_definition'
```

**Comment by feelepxyz** [comment]
I have marked these as pending until we figure out what's going wrong:

- rspec ./spec/dependabot/bundler/update_checker/version_resolver_spec.rb:150
- rspec ./spec/dependabot/bundler/update_checker/version_resolver_spec.rb:122
- rspec ./spec/dependabot/bundler/update_checker/version_resolver_spec.rb:434
