### ISSUE TITLE
Dependencies gets updated only when falling back from python version 3.8.5 to 3.7.7

### ISSUE THREAD

**Issue by omartrigui** [dependabot/dependabot-core#2387]
**Version**

dependabot-omnibus", "~> 0.118.8 (latest)

**Package manager/ecosystem**

pip

**Installed python versions**

2.7.18 and 3.8.5 retrieved from [python_versions.rb](https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/python_versions.rb#L7) 

**Project's python version**

3.7.7

**More context**

For a specific private project, Dependabot works fine only when I fallback from the latest python version `3.8.5` to `3.7.7` (updating [python_versions.rb](https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/python_versions.rb#L7) and [Dockerfile](https://github.com/dependabot/dependabot-core/blob/main/Dockerfile#L71-L73))

**Stacktrace**

```
Fetching pip dependency files for private-org/private-repo
Parsing dependencies information
pip._internal.exceptions.DistributionNotFound: No matching distribution found for torch==1.2.0 (from _REDACTED_==_REDACTED_->_REDACTED_==202015.0->-r requirements.in (line 22))
/var/lib/gems/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:174:in `rescue in block (2 levels) in check_original_requirements_resolvable'
/var/lib/gems/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:156:in `block (2 levels) in check_original_requirements_resolvable'
dependabot.rb:56:in `with_git_configured'
/var/lib/gems/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:155:in `block in check_original_requirements_resolvable'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `chdir'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
/var/lib/gems/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:154:in `check_original_requirements_resolvable'
/var/lib/gems/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:104:in `handle_pip_compile_errors'
/var/lib/gems/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:96:in `rescue in block in fetch_latest_resolvable_version_string'
/var/lib/gems/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:69:in `block in fetch_latest_resolvable_version_string'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block (2 levels) in in_a_temporary_directory'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `chdir'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:37:in `block in in_a_temporary_directory'
/usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_directory'
/var/lib/gems/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:68:in `fetch_latest_resolvable_version_string'
/var/lib/gems/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:43:in `latest_resolvable_version'
/var/lib/gems/2.6.0/gems/dependabot-python-0.118.8/lib/dependabot/python/update_checker.rb:47:in `latest_resolvable_version'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:72:in `preferred_resolvable_version'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:235:in `preferred_version_resolvable_with_unlock?'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:227:in `numeric_version_can_update?'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:177:in `version_can_update?'
/var/lib/gems/2.6.0/gems/dependabot-common-0.118.8/lib/dependabot/update_checkers/base.rb:40:in `can_update?'
dependabot.rb:119:in `block in <main>'
dependabot.rb:104:in `each'
dependabot.rb:104:in `<main>'
Failed to update repository private-org/private-repo
```

I appreciate any hints to solve this issue (could this be a bug ?)

**Comment by omartrigui** [comment]
https://github.com/dependabot/dependabot-core/issues/1455 as a workaround
