### ISSUE TITLE
"Couldn't find Ruby version!" occurs for Ruby 2.7

### ISSUE THREAD

**Issue by ybiquitous** [dependabot/dependabot-core#2910]
Hi, I have a `.gemspec` file with `required_ruby_version = ">= 2.7.2"` as follows:

https://github.com/sider/runners/blob/c272ab680b5bf2f1a4f0f268e154941c77085bdf/runners.gemspec#L13

But unfortunately, Dependabot updates fail. 😢 

**Package manager/ecosystem**
ruby:bundler

**Manifest contents prior to update**
`*.gemspec`, `Gemfile`, and `Gemfile.lock`

**Updated dependency**
All Ruby gems in my project

**What you expected to see, versus what you actually saw**
Some outdated packages should be updated. See below:

```console
$ bundle outdated

Gem             Current  Latest   Requested  Groups
aws-partitions  1.412.0  1.413.0
ffi             1.13.1   1.14.2
psych           3.2.1    3.3.0
regexp_parser   2.0.0    2.0.1
steep           0.37.0   0.38.0   = 0.37.0   development
```

**Images of the diff or a link to the PR, issue or logs**
The following is a part of the error log.

```
updater | INFO <job_78815922> Starting job processing
updater | INFO <job_78815922> Starting update job for sider/runners
updater | INFO <job_78815922> Checking if json 2.5.1 needs updating
updater | I, [2020-12-24T04:30:23.673900 #72]  INFO -- sentry: ** [Raven] Sending event 289c81fabf9b4d40816a9057f8c13884 to Sentry
  proxy | 2020/12/24 04:30:24 [042] POST https://sentry.io:443/api/1451818/store/
  proxy | 2020/12/24 04:30:24 [042] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_78815922> Error processing json (RuntimeError)
updater | ERROR <job_78815922> Couldn't find Ruby version!
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.1/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:56:in `ruby_version'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.1/lib/dependabot/bundler/file_updater/ruby_requirement_setter.rb:31:in `rewrite'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.1/lib/dependabot/bundler/update_checker/file_preparer.rb:254:in `block in lock_ruby_version'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.1/lib/dependabot/bundler/update_checker/file_preparer.rb:252:in `each'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.1/lib/dependabot/bundler/update_checker/file_preparer.rb:252:in `lock_ruby_version'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.1/lib/dependabot/bundler/update_checker/file_preparer.rb:170:in `gemfile_content_for_update_check'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.1/lib/dependabot/bundler/update_checker/file_preparer.rb:61:in `prepared_dependency_files'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.1/lib/dependabot/bundler/update_checker.rb:402:in `prepared_dependency_files'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.1/lib/dependabot/bundler/update_checker.rb:377:in `latest_version_finder'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.1/lib/dependabot/bundler/update_checker.rb:197:in `latest_version_details'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.129.1/lib/dependabot/bundler/update_checker.rb:21:in `latest_version'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:446:in `log_checking_for_update'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:177:in `check_and_create_pull_request'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:68:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `block in run'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `each'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `run'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_78815922> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_78815922> bin/update_files.rb:21:in `<main>'
```

**Comment by feelepxyz** [comment]
@ybiquitous thanks for reporting this! I'm working on a partial fix for this here: https://github.com/dependabot/dependabot-core/issues/2910

The remaining piece will be supporting bundler 2 tracked here: https://github.com/dependabot/dependabot-core/issues/1699

We're prioritising ecosystem upgrades over the coming weeks and months so should have this fixed up soon.

**Comment by mattt** [comment]
@ybiquitous Following up on this: Dependabot now runs Ruby 2.7 and supports Bundler 2, which together should resolve your issue. Please let me know if you're still encountering this issue.
