### ISSUE TITLE
D-bot encountered an unknown error: undefined method `zero?' for nil:NilClass

### ISSUE THREAD

**Issue by pzygielo** [dependabot/dependabot-core#2992]
**Package manager/ecosystem**
maven

**What you expected to see, versus what you actually saw**
Expected - clean run at least, finally "error prone needs update to [2.5.1](https://github.com/google/error-prone/releases/tag/v2.5.1)" to be discovered.

Actually seen:
>  Dependabot encountered an unknown error
>
>  Dependabot failed to update your dependencies because an unexpected error occured. See the logs for more details.
```
...
INFO <job_83400252> Checking if com.google.errorprone:javac 9+181-r4173-1 needs updating
  proxy | 2021/01/15 08:19:47 [026] GET https://jitpack.io:443/com/google/errorprone/javac/maven-metadata.xml
  proxy | 2021/01/15 08:19:47 [026] 404 https://jitpack.io:443/com/google/errorprone/javac/maven-metadata.xml
  proxy | 2021/01/15 08:19:47 [028] GET https://repo.maven.apache.org:443/maven2/com/google/errorprone/javac/maven-metadata.xml
  proxy | 2021/01/15 08:19:47 [028] 200 https://repo.maven.apache.org:443/maven2/com/google/errorprone/javac/maven-metadata.xml
updater | I, [2021-01-15T08:19:47.183815 #73]  INFO -- sentry: ** [Raven] Sending event e5a5f5d4896249929c2d41823ca6f0d7 to Sentry
  proxy | 2021/01/15 08:19:47 [030] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/01/15 08:19:47 [030] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_83400252> Error processing com.google.errorprone:javac (NoMethodError)
updater | ERROR <job_83400252> undefined method `zero?' for nil:NilClass
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-maven-0.130.0/lib/dependabot/maven/version.rb:83:in `block in <=>'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-maven-0.130.0/lib/dependabot/maven/version.rb:76:in `times'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-maven-0.130.0/lib/dependabot/maven/version.rb:76:in `each'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-maven-0.130.0/lib/dependabot/maven/version.rb:76:in `<=>'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-maven-0.130.0/lib/dependabot/maven/update_checker/version_finder.rb:67:in `sort_by'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-maven-0.130.0/lib/dependabot/maven/update_checker/version_finder.rb:67:in `versions'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-maven-0.130.0/lib/dependabot/maven/update_checker/version_finder.rb:31:in `latest_version_details'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-maven-0.130.0/lib/dependabot/maven/update_checker.rb:109:in `latest_version_details'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-maven-0.130.0/lib/dependabot/maven/update_checker.rb:15:in `latest_version'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:446:in `log_checking_for_update'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:177:in `check_and_create_pull_request'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:68:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `block in run'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `each'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `run'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_83400252> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:29:in `run'
updater | ERROR <job_83400252> bin/update_files.rb:21:in `<main>'
...
```

**Comment by pzygielo** [comment]
[Previously discovered error prone upgrades](https://github.com/pzlc4will/will/pulls?q=is%3Apr+author%3Aapp%2Fdependabot-preview+prone)

**Comment by veithen** [comment]
I'm seeing the same error: https://github.com/veithen/parent/network/updates.

**Comment by jurre** [comment]
That definitely seems like an issue on our side, I'll check out what's going on
