### ISSUE TITLE
TCP Socket timeout

### ISSUE THREAD

**Issue by TabithaLarkin** [dependabot/dependabot-core#3012]
We have a ruby script set up with Azure DevOps to run dependabot. It succeeds at checking some of our other dependencies, until it reaches the node-sass one, at which point it seems to hit some sort of TCP timeout. This succeeded yesterday, so I'm a little confused as to what could have happened, and the error isn't particularly helpful.

**Package manager/ecosystem**
npm
**Dependabot version**
0.130.1
**Updated dependency**
node-sass from 4.14.1 to 5.0.0
**Log**
```
2021-01-19T13:26:02.6177017Z Found lint-staged @ 10.2.7...
2021-01-19T13:26:11.4992054Z   considering upgrade to 10.5.3
2021-01-19T13:26:29.7508556Z   PR already exists or an error has occurred
2021-01-19T13:26:29.7510094Z Found node-sass @ 4.14.1...
2021-01-19T13:26:38.7966448Z   considering upgrade to 5.0.0
2021-01-19T13:27:10.9261961Z /usr/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Faraday::TimeoutError)
2021-01-19T13:27:10.9263883Z 	from /usr/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
2021-01-19T13:27:10.9271647Z 	from /usr/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
2021-01-19T13:27:10.9273141Z 	from /usr/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
2021-01-19T13:27:10.9274666Z 	from /usr/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
2021-01-19T13:27:10.9275911Z 	from /usr/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
2021-01-19T13:27:10.9277273Z 	from /usr/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
2021-01-19T13:27:10.9278461Z 	from /usr/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
2021-01-19T13:27:10.9279632Z 	from /usr/lib/ruby/2.6.0/net/http.rb:1479:in `request'
2021-01-19T13:27:10.9280596Z 	from /usr/lib/ruby/2.6.0/net/http.rb:1228:in `get'
2021-01-19T13:27:10.9282545Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:139:in `block in request_via_get_method'
2021-01-19T13:27:10.9316033Z 	from /usr/lib/ruby/2.6.0/net/http.rb:920:in `start'
2021-01-19T13:27:10.9317166Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:138:in `request_via_get_method'
2021-01-19T13:27:10.9318294Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:129:in `request_with_wrapped_block'
2021-01-19T13:27:10.9319779Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
2021-01-19T13:27:10.9320837Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
2021-01-19T13:27:10.9321814Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/adapter.rb:60:in `connection'
2021-01-19T13:27:10.9322957Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
2021-01-19T13:27:10.9324078Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
2021-01-19T13:27:10.9325002Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
2021-01-19T13:27:10.9326053Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
2021-01-19T13:27:10.9327123Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
2021-01-19T13:27:10.9328087Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/request/retry.rb:148:in `call'
2021-01-19T13:27:10.9329090Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
2021-01-19T13:27:10.9330055Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
2021-01-19T13:27:10.9331193Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/connection.rb:198:in `get'
2021-01-19T13:27:10.9332095Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
2021-01-19T13:27:10.9333023Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/connection.rb:156:in `request'
2021-01-19T13:27:10.9333985Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/connection.rb:84:in `paginate'
2021-01-19T13:27:10.9334938Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/client/releases.rb:15:in `releases'
2021-01-19T13:27:10.9336001Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/clients/github_with_retries.rb:95:in `public_send'
2021-01-19T13:27:10.9337176Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/clients/github_with_retries.rb:95:in `block in method_missing'
2021-01-19T13:27:10.9338368Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/clients/github_with_retries.rb:115:in `retry_connection_failures'
2021-01-19T13:27:10.9339591Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/clients/github_with_retries.rb:92:in `method_missing'
2021-01-19T13:27:10.9340765Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:206:in `fetch_github_releases'
2021-01-19T13:27:10.9341999Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:197:in `fetch_dependency_releases'
2021-01-19T13:27:10.9343198Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:56:in `all_releases'
2021-01-19T13:27:10.9344380Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:42:in `all_dep_releases'
2021-01-19T13:27:10.9345713Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:164:in `release_for_version'
2021-01-19T13:27:10.9346938Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:156:in `previous_release'
2021-01-19T13:27:10.9347978Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:82:in `releases_since_previous_version'
2021-01-19T13:27:10.9348997Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:60:in `relevant_releases'
2021-01-19T13:27:10.9349977Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:33:in `releases_text'
2021-01-19T13:27:10.9350928Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base.rb:88:in `releases_text'
2021-01-19T13:27:10.9351745Z 	from /usr/lib/ruby/2.6.0/forwardable.rb:230:in `releases_text'
2021-01-19T13:27:10.9352623Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb:64:in `release_cascade'
2021-01-19T13:27:10.9353659Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb:38:in `to_s'
2021-01-19T13:27:10.9354785Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator/message_builder.rb:313:in `metadata_cascades_for_dep'
2021-01-19T13:27:10.9355800Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator/message_builder.rb:289:in `metadata_cascades'
2021-01-19T13:27:10.9356810Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator/message_builder.rb:48:in `pr_message'
2021-01-19T13:27:10.9357768Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator.rb:159:in `azure_creator'
2021-01-19T13:27:10.9358681Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator.rb:91:in `create'
2021-01-19T13:27:10.9359352Z 	from ./update.rb:79:in `block in check_package_deps'
2021-01-19T13:27:10.9359797Z 	from ./update.rb:27:in `each'
2021-01-19T13:27:10.9360239Z 	from ./update.rb:27:in `check_package_deps'
2021-01-19T13:27:10.9360710Z 	from ./update.rb:138:in `block in <main>'
2021-01-19T13:27:10.9361144Z 	from ./update.rb:128:in `each'
2021-01-19T13:27:10.9361557Z 	from ./update.rb:128:in `<main>'
2021-01-19T13:27:10.9362236Z /usr/lib/ruby/2.6.0/net/protocol.rb:217:in `rbuf_fill': Net::ReadTimeout with #<TCPSocket:(closed)> (Net::ReadTimeout)
2021-01-19T13:27:10.9363015Z 	from /usr/lib/ruby/2.6.0/net/protocol.rb:191:in `readuntil'
2021-01-19T13:27:10.9363541Z 	from /usr/lib/ruby/2.6.0/net/protocol.rb:201:in `readline'
2021-01-19T13:27:10.9364096Z 	from /usr/lib/ruby/2.6.0/net/http/response.rb:40:in `read_status_line'
2021-01-19T13:27:10.9364651Z 	from /usr/lib/ruby/2.6.0/net/http/response.rb:29:in `read_new'
2021-01-19T13:27:10.9365228Z 	from /usr/lib/ruby/2.6.0/net/http.rb:1509:in `block in transport_request'
2021-01-19T13:27:10.9365782Z 	from /usr/lib/ruby/2.6.0/net/http.rb:1506:in `catch'
2021-01-19T13:27:10.9366348Z 	from /usr/lib/ruby/2.6.0/net/http.rb:1506:in `transport_request'
2021-01-19T13:27:10.9366882Z 	from /usr/lib/ruby/2.6.0/net/http.rb:1479:in `request'
2021-01-19T13:27:10.9367380Z 	from /usr/lib/ruby/2.6.0/net/http.rb:1228:in `get'
2021-01-19T13:27:10.9368271Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:139:in `block in request_via_get_method'
2021-01-19T13:27:10.9368952Z 	from /usr/lib/ruby/2.6.0/net/http.rb:920:in `start'
2021-01-19T13:27:10.9369714Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:138:in `request_via_get_method'
2021-01-19T13:27:10.9370642Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:129:in `request_with_wrapped_block'
2021-01-19T13:27:10.9371556Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:122:in `perform_request'
2021-01-19T13:27:10.9372424Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:66:in `block in call'
2021-01-19T13:27:10.9373249Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/adapter.rb:60:in `connection'
2021-01-19T13:27:10.9374059Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-net_http-1.0.1/lib/faraday/adapter/net_http.rb:64:in `call'
2021-01-19T13:27:10.9374853Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
2021-01-19T13:27:10.9375625Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/middleware.rb:18:in `call'
2021-01-19T13:27:10.9376490Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
2021-01-19T13:27:10.9377448Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
2021-01-19T13:27:10.9378263Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/request/retry.rb:148:in `call'
2021-01-19T13:27:10.9379077Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/rack_builder.rb:154:in `build_response'
2021-01-19T13:27:10.9379893Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/connection.rb:492:in `run_request'
2021-01-19T13:27:10.9380679Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/faraday-1.3.0/lib/faraday/connection.rb:198:in `get'
2021-01-19T13:27:10.9381429Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/sawyer-0.8.2/lib/sawyer/agent.rb:94:in `call'
2021-01-19T13:27:10.9382205Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/connection.rb:156:in `request'
2021-01-19T13:27:10.9382991Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/connection.rb:84:in `paginate'
2021-01-19T13:27:10.9383797Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/octokit-4.20.0/lib/octokit/client/releases.rb:15:in `releases'
2021-01-19T13:27:10.9384692Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/clients/github_with_retries.rb:95:in `public_send'
2021-01-19T13:27:10.9385657Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/clients/github_with_retries.rb:95:in `block in method_missing'
2021-01-19T13:27:10.9386653Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/clients/github_with_retries.rb:115:in `retry_connection_failures'
2021-01-19T13:27:10.9387622Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/clients/github_with_retries.rb:92:in `method_missing'
2021-01-19T13:27:10.9388620Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:206:in `fetch_github_releases'
2021-01-19T13:27:10.9389723Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:197:in `fetch_dependency_releases'
2021-01-19T13:27:10.9390721Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:56:in `all_releases'
2021-01-19T13:27:10.9391705Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:42:in `all_dep_releases'
2021-01-19T13:27:10.9392707Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:164:in `release_for_version'
2021-01-19T13:27:10.9393710Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:156:in `previous_release'
2021-01-19T13:27:10.9394742Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:82:in `releases_since_previous_version'
2021-01-19T13:27:10.9395753Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:60:in `relevant_releases'
2021-01-19T13:27:10.9396738Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base/release_finder.rb:33:in `releases_text'
2021-01-19T13:27:10.9397751Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/metadata_finders/base.rb:88:in `releases_text'
2021-01-19T13:27:10.9398440Z 	from /usr/lib/ruby/2.6.0/forwardable.rb:230:in `releases_text'
2021-01-19T13:27:10.9399306Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb:64:in `release_cascade'
2021-01-19T13:27:10.9400354Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb:38:in `to_s'
2021-01-19T13:27:10.9401388Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator/message_builder.rb:313:in `metadata_cascades_for_dep'
2021-01-19T13:27:10.9402395Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator/message_builder.rb:289:in `metadata_cascades'
2021-01-19T13:27:10.9405878Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator/message_builder.rb:48:in `pr_message'
2021-01-19T13:27:10.9406868Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator.rb:159:in `azure_creator'
2021-01-19T13:27:10.9408481Z 	from /__w/320/s/build/Pipeline/Dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.130.1/lib/dependabot/pull_request_creator.rb:91:in `create'
2021-01-19T13:27:10.9409315Z 	from ./update.rb:79:in `block in check_package_deps'
2021-01-19T13:27:10.9409808Z 	from ./update.rb:27:in `each'
2021-01-19T13:27:10.9410291Z 	from ./update.rb:27:in `check_package_deps'
2021-01-19T13:27:10.9410780Z 	from ./update.rb:138:in `block in <main>'
2021-01-19T13:27:10.9411238Z 	from ./update.rb:128:in `each'
2021-01-19T13:27:10.9411714Z 	from ./update.rb:128:in `<main>'
```

**Comment by TabithaLarkin** [comment]
It appears that this may have been caused by a disk space issue. It might be nice if the error reporting was improved in this area. If this is not something that should be tracked in this issue, then I am happy for it to be closed.
