### ISSUE TITLE
Azure private maven/gradle - Dependabot::PrivateSourceAuthenticationFailure

### ISSUE THREAD

**Issue by abs-paradigm** [dependabot/dependabot-core#3069]
We are trying to use the generic script in an azure devops pipeline. It was working until we added an private dependency (azure artifact feed) in the project.

It's throwing an exception:

/opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/bundler/gems/Dependabot-Core-6408d737ab06/gradle/lib/dependabot/gradle/update_checker/version_finder.rb:68:in `versions': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): https://pkgs.dev.azure.com/OurCompany/Project1/_packaging/OurCompany%40Release/maven/v1 (Dependabot::PrivateSourceAuthenticationFailure)
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/bundler/gems/Dependabot-Core-Fork-6408d737ab06/gradle/lib/dependabot/gradle/update_checker/version_finder.rb:33:in `latest_version_details'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/bundler/gems/Dependabot-Core-Fork-6408d737ab06/gradle/lib/dependabot/gradle/update_checker.rb:109:in `latest_version_details'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/bundler/gems/Dependabot-Core-Fork-6408d737ab06/gradle/lib/dependabot/gradle/update_checker.rb:17:in `latest_version'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/bundler/gems/Dependabot-Core-Fork-6408d737ab06/common/lib/dependabot/update_checkers/base.rb:224:in `numeric_version_up_to_date?'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/bundler/gems/Dependabot-Core-Fork-6408d737ab06/gradle/lib/dependabot/gradle/update_checker.rb:93:in `numeric_version_up_to_date?'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/bundler/gems/Dependabot-Core-Fork-6408d737ab06/common/lib/dependabot/update_checkers/base.rb:182:in `version_up_to_date?'
	from /opt/hostedtoolcache/Ruby/2.7.2/x64/lib/ruby/gems/2.7.0/bundler/gems/Dependabot-Core-Fork-6408d737ab06/common/lib/dependabot/update_checkers/base.rb:30:in `up_to_date?'
	from ./update-script.rb:156:in `block in <main>'
	from ./update-script.rb:146:in `each'
	from ./update-script.rb:146:in `<main>'

In update-script.rb the credentials for the feeds were added like this (https://github.com/dependabot/dependabot-core/pull/1465) :

credentials = [{
    "type" => "git_source",
    "host" => azure_hostname,
    "username" => "x-access-token",
    "password" => ENV["AZURE_ACCESS_TOKEN"]
  },{
    "type" => "maven-repository",
    "url" => "https://pkgs.dev.azure.com/OurCompany/Project1/_packaging/MyFeed/maven/v1",
    "username" => "Azure DevOps Services",
    "password" => ENV["AZURE_ACCESS_TOKEN"]
  },{
    "type" => "maven-repository",
    "url" => "https://pkgs.dev.azure.com/OurCompany/Project1/_packaging/MyFeed%40Release/maven/v1",
    "username" => "Azure DevOps Services",
    "password" => ENV["AZURE_ACCESS_TOKEN"]
  }
]

The feeds credentials are there:
puts(credentials) -->

{"type"=>"git_source", "host"=>"dev.azure.com", "username"=>"x-access-token", "password"=>***}

{"type"=>"maven-repository", "url"=>"https://pkgs.dev.azure.com/OurCompany/Project1/_packaging/MyFeed/maven/v1", "username"=>"Azure DevOps Services", "password"=>***}

{"type"=>"maven-repository", "url"=>"https://pkgs.dev.azure.com/OurCompany/Project1/_packaging/MyFeed%40Release/maven/v1", "username"=>"Azure DevOps Services", "password"=>***}

But it's throwing Dependabot::PrivateSourceAuthenticationFailure.

Anyone know how to fix that?

**Comment by its-a-wrap** [comment]
@abs-paradigm did you get a fix for this?

**Comment by mburumaxwell** [comment]
Hi @its-a-wrap and @abs-paradigm ,

Had a similar problem and solved it by granting permissions feed permissions to the user with the PAT. It turns out that it is not sufficient to grant the Packages\Read permission to the PAT. The user owning the PAT (or a group they belong to) needs permissions to access the particular feed. This can be done in the `Feed Settings -> Permission` page.

 See also https://github.com/tinglesoftware/dependabot-azure-devops/issues/50#issuecomment-820273608
