### ISSUE TITLE
[GitLab] gradle failed to open TCP connection

### ISSUE THREAD

**Issue by Ciatzo** [dependabot/dependabot-core#3162]
**Package manager/ecosystem**

Gradle 
Gitlab CI pipeline

Using the default gitlab-ci.yml file. 

**What you expected to see, versus what you actually saw**

Run scheduled GitLab CI pipeline for updating gradle dependencies.

Expected: it works

What happened:
GitLab pipeline fails with following log
```
bundle exec ruby ./generic-update-script.rb
/usr/lib/ruby/2.6.0/net/http.rb:949:in `rescue in block in connect': Failed to open TCP connection to https:443 (getaddrinfo: Name or service not known) (SocketError)
	from /usr/lib/ruby/2.6.0/net/http.rb:946:in `block in connect'
	from /usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /usr/lib/ruby/2.6.0/net/http.rb:1470:in `request'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/httparty-0.18.1/lib/httparty/request.rb:145:in `perform'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/httparty-0.18.1/lib/httparty.rb:594:in `perform_request'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/httparty-0.18.1/lib/httparty.rb:508:in `get'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:51:in `block (2 levels) in <class:Request>'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/gitlab-4.17.0/lib/gitlab/client/projects.rb:49:in `project'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/clients/gitlab_with_retries.rb:67:in `public_send'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/clients/gitlab_with_retries.rb:67:in `block in method_missing'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/clients/gitlab_with_retries.rb:82:in `retry_connection_failures'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/clients/gitlab_with_retries.rb:64:in `method_missing'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/clients/gitlab_with_retries.rb:51:in `fetch_default_branch'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:442:in `default_branch_for_repo'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:70:in `commit'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:359:in `_full_specification_for'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:174:in `_fetch_repo_contents'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:159:in `repo_contents'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:102:in `fetch_file_if_present'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:115:in `block in supported_file'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:114:in `each'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:114:in `supported_file'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:106:in `supported_build_file'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:40:in `buildfile'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:31:in `fetch_files'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./generic-update-script.rb:115:in `<main>'
/usr/lib/ruby/2.6.0/net/http.rb:947:in `initialize': getaddrinfo: Name or service not known (SocketError)
	from /usr/lib/ruby/2.6.0/net/http.rb:947:in `open'
	from /usr/lib/ruby/2.6.0/net/http.rb:947:in `block in connect'
	from /usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
	from /usr/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
	from /usr/lib/ruby/2.6.0/net/http.rb:945:in `connect'
	from /usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	from /usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
	from /usr/lib/ruby/2.6.0/net/http.rb:1470:in `request'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/httparty-0.18.1/lib/httparty/request.rb:145:in `perform'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/httparty-0.18.1/lib/httparty.rb:594:in `perform_request'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/httparty-0.18.1/lib/httparty.rb:508:in `get'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/gitlab-4.17.0/lib/gitlab/request.rb:51:in `block (2 levels) in <class:Request>'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/gitlab-4.17.0/lib/gitlab/client/projects.rb:49:in `project'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/clients/gitlab_with_retries.rb:67:in `public_send'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/clients/gitlab_with_retries.rb:67:in `block in method_missing'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/clients/gitlab_with_retries.rb:82:in `retry_connection_failures'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/clients/gitlab_with_retries.rb:64:in `method_missing'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/clients/gitlab_with_retries.rb:51:in `fetch_default_branch'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:442:in `default_branch_for_repo'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:70:in `commit'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:359:in `_full_specification_for'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:174:in `_fetch_repo_contents'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:159:in `repo_contents'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:102:in `fetch_file_if_present'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:115:in `block in supported_file'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:114:in `each'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:114:in `supported_file'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:106:in `supported_build_file'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:40:in `buildfile'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-gradle-0.133.3/lib/dependabot/gradle/file_fetcher.rb:31:in `fetch_files'
	from /builds/mobile/android-dependabot/vendor/ruby/2.6.0/gems/dependabot-common-0.133.3/lib/dependabot/file_fetchers/base.rb:64:in `files'
	from ./generic-update-script.rb:115:in `<main>'
Fetching gradle dependency files for PACKAGE/PROJECT NAME
ERROR: Job failed: exit code 1
```

(package and project name replaced in the log for private repo)

**Comment by Ciatzo** [comment]
solution was to remove "https://" from GitLab hostname
