### ISSUE TITLE
Bundler updates fail (undefined method `fetchers' for nil:NilClass)

### ISSUE THREAD

**Issue by jdelStrother** [dependabot/dependabot-core#3444]
**Package ecosystem**
bundler (& yarn, but dependabot's yarn updates are working fine)

**Package manager version**
bundler 2.2.11

**Language version**
ruby 2.7

**Manifest location and content prior to update**
/Gemfile

**dependabot.yml content**
```yml
version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "06:30"
  open-pull-requests-limit: 99
  vendor: true

- package-ecosystem: npm
  directory: "/webpack"
  schedule:
    interval: weekly
    time: "06:30"
  open-pull-requests-limit: 99
  ignore:
    # use `npx sb@next upgrade` instead of having dependabot open 8 PRs for all the separate
    # storybook repos
    - dependency-name: "@storybook/*"
    # And types can be quite noisy, use `yarn upgrade-interactive --latest` to update them all in one go instead
    - dependency-name: "@types/*"

# version tickle 1
```

**What you expected to see, versus what you actually saw**
Expect to see dependabot opening new bundler PRs every week.
Instead, it seems to be repeatedly failing with, eg: 

```
updater | INFO <job_108075088> Checking if rubocop 1.12.0 needs updating
  proxy | 2021/04/05 13:46:46 [207] GET https://rubygems.org:443/api/v1/versions/rubocop.json
  proxy | 2021/04/05 13:46:46 [207] 200 https://rubygems.org:443/api/v1/versions/rubocop.json
updater | INFO <job_108075088> Latest version is 1.12.1
updater | I, [2021-04-05T13:46:50.554860 #9]  INFO -- sentry: ** [Raven] Sending event 9aa38a6be4f74f2ba4d792b7ec70d9cc to Sentry
  proxy | 2021/04/05 13:46:50 [209] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/04/05 13:46:50 [209] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_108075088> Error processing rubocop (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_108075088> undefined method `fetchers' for nil:NilClass
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.139.1/lib/dependabot/shared_helpers.rb:115:in `run_helper_subprocess'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.139.1/lib/dependabot/bundler/native_helpers.rb:12:in `block in run_bundler_subprocess'
updater | ERROR <job_108075088> /var/lib/gems/2.6.0/gems/bundler-1.17.3/lib/bundler.rb:309:in `block in with_original_env'
updater | ERROR <job_108075088> /var/lib/gems/2.6.0/gems/bundler-1.17.3/lib/bundler.rb:562:in `with_env'
updater | ERROR <job_108075088> /var/lib/gems/2.6.0/gems/bundler-1.17.3/lib/bundler.rb:309:in `with_original_env'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.139.1/lib/dependabot/bundler/native_helpers.rb:11:in `run_bundler_subprocess'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.139.1/lib/dependabot/bundler/update_checker/version_resolver.rb:82:in `block (2 levels) in fetch_latest_resolvable_version_details'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.139.1/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb:54:in `block in in_a_native_bundler_context'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.139.1/lib/dependabot/shared_helpers.rb:34:in `block in in_a_temporary_repo_directory'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.139.1/lib/dependabot/shared_helpers.rb:34:in `chdir'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.139.1/lib/dependabot/shared_helpers.rb:34:in `in_a_temporary_repo_directory'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.139.1/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb:50:in `in_a_native_bundler_context'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.139.1/lib/dependabot/bundler/update_checker/version_resolver.rb:81:in `block in fetch_latest_resolvable_version_details'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.139.1/lib/dependabot/shared_helpers.rb:159:in `with_git_configured'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.139.1/lib/dependabot/bundler/update_checker/version_resolver.rb:77:in `fetch_latest_resolvable_version_details'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.139.1/lib/dependabot/bundler/update_checker/version_resolver.rb:43:in `latest_resolvable_version_details'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.139.1/lib/dependabot/bundler/update_checker.rb:208:in `latest_resolvable_version_details'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-bundler-0.139.1/lib/dependabot/bundler/update_checker.rb:27:in `latest_resolvable_version'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.139.1/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.139.1/lib/dependabot/update_checkers/base.rb:253:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.139.1/lib/dependabot/update_checkers/base.rb:245:in `numeric_version_can_update?'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.139.1/lib/dependabot/update_checkers/base.rb:195:in `version_can_update?'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.139.1/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:409:in `requirements_to_unlock'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:208:in `check_and_create_pull_request'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:68:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `block in run'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `each'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `run'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_108075088> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
updater | ERROR <job_108075088> bin/update_files.rb:21:in `<main>'
```

**Native package manager behavior**

`bundle update rubocop` bumps our rubocop version from 1.11.0 to 1.12.1

(rubocop isn't the only gem causing errors, I see similar problems with a number of others. Pretty sure all gems that need updates are producing that output.)

**Comment by jurre** [comment]
@jdelStrother could you share what your Gemfile and Gemfile.lock look like? Perhaps the smallest version of those files that replicates the error? That would help tremendously with debugging this

**Comment by jdelStrother** [comment]
Hm. I've not been able to reproduce it locally with dependabot-core's dry-run.
Is there somewhere private I can send my Gemfile & Gemfile.lock ?

**Comment by jurre** [comment]
Yeah the best way to do this is opening an issue with support (https://support.github.com/), and referencing this issue

**Comment by jeffwidman** [comment]
Closing, as the associated support ticket was resolved.
