### ISSUE TITLE
Error with poetry file

### ISSUE THREAD

**Issue by brianmay** [dependabot/dependabot-core#3460]
From https://app.dependabot.com/accounts/Karaage-Cluster/update-logs/75817559:

```
updater | ERROR <job_75817559> Error processing wheel (RuntimeError)

updater | ERROR <job_75817559> No version in lockfile!

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.140.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:111:in `fetch_version_from_parsed_lockfile'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.140.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:96:in `block (2 levels) in fetch_latest_resolvable_version_string'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.0/lib/dependabot/shared_helpers.rb:159:in `with_git_configured'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.140.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:76:in `block in fetch_latest_resolvable_version_string'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.0/lib/dependabot/shared_helpers.rb:45:in `block (2 levels) in in_a_temporary_directory'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.0/lib/dependabot/shared_helpers.rb:45:in `chdir'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.0/lib/dependabot/shared_helpers.rb:45:in `block in in_a_temporary_directory'

updater | ERROR <job_75817559> /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.0/lib/dependabot/shared_helpers.rb:42:in `in_a_temporary_directory'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.140.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:75:in `fetch_latest_resolvable_version_string'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.140.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:48:in `latest_resolvable_version'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.140.0/lib/dependabot/python/update_checker.rb:43:in `latest_resolvable_version'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.0/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-python-0.140.0/lib/dependabot/python/update_checker.rb:93:in `updated_requirements'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.0/lib/dependabot/update_checkers/base.rb:281:in `changed_requirements'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.0/lib/dependabot/update_checkers/base.rb:295:in `requirements_can_update?'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.140.0/lib/dependabot/update_checkers/base.rb:49:in `can_update?'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:409:in `requirements_to_unlock'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:208:in `check_and_create_pull_request'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:68:in `check_and_create_pr_with_error_handling'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `block in run'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `each'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:53:in `run'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'

updater | ERROR <job_75817559> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'

updater | ERROR <job_75817559> bin/update_files.rb:21:in `<main>'
```

Lock file:

https://github.com/Karaage-Cluster/python-tldap/blob/master/poetry.lock

Me thinks this should work.

**Comment by jakecoffman** [comment]
Interesting that Poetry doesn't put pip or wheel in the lockfile, it looks like that might be changing in Poetry 1.2: https://github.com/python-poetry/poetry/issues/3075

That said, I think Dependabot is acting appropriately here. It sees `wheel="*"` and can't find a version in the lockfile, there's nothing that can be done. The version cannot be determined. 

It also appears to not be stopping other updates from happening, so I think this is working as designed. 

Thanks for the report, we'll upgrade to Poetry 1.2 when it is released and hopefully that will place wheel in the lockfile 🤞
