### ISSUE TITLE
JavaScript: error in fetcher: key not found: :security_updates_only

### ISSUE THREAD

**Issue by sgerrand** [dependabot/dependabot-core#3530]
💁 It appears that an error occurs inside the `fetcher` process for updates to JavaScript projects. No other language types appear to be affected.

**Package ecosystem**
JavaScript: `npm` & `yarn`

**Package manager version**

**Language version**

**Manifest location and content prior to update**
`./package.json`

(contents edited for privacy, etc)
```js
  "dependencies": {
    "@octokit/core": "^3.3.1",
    "@popperjs/core": "^2.9.2",
    "@segment/snippet": "^4.13.2",
    "@sentry/browser": "^6.2.5",
    "@sentry/integrations": "^6.2.5",
    "@sentry/node": "^6.2.5",
    "@sentry/webpack-plugin": "^1.14.1",
    "@stripe/react-stripe-js": "^1.4.0",
    "@stripe/stripe-js": "^1.13.1",
    "@typeform/embed": "^1.1.1",
    "@vercel/node": "^1.9.1",
    "@zeit/next-source-maps": "0.0.4-canary.1",
    "axios": "^0.21.1",
    "classnames": "^2.3.1",
    "cookie": "^0.4.1",
    "credit-card-type": "^9.1.0",
    "formik": "^2.2.6",
    "highlight.js": "10.7.1",
    "htmlescape": "^1.1.1",
    "isomorphic-unfetch": "^3.1.0",
    "jsonwebtoken": "^8.5.1",
    "lodash": "^4.17.21",
    "micro": "^9.3.4",
    "ms": "^2.1.3",
    "nanoid": "^3.1.22",
    "next": "^10.1.3",
    "next-absolute-url": "^1.2.2",
    "node-gzip": "^1.1.2",
    "nprogress": "^0.2.0",
    "react": "17.0.2",
    "react-day-picker": "^7.4.8",
    "react-dom": "17.0.2",
    "react-popper": "^2.2.5",
    "react-scroll": "^1.8.2",
    "react-syntax-highlighter": "^15.4.3",
    "react-transition-group": "^4.4.1",
    "statuses": "^2.0.1",
    "stripe": "^8.142.0",
    "typescript": "^4.2.4",
    "url-parse": "^1.5.1",
    "yup": "^0.32.9",
    "zlib": "^1.0.5"
  },
  "devDependencies": {
    "@babel/core": "^7.13.15",
    "@storybook/addon-essentials": "^6.2.3",
    "@storybook/addon-links": "^6.1.21",
    "@storybook/react": "^6.2.7",
    "@testing-library/dom": "^7.30.1",
    "@testing-library/jest-dom": "^5.11.10",
    "@testing-library/react": "^11.2.5",
    "@testing-library/user-event": "13.1.1",
    "@types/classnames": "^2.2.11",
    "@types/cookie": "^0.4.0",
    "@types/htmlescape": "^1.1.1",
    "@types/jsonwebtoken": "^8.5.1",
    "@types/lodash": "^4.14.168",
    "@types/micro": "^7.3.3",
    "@types/ms": "^0.7.30",
    "@types/nanoid": "^2.1.0",
    "@types/next": "^9.0.0",
    "@types/nock": "^11.1.0",
    "@types/node": "^14.14.37",
    "@types/node-gzip": "^1.1.0",
    "@types/nprogress": "^0.2.0",
    "@types/puppeteer": "^5.4.3",
    "@types/qs": "^6.9.6",
    "@types/react": "^17.0.3",
    "@types/react-day-picker": "^5.3.0",
    "@types/react-scroll": "^1.8.2",
    "@types/react-syntax-highlighter": "^13.5.0",
    "@types/react-transition-group": "^4.4.1",
    "@types/segment-analytics": "^0.0.33",
    "@types/statuses": "^2.0.0",
    "@types/styled-jsx": "^2.2.8",
    "@types/url-parse": "^1.4.3",
    "@types/yup": "^0.29.11",
    "@typescript-eslint/eslint-plugin": "^4.21.0",
    "@typescript-eslint/parser": "^4.21.0",
    "@vercel/next": "^2.7.9",
    "babel-loader": "^8.2.2",
    "babel-plugin-module-resolver": "^4.1.0",
    "cross-env": "^7.0.3",
    "eslint": "^7.24.0",
    "eslint-plugin-react": "^7.22.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "eslint-plugin-spellcheck": "^0.0.17",
    "full-icu": "^1.3.4",
    "husky": "^6.0.0",
    "jest": "^26.6.3",
    "jest-puppeteer": "^4.4.0",
    "nock": "^13.0.11",
    "now": "^21.0.1",
    "puppeteer": "^8.0.0",
    "react-is": "^17.0.2",
    "storybook-formik": "^2.1.5",
    "ts-node": "^9.1.1"
  },
  "engines": {
    "node": "~14.*"
  }
```

**dependabot.yml content**
N/A

**What you expected to see, versus what you actually saw**
Expected to see `nom` or `yarn` output, instead saw the following:
```
  proxy | time="2021-04-20T17:49:34Z" level=info msg="proxy starting" commit=6110d80abea2da3ba0227fa83d27d2e39fd3bd85
  proxy | 2021/04/20 17:49:34 Listening (:1080)
fetcher | I, [2021-04-20T17:49:35.625334 #6]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
fetcher | warning: parser/current is loading parser/ruby26, which recognizes
fetcher | warning: 2.6.7-compliant syntax, but you are running 2.6.6.
fetcher | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
fetcher | INFO <job_77340875> Starting job processing
fetcher | ERROR <job_77340875> Error during file fetching; aborting
fetcher | ERROR <job_77340875> key not found: :security_updates_only
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/job.rb:30:in `fetch'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/job.rb:30:in `initialize'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:74:in `new'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:74:in `job'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:88:in `file_fetcher'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:78:in `base_commit_sha'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:12:in `perform_job'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
fetcher | ERROR <job_77340875> bin/fetch_files.rb:21:in `<main>'
fetcher | ERROR <job_77340875> key not found: :security_updates_only
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/job.rb:30:in `fetch'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/job.rb:30:in `initialize'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:74:in `new'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:74:in `job'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:84:in `raven_context'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:151:in `handle_file_fetcher_error'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:23:in `rescue in perform_job'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:11:in `perform_job'
fetcher | ERROR <job_77340875> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
fetcher | ERROR <job_77340875> bin/fetch_files.rb:21:in `<main>'
fetcher | /home/dependabot/dependabot-updater/lib/dependabot/job.rb:30:in `fetch': key not found: :security_updates_only (KeyError)
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/job.rb:30:in `initialize'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:74:in `new'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:74:in `job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:84:in `raven_context'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:39:in `handle_exception'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:31:in `rescue in run'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:26:in `run'
fetcher | 	from bin/fetch_files.rb:21:in `<main>'
fetcher | /home/dependabot/dependabot-updater/lib/dependabot/job.rb:30:in `fetch': key not found: :security_updates_only (KeyError)
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/job.rb:30:in `initialize'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:74:in `new'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:74:in `job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:84:in `raven_context'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:151:in `handle_file_fetcher_error'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:23:in `rescue in perform_job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:11:in `perform_job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
fetcher | 	from bin/fetch_files.rb:21:in `<main>'
fetcher | /home/dependabot/dependabot-updater/lib/dependabot/job.rb:30:in `fetch': key not found: :security_updates_only (KeyError)
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/job.rb:30:in `initialize'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:74:in `new'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:74:in `job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:88:in `file_fetcher'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:78:in `base_commit_sha'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_job.rb:12:in `perform_job'
fetcher | 	from /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
fetcher | 	from bin/fetch_files.rb:21:in `<main>'
```

**Native package manager behavior**
```
$ yarn outdated
yarn outdated v1.22.10
info Color legend : 
 "<red>"    : Major Update backward-incompatible updates 
 "<yellow>" : Minor Update backward-compatible features 
 "<green>"  : Patch Update backward-compatible bug fixes
Package                          Current  Wanted   Latest   Package Type    URL                                                                             
@babel/core                      7.13.15  7.13.16  7.13.16  devDependencies https://babel.dev/docs/en/next/babel-core                                       
@octokit/core                    3.3.1    3.4.0    3.4.0    dependencies    https://github.com/octokit/core.js#readme                                       
@sentry/browser                  6.2.5    6.3.0    6.3.0    dependencies    https://github.com/getsentry/sentry-javascript/tree/master/packages/browser     
@sentry/integrations             6.2.5    6.3.0    6.3.0    dependencies    https://github.com/getsentry/sentry-javascript/tree/master/packages/integrations
@sentry/node                     6.2.5    6.3.0    6.3.0    dependencies    https://github.com/getsentry/sentry-javascript/tree/master/packages/node        
@sentry/webpack-plugin           1.14.2   1.15.0   1.15.0   dependencies    https://github.com/getsentry/sentry-webpack-plugin                              
@storybook/addon-essentials      6.2.3    6.2.8    6.2.8    devDependencies https://github.com/storybookjs/storybook/tree/master/addons/essentials          
@storybook/addon-links           6.1.21   6.2.8    6.2.8    devDependencies https://github.com/storybookjs/storybook/tree/master/addons/links               
@storybook/react                 6.2.7    6.2.8    6.2.8    devDependencies https://github.com/storybookjs/storybook/tree/master/app/react                  
@testing-library/dom             7.30.1   7.30.3   7.30.3   devDependencies https://github.com/testing-library/dom-testing-library#readme                   
@testing-library/react           11.2.5   11.2.6   11.2.6   devDependencies https://github.com/testing-library/react-testing-library#readme                 
@testing-library/user-event      13.1.1   13.1.1   13.1.5   devDependencies https://github.com/testing-library/user-event#readme                            
@typeform/embed                  1.1.1    1.1.5    1.1.5    dependencies                                                                                    
@types/classnames                2.2.11   2.3.1    2.3.1    devDependencies                                                                                 
@types/node                      14.14.37 14.14.41 14.14.41 devDependencies https://github.com/DefinitelyTyped/DefinitelyTyped.git                          
@typescript-eslint/eslint-plugin 4.21.0   4.22.0   4.22.0   devDependencies https://github.com/typescript-eslint/typescript-eslint#readme                   
@typescript-eslint/parser        4.21.0   4.22.0   4.22.0   devDependencies https://github.com/typescript-eslint/typescript-eslint#readme                   
eslint-plugin-react              7.22.0   7.23.2   7.23.2   devDependencies https://github.com/yannickcr/eslint-plugin-react                                
highlight.js                     10.7.1   10.7.1   10.7.2   dependencies    https://highlightjs.org/                                                        
jest-puppeteer                   4.4.0    4.4.0    5.0.1    devDependencies https://github.com/smooth-code/jest-puppeteer/tree/master#readme                
stripe                           8.142.0  8.144.0  8.144.0  dependencies    https://github.com/stripe/stripe-node                                           
✨  Done in 9.10s.
```

**Images of the diff or a link to the PR, issue or logs**
See above for the logs output from Dependabot.

**🕹 Bonus points: Smallest manifest that reproduces the issue**
Apologies, it appears that any `package.json` in our org makes Dependabot sad!

**Comment by jurre** [comment]
Thanks, we're looking into it!

**Comment by jurre** [comment]
Are you on the GitHub native version of Dependabot or on dependabot-preview?

**Comment by mvz** [comment]
I'm not the reporter but am facing this same problem on dependabot-preview.

**Comment by jurre** [comment]
> I'm not the reporter but am facing this same problem on dependabot-preview.

Thanks! That clarified some things for me, I have a fix in the making

**Comment by juanibiapina** [comment]
And what was the fix?

**Comment by jurre** [comment]
> And what was the fix? I see the same problem with ruby in dependabot-preview.

When did you see this? The fix was in one of our private projects, not in this repo.

**Comment by mvz** [comment]
I can confirm that the problem did occur with ruby as well, and that things seem to be working fine now.

**Comment by juanibiapina** [comment]
Sorry, I misspoke. It was a private project in ruby using dependabot-preview. And indeed it has been fixed.

**Comment by sgerrand** [comment]
@jurre: Dank u wel!
