### ISSUE TITLE
Failing when update elastic-apm-node

### ISSUE THREAD

**Issue by xx728** [dependabot/dependabot-core#3549]
npm_and_yarn

Parsing dependencies information
```
    Updating elastic-apm-node (from 2.17.3)…Traceback (most recent call last):
        25: from dependabot_orig.rb:85:in `<main>'
        24: from dependabot_orig.rb:85:in `each'
        23: from dependabot_orig.rb:123:in `block in <main>'
        22: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:39:in `updated_dependency_files'
        21: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `updated_lockfiles'
        20: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `each'
        19: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:149:in `block in updated_lockfiles'
        18: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:120:in `package_lock_changed?'
        17: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:187:in `updated_package_lock_content'
        16: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:30:in `updated_lockfile_content'
        15: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:57:in `in_a_temporary_directory'
        14: from /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
        13: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:60:in `block in in_a_temporary_directory'
        12: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:60:in `chdir'
        11: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:60:in `block (2 levels) in in_a_temporary_directory'
        10: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:34:in `block in updated_lockfile_content'
         9: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:34:in `chdir'
         8: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:35:in `block (2 levels) in updated_lockfile_content'
         7: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:115:in `run_current_npm_update'
         6: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:137:in `run_npm_updater'
         5: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:170:in `with_git_configured'
         4: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:139:in `block in run_npm_updater'
         3: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:151:in `run_npm_top_level_updater'
         2: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:123:in `run_helper_subprocess'
         1: from /usr/lib/ruby/2.6.0/json/common.rb:156:in `parse'
/usr/lib/ruby/2.6.0/json/common.rb:156:in `parse': 767: unexpected token at '' (JSON::ParserError)
        24: from dependabot_orig.rb:85:in `<main>'
        23: from dependabot_orig.rb:85:in `each'
        22: from dependabot_orig.rb:123:in `block in <main>'
        21: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:39:in `updated_dependency_files'
        20: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `updated_lockfiles'
        19: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:148:in `each'
        18: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:149:in `block in updated_lockfiles'
        17: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:120:in `package_lock_changed?'
        16: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:187:in `updated_package_lock_content'
        15: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:30:in `updated_lockfile_content'
        14: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:57:in `in_a_temporary_directory'
        13: from /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
        12: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:60:in `block in in_a_temporary_directory'
        11: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:60:in `chdir'
        10: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:60:in `block (2 levels) in in_a_temporary_directory'
         9: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:34:in `block in updated_lockfile_content'
         8: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:34:in `chdir'
         7: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:35:in `block (2 levels) in updated_lockfile_content'
         6: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:115:in `run_current_npm_update'
         5: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:137:in `run_npm_updater'
         4: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:170:in `with_git_configured'
         3: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:139:in `block in run_npm_updater'
         2: from /aea-dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/npm_lockfile_updater.rb:151:in `run_npm_top_level_updater'
         1: from /aea-dependabot/common/lib/dependabot/shared_helpers.rb:87:in `run_helper_subprocess'
/aea-dependabot/common/lib/dependabot/shared_helpers.rb:133:in `rescue in run_helper_subprocess': Dependabot::SharedHelpers::HelperSubprocessFailed
```

**Comment by jeffwidman** [comment]
Sorry for the slow response time, we've been very focused on a number of internal infrastructure changes and only now starting to catchup on issues.

Looking at this traceback, it doesn't provide enough info to debug further without knowing the manifest file that generated this in the first place. It looks like it calls out `npm` and that returned an empty response instead of what we expected... 

Given that this is over a year old, I'm guessing that either this issue was already fixed or you no longer have the original file that was causing problems, so I'm going to close this. If you're still experiencing the problem with the current dependabot, then post here including a copy of the manifest file and I can re-open.
