### ISSUE TITLE
Dependabot throws an unknown error for expanded dependency specification syntax in Poetry

### ISSUE THREAD

**Issue by Nishnha** [dependabot/dependabot-core#3565]
**Context**
Poetry supports an [expanded dependency specification syntax](https://python-poetry.org/docs/dependency-specification/#expanded-dependency-specification-syntax) for defining additional dependency attributes.

While the Python ecosystem can correctly identify dependencies listed with this syntax and attempt to update them, the update fails:
```
/home/dependabot/dependabot-core/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:82:in `block in updated_pyproject_content': Content did not change! (RuntimeError)
```

This is because the parser for the manifest file, TomlRB, adds dependencies defined using the expanded syntax to the dependencies hash as an object rather than a key. Thus, regex that normally detects a version change fails on the object, throwing the error.

**Package ecosystem**
Python/Poetry

**Manifest location and content prior to update**
path: `/pyproject.toml` 
<details><summary>contents</summary>
<p>

```toml
[build-system]
requires = [ "poetry>=0.12",]
build-backend = "poetry.masonry.api"

[tool.poetry]
name = "downforeveryone"
version = "1.0.0"
description = "checks if a website is really down via isup.me"
authors = [ "Ryan Delaney <ryan.patrick.delaney@protonmail.com>",]
readme = "README.rst"
repository = "https://github.com/rpdelaney/downforeveryone"
homepage = "https://pypi.org/project/downforeveryone"
classifiers = [ "Environment :: Console", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python :: 3 :: Only",]

[tool.black]
line-length = 79
target_version = [ "py38",]

[tool.isort]
combine_star = true
indent = "    "
length_sort = false
line_length = 79
multi_line_output = 3

[tool.poetry.dependencies]
python = ">=3.7, <4"
requests = "^2.22"

[tool.poetry.dev-dependencies]
mock = "^4.0"
pytest = "^6.2"
pytest-cov = "^2.11"
pytest-mock = "^3.5"
flake8 = "^3.9"
black = "20.8b1"
mypy = "^0.812"
flake8-bugbear = "^21.4"
flake8-docstrings = "^1.6"
flake8-breakpoint = "^1.1"
pytest-icdiff = "^0.5"
toml = "^0.10.2"
responses = "^0.13.2"
semver = "^2.13.0"

[tool.poetry.scripts]
isup = "downforeveryone.isup:main"

[tool.pytest.ini_options]
console_output_style = "progress"
addopts = "--cov=downforeveryone"
mock_use_standalone_module = true

[tool.poetry.dev-dependencies.isort]
version = "^5.4"
extras = [ "pyproject",]
```
</p>
</details> 

**Updated dependency**
Bumping `isort` from v5.7.0 to v5.8.0

**What you expected to see, versus what you actually saw**
- Expected Dependabot to upgrade `isort` from v5.7.0 to v5.8.0.

- Received a traceback for `poetry_file_updater.rb` 

<details><summary>traceback</summary>

```sh
=== isort (5.7.0)
=> checking for updates 16/16
=> latest available version is 5.8.0
=> latest allowed version is 5.8.0
=> requirements to unlock: own
=> requirements update strategy: widen_ranges
=> updating isort from 5.7.0 to 5.8.0
Traceback (most recent call last):
	10: from bin/dry-run.rb:594:in `<main>'
	 9: from bin/dry-run.rb:594:in `each'
	 8: from bin/dry-run.rb:682:in `block in <main>'
	 7: from /home/dependabot/dependabot-core/python/lib/dependabot/python/file_updater.rb:32:in `updated_dependency_files'
	 6: from /home/dependabot/dependabot-core/python/lib/dependabot/python/file_updater.rb:92:in `updated_poetry_based_files'
	 5: from /home/dependabot/dependabot-core/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:33:in `updated_dependency_files'
	 4: from /home/dependabot/dependabot-core/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:50:in `fetch_updated_dependency_files'
	 3: from /home/dependabot/dependabot-core/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:67:in `updated_pyproject_content'
	 2: from /home/dependabot/dependabot-core/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:67:in `reduce'
	 1: from /home/dependabot/dependabot-core/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:67:in `each'
 /home/dependabot/dependabot-core/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:82:in `block in updated_pyproject_content': Content did not change! (RuntimeError)
```
</details> 

**🕹 Bonus points: Smallest manifest that reproduces the issue**
```toml
[tool.poetry.dev-dependencies.isort]
version = "^5.4"
extras = [ "pyproject",]
```

**Reproduce**
```sh
bin/dry-run.rb pip "rpdelaney/downforeveryone" --dir="/." --commit=8729649e0552284de145a9a4b840b14a1f99d941 --cache=files
```

Related issues:
- #2855 
- #2715

**Comment by jeffwidman** [comment]
Related:
* #3290
