### ISSUE TITLE
New unhandled error in go_modules `update_checker` code

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#3664]
Traceback I started seeing this morning:

```
updater | ERROR <job_119676076> Error processing github.com/zeromq/goczmq (NoMethodError)
updater | ERROR <job_119676076> private method `select' called for nil:NilClass
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-go_modules-0.145.1/lib/dependabot/go_modules/update_checker/latest_version_finder.rb:73:in `block (2 levels) in available_versions'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.145.1/lib/dependabot/shared_helpers.rb:159:in `with_git_configured'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-go_modules-0.145.1/lib/dependabot/go_modules/update_checker/latest_version_finder.rb:54:in `block in available_versions'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.145.1/lib/dependabot/shared_helpers.rb:45:in `block (2 levels) in in_a_temporary_directory'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.145.1/lib/dependabot/shared_helpers.rb:45:in `chdir'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.145.1/lib/dependabot/shared_helpers.rb:45:in `block in in_a_temporary_directory'
updater | ERROR <job_119676076> /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.145.1/lib/dependabot/shared_helpers.rb:42:in `in_a_temporary_directory'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-go_modules-0.145.1/lib/dependabot/go_modules/update_checker/latest_version_finder.rb:53:in `available_versions'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-go_modules-0.145.1/lib/dependabot/go_modules/update_checker/latest_version_finder.rb:44:in `fetch_latest_version'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-go_modules-0.145.1/lib/dependabot/go_modules/update_checker/latest_version_finder.rb:34:in `latest_version'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-go_modules-0.145.1/lib/dependabot/go_modules/update_checker.rb:34:in `latest_resolvable_version'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-go_modules-0.145.1/lib/dependabot/go_modules/update_checker.rb:41:in `latest_version'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:448:in `log_checking_for_update'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:186:in `check_and_create_pull_request'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:79:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_119676076> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
updater | ERROR <job_119676076> bin/update_files.rb:21:in `<main>'
```

**Comment by jurre** [comment]
Thanks @jeffwidman we'll need to dig into it, but we should be able to view the full logs etc using the job ID 👍

**Comment by feelepxyz** [comment]
There's a fix for this here: https://github.com/dependabot/dependabot-core/pull/3661

**Comment by jeffwidman** [comment]
Thanks!
