### ISSUE TITLE
Multiple terraform providers in single file does not work

### ISSUE THREAD

**Issue by jtgrohn** [dependabot/dependabot-core#3760]
**Package ecosystem**
`terraform`

**Language version**
`0.15.3`

**Manifest location and content prior to update**
`/backend.tf`

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.41.0"
    }

    github = {
      source  = "integrations/github"
      version = "4.9.3"
    }
  }
}
```

**dependabot.yml content**

```
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
```

**Updated dependency**

`integrations/github` from `4.9.3` to `4.9.4`

**What you expected to see, versus what you actually saw**

I expected a PR to be created to update `hashicorp/aws` from `3.41.0` to `3.42.0` and `integrations/github` from `4.9.3` to `4.9.4`, but instead only the `hashicorp/aws` PR was created and there were these errors in the dependabot log.

```
updater | INFO <job_136903021> Checking if integrations/github 4.9.3 needs updating
  proxy | 2021/05/20 21:28:03 [014] GET https://registry.terraform.io:443/v1/providers/integrations/github/versions
  proxy | 2021/05/20 21:28:03 [014] 200 https://registry.terraform.io:443/v1/providers/integrations/github/versions
updater | INFO <job_136903021> Latest version is 4.9.4
updater | INFO <job_136903021> Requirements to unlock own
updater | INFO <job_136903021> Requirements update strategy 
updater | INFO <job_136903021> Updating integrations/github from 4.9.3 to 4.9.4
updater | I, [2021-05-20T21:28:03.661521 #7]  INFO -- sentry: ** [Raven] Sending event 64e74927273e47baa33b3e3b3d6110f7 to Sentry
  proxy | 2021/05/20 21:28:03 [016] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/05/20 21:28:04 [016] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_136903021> Error processing integrations/github (RuntimeError)
updater | ERROR <job_136903021> Content didn't change!
updater | ERROR <job_136903021> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.148.3/lib/dependabot/terraform/file_updater.rb:24:in `block in updated_dependency_files'
updater | ERROR <job_136903021> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.148.3/lib/dependabot/terraform/file_updater.rb:20:in `each'
updater | ERROR <job_136903021> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.148.3/lib/dependabot/terraform/file_updater.rb:20:in `updated_dependency_files'
updater | ERROR <job_136903021> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:691:in `generate_dependency_files_for'
updater | ERROR <job_136903021> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:281:in `check_and_create_pull_request'
updater | ERROR <job_136903021> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:89:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_136903021> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_136903021> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_136903021> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_136903021> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_136903021> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
updater | ERROR <job_136903021> bin/update_files.rb:21:in `<main>'
updater | INFO <job_136903021> Finished job processing
updater | time="2021-05-20T21:28:04Z" level=info msg="task complete" container_id=job-136903021-updater exit_code=0 job_id=136903021 step=updater
```

Note, that when I change the contents of the file to only have a single required provider,

```
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "4.9.3"
    }
  }
}
```

the PR is created as expected: 
![image](https://user-images.githubusercontent.com/14808144/119051057-aafbf400-b990-11eb-96ec-de67c3074631.png)

**🕹 Bonus points: Smallest manifest that reproduces the issue**

See above (`Manifest location and content prior to update` and `dependabot.yml content`)

**Comment by jtgrohn** [comment]
I performed a few other tests - it seems to only ever be able to update the first provider in the list.

If I reorder the providers to 
```
terraform {
  required_providers {

    github = {
      source  = "integrations/github"
      version = "4.9.3"
    }

    aws = {
      source  = "hashicorp/aws"
      version = "3.41.0"
    }
  }
}
```

it sends a PR to update `integrations/github` and fails to send a PR for `hashicorp/aws`.

If `hashicorp/aws` is up to date:

```
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.42.0"
    }

    github = {
      source  = "integrations/github"
      version = "4.9.3"
    }
  }
}
```
It still fails to update `integrations/github`


If I add a third provider:
```
terraform {
  required_providers {
    github = {
      source  = "integrations/github"
      version = "4.9.3"
    }

    aws = {
      source  = "hashicorp/aws"
      version = "3.41.0"
    }

    http = {
      source  = "hashicorp/http"
      version = "1.0"
    }

  }
}
```

It will send a PR to update `integrations/github`, but fails to do so for `hashicorp/aws` and `hashicorp/http`

**Comment by jurre** [comment]
Thanks @jtgrohn, I'm working on a fix, should hopefully be out a little later today 🤞
