### ISSUE TITLE
Dependabot failed to update dependencies

### ISSUE THREAD

**Issue by coding-red-panda** [dependabot/dependabot-core#3868]
**Package ecosystem**
npm
**Package manager version**
yarn 1.22.10
**Language version**
node 12.19.0
**Manifest location and content prior to update**
/yarn.lock
**dependabot.yml content**

**Updated dependency**

**What you expected to see, versus what you actually saw**
Expected the dependencies to be updated
**Native package manager behavior**
Works locally
**Images of the diff or a link to the PR, issue or logs**
/
**🕹 Bonus points: Smallest manifest that reproduces the issue**
```

updater | INFO <job_153428905> Updating vue, vue-template-compiler
updater | I, [2021-06-09T09:32:34.357654 #8]  INFO -- sentry: ** [Raven] Sending event 6a6649a009ce4be1a5b2b253880d6eb5 to Sentry
  proxy | 2021/06/09 09:32:34 [088] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/06/09 09:32:34 [088] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_153428905> Error processing vue-template-compiler (RuntimeError)
updater | ERROR <job_153428905> Expected content to change!
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater/package_json_updater.rb:36:in `block (2 levels) in updated_package_json_content'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater/package_json_updater.rb:26:in `each'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater/package_json_updater.rb:26:in `block in updated_package_json_content'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater/package_json_updater.rb:25:in `each'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater/package_json_updater.rb:25:in `reduce'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater/package_json_updater.rb:25:in `updated_package_json_content'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater/package_json_updater.rb:16:in `updated_package_json'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater.rb:199:in `updated_package_json_content'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater.rb:127:in `block in updated_manifest_files'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater.rb:126:in `map'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater.rb:126:in `updated_manifest_files'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.151.1/lib/dependabot/npm_and_yarn/file_updater.rb:38:in `updated_dependency_files'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:680:in `generate_dependency_files_for'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:272:in `check_and_create_pull_request'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:80:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_153428905> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
updater | ERROR <job_153428905> bin/update_files.rb:21:in `<main>'
```

**Comment by wengjq** [comment]
@coding-bunny Can some other dependent packages can be updated?

**Comment by coding-bunny** [comment]
It seems to be able to update other private dependencies yes

**Comment by wengjq** [comment]
I also encountered the same problem，When I encounter these two dependencies，For example，vue、vue-template-compiler、is-windows、prettier and so on。Very stable reproduction！

**Comment by jurre** [comment]
@coding-bunny could you please share a little more information like the package.json and package-lock.json files, your dependabot config file etc, that'll help us figure out what's going on.

**Comment by coding-bunny** [comment]
If I see it happen again I'll add it here.

**Comment by coding-bunny** [comment]
found another example where it happened in one of our private repositories that has a dependency on another private repository:

```

updater | I, [2021-09-29T10:43:00.161530 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes
updater | warning: 2.7.4-compliant syntax, but you are running 2.7.1.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_214705855> Starting job processing
updater | INFO <job_214705855> Starting update job for customink/application_service_catalog
updater | INFO <job_214705855> Checking if nokogiri 1.12.4 needs updating
  proxy | 2021/09/29 10:43:03 [016] GET https://rubygems.org:443/api/v1/versions/nokogiri.json
  proxy | 2021/09/29 10:43:03 [016] 200 https://rubygems.org:443/api/v1/versions/nokogiri.json
updater | INFO <job_214705855> Latest version is 1.12.5
  proxy | 2021/09/29 10:43:04 [019] GET https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:04 [019] * authenticating git server request (host: github.com)
  proxy | 2021/09/29 10:43:04 [019] 404 https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:04 [019] * auth'd git request returned 404, retrying without auth
  proxy | 2021/09/29 10:43:05 [019] * de-auth'd request returned 401, replacing response
  proxy | 2021/09/29 10:43:05 [022] GET https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:05 [022] * authenticating git server request (host: github.com)
  proxy | 2021/09/29 10:43:05 [022] 404 https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:05 [022] * auth'd git request returned 404, retrying without auth
  proxy | 2021/09/29 10:43:05 [022] * de-auth'd request returned 401, replacing response
  proxy | 2021/09/29 10:43:05 [025] GET https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:05 [025] * authenticating git server request (host: github.com)
  proxy | 2021/09/29 10:43:05 [025] 404 https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:05 [025] * auth'd git request returned 404, retrying without auth
  proxy | 2021/09/29 10:43:05 [025] * de-auth'd request returned 401, replacing response
  proxy | 2021/09/29 10:43:06 [028] GET https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:06 [028] * authenticating git server request (host: github.com)
  proxy | 2021/09/29 10:43:06 [028] 404 https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:06 [028] * auth'd git request returned 404, retrying without auth
  proxy | 2021/09/29 10:43:06 [028] * de-auth'd request returned 401, replacing response
  proxy | 2021/09/29 10:43:06 [030] GET https://github.com:443/customink/is_it_up.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:06 [030] * authenticating git server request (host: github.com)
  proxy | 2021/09/29 10:43:06 [030] 200 https://github.com:443/customink/is_it_up.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:06 [032] GET https://github.com:443/customink/is_it_working.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:06 [032] * authenticating git server request (host: github.com)
  proxy | 2021/09/29 10:43:06 [032] 200 https://github.com:443/customink/is_it_working.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:06 [034] GET https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:06 [034] * authenticating git server request (host: github.com)
  proxy | 2021/09/29 10:43:07 [034] 404 https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2021/09/29 10:43:07 [034] * auth'd git request returned 404, retrying without auth
  proxy | 2021/09/29 10:43:07 [034] * de-auth'd request returned 401, replacing response
updater | INFO <job_214705855> Handled error whilst updating nokogiri: git_dependencies_not_reachable {:"dependency-urls"=>["git@github.com:customink/inkycop.git"]}
updater | INFO <job_214705855> Finished job processing
updater | time="2021-09-29T10:43:07Z" level=info msg="task complete" container_id=job-214705855-updater exit_code=0 job_id=214705855 step=updater
```

**Comment by coding-bunny** [comment]
This is what is inside the `Gemfile`:

```
group :development, :test do
  gem 'bundle-audit'
  gem 'byebug', platforms: %i[mri mingw x64_mingw]
  gem 'factory_bot_rails'
  gem 'inkycop', github: 'customink/inkycop', tag: '3.11.2'
  gem 'rspec-rails'
end
```

I kind of expect Dependabot to have access to our private repositories when it's added on the Company level.

**Comment by coding-bunny** [comment]
Happens to both Ruby projects and/or nodeJS/Yarn updates.
Every time it tries to check for a private dependency the process just fails.

**Comment by jurre** [comment]
> I kind of expect Dependabot to have access to our private repositories when it's added on the Company level.

You'll need to explicitly give dependabot access to the repository: https://docs.github.com/en/organizations/keeping-your-organization-secure/managing-security-and-analysis-settings-for-your-organization#allowing-dependabot-to-access-private-repositories

**Comment by coding-bunny** [comment]
It has. 
Dependabot has been configured to access all our private repositories.

**Comment by dentarg** [comment]
@asciimike Thanks for the clarification. Hope you can get to that rather sooner than later.

Would I be able to workaround this, and make Dependabot work for my repo, if I was [vendoring](https://bundler.io/man/bundle-cache.1.html) my dependencies? (i.e. no need to fetch the private repo)

**Comment by asciimike** [comment]
I admit that I don't immediately know; my assumption is that even if you vendor deps, we'd still need to make requests to the locations those deps are stored in order to determine if they need to be updated, which would require access.

**Comment by dentarg** [comment]
Maybe @jurre or @feelepxyz knows?

**Comment by brcarp** [comment]
Also in `customink` org, we had similar issue with an application that included the following in its `Gemfile`:

```ruby
# Custom Ink internal gems
gem "client_client",        github: "customink/client_client",        tag: "v0.2.4"
gem "decorator_client",     github: "customink/decorator_client",     tag: "v2.6.0"
gem "foreman-export-monit", github: "customink/foreman-export-monit", tag: "v0.0.4"
gem "ink_colors",           github: "customink/ink_colors",           tag: "v1.7.7"
gem "messaging_helper",     github: "customink/messaging_helper",     tag: "v2.1.1"
gem "omniauth-customink",   github: "customink/omniauth-customink",   tag: "v0.1.3"
gem "quote_client",         github: "customink/quote_client",         tag: "v0.0.15"
gem "reviews_client",       github: "customink/reviews_client",       tag: "v0.2.0"
gem "service_config",       github: "customink/service_config",       tag: "v0.3.1"
gem "supplier_client",      github: "customink/supplier_client",      tag: "v2.4.2"

# [...]
# (other sources/groups not relevant to this issue)
# [...]

group :development, :test do
  gem "database_cleaner"
  gem "faker"
  gem "named_seeds"
  gem "pry"
  gem "pry-byebug"
  gem "pry-stack_explorer"
  gem "rspec-rails"
  gem "rubocop-junit_formatter"
  gem "ruby-oci8", "2.2.9"
  gem "rubyzip", require: "zip"
  gem "stuffed_bunny", require: false

  gem "inkycop", github: "customink/inkycop", tag: "v0.0.13"
end
```

**Comment by coding-bunny** [comment]
Found again an issue with one of our repositories not being able to apply a Dependabot update from an Alert:

```

  proxy | time="2022-04-14T06:16:57Z" level=info msg="proxy starting" commit=0cfe6fc8a85a641097e4d9faf5c8349b892b1e40
  proxy | 2022/04/14 06:16:57 Listening (:1080)
updater | 2022-04-14T06:16:57.225808076 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2022-04-14T06:16:57.248357787 [345939629:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2022-04-14T06:16:58Z" level=info msg="guest starting" commit=284b5dacb1face4d3c6d1a0b48f574503fb7ea54
updater | time="2022-04-14T06:16:58Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=345939629 updater_timeout=30m0s updater_version=0.180.5-6fcec953c00ec2a7270e2e6c7912aa60a97d92d8
updater | I, [2022-04-14T06:17:00.161749 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_345939629> Starting job processing
  proxy | 2022/04/14 06:17:02 [002] GET https://api.github.com:443/repos/customink/application-service-catalog
  proxy | 2022/04/14 06:17:02 [002] * authenticating github api request
  proxy | 2022/04/14 06:17:02 [002] 200 https://api.github.com:443/repos/customink/application-service-catalog
  proxy | 2022/04/14 06:17:02 [004] GET https://api.github.com:443/repos/customink/application-service-catalog/git/refs/heads/main
  proxy | 2022/04/14 06:17:02 [004] * authenticating github api request
  proxy | 2022/04/14 06:17:02 [004] 200 https://api.github.com:443/repos/customink/application-service-catalog/git/refs/heads/main
  proxy | 2022/04/14 06:17:02 [006] GET https://api.github.com:443/repos/customink/application-service-catalog/contents/?ref=825d98dedd50b8aadc46b547f8c29a04922f069c
  proxy | 2022/04/14 06:17:02 [006] * authenticating github api request
  proxy | 2022/04/14 06:17:02 [006] 200 https://api.github.com:443/repos/customink/application-service-catalog/contents/?ref=825d98dedd50b8aadc46b547f8c29a04922f069c
  proxy | 2022/04/14 06:17:02 [008] GET https://api.github.com:443/repos/customink/application-service-catalog/contents/Gemfile?ref=825d98dedd50b8aadc46b547f8c29a04922f069c
  proxy | 2022/04/14 06:17:02 [008] * authenticating github api request
  proxy | 2022/04/14 06:17:02 [008] 200 https://api.github.com:443/repos/customink/application-service-catalog/contents/Gemfile?ref=825d98dedd50b8aadc46b547f8c29a04922f069c
  proxy | 2022/04/14 06:17:02 [010] GET https://api.github.com:443/repos/customink/application-service-catalog/contents/Gemfile.lock?ref=825d98dedd50b8aadc46b547f8c29a04922f069c
  proxy | 2022/04/14 06:17:02 [010] * authenticating github api request
  proxy | 2022/04/14 06:17:03 [010] 200 https://api.github.com:443/repos/customink/application-service-catalog/contents/Gemfile.lock?ref=825d98dedd50b8aadc46b547f8c29a04922f069c
updater | INFO <job_345939629> Finished job processing
updater | time="2022-04-14T06:17:03Z" level=info msg="task complete" container_id=job-345939629-file-fetcher exit_code=0 job_id=345939629 step=fetcher
updater | I, [2022-04-14T06:17:04.212992 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_345939629> Starting job processing
updater | INFO <job_345939629> Starting update job for customink/application-service-catalog
updater | INFO <job_345939629> Checking if nokogiri 1.13.3 needs updating
  proxy | 2022/04/14 06:17:08 [016] GET https://rubygems.org:443/api/v1/versions/nokogiri.json
  proxy | 2022/04/14 06:17:08 [016] 200 https://rubygems.org:443/api/v1/versions/nokogiri.json
updater | INFO <job_345939629> Latest version is 1.13.4
  proxy | 2022/04/14 06:17:09 [019] GET https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:09 [019] * authenticating git server request (host: github.com)
  proxy | 2022/04/14 06:17:09 [019] 404 https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:09 [019] * auth'd git request returned 404, retrying without auth
  proxy | 2022/04/14 06:17:09 [019] * de-auth'd request returned 401, replacing response
  proxy | 2022/04/14 06:17:09 [022] GET https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:09 [022] * authenticating git server request (host: github.com)
  proxy | 2022/04/14 06:17:09 [022] 404 https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:09 [022] * auth'd git request returned 404, retrying without auth
  proxy | 2022/04/14 06:17:09 [022] * de-auth'd request returned 401, replacing response
  proxy | 2022/04/14 06:17:10 [025] GET https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:10 [025] * authenticating git server request (host: github.com)
  proxy | 2022/04/14 06:17:10 [025] 404 https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:10 [025] * auth'd git request returned 404, retrying without auth
  proxy | 2022/04/14 06:17:10 [025] * de-auth'd request returned 401, replacing response
  proxy | 2022/04/14 06:17:10 [028] GET https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:10 [028] * authenticating git server request (host: github.com)
  proxy | 2022/04/14 06:17:10 [028] 404 https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:10 [028] * auth'd git request returned 404, retrying without auth
  proxy | 2022/04/14 06:17:10 [028] * de-auth'd request returned 401, replacing response
  proxy | 2022/04/14 06:17:11 [030] GET https://github.com:443/customink/is_it_up.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:11 [030] * authenticating git server request (host: github.com)
  proxy | 2022/04/14 06:17:11 [030] 200 https://github.com:443/customink/is_it_up.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:11 [032] GET https://github.com:443/customink/is_it_working.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:11 [032] * authenticating git server request (host: github.com)
  proxy | 2022/04/14 06:17:11 [032] 200 https://github.com:443/customink/is_it_working.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:11 [034] GET https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:11 [034] * authenticating git server request (host: github.com)
  proxy | 2022/04/14 06:17:11 [034] 404 https://github.com:443/customink/inkycop.git/info/refs?service=git-upload-pack
  proxy | 2022/04/14 06:17:11 [034] * auth'd git request returned 404, retrying without auth
  proxy | 2022/04/14 06:17:11 [034] * de-auth'd request returned 401, replacing response
updater | INFO <job_345939629> Handled error whilst updating nokogiri: git_dependencies_not_reachable {:"dependency-urls"=>["git@github.com:customink/inkycop.git"]}
updater | INFO <job_345939629> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2022-04-14T06:17:11Z" level=info msg="task complete" container_id=job-345939629-updater exit_code=0 job_id=345939629 step=updater
```

Yet Dependabot has successfully created pull requests on this repository before and even has one open.
So Dependabot is supposed to work just fine.

**Comment by deivid-rodriguez** [comment]
Regarding this part of the error message in the previous comment:

```
updater | INFO <job_345939629> Handled error whilst updating nokogiri: git_dependencies_not_reachable {:"dependency-urls"=>["git@github.com:customink/inkycop.git"]}
```

Dependabot should be using https instead 🤔, it seems to be failing to replace the protocol? Does that come from your lockfile?

**Comment by coding-bunny** [comment]
Yes, we have most private ruby dependencies set to use git as protocol and not the https.
Easier to use the SSH access for everyone instead of constantly juggling tokens.

And yes, Dependabot should swap protocols

**Comment by jeffwidman** [comment]
Related--likely the same root cause:
* https://github.com/dependabot/dependabot-core/issues/5071
