### ISSUE TITLE
invalid byte sequence in US-ASCII (ArgumentError) 

### ISSUE THREAD

**Issue by wengjq** [dependabot/dependabot-core#3869]
Some dependent packages will have this problem.Is there any way to solve the problem？This problem has bothered me for a long time。

[Related issues](https://github.com/dependabot/dependabot-core/issues/1800)

``` json
  - Updating @babel/runtime (from 7.10.2)… submitted
  - Updating @vant/icons (from 1.2.1)… submitted
  - Updating @vue/babel-helper-vue-jsx-merge-props (from 1.0.0)… submitted
  - Updating vue-lazyload (from 1.2.3)… submitted
error updating vue-template-compiler (continuing)
/home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:354:in `start_with?': invalid byte sequence in US-ASCII (ArgumentError)
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:354:in `private_dependency_not_reachable?'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:331:in `check_npm_response'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:287:in `npm_details'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:78:in `possible_previous_versions_with_details'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:85:in `possible_versions_with_details'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:94:in `possible_versions'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb:203:in `block in updated_monorepo_dependencies'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb:196:in `each'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb:196:in `updated_monorepo_dependencies'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb:91:in `dependency_updates_from_full_unlock'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker/version_resolver.rb:80:in `latest_version_resolvable_with_full_unlock?'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-npm_and_yarn-0.149.4/lib/dependabot/npm_and_yarn/update_checker.rb:115:in `latest_version_resolvable_with_full_unlock?'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.149.4/lib/dependabot/update_checkers/base.rb:251:in `numeric_version_can_update?'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.149.4/lib/dependabot/update_checkers/base.rb:199:in `version_can_update?'
	from /home/faier/builds/6eb0e132/0/frontend/kira-dependencies/vendor/ruby/2.6.0/gems/dependabot-common-0.149.4/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
	from ./update.rb:132:in `block in <main>'
	from ./update.rb:105:in `each'
	from ./update.rb:105:in `<main>'

**Comment by wengjq** [comment]
@asciimike

**Comment by jurre** [comment]
It looks like the registry is returning malformed data, but other than that I am not able to offer much support without having access to the data.

Could you provide a way for me to reproduce the error?

**Comment by wengjq** [comment]
the project [package.json](https://github.com/wengjq/Share/blob/master/package.json)
the project [yarn.lock](https://github.com/wengjq/Share/blob/master/yarn.lock)

Is the above information useful?

**Comment by wengjq** [comment]
@jurre I cloned the project into my environment and ran the test。Then follow the steps to run the test [npm_and_yarn](https://github.com/dependabot/dependabot-core/tree/main/npm_and_yarn)。I found the following phenomenon。

before：
1、run bundle exec rspec spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb
2、The error is as follows 

``` json
Failures:

  1) Dependabot::NpmAndYarn::UpdateChecker::LatestVersionFinder#latest_version_with_no_unlock 
     Failure/Error: return true if npm_response.body.start_with?(/user ".*?" is not a /)

     ArgumentError:
       invalid byte sequence in US-ASCII
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:347:in `start_with?'
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:347:in `private_dependency_not_reachable?'
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:322:in `check_npm_response'
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:278:in `npm_details'
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:107:in `valid_npm_details?'
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:48:in `latest_version_with_no_unlock'
     # ./spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb:871:in `block (3 levels) in <top (required)>'
     # ./spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb:891:in `block (3 levels) in <top (required)>'
     # /home/faier/wjq/dependabot-core/common/spec/spec_helper.rb:49:in `block (2 levels) in <top (required)>'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  2) Dependabot::NpmAndYarn::UpdateChecker::LatestVersionFinder#latest_version_with_no_unlock when constrained 
     Failure/Error: return true if npm_response.body.start_with?(/user ".*?" is not a /)

     ArgumentError:
       invalid byte sequence in US-ASCII
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:347:in `start_with?'
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:347:in `private_dependency_not_reachable?'
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:322:in `check_npm_response'
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:278:in `npm_details'
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:107:in `valid_npm_details?'
     # ./lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:48:in `latest_version_with_no_unlock'
     # ./spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb:871:in `block (3 levels) in <top (required)>'
     # ./spec/dependabot/npm_and_yarn/update_checker/latest_version_finder_spec.rb:926:in `block (4 levels) in <top (required)>'
     # /home/faier/wjq/dependabot-core/common/spec/spec_helper.rb:49:in `block (2 levels) in <top (required)>'
     # /usr/local/rvm/gems/ruby-2.6.6/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

```

after：
1、I modified the file [latest_version_finder.rb](https://github.com/dependabot/dependabot-core/blob/07243bf2365993508e08aee1d7f055336168395e/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb#L347)

![image](https://user-images.githubusercontent.com/17982300/123241498-ca4beb00-d513-11eb-8e5c-733be7a0f115.png)

2、Then the problem is solved

So is there any way to set the character encoding？

**Comment by jurre** [comment]
> So is there any way to set the character encoding？

There's not.

It looks like you're not running Dependabot in the docker environment that it ships with, I'd highly recommend you do so. It seems like _something_ in your environment is causing files to be encoded as not-utf-8, running dependabot inside the docker environment we publish should prevent this.

**Comment by wengjq** [comment]
@jurre My scene cannot use docker. 

But I found the solution。Added  the following script 

> export RUBYOPT="-KU -E utf-8:utf-8" 

in the gitlab-ci.yml file 

It solves the problem perfectly！Thanks for your answer！
