### ISSUE TITLE
Terraform lockfile update failed when using modules

### ISSUE THREAD

**Issue by hosht** [dependabot/dependabot-core#3909]
**Package ecosystem**
Terraform

**Language version**
1.0.0

**Manifest location and content prior to update**
https://github.com/hosht/dependabot-terraform/tree/main/example5

**dependabot.yml content**
https://github.com/hosht/dependabot-terraform/blob/main/.github/dependabot.yml

**What you expected to see, versus what you actually saw**

When the root module has child modules, terraform providers lock command failed.
To fix it, running terraform init before.

Error output
```
updater | INFO <job_161564816> Starting job processing
updater | INFO <job_161564816> Starting update job for hosht/dependabot-terraform
updater | INFO <job_161564816> Checking if hashicorp/null 3.0.0 needs updating
  proxy | 2021/06/15 15:40:19 [012] GET https://registry.terraform.io:443/.well-known/terraform.json
  proxy | 2021/06/15 15:40:19 [012] 200 https://registry.terraform.io:443/.well-known/terraform.json
  proxy | 2021/06/15 15:40:19 [014] GET https://registry.terraform.io:443/v1/providers/hashicorp/null/versions
  proxy | 2021/06/15 15:40:19 [014] 200 https://registry.terraform.io:443/v1/providers/hashicorp/null/versions
updater | INFO <job_161564816> Latest version is 3.1.0
updater | INFO <job_161564816> Requirements to unlock own
updater | INFO <job_161564816> Requirements update strategy 
updater | INFO <job_161564816> Updating hashicorp/null from 3.0.0 to 3.1.0
updater | I, [2021-06-15T15:40:19.571809 #7]  INFO -- sentry: ** [Raven] Sending event b6f835a1f2864b80b01fcb292b587a8b to Sentry
  proxy | 2021/06/15 15:40:19 [017] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/06/15 15:40:19 [015] WARN: Cannot handshake client checkpoint-api.hashicorp.com:443 EOF
  proxy | 2021/06/15 15:40:19 [017] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_161564816> Error processing hashicorp/null (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_161564816> ╷
  proxy | 2021/06/15 15:40:19 [021] GET https://registry.terraform.io:443/.well-known/terraform.json
  proxy | 2021/06/15 15:40:19 [021] 200 https://registry.terraform.io:443/.well-known/terraform.json
updater | <job_161564816> │ Error: Module not installed
  proxy | 2021/06/15 15:40:19 [023] GET https://registry.terraform.io:443/v1/modules/matti/resource/shell/versions
updater | <job_161564816> │ 
  proxy | 2021/06/15 15:40:20 [023] 200 https://registry.terraform.io:443/v1/modules/matti/resource/shell/versions
updater | <job_161564816> │   on main.tf line 14:
updater | <job_161564816> │   14: module "files" {
updater | <job_161564816> │ 
updater | <job_161564816> │ This module is not yet installed. Run "terraform init" to install all
updater | <job_161564816> │ modules required by this configuration.
updater | <job_161564816> ╵
updater | <job_161564816> 
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.153.0/lib/dependabot/shared_helpers.rb:294:in `run_shell_command'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.153.0/lib/dependabot/terraform/file_updater.rb:107:in `block in update_lockfile_declaration'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.153.0/lib/dependabot/shared_helpers.rb:45:in `block (2 levels) in in_a_temporary_directory'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.153.0/lib/dependabot/shared_helpers.rb:45:in `chdir'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.153.0/lib/dependabot/shared_helpers.rb:45:in `block in in_a_temporary_directory'
updater | ERROR <job_161564816> /usr/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-common-0.153.0/lib/dependabot/shared_helpers.rb:42:in `in_a_temporary_directory'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.153.0/lib/dependabot/terraform/file_updater.rb:103:in `update_lockfile_declaration'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/vendor/ruby/2.6.0/gems/dependabot-terraform-0.153.0/lib/dependabot/terraform/file_updater.rb:30:in `updated_dependency_files'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:680:in `generate_dependency_files_for'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:272:in `check_and_create_pull_request'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:80:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_161564816> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
updater | ERROR <job_161564816> bin/update_files.rb:21:in `<main>'
```

**Comment by feelepxyz** [comment]
@hosht thanks for reporting. We're looking into a fix for this.

**Comment by feelepxyz** [comment]
@hosht this should be fixed now, can you confirm?

**Comment by hfurubotten** [comment]
I have taken a quick test in some of the repositories I have enabled dependabot with terraform in, and uses modules. Looks like it came a bit longer with todays update, but didn't get quite there yet with updates on all of them. Found two things that might be an issue for people. 

If there is backend information (state storage pointers) within the terraform configuration it will try to initialize that as well, which won't be possible with most backend types, as it should be well protected. Might need to add the [`-backend=false`](https://www.terraform.io/docs/cli/commands/init.html#backend-initialization) parameter to the `terraform init` command to disable the backend initialization in this process. Gets this error message with some of the backend information set in terraform:
```txt
updater | ERROR <job_165022024> Error processing corp/function-app/azurerm (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_165022024> Initializing modules...
updater | <job_165022024> Downloading app.terraform.io/corp/function-app/azurerm 1.0.0-b11 for function_app...
updater | <job_165022024> - function_app in .terraform/modules/function_app
updater | <job_165022024> Downloading app.terraform.io/corp/key-vault/azurerm 1.0.0 for key_vault...
updater | <job_165022024> - key_vault in .terraform/modules/key_vault
updater | <job_165022024> Downloading app.terraform.io/corp/resource-group/azurerm 1.0.0 for resource_group...
updater | <job_165022024> - resource_group in .terraform/modules/resource_group
updater | <job_165022024> Downloading app.terraform.io/corp/taggify/azurerm 1.0.0 for std_tags...
updater | <job_165022024> - std_tags in .terraform/modules/std_tags
updater | <job_165022024> 
updater | <job_165022024> Initializing the backend...
updater | <job_165022024> ╷
updater | <job_165022024> │ Error: Error building ARM Config: Please ensure you have installed Azure CLI version 2.0.79 or newer. Error parsing json result from the Azure CLI: Error launching Azure CLI: exec: "az": executable file not found in $PATH.
updater | <job_165022024> │ 
updater | <job_165022024> │ 
updater | <job_165022024> ╵
updater | <job_165022024> 
updater | ERROR <job_165022024> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.154.5/lib/dependabot/shared_helpers.rb:295:in `run_shell_command'
updater | ERROR <job_165022024> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.154.5/lib/dependabot/terraform/file_updater.rb:124:in `rescue in block in update_lockfile_declaration'
updater | ERROR <job_165022024> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.154.5/lib/dependabot/terraform/file_updater.rb:104:in `block in update_lockfile_declaration'
updater | ERROR <job_165022024> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.154.5/lib/dependabot/shared_helpers.rb:46:in `block (2 levels) in in_a_temporary_directory'
```

The other problem is with local modules where it looks like it can't find them in the file system. Don't know how much of the code you pull down from to run the updater, but looks like it can't find or access the sub folders that holds the modules. The error I get:
```txt
updater | ERROR <job_165015090> Error processing hashicorp/azurerm (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_165015090> Initializing modules...
updater | <job_165015090> Downloading app.terraform.io/corp/taggify/azurerm 1.0.0 for core_func_app_tags...
updater | <job_165015090> - core_func_app_tags in .terraform/modules/core_func_app_tags
updater | <job_165015090> - core_func_ingress_app_plan in 
updater | <job_165015090> 
updater | <job_165015090> ╷
updater | <job_165015090> │ Error: Failed to read module directory
updater | <job_165015090> │ 
updater | <job_165015090> │ Module directory  does not exist or cannot be read.
updater | <job_165015090> ╵
updater | <job_165015090> 
updater | ERROR <job_165015090> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.154.5/lib/dependabot/shared_helpers.rb:295:in `run_shell_command'
updater | ERROR <job_165015090> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.154.5/lib/dependabot/terraform/file_updater.rb:124:in `rescue in block in update_lockfile_declaration'
updater | ERROR <job_165015090> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.154.5/lib/dependabot/terraform/file_updater.rb:104:in `block in update_lockfile_declaration'
```

I could probably manage to come with a pull request for the first one, but the last one I have no idea how to do something with. 🙂

**Comment by hosht** [comment]
@feelepxyz 
thank you for quick response.
Updating lockfile seems to be working fine.

Then, sub modules update failed.
Here is the error output.
```
updater | INFO <job_165018022> Checking if matti/resource/shell 1.1.0 needs updating
  proxy | 2021/06/22 17:55:12 [016] GET https://registry.terraform.io:443/.well-known/terraform.json
  proxy | 2021/06/22 17:55:12 [016] 200 https://registry.terraform.io:443/.well-known/terraform.json
  proxy | 2021/06/22 17:55:12 [018] GET https://registry.terraform.io:443/v1/modules/matti/resource/shell/versions
  proxy | 2021/06/22 17:55:12 [018] 200 https://registry.terraform.io:443/v1/modules/matti/resource/shell/versions
updater | INFO <job_165018022> Latest version is 1.2.0
updater | INFO <job_165018022> Requirements to unlock own
updater | INFO <job_165018022> Requirements update strategy 
updater | INFO <job_165018022> Updating matti/resource/shell from 1.1.0 to 1.2.0
  proxy | 2021/06/22 17:55:12 [021] GET https://registry.terraform.io:443/.well-known/terraform.json
  proxy | 2021/06/22 17:55:12 [021] 200 https://registry.terraform.io:443/.well-known/terraform.json
  proxy | 2021/06/22 17:55:12 [023] GET https://registry.terraform.io:443/v1/modules/matti/resource/shell/versions
  proxy | 2021/06/22 17:55:12 [023] 200 https://registry.terraform.io:443/v1/modules/matti/resource/shell/versions
  proxy | 2021/06/22 17:55:12 [025] GET https://registry.terraform.io:443/v1/modules/matti/resource/shell/1.1.0/download
  proxy | 2021/06/22 17:55:12 [025] 204 https://registry.terraform.io:443/v1/modules/matti/resource/shell/1.1.0/download
  proxy | 2021/06/22 17:55:13 [028] GET https://checkpoint-api.hashicorp.com:443/v1/check/terraform?arch=amd64&os=linux&signature=498e68b5-4d46-8bb7-4883-650b918f438c&version=1.0.0
  proxy | 2021/06/22 17:55:13 [029] GET https://github.com:443/matti/terraform-shell-resource/info/refs?service=git-upload-pack
  proxy | 2021/06/22 17:55:13 [029] * authenticating git server request (host: github.com)
  proxy | 2021/06/22 17:55:13 [028] 200 https://checkpoint-api.hashicorp.com:443/v1/check/terraform?arch=amd64&os=linux&signature=498e68b5-4d46-8bb7-4883-650b918f438c&version=1.0.0
  proxy | 2021/06/22 17:55:13 [029] 200 https://github.com:443/matti/terraform-shell-resource/info/refs?service=git-upload-pack
  proxy | 2021/06/22 17:55:13 [031] POST https://github.com:443/matti/terraform-shell-resource/git-upload-pack
  proxy | 2021/06/22 17:55:13 [031] * authenticating git server request (host: github.com)
  proxy | 2021/06/22 17:55:13 [031] 200 https://github.com:443/matti/terraform-shell-resource/git-upload-pack
  proxy | 2021/06/22 17:55:13 [033] GET https://registry.terraform.io:443/v1/providers/hashicorp/random/versions
  proxy | 2021/06/22 17:55:13 [033] 200 https://registry.terraform.io:443/v1/providers/hashicorp/random/versions
  proxy | 2021/06/22 17:55:13 [035] GET https://registry.terraform.io:443/v1/providers/hashicorp/null/versions
  proxy | 2021/06/22 17:55:13 [035] 200 https://registry.terraform.io:443/v1/providers/hashicorp/null/versions
  proxy | 2021/06/22 17:55:13 [037] GET https://registry.terraform.io:443/v1/providers/hashicorp/null/3.0.0/download/linux/amd64
  proxy | 2021/06/22 17:55:13 [037] 200 https://registry.terraform.io:443/v1/providers/hashicorp/null/3.0.0/download/linux/amd64
  proxy | 2021/06/22 17:55:13 [039] GET https://releases.hashicorp.com:443/terraform-provider-null/3.0.0/terraform-provider-null_3.0.0_SHA256SUMS
  proxy | 2021/06/22 17:55:13 [039] 200 https://releases.hashicorp.com:443/terraform-provider-null/3.0.0/terraform-provider-null_3.0.0_SHA256SUMS
  proxy | 2021/06/22 17:55:13 [041] GET https://releases.hashicorp.com:443/terraform-provider-null/3.0.0/terraform-provider-null_3.0.0_SHA256SUMS.72D7468F.sig
  proxy | 2021/06/22 17:55:13 [041] 200 https://releases.hashicorp.com:443/terraform-provider-null/3.0.0/terraform-provider-null_3.0.0_SHA256SUMS.72D7468F.sig
  proxy | 2021/06/22 17:55:13 [043] GET https://releases.hashicorp.com:443/terraform-provider-null/3.0.0/terraform-provider-null_3.0.0_linux_amd64.zip
  proxy | 2021/06/22 17:55:13 [043] 200 https://releases.hashicorp.com:443/terraform-provider-null/3.0.0/terraform-provider-null_3.0.0_linux_amd64.zip
  proxy | 2021/06/22 17:55:14 [045] GET https://registry.terraform.io:443/v1/providers/hashicorp/random/3.1.0/download/linux/amd64
  proxy | 2021/06/22 17:55:14 [045] 200 https://registry.terraform.io:443/v1/providers/hashicorp/random/3.1.0/download/linux/amd64
  proxy | 2021/06/22 17:55:14 [047] GET https://releases.hashicorp.com:443/terraform-provider-random/3.1.0/terraform-provider-random_3.1.0_SHA256SUMS
  proxy | 2021/06/22 17:55:14 [047] 200 https://releases.hashicorp.com:443/terraform-provider-random/3.1.0/terraform-provider-random_3.1.0_SHA256SUMS
  proxy | 2021/06/22 17:55:14 [049] GET https://releases.hashicorp.com:443/terraform-provider-random/3.1.0/terraform-provider-random_3.1.0_SHA256SUMS.72D7468F.sig
  proxy | 2021/06/22 17:55:14 [049] 200 https://releases.hashicorp.com:443/terraform-provider-random/3.1.0/terraform-provider-random_3.1.0_SHA256SUMS.72D7468F.sig
  proxy | 2021/06/22 17:55:14 [051] GET https://releases.hashicorp.com:443/terraform-provider-random/3.1.0/terraform-provider-random_3.1.0_linux_amd64.zip
  proxy | 2021/06/22 17:55:14 [051] 200 https://releases.hashicorp.com:443/terraform-provider-random/3.1.0/terraform-provider-random_3.1.0_linux_amd64.zip
updater | I, [2021-06-22T17:55:14.951974 #8]  INFO -- sentry: ** [Raven] Sending event 79df29eb04424a19a729bdfedf16adc5 to Sentry
  proxy | 2021/06/22 17:55:15 [053] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/06/22 17:55:15 [053] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_165018022> Error processing matti/resource/shell (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_165018022> ╷
updater | <job_165018022> │ Error: Invalid provider source string
updater | <job_165018022> │ 
updater | <job_165018022> │ The "source" attribute must be in the format "[hostname/][namespace/]name"
updater | <job_165018022> ╵
updater | <job_165018022> 
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.154.5/lib/dependabot/shared_helpers.rb:295:in `run_shell_command'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.154.5/lib/dependabot/terraform/file_updater.rb:107:in `block in update_lockfile_declaration'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.154.5/lib/dependabot/shared_helpers.rb:46:in `block (2 levels) in in_a_temporary_directory'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.154.5/lib/dependabot/shared_helpers.rb:46:in `chdir'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.154.5/lib/dependabot/shared_helpers.rb:46:in `block in in_a_temporary_directory'
updater | ERROR <job_165018022> /usr/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.154.5/lib/dependabot/shared_helpers.rb:43:in `in_a_temporary_directory'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.154.5/lib/dependabot/terraform/file_updater.rb:103:in `update_lockfile_declaration'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.154.5/lib/dependabot/terraform/file_updater.rb:30:in `updated_dependency_files'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:674:in `generate_dependency_files_for'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:272:in `check_and_create_pull_request'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:80:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_165018022> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
updater | ERROR <job_165018022> bin/update_files.rb:21:in `<main>'
updater | INFO <job_165018022> Finished job processing
updater | time="2021-06-22T17:55:15Z" level=info msg="task complete" container_id=job-165018022-updater exit_code=0 job_id=165018022 step=updater
```

**Comment by feelepxyz** [comment]
@hosht thanks for reporting, I've got a fix lined up https://github.com/dependabot/dependabot-core/pull/3976

**Comment by HorizonNet** [comment]
Just tried it out. I run into a similar problem like @hfurubotten 

```
updater | ERROR <job_165226795> Error processing hashicorp/aws (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_165226795> Initializing modules...
updater | <job_165226795> - iam in 
updater | <job_165226795> - organizations in 
updater | <job_165226795> ╷
updater | <job_165226795> │ Error: Unreadable module directory
updater | <job_165226795> │ 
updater | <job_165226795> │ Unable to evaluate directory symlink: lstat modules: no such file or
updater | <job_165226795> │ directory
updater | <job_165226795> ╵
updater | <job_165226795> 
updater | <job_165226795> ╷
updater | <job_165226795> │ Error: Failed to read module directory
updater | <job_165226795> │ 
updater | <job_165226795> │ Module directory  does not exist or cannot be read.
```

I'm also using Terraform 1.0.0, but I can see a similar behavior in Terraform 0.15.3. For both versions I use lock files and modules.

**Comment by feelepxyz** [comment]
> Just tried it out. I run into a similar problem like @hfurubotten

@HorizonNet looks like a different issue, we don't fetch all files from the repo for terraform yet and seems like there are some referenced files that are not included. Are you referencing a symlinked file? Can you provide an example file setup that does this?

**Comment by hfurubotten** [comment]
Quickly put together example of local modules: https://github.com/hfurubotten/dependabot-local-modules-example

Dependabot file: https://github.com/hfurubotten/dependabot-local-modules-example/blob/main/.github/dependabot.yml
Providers manifest: https://github.com/hfurubotten/dependabot-local-modules-example/blob/main/providers.tf

`main.tf` file uses modules located in the `modules` folder.

**Comment by feelepxyz** [comment]
@hfurubotten thanks thats really helpful. I'm working on a fix here https://github.com/dependabot/dependabot-core/pull/3978

**Comment by feelepxyz** [comment]
The fix for local modules should be out now :tada:

**Comment by hfurubotten** [comment]
Now with `v0.156.2` all my repos with module usage in them runs with success. Had quite a few pull requests to take care of today.. 🎉
