### ISSUE TITLE
Unexpected error during running docker dependabot

### ISSUE THREAD

**Issue by flaxel** [dependabot/dependabot-core#3963]
**Package ecosystem**
docker
**Package manager version**

**Language version**

**Manifest location and content prior to update**

**dependabot.yml content**
```yml
version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "10:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 5
    labels:
      - "Run UI tests"
      - "dependencies"
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
    reviewers:
      - "@team"
```

**Updated dependency**

checked if there is an update for `node 16`
**What you expected to see, versus what you actually saw**

I got this error if I run the above dependabot configuration:
```
updater | I, [2021-06-22T08:44:28.468504 #8]  INFO -- sentry: ** [Raven] Sending event b27b58b4f79a4bd7b8befb5a8ed2119e to Sentry
  proxy | 2021/06/22 08:44:28 [024] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/06/22 08:44:28 [024] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_164872301> Error processing node (DockerRegistry2::NotFound)
updater | ERROR <job_164872301> 404 Not Found
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:261:in `rescue in doreq'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:245:in `doreq'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:26:in `doget'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/docker_registry2-1.10.0/lib/registry/registry.rb:65:in `tags'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-docker-0.154.3/lib/dependabot/docker/update_checker.rb:231:in `tags_from_registry'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-docker-0.154.3/lib/dependabot/docker/update_checker.rb:173:in `comparable_tags_from_registry'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-docker-0.154.3/lib/dependabot/docker/update_checker.rb:148:in `fetch_latest_version'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-docker-0.154.3/lib/dependabot/docker/update_checker.rb:60:in `latest_version'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:460:in `all_versions_ignored?'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:191:in `check_and_create_pull_request'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:80:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_164872301> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
updater | ERROR <job_164872301> bin/update_files.rb:21:in `<main>'
updater | INFO <job_164872301> Finished job processing
```
**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by feelepxyz** [comment]
@flaxel I'm investigating this, it seems requests to docker registry are returning 404 so trying to figure out if something has changed our their end or if there's an issue with docker registry.

**Comment by feelepxyz** [comment]
@flaxel this should be fixed now, not sure what happened yet but we're not seeing these errors from docker registry anymore.
