### ISSUE TITLE
`RuntimeError`s for updates to python deps

### ISSUE THREAD

**Issue by adamtheturtle** [dependabot/dependabot-core#4066]
**Package ecosystem**

Python

**Language version**

Python 3.8 / 3.9

**Manifest location and content prior to update**

`pyproject.toml`
`*requirements.txt` (multiple text files).

**dependabot.yml content**

https://github.com/VWS-Python/vws-python-mock/blob/master/.github/dependabot.yml

**Updated dependency**

Black 21.5b0 to 21.7b0
doc8 0.8.1 to 0.9.0
Sphinx 4.0.3 to 4.1.1

**What you expected to see, versus what you actually saw**

I expected to see a PR for each of these dependencies with updates.

**Images of the diff or a link to the PR, issue or logs**

https://github.com/VWS-Python/vws-python-mock/network/updates/173115376

```
er | ERROR <job_173259915> Error processing sphinx (RuntimeError)
updater | ERROR <job_173259915> Declaration not found for sphinx!
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.156.8/lib/dependabot/python/file_updater/requirement_replacer.rb:159:in `original_dependency_declaration_string'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.156.8/lib/dependabot/python/file_updater/requirement_replacer.rb:100:in `original_declaration_replacement_regex'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.156.8/lib/dependabot/python/file_updater/requirement_replacer.rb:25:in `updated_content'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.156.8/lib/dependabot/python/file_updater/requirement_file_updater.rb:61:in `updated_requirement_or_setup_file_content'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.156.8/lib/dependabot/python/file_updater/requirement_file_updater.rb:44:in `block in fetch_updated_dependency_files'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.156.8/lib/dependabot/python/file_updater/requirement_file_updater.rb:39:in `map'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.156.8/lib/dependabot/python/file_updater/requirement_file_updater.rb:39:in `fetch_updated_dependency_files'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.156.8/lib/dependabot/python/file_updater/requirement_file_updater.rb:26:in `updated_dependency_files'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.156.8/lib/dependabot/python/file_updater.rb:108:in `updated_requirement_based_files'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.156.8/lib/dependabot/python/file_updater.rb:34:in `updated_dependency_files'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:674:in `generate_dependency_files_for'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:272:in `check_and_create_pull_request'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:80:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_173259915> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:28:in `run'
updater | ERROR <job_173259915> bin/update_files.rb:21:in `<main>'
```

---

I wonder - is this because I have a `requirements.txt` which specifies the dependencies, and I also have a `pyproject.toml` which does not?

**Comment by adamtheturtle** [comment]
Thanks @asciimike - I trust that you know the project better than me. However, just to be clear, I am not using `poetry` and in particular I am not specifying any dependencies in `pyproject.toml`.

I expect that I can work around this by putting my `requirements.txt` files into a new directory, and I can point Dependabot to that directory.

**Comment by asciimike** [comment]
> I expect that I can work around this by putting my requirements.txt files into a new directory, and I can point Dependabot to that directory.

Would you mind giving this a try and letting us know if it works? That would help narrow down the issue here.

**Comment by adamtheturtle** [comment]
@asciimike It worked https://github.com/dependabot/dependabot-core/issues/4066

**Comment by jeffwidman** [comment]
Pretty sure this was resolved by https://github.com/dependabot/dependabot-core/pull/5932.
