### ISSUE TITLE
Poetry packages with list syntax results in no directory found

### ISSUE THREAD

**Issue by njgrisafi** [dependabot/dependabot-core#4229]
When using the syntax for poetry:
```
# pyproject.toml
[tool.poetry.dependencies]
local-pkg = [
    {path = "./local-pkg", platform = "linux"}
]
```

results in dependabot not being able to find the local directory.

If you update the syntax above to fix the error
```
# pyproject.toml
[tool.poetry.dependencies]
local-pkg = {path = "./local-pkg", platform = "linux"}
```

**Package ecosystem**
Poetry (version 1.1.8)

**Language version**
Python 3.6.10

**What you expected to see, versus what you actually saw**
We expect the directory to found with the syntax of `local-pkg = [{path = "./local-pkg"}]`

**Images of the diff or a link to the PR, issue or logs**
```
Traceback (most recent call last):
	14: from bin/dry-run.rb:613:in `<main>'
	13: from bin/dry-run.rb:613:in `each'
	12: from bin/dry-run.rb:646:in `block in <main>'
	11: from /home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker.rb:43:in `latest_resolvable_version'
	10: from /home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:48:in `latest_resolvable_version'
	 9: from /home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:75:in `fetch_latest_resolvable_version_string'
	 8: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:43:in `in_a_temporary_directory'
	 7: from /usr/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
	 6: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:46:in `block in in_a_temporary_directory'
	 5: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:46:in `chdir'
	 4: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:46:in `block (2 levels) in in_a_temporary_directory'
	 3: from /home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:76:in `block in fetch_latest_resolvable_version_string'
	 2: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:160:in `with_git_configured'
	 1: from /home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:88:in `block (2 levels) in fetch_latest_resolvable_version_string'
/home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:323:in `run_poetry_command': ValueError (Dependabot::SharedHelpers::HelperSubprocessFailed)

  Directory local-pkg does not exist

  at /usr/local/.pyenv/versions/3.6.10/lib/python3.6/site-packages/poetry/core/packages/directory_dependency.py:41 in __init__
       37│         self._develop = develop
       38│         self._supports_poetry = False
       39│
       40│         if not self._full_path.exists():
    →  41│             raise ValueError("Directory {} does not exist".format(self._path))
       42│
       43│         if self._full_path.is_file():
       44│             raise ValueError("{} is a file, expected a directory".format(self._path))
       45│
```

**🕹 Bonus points: Smallest manifest that reproduces the issue**

Example repo here: https://github.com/njgrisafi/dependabot-example

You can run the following in the docker shell to test:
```
bin/dry-run.rb pip njgrisafi/dependabot-example
```

**Comment by njgrisafi** [comment]
You can also reproduce this error by removing `./` from the path.

for example:
```
# pyproject.toml
[tool.poetry.dependencies]
local-pkg = {path = "local-pkg", platform = "linux"}
```

will produce an error.

**Comment by phillipuniverse** [comment]
I had a very similar error from Dependabot, but I could not get this to work even with `./`

```console
https://files.pythonhosted.org:443/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl
  proxy | 2021/11/24 16:12:51 [244] GET https://pypi.org:443/simple/pip/
  proxy | 2021/11/24 16:12:51 [244] 200 https://pypi.org:443/simple/pip/
updater | I, [2021-11-24T16:12:52.081534 #8]  INFO -- sentry: ** [Raven] Sending event 33100744f0f54821aa0a622e69e03ab6 to Sentry
  proxy | 2021/11/24 16:12:52 [246] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/11/24 16:12:52 [246] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_236489858> Error processing fastapi (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_236489858> ValueError
updater | <job_236489858> 
updater | <job_236489858>   File here_api/geocoding-7.74.tar.gz does not exist
updater | <job_236489858> 
updater | <job_236489858>   at /usr/local/.pyenv/versions/3.8.7/lib/python3.8/site-packages/poetry/core/packages/file_dependency.py:40 in __init__
updater | <job_236489858>        36│             except FileNotFoundError:
updater | <job_236489858>        37│                 raise ValueError("Directory {} does not exist".format(self._path))
updater | <job_236489858>        38│ 
updater | <job_236489858>        39│         if not self._full_path.exists():
updater | <job_236489858>     →  40│             raise ValueError("File {} does not exist".format(self._path))
updater | <job_236489858>        41│ 
updater | <job_236489858>        42│         if self._full_path.is_dir():
updater | <job_236489858>        43│             raise ValueError("{} is a directory, expected a file".format(self._path))
updater | <job_236489858>        44│
updater | ERROR <job_236489858> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:324:in `run_poetry_command'
updater | ERROR <job_236489858> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.0/lib/dependabot/python/update_checker/poetry_version_resolver.rb:89:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_236489858> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.0/lib/dependabot/shared_helpers.rb:164:in `with_git_configured'
updater | ERROR <job_236489858> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-
```

Here is my example project: https://github.com/phillipuniverse/dependabot-patherror

You can see the ways I tried to fix this: adding a `./`, moving out of a subdirectory [in these commits](https://github.com/phillipuniverse/dependabot-patherror/commits/main).

All have the same error [in the dependabot logs](https://github.com/phillipuniverse/dependabot-patherror/network/updates/236911480).

@njgrisafi it sounds like you were able to get this working somehow though? Maybe the difference is that this works with a _directory_ and not a file? That seems like the only difference.

**Comment by phillipuniverse** [comment]
I tried [to use a directory](https://github.com/phillipuniverse/dependabot-patherror/commit/57ccd9410a5b0cafdcf6a52f5f65422d106dc26e) and this worked, with [no error in the logs](https://github.com/phillipuniverse/dependabot-patherror/network/updates/236911480).

So this looks like a problem isolated to file-based dependencies. I opened #4456 to track this specifically.

**Comment by phillipuniverse** [comment]
@njgrisafi looking more closely at your specific problem, it doesn't look like the list syntaxi [is documented for path dependencies](https://python-poetry.org/docs/dependency-specification/#path-dependencies). The same went for my `file =` specification, but both do work with `poetry lock`.

Maybe the better thing to do for Dependabot is to try to detect this issue and raise a more specific error instead of what to change?

**Comment by jeffwidman** [comment]
👋 Sorry for the slow reply.

I'm going to close as there's been no response from the original poster, and per ☝️ this config is non-documented. We call out to `poetry`, so they're the ones who should probably be issuing the error here (or documenting their spec if they want to support more options). Thanks for your help @phillipuniverse, I appreciate you saving me time digging into this further.
