### ISSUE TITLE
pip-compile No such option: --no-index

### ISSUE THREAD

**Issue by michael-yin** [dependabot/dependabot-core#4272]
We have a project using `dependabot-core` via `dependabot-script` in Gitlab CI, but it stopped working

```
/builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/update_checker.rb:183: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:35: warning: The called method `initialize' is defined here
  - Updating bleach (from 3.2.1)…/builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/file_updater/pip_compile_file_updater.rb:157:in `run_command': Usage: pip-compile [OPTIONS] [SRC_FILES]... (Dependabot::SharedHelpers::HelperSubprocessFailed)
Try 'pip-compile -h' for help.
Error: No such option: --no-index (Possible options: --index-url, --no-emit-index-url, --no-header)
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/file_updater/pip_compile_file_updater.rb:169:in `run_pip_compile_command'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/file_updater/pip_compile_file_updater.rb:78:in `block (2 levels) in compile_new_requirement_files'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/file_updater/pip_compile_file_updater.rb:70:in `each'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/file_updater/pip_compile_file_updater.rb:70:in `block in compile_new_requirement_files'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.142.0/lib/dependabot/shared_helpers.rb:45:in `block (2 levels) in in_a_temporary_directory'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.142.0/lib/dependabot/shared_helpers.rb:45:in `chdir'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.142.0/lib/dependabot/shared_helpers.rb:45:in `block in in_a_temporary_directory'
	from /usr/lib/ruby/2.7.0/tmpdir.rb:89:in `mktmpdir'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.142.0/lib/dependabot/shared_helpers.rb:42:in `in_a_temporary_directory'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/file_updater/pip_compile_file_updater.rb:66:in `compile_new_requirement_files'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/file_updater/pip_compile_file_updater.rb:52:in `fetch_updated_dependency_files'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/file_updater/pip_compile_file_updater.rb:41:in `updated_dependency_files'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/file_updater.rb:99:in `updated_pip_compile_based_files'
	from /builds/project/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-python-0.142.0/lib/dependabot/python/file_updater.rb:32:in `updated_dependency_files'
	from ./generic-update-script.rb:207:in `block in <main>'
	from ./generic-update-script.rb:169:in `each'
	from ./generic-update-script.rb:169:in `<main>'
```

**Comment by jeffwidman** [comment]
👋 sorry for the slow response. We've been buried, and finally starting to dig through our backlog.

`pip-compile` replaced the `--no-index` flag with `--no-emit-index-url`... but this issue is a little confusing to me because I thought we didn't even _use_ the `--no-index` flag... maybe we're stripping the command from `requirements.in`, I'm not sure. 

We aren't going to go back to running an older version of `pip-compile`, and since they renamed this option, you'll need to manually update your `requirements.in` file or whatever `pip-compile` config option (could be one of their env vars) that you're setting that's prompting Dependabot to use that deprecated flag.

If I'm misunderstanding something, please comment and we can reopen.
