### ISSUE TITLE
Dependabot crash on git-crypt'ed .npmrc

### ISSUE THREAD

**Issue by aenario** [dependabot/dependabot-core#4475]
**Package ecosystem**
npm

**Manifest location and content prior to update**
https://github.com/aenario/dependabot-npmrc-crash/blob/main/package.json

**dependabot.yml content**
Empty / Github defaults

**What you expected to see, versus what you actually saw**
Dependabot crash with an unknown error and the log below

This is caused by a `git-crypt`ed `.npmrc`, so the content is not UTF8, which crash the [registries_finder](https://github.com/dependabot/dependabot-core/blob/main/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L138)

Dependabot should instead act as if the `.npmrc` was not present.

I know this is an edge case, but I am not proficient enough in ruby to figure out where to catch this error for a PR. Sorry and thanks for the hard work ! 

**🕹 Bonus points: Smallest manifest that reproduces the issue**
https://github.com/aenario/dependabot-npmrc-crash

*screenshot*
<img width="1185" alt="Capture d’écran 2021-12-01 à 18 48 22" src="https://user-images.githubusercontent.com/1580287/144286830-9d9969ff-1698-441b-ac64-4fdb22fdb1db.png">

*log*
```
 proxy | time="2021-12-01T17:47:21Z" level=info msg="proxy starting" commit=d5f262668736016da1a91e42cb4fba36a081bddf
  proxy | 2021/12/01 17:47:21 Listening (:1080)
updater | 2021-12-01T17:47:21.402882008 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2021-12-01T17:47:21.431414907 [238927419:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2021-12-01T17:47:23Z" level=info msg="guest starting" commit=8e918e4cf121d74a5b43e170ec4a717c1df98819
updater | time="2021-12-01T17:47:23Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=238927419 updater_timeout=30m0s updater_version=0.169.2-9b22d94fe19776c90070823e7e1eeacd8d321dd9
updater | I, [2021-12-01T17:47:24.397956 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes
updater | warning: 2.7.5-compliant syntax, but you are running 2.7.1.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_238927419> Starting job processing
  proxy | 2021/12/01 17:47:26 [002] GET https://api.github.com:443/repos/aenario/dependabot-npmrc-crash
  proxy | 2021/12/01 17:47:26 [002] * authenticating github api request
  proxy | 2021/12/01 17:47:26 [002] 200 https://api.github.com:443/repos/aenario/dependabot-npmrc-crash
  proxy | 2021/12/01 17:47:26 [004] GET https://api.github.com:443/repos/aenario/dependabot-npmrc-crash/git/refs/heads/main
  proxy | 2021/12/01 17:47:26 [004] * authenticating github api request
  proxy | 2021/12/01 17:47:26 [004] 200 https://api.github.com:443/repos/aenario/dependabot-npmrc-crash/git/refs/heads/main
  proxy | 2021/12/01 17:47:26 [006] GET https://api.github.com:443/repos/aenario/dependabot-npmrc-crash/contents/package.json?ref=07c68a53b25ed18c2eb09a5e977a58efbf2c6adc
  proxy | 2021/12/01 17:47:26 [006] * authenticating github api request
  proxy | 2021/12/01 17:47:26 [006] 200 https://api.github.com:443/repos/aenario/dependabot-npmrc-crash/contents/package.json?ref=07c68a53b25ed18c2eb09a5e977a58efbf2c6adc
  proxy | 2021/12/01 17:47:26 [008] GET https://api.github.com:443/repos/aenario/dependabot-npmrc-crash/contents/?ref=07c68a53b25ed18c2eb09a5e977a58efbf2c6adc
  proxy | 2021/12/01 17:47:26 [008] * authenticating github api request
  proxy | 2021/12/01 17:47:26 [008] 200 https://api.github.com:443/repos/aenario/dependabot-npmrc-crash/contents/?ref=07c68a53b25ed18c2eb09a5e977a58efbf2c6adc
  proxy | 2021/12/01 17:47:26 [010] GET https://api.github.com:443/repos/aenario/dependabot-npmrc-crash/contents/.npmrc?ref=07c68a53b25ed18c2eb09a5e977a58efbf2c6adc
  proxy | 2021/12/01 17:47:26 [010] * authenticating github api request
  proxy | 2021/12/01 17:47:26 [010] 200 https://api.github.com:443/repos/aenario/dependabot-npmrc-crash/contents/.npmrc?ref=07c68a53b25ed18c2eb09a5e977a58efbf2c6adc
updater | INFO <job_238927419> Finished job processing
updater | time="2021-12-01T17:47:26Z" level=info msg="task complete" container_id=job-238927419-file-fetcher exit_code=0 job_id=238927419 step=fetcher
updater | I, [2021-12-01T17:47:27.861380 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes
updater | warning: 2.7.5-compliant syntax, but you are running 2.7.1.
updater | warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_238927419> Starting job processing
updater | INFO <job_238927419> Starting update job for aenario/dependabot-npmrc-crash
updater | INFO <job_238927419> Checking if axios  needs updating
updater | I, [2021-12-01T17:47:29.592017 #8]  INFO -- sentry: ** [Raven] Sending event b6152f5a29e543e8b10fdeae56b1e0a7 to Sentry
  proxy | 2021/12/01 17:47:30 [014] POST https://sentry.io:443/api/1451818/store/
  proxy | 2021/12/01 17:47:30 [014] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_238927419> Error processing axios (ArgumentError)
updater | ERROR <job_238927419> invalid byte sequence in UTF-8
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb:138:in `scan'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb:138:in `npmrc_registries'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb:127:in `known_registries'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb:55:in `first_registry_with_dependency_details'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb:32:in `registry'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb:82:in `registry_url'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb:40:in `dependency_url'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:368:in `dependency_url'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:297:in `fetch_npm_response'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:276:in `npm_details'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:107:in `valid_npm_details?'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker/latest_version_finder.rb:36:in `latest_version_from_registry'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker.rb:180:in `latest_released_version'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker.rb:205:in `latest_version_details'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.169.2/lib/dependabot/npm_and_yarn/update_checker.rb:23:in `latest_version'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:462:in `all_versions_ignored?'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:193:in `check_and_create_pull_request'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_238927419> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:35:in `run'
updater | ERROR <job_238927419> bin/update_files.rb:22:in `<main>'
updater | INFO <job_238927419> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2021-12-01T17:47:30Z" level=info msg="task complete" container_id=job-238927419-updater exit_code=0 job_id=238927419 step=updater
```

**Comment by jeffwidman** [comment]
👋 sorry for the slow response.

This one looks pretty tricky to handle.

First, I'm not seeing any well-known file header mentioned on https://github.com/AGWA/git-crypt, so the only way to differentiate between a `git-crypted` file and a simply malformed file would be to search [the `.gitattributes` file for the well-known filter](https://github.com/AGWA/git-crypt#gitattributes-file). That gets complicated fast.

Second, I'm also not sure that blithely ignoring the `.npmrc` file is always the best solution... that file may contain config information that is relevant for fetching updates. IE, if you check that repo out locally and run `npm` against it, `npm` will have access to the decrypted content and use any config information. So if Dependabot starts ignoring that, then that may surprise users who wonder why Dependabot behaves different than their local copy of `npm`.

We could certainly improve the warning here by explicitly saying that the `.npmrc` appears to be malformed; however, it's still relatively easy to identify from the logs what's going wrong.

Given the infrequency of this, the complexity of the fix, and that it's not always guaranteed that ignoring the file is the right way, I'm going to close as "wontfix". 

If someone feels strongly about this and wants to submit a PR tackling it, feel free to comment and we can continue the discussion.

**Comment by deivid-rodriguez** [comment]
For what it's worth, there does seem to be a standard (and boring 😆) header for these files. From the given repo:

```
$ head -c10 .npmrc 
GITCRYPT%
```

**Comment by jeffwidman** [comment]
🤦‍♂️  Good catch Deivid. I filed https://github.com/AGWA/git-crypt/issues/275 to get that added to the readme.

I think this should remain a wontfix because ignoring the `.npmrc` isn't a great idea when generating updates....

**Comment by deivid-rodriguez** [comment]
My idea of "fix" would be to raise an error about the file being encrypted. But this can happen with any file really, so we'd need some more global rescue. Unless this thing gains more popularity I agree not worth doing anything about this.
