### ISSUE TITLE
pip update fails with undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by nijel** [dependabot/dependabot-core#4538]
**Package ecosystem**
pip

**Package manager version**

**Language version**

**Manifest location and content prior to update**
[requirements.txt
](https://github.com/WeblateOrg/docker/blob/a21ded89699e64215e900f1b4b39d425c2511abc/requirements.txt)

**dependabot.yml content**
[dependabot.yml](https://github.com/WeblateOrg/docker/blob/a21ded89699e64215e900f1b4b39d425c2511abc/.github/dependabot.yml)

**Updated dependency**
git-review

**What you expected to see, versus what you actually saw**
I'd expect upgrade to 2.2.2, instead I see error in the dependabot log

**Native package manager behavior**

It installs just fine.
**Images of the diff or a link to the PR, issue or logs**
Log: https://github.com/WeblateOrg/docker/network/updates/245528700

<detail>

```

updater | ERROR <job_245528700> Error processing git-review (NoMethodError)
updater | ERROR <job_245528700> undefined method `+' for nil:NilClass
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/excon-0.89.0/lib/excon/connection.rb:247:in `request'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/excon-0.89.0/lib/excon.rb:250:in `get'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/source.rb:86:in `github_enterprise?'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/source.rb:73:in `github_enterprise_from_url'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/source.rb:54:in `from_url'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.6/lib/dependabot/python/metadata_finder.rb:36:in `block in look_up_source'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.6/lib/dependabot/python/metadata_finder.rb:36:in `each'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.6/lib/dependabot/python/metadata_finder.rb:36:in `find'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.6/lib/dependabot/python/metadata_finder.rb:36:in `look_up_source'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/metadata_finders/base.rb:123:in `source'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/metadata_finders/base.rb:25:in `source_url'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:357:in `source_url'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:282:in `block in dependency_links'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:281:in `map'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:281:in `dependency_links'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:203:in `version_commit_message_intro'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:129:in `commit_message_intro'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:49:in `pr_message'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:64:in `message'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:932:in `pr_message'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:281:in `check_and_create_pull_request'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:35:in `run'
updater | ERROR <job_245528700> bin/update_files.rb:22:in `<main>'

```
</detail>

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jurre** [comment]
Interesting, seems to hit an error when making a request to E, the error happens [fairly deep in our http library](https://github.com/excon/excon/blob/0ac208d6f8e7bede0c3d2f6fd6b38a7358664a5c/lib/excon/connection.rb#L247).

This error occurs when trying to fetch metadata for the library, I'll widen the error handling that we perform there because the PR should not fail because we can't reach some host for metadata.

Curious, if you attempt to re-run the job does it pass?

**Comment by nijel** [comment]
It seems to be still hitting that, current one: https://github.com/WeblateOrg/docker/network/updates/246747449 (not sure if you have access to that):

```

updater | ERROR <job_245528700> Error processing git-review (NoMethodError)
updater | ERROR <job_245528700> undefined method `+' for nil:NilClass
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/excon-0.89.0/lib/excon/connection.rb:247:in `request'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/excon-0.89.0/lib/excon.rb:250:in `get'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/source.rb:86:in `github_enterprise?'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/source.rb:73:in `github_enterprise_from_url'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/source.rb:54:in `from_url'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.6/lib/dependabot/python/metadata_finder.rb:36:in `block in look_up_source'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.6/lib/dependabot/python/metadata_finder.rb:36:in `each'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.6/lib/dependabot/python/metadata_finder.rb:36:in `find'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.6/lib/dependabot/python/metadata_finder.rb:36:in `look_up_source'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/metadata_finders/base.rb:123:in `source'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/metadata_finders/base.rb:25:in `source_url'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:357:in `source_url'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:282:in `block in dependency_links'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:281:in `map'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:281:in `dependency_links'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:203:in `version_commit_message_intro'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:129:in `commit_message_intro'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:49:in `pr_message'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.6/lib/dependabot/pull_request_creator/message_builder.rb:64:in `message'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:932:in `pr_message'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:281:in `check_and_create_pull_request'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_245528700> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:35:in `run'
updater | ERROR <job_245528700> bin/update_files.rb:22:in `<main>'
```

**Comment by jurre** [comment]
Thanks @nijel, I'm wondering if dependabot's update infrastructure might be hitting some sort of IP blocklist on their end 🤔 

I'll release the version that ignores this error later today, which should result in the job succeeding but might exclude some metadata like a changelog entry etc.

**Comment by nijel** [comment]
Logging the actual HTTP or connection error might help to understand what went wrong there (it's just mu assumption what went wrong, I didn't really look into your code).

**Comment by jurre** [comment]
Right, they are actually in the logs:

```
  proxy | 2021/12/16 20:04:03 [100] GET https://opendev.org:443/status
  proxy | 2021/12/16 20:04:03 [100] 404 https://opendev.org:443/status
```

So we get a 404 response, but then something about that response is deemed invalid by our http library which I cannot reproduce locally (locally I get a valid 404). I think ignoring that 404 is still the right thing to do either way.

**Comment by nijel** [comment]
Thanks, it now created the pull request: https://github.com/WeblateOrg/docker/pull/1329, the run: https://github.com/WeblateOrg/docker/network/updates/247462446

I'm uncertain if it intended to fire so many requests to check whether a site is GitHub or not:

```
  proxy | 2021/12/22 13:11:07 [150] GET https://docs.opendev.org:443/status
  proxy | 2021/12/22 13:11:07 [150] 404 https://docs.opendev.org:443/status
  proxy | 2021/12/22 13:11:07 [152] GET https://opendev.org:443/status
  proxy | 2021/12/22 13:11:07 [152] 404 https://opendev.org:443/status
  proxy | 2021/12/22 13:11:08 [154] GET https://docs.opendev.org:443/status
  proxy | 2021/12/22 13:11:08 [154] 404 https://docs.opendev.org:443/status
  proxy | 2021/12/22 13:11:08 [156] GET https://opendev.org:443/status
  proxy | 2021/12/22 13:11:08 [156] 404 https://opendev.org:443/status
  proxy | 2021/12/22 13:11:08 [158] GET https://docs.opendev.org:443/status
  proxy | 2021/12/22 13:11:08 [158] 404 https://docs.opendev.org:443/status
  proxy | 2021/12/22 13:11:08 [160] GET https://opendev.org:443/status
  proxy | 2021/12/22 13:11:08 [160] 404 https://opendev.org:443/status
  proxy | 2021/12/22 13:11:08 [162] GET https://docs.opendev.org:443/status
  proxy | 2021/12/22 13:11:08 [162] 404 https://docs.opendev.org:443/status
```

**Comment by jurre** [comment]
Seems a little excessive yeah, we should look into tweaking the retries there 👍
