### ISSUE TITLE
Dependabot fails for Python `types-waitress` package

### ISSUE THREAD

**Issue by fujiapple852** [dependabot/dependabot-core#4580]
**Package ecosystem**

Python (Poetry)

**Manifest location and content prior to update**
Python 3.9.9

**dependabot.yml content**
```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "fujiapplee852"
```

**Updated dependency**

 [`types-waitress`](https://pypi.org/project/types-waitress/)

Extract from `pyproject.toml`:

```toml
[tool.poetry.dev-dependencies]
types-waitress = "*"
```

Extract from `poetry.lock`:
```
[[package]]
name = "types-waitress"
version = "2.0.3"
description = "Typing stubs for waitress"
category = "dev"
optional = false
python-versions = "*"

types-waitress = [
    {file = "types-waitress-2.0.3.tar.gz", hash = "sha256:d0fbebadd55ac6f74ca095003147444150c6a451099d040443243f8d30b210e9"},
    {file = "types_waitress-2.0.3-py3-none-any.whl", hash = "sha256:01d145ea41f1ef02d462ee6eb9c81964809e88631ef2085b0962f876ff4b9d91"},
]
```

**What you expected to see, versus what you actually saw**

Repeatable error observed processing the `types-waitress` package:

```
HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/types-waitress/2.0.3/json (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))
```

The full error:

```
updater | ERROR <job_251840896> Error processing pulumi (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_251840896> Creating virtualenv xxxx--1aMM9jv-py3.9 in /home/dependabot/.cache/pypoetry/virtualenvs
updater | <job_251840896> Updating dependencies
updater | <job_251840896> Resolving dependencies...
updater | <job_251840896> 
updater | <job_251840896>   ProxyError
updater | <job_251840896> 
updater | <job_251840896>   HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/types-waitress/2.0.3/json (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))
updater | <job_251840896> 
updater | <job_251840896>   at /usr/local/.pyenv/versions/3.9.9/lib/python3.9/site-packages/requests/adapters.py:513 in send
updater | <job_251840896>       509│             if isinstance(e.reason, ResponseError):
updater | <job_251840896>       510│                 raise RetryError(e, request=request)
updater | <job_251840896>       511│ 
updater | <job_251840896>       512│             if isinstance(e.reason, _ProxyError):
updater | <job_251840896>     → 513│                 raise ProxyError(e, request=request)
updater | <job_251840896>       514│ 
updater | <job_251840896>       515│             if isinstance(e.reason, _SSLError):
updater | <job_251840896>       516│                 # This branch is for urllib3 v1.22 and later.
updater | <job_251840896>       517│                 raise SSLError(e, request=request)
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:325:in `run_poetry_command'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:89:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/shared_helpers.rb:164:in `with_git_configured'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:77:in `block in fetch_latest_resolvable_version_string'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/shared_helpers.rb:48:in `block in in_a_temporary_directory'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/shared_helpers.rb:48:in `chdir'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/shared_helpers.rb:48:in `in_a_temporary_directory'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:76:in `fetch_latest_resolvable_version_string'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:49:in `latest_resolvable_version'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker.rb:43:in `latest_resolvable_version'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/update_checkers/base.rb:257:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/update_checkers/base.rb:249:in `numeric_version_can_update?'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/update_checkers/base.rb:199:in `version_can_update?'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:432:in `requirements_to_unlock'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:226:in `check_and_create_pull_request'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_251840896> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:35:in `run'
updater | ERROR <job_251840896> bin/update_files.rb:22:in `<main>'
```

**Comment by fujiapple852** [comment]
I marked the package in question as ignored and the errors continued for a variety of packages. 

Now, `dependabot` is working correctly without further changes and so this appears to have been a transient issues and so I will close this.
