### ISSUE TITLE
Lots of 407 Proxy Authentication Required errors for pypi fakeredis

### ISSUE THREAD

**Issue by yawhide** [dependabot/dependabot-core#4587]
Cannot get dependabot to create any PRs to update my dependencies. I have clicked `check for updates` in the `insights -> dependency graph -> dependabot` web page about 6 times over 2 days.

Seeing lots of `407 Proxy Authentication Required errors for pypi fakeredis` errors in the logs.

**Package ecosystem**

pip/poetry

**Package manager version**

**Language version**

python 3.9.6

**Manifest location and content prior to update**

**dependabot.yml content**

```
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 3
  - package-ecosystem: 'pip'
    directory: '/'
    schedule:
      interval: 'weekly'
    open-pull-requests-limit: 2
```

**Updated dependency**

fakeredis
https://pypi.org/project/fakeredis/

**What you expected to see, versus what you actually saw**

cannot get new dependabot PRs created because `Dependabot encountered an unknown error`
**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

section of error logs
```
...
updater | <job_252069871> Updating dependencies
updater | <job_252069871> Resolving dependencies...
updater | <job_252069871> 
updater | <job_252069871>   ProxyError
updater | <job_252069871> 
updater | <job_252069871>   HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/fakeredis/json (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 407 Proxy Authentication Required')))
updater | <job_252069871> 
updater | <job_252069871>   at /usr/local/.pyenv/versions/3.9.6/lib/python3.9/site-packages/requests/adapters.py:513 in send
updater | <job_252069871>       509│             if isinstance(e.reason, ResponseError):
updater | <job_252069871>       510│                 raise RetryError(e, request=request)
updater | <job_252069871>       511│ 
updater | <job_252069871>       512│             if isinstance(e.reason, _ProxyError):
updater | <job_252069871>     → 513│                 raise ProxyError(e, request=request)
updater | <job_252069871>       514│ 
updater | <job_252069871>       515│             if isinstance(e.reason, _SSLError):
updater | <job_252069871>       516│                 # This branch is for urllib3 v1.22 and later.
updater | <job_252069871>       517│                 raise SSLError(e, request=request)
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:325:in `run_poetry_command'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:89:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/shared_helpers.rb:164:in `with_git_configured'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:77:in `block in fetch_latest_resolvable_version_string'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/shared_helpers.rb:48:in `block in in_a_temporary_directory'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/shared_helpers.rb:48:in `chdir'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/shared_helpers.rb:48:in `in_a_temporary_directory'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:76:in `fetch_latest_resolvable_version_string'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker/poetry_version_resolver.rb:49:in `latest_resolvable_version'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.169.8/lib/dependabot/python/update_checker.rb:43:in `latest_resolvable_version'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/update_checkers/base.rb:257:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/update_checkers/base.rb:249:in `numeric_version_can_update?'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/update_checkers/base.rb:199:in `version_can_update?'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.169.8/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:432:in `requirements_to_unlock'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:226:in `check_and_create_pull_request'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_252069871> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:35:in `run'
updater | ERROR <job_252069871> bin/update_files.rb:22:in `<main>'
...
updater | INFO <job_252069871> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '25' error(s) during execution, please check the logs for more details.
updater | time="2022-01-05T12:56:41Z" level=info msg="task complete" container_id=job-252069871-updater exit_code=0 job_id=252069871 step=updater

```

**Comment by jurre** [comment]
Thanks for reporting, going to look into this shortly

**Comment by jurre** [comment]
So far haven't been able to reproduce this and also haven't seen a spike in errors related to this, when you retry the job, does it consistently happen?
