### ISSUE TITLE
When dependabot chooses an incompatible Python version, `pip-compile` fails

### ISSUE THREAD

**Issue by webknjaz** [dependabot/dependabot-core#4606]
$sbj. See the linked log below.
I know about hacks with [`.python-version` and `runtime.txt`](https://github.com/dependabot/dependabot-core/issues/1455) but those won't work for us because there are multiple pip constraints files targeting different Python interpreters.
Also, this specific dependency has different `python_version`s in the metadata of its releases and there's no version that supports the whole specter of Pythons we need (which is one of the reasons we need different "lockfiles" per environment).

**Package ecosystem**

pip

**Package manager version**

pip-compile

**Language version**

python

**Manifest location and content prior to update**

Files under https://github.com/cherrypy/cheroot/tree/e1a45fa/requirements.

**dependabot.yml content**

https://github.com/cherrypy/cheroot/blob/e1a45fa/.github/dependabot.yml

**Updated dependency**

watchdog

**What you expected to see, versus what you actually saw**

Expected to see a successful update log. Saw a traceback:
```python-traceback
 Dependabot can't resolve your Python dependency files
Dependabot failed to update your dependencies because there was an error resolving your Python dependency files.

Dependabot encountered the following error:

ERROR: Could not find a version that satisfies the requirement watchdog==0.10.7 (from pytest-watch==4.2.0->-r requirements/tox-py27-cp27-linux-x86_64.in (line 51)) (from versions: 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.6.0, 0.7.0, 0.7.1, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.9.0, 0.10.0, 0.10.1, 0.10.2, 0.10.3, 0.10.4, 0.10.5, 1.0.0, 1.0.1, 1.0.2, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6)
Traceback (most recent call last):
  File "/usr/local/.pyenv/versions/3.10.0/bin/pip-compile", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/piptools/scripts/compile.py", line 466, in cli
    results = resolver.resolve(max_rounds=max_rounds)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/piptools/resolver.py", line 175, in resolve
    has_changed, best_matches = self._resolve_one_round()
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/piptools/resolver.py", line 319, in _resolve_one_round
    their_constraints.extend(self._iter_dependencies(best_match))
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/piptools/resolver.py", line 428, in _iter_dependencies
    dependencies = self.repository.get_dependencies(ireq)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/piptools/repositories/local.py", line 79, in get_dependencies
    return self.repository.get_dependencies(ireq)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/piptools/repositories/pypi.py", line 236, in get_dependencies
    self._dependencies_cache[ireq] = self.resolve_reqs(
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/piptools/repositories/pypi.py", line 199, in resolve_reqs
    results = resolver._resolve_one(reqset, ireq)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/legacy/resolver.py", line 379, in _resolve_one
    dist = self._get_dist_for(req_to_install)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/legacy/resolver.py", line 331, in _get_dist_for
    self._populate_link(req)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/legacy/resolver.py", line 300, in _populate_link
    req.link = self._find_requirement_link(req)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip/_internal/resolution/legacy/resolver.py", line 266, in _find_requirement_link
    best_candidate = self.finder.find_requirement(req, upgrade)
  File "/usr/local/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pip/_internal/index/package_finder.py", line 909, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for watchdog==0.10.7 (from pytest-watch==4.2.0->-r requirements/tox-py27-cp27-linux-x86_64.in (line 51))
```

**Native package manager behavior**

It is able to resolve the dependencies for as long as a compatible Python interpreter is used.

**Images of the diff or a link to the PR, issue or logs**

https://github.com/cherrypy/cheroot/network/updates/253089065

**🕹 Bonus points: Smallest manifest that reproduces the issue**

N/A

**Comment by jeffwidman** [comment]
Let's track this under:
* https://github.com/dependabot/dependabot-core/issues/4216
