### ISSUE TITLE
Cannot use dependabot (Github repository variant) for git dependencies specified by hash

### ISSUE THREAD

**Issue by mitchellbusby** [dependabot/dependabot-core#4746]
**Package ecosystem**

npm / yarn

**Package manager version**

N/A
**Language version**

N/A
**Manifest location and content prior to update**
N/A

**dependabot.yml content**
N/A

**Updated dependency**
N/A

**What you expected to see, versus what you actually saw**

Not sure if this is intentionally not supported, or a bug, but I have a private Git repo that we depend on as an npm dependency; it is depended in package.json like:

`"dependency-name": "git+ssh://git@github.com:orgname/reponame.git#COMMIT_HASH"`

I definitely have everything correctly configured and it's able to access the private Git repo; I don't think the code handles commit SHAs? but I could be wrong. 

I've attached the stack trace I see in the dependabot logs below. It says there's an issue with a "Malformed version number string <hash>".

**Native package manager behavior**

N/A
**Images of the diff or a link to the PR, issue or logs**

Stack trace that I think is responsible (note kaleidoscope is the dependency in question and 4fd14dec46ee1b16f80ca0858ceb349197737865 is the hash we have set as the one in package.json + yarn.lock): 

```
updater | ERROR <job_293815574> Error processing kaleidoscope (ArgumentError)
updater | ERROR <job_293815574> Malformed version number string 4fd14dec46ee1b16f80ca0858ceb349197737865
updater | ERROR <job_293815574> /usr/local/lib/site_ruby/2.7.0/rubygems/version.rb:214:in `initialize'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.173.0/lib/dependabot/npm_and_yarn/version.rb:34:in `initialize'
updater | ERROR <job_293815574> /usr/local/lib/site_ruby/2.7.0/rubygems/version.rb:203:in `new'
updater | ERROR <job_293815574> /usr/local/lib/site_ruby/2.7.0/rubygems/version.rb:203:in `new'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.173.0/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb:85:in `version_from_updated_lockfiles'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.173.0/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb:44:in `block in latest_resolvable_version'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.173.0/lib/dependabot/shared_helpers.rb:48:in `block in in_a_temporary_directory'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.173.0/lib/dependabot/shared_helpers.rb:48:in `chdir'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.173.0/lib/dependabot/shared_helpers.rb:48:in `in_a_temporary_directory'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.173.0/lib/dependabot/npm_and_yarn/update_checker/subdependency_version_resolver.rb:34:in `latest_resolvable_version'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-npm_and_yarn-0.173.0/lib/dependabot/npm_and_yarn/update_checker.rb:36:in `latest_resolvable_version'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.173.0/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.173.0/lib/dependabot/update_checkers/base.rb:257:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.173.0/lib/dependabot/update_checkers/base.rb:249:in `numeric_version_can_update?'
updater | ERROR <job_293815574> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.173.0/lib/dependabot/update_checkers/base.rb:199:in `version_can_update?'
```

**Comment by jeffwidman** [comment]
I suspect Dependabot expected a version that is comparable, and `npm` may not be giving it that.

What is the behavior you expected from Dependabot? Are you expecting it to bump this package to a newer commit on that branch?
