### ISSUE TITLE
Issue when fixing runtime version to python3.6.15

### ISSUE THREAD

**Issue by JonathanRenon-EDB** [dependabot/dependabot-core#4799]
**Package ecosystem**
pip (pip-compile)
**Package manager version**
pip-tools 6.4.0
**Language version**
python3.6.15
**Manifest location and content prior to update**
requirements.txt
**dependabot.yml content**
```
---

version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependabot"
      - "pip dependencies"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      separator: "/"
```

**What you expected to see,** 
When using a .python-version file or runtime.txt pointing to python3.6.15 we want dependabot to be able to run its check normally
**versus what you actually saw**
Dependabot fails to install pip-tools 6.5.1 since latest version available in python3.6.15 is pip-tools 6.4.0 
We need to keep supporting python3.6 and generating requirements through python3.7+ will modify the dependency list and break install for python3.6 due to dependencies not pinned and with no hash.
**Images of the diff or a link to the PR, issue or logs**
```
Dependabot encountered the following error:

The directory '/home/dependabot/.cache/pip/<redacted> or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/dependabot/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip==21.3.1 (from -r /opt/python/helpers/requirements.txt (line 1))
  Downloading <redacted>
Collecting pip-tools==6.5.1 (from -r /opt/python/helpers/requirements.txt (line 2))
  Could not find a version that satisfies the requirement pip-tools==6.5.1 (from -r /opt/python/helpers/requirements.txt (line 2)) (from versions: 0.1, 0.2, 0.2.1, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5, 1.6, 1.6.1, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.8.0, 1.8.1.dev0, 1.8.1rc1, 1.8.1rc2, 1.8.1rc3, 1.8.1, 1.8.2, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0, 1.10.1, 1.10.2rc1, 1.10.2rc2, 1.10.2rc3, 1.10.2, 1.11.0rc1, 1.11.0, 2.0.0, 2.0.1, 2.0.2, 3.0.0rc1, 3.0.0, 3.1.0, 3.2.0, 3.3.1, 3.3.2, 3.4.0, 3.5.0, 3.6.0, 3.6.1, 3.7.0, 3.8.0, 3.9.0, 4.0.0, 4.1.0, 4.2.0, 4.3.0, 4.4.0, 4.4.1, 4.5.0, 4.5.1, 5.0.0, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.2.1, 5.3.0, 5.3.1, 5.4.0, 5.5.0, 6.0.0, 6.0.1, 6.1.0, 6.2.0, 6.3.0, 6.3.1, 6.4.0)
No matching distribution found for pip-tools==6.5.1 (from -r /opt/python/helpers/requirements.txt (line 2))
You are using pip version 18.1, however version 21.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
**🕹 Bonus points: Smallest manifest that reproduces the issue**
any manifest will do since the issue lays before checking manifest files
the smallest to see difference in generation between python3.6 and python3.7 could be:
requirements.in:
```
netaddr==0.8.0
```
will lack of these dependencies in latter version of python( >3.6.15):
```
importlib-resources==5.4.0 \
    --hash=sha256:33a95faed5fc19b4bc16b29a6eeae248a3fe69dd55d4d229d2b480e23eeaad45 \
    --hash=sha256:d756e2f85dd4de2ba89be0b21dba2a3bbec2e871a42a3a16719258a11f87506b
    # via netaddr
zipp==3.6.0 \
    --hash=sha256:71c644c5369f4a6e07636f0aa966270449561fcea2e3d6747b8d23efaa9d7832 \
    --hash=sha256:9fe5ea21568a0a70e50f273397638d39b03353731e6cbbb3fd8502a33fec40bc
    # via importlib-resources
```

**Comment by invalidusrname** [comment]
I'm actually running into this problem too with python 3.6.9. Here's what I see using docker-dev-shell on a [demo repo](https://github.com/invalidusrname/pipfile-dependabot-demo)

```
$ docker pull ghcr.io/dependabot/dependabot-core-development:latest
$ docker tag ghcr.io/dependabot/dependabot-core-development dependabot/dependabot-core-development
$ bin/docker-dev-shell

dependabot/dependabot-core-development
[dependabot-core-dev] ~/dependabot-core $ DEBUG_HELPERS=1 ./bin/dry-run.rb --clone pip invalidusrname/pipfile-dependabot-demo
=> cloning into /home/dependabot/dependabot-core/tmp/invalidusrname/pipfile-dependabot-demo
=> parsing dependency files
=> updating 1 dependencies: pydantic

=== pydantic (1.4)
 => checking for updates 1/1
 => latest available version is 1.9.0
"-----"
  system
  3.10.2
* 3.6.9 (set by /home/dependabot/dependabot-core/tmp/dependabot_20220316-19379-1ldnnhv/.python-version)
"-----"
Traceback (most recent call last):
	13: from ./bin/dry-run.rb:627:in `<main>'
	12: from ./bin/dry-run.rb:627:in `each'
	11: from ./bin/dry-run.rb:660:in `block in <main>'
	10: from /home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker.rb:39:in `latest_resolvable_version'
	 9: from /home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb:61:in `latest_resolvable_version'
	 8: from /home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb:80:in `fetch_latest_resolvable_version_string'
	 7: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:48:in `in_a_temporary_directory'
	 6: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:48:in `chdir'
	 5: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:48:in `block in in_a_temporary_directory'
	 4: from /home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb:81:in `block in fetch_latest_resolvable_version_string'
	 3: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:165:in `with_git_configured'
	 2: from /home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb:83:in `block (2 levels) in fetch_latest_resolvable_version_string'
	 1: from /home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb:333:in `install_required_python'
/home/dependabot/dependabot-core/python/lib/dependabot/python/update_checker/pipenv_version_resolver.rb:464:in `run_command': Requirement already satisfied: pip==21.3.1 in /usr/local/.pyenv/versions/3.6.9/lib/python3.6/site-packages (from -r /opt/python/helpers/requirements.txt (line 1)) (21.3.1) (Dependabot::SharedHelpers::HelperSubprocessFailed)
ERROR: Could not find a version that satisfies the requirement pip-tools==6.5.1 (from versions: 0.1, 0.2, 0.2.1, 0.3, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 1.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.5, 1.6, 1.6.1, 1.6.3, 1.6.4, 1.6.5, 1.7.0, 1.8.0, 1.8.1.dev0, 1.8.1rc1, 1.8.1rc2, 1.8.1rc3, 1.8.1, 1.8.2, 1.9.0rc1, 1.9.0rc2, 1.9.0, 1.10.0, 1.10.1, 1.10.2rc1, 1.10.2rc2, 1.10.2rc3, 1.10.2, 1.11.0rc1, 1.11.0, 2.0.0, 2.0.1, 2.0.2, 3.0.0rc1, 3.0.0, 3.1.0, 3.2.0, 3.3.1, 3.3.2, 3.4.0, 3.5.0, 3.6.0, 3.6.1, 3.7.0, 3.8.0, 3.9.0, 4.0.0, 4.1.0, 4.2.0, 4.3.0, 4.4.0, 4.4.1, 4.5.0, 4.5.1, 5.0.0, 5.1.0, 5.1.1, 5.1.2, 5.2.0, 5.2.1, 5.3.0, 5.3.1, 5.4.0, 5.5.0, 6.0.0, 6.0.1, 6.1.0, 6.2.0, 6.3.0, 6.3.1, 6.4.0)
ERROR: No matching distribution found for pip-tools==6.5.1

```

**Comment by JonathanRenon-EDB** [comment]
Still having this issue.

**Comment by jeffwidman** [comment]
👋 sorry for the slow response.

We're planning to drop support for Python `3.6` this coming April when `ubuntu` `18.04` goes EOL. Given that that's only a few months away, we won't be investing time in fixing this.

So I'm going to close as unplanned, but the great thing is this code is open source, so if it's really important to you feel free to open a PR and we'll happily review/merge.

Just be aware that when we do drop Python 3.6 support, we will probably remove all the workarounds we've currently got in place to support it, so you'd need to maintain a forked version of `dependabot-core` at that point.
