### ISSUE TITLE
dry-run.rb Could not find gem 'vcr (= 6.0.0)' in locally installed gems. (Bundler::GemNotFound) in latest ghcr.io/dependabot/dependabot-core-development:latest DockerImage

### ISSUE THREAD

**Issue by kazuooooo** [dependabot/dependabot-core#4896]
Hi, I tried dry-run.rb following README.md, it raise an error below.

```shell
$ docker pull ghcr.io/dependabot/dependabot-core-development:latest
$ docker tag ghcr.io/dependabot/dependabot-core-development dependabot/dependabot-core-development
$ bin/docker-dev-shell
=> running docker development shell
[dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb go_modules rsc/quote

$ ruby bin/dry-run.rb go_modules zonedb/zonedb
Traceback (most recent call last):
        11: from bin/dry-run.rb:69:in `<main>'
        10: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.3.8/lib/bundler.rb:151:in `setup'
         9: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.3.8/lib/bundler/runtime.rb:18:in `setup'
         8: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.3.8/lib/bundler/definition.rb:238:in `specs_for'
         7: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.3.8/lib/bundler/definition.rb:190:in `specs'
         6: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.3.8/lib/bundler/definition.rb:468:in `materialize'
         5: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.3.8/lib/bundler/definition.rb:269:in `resolve'
         4: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.3.8/lib/bundler/resolver.rb:23:in `resolve'
         3: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.3.8/lib/bundler/resolver.rb:48:in `start'
         2: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.3.8/lib/bundler/resolver.rb:252:in `verify_gemfile_dependencies_are_found!'
         1: from /usr/lib/ruby/gems/2.7.0/gems/bundler-2.3.8/lib/bundler/resolver.rb:252:in `map!'
/usr/lib/ruby/gems/2.7.0/gems/bundler-2.3.8/lib/bundler/resolver.rb:269:in `block in verify_gemfile_dependencies_are_found!': Could not find gem 'vcr (= 6.0.0)' in locally installed gems. (Bundler::GemNotFound)

The source contains the following gems matching 'vcr':
  * vcr-6.1.0
```

It looks common/dependabot-common.gemspec version is invalid.
By changing package version below.(I also need fix `faraday` and `gitlab` versions)
It works fine.
```
-  spec.add_dependency "faraday", "1.7.0"
-  spec.add_dependency "gitlab", "4.17.0"
+  spec.add_dependency "faraday", "1.10.0"
+  spec.add_dependency "gitlab", "4.18.0"
-  spec.add_development_dependency "vcr", "6.0.0"
+  spec.add_development_dependency "vcr", "6.1.0"
```

**Package ecosystem**
docker

**Package manager version**
-

**Language version**
-

**Manifest location and content prior to update**
-

**dependabot.yml content**
-

**Updated dependency**

**What you expected to see, versus what you actually saw**
Can run dry-run without change, but it raise an error.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by deivid-rodriguez** [comment]
I think you might need to rebuild your development image to get it up to date with https://github.com/dependabot/dependabot-core/commit/bad36d91e84194bb3d1dfc793c321cc98839f518 and other recent dependency changes.

**Comment by deivid-rodriguez** [comment]
A way to make this get in the middle less would be to not specify exact dependencies in the gemspec, which is best practice anyways.

**Comment by kazuooooo** [comment]
@deivid-rodriguez 
OK, thank you!
