### ISSUE TITLE
Pub error: Unsupported operation: Trying to serialize a root package description.

### ISSUE THREAD

**Issue by mctofu** [dependabot/dependabot-core#5199]
**Package ecosystem**
Pub

**What you expected to see, versus what you actually saw**
Expected Dependabot to run successful.

Actual:
```
=> parsing dependency files
Traceback (most recent call last):
        14: from bin/dry-run.rb:533:in `<main>'
        13: from bin/dry-run.rb:282:in `cached_read'
        12: from bin/dry-run.rb:533:in `block in <main>'
        11: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/file_parser.rb:17:in `parse'
        10: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/file_parser.rb:30:in `list'
         9: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:17:in `dependency_services_list'
         8: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:46:in `run_dependency_services'
         7: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_directory'
         6: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `chdir'
         5: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `block in in_a_temporary_directory'
         4: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:52:in `block in run_dependency_services'
         3: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
         2: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:59:in `block (2 levels) in run_dependency_services'
         1: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:59:in `chdir'
/home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:71:in `block (3 levels) in run_dependency_services': dart pub failed: Unsupported operation: Trying to serialize a root package description. (Dependabot::DependabotError)
package:pub/src/source/root.dart 69:5                    ResolvedRootDescription.serializeForLockfile
package:pub/src/command/dependency_services.dart 241:24  _source
package:pub/src/command/dependency_services.dart 290:19  DependencyServicesListCommand.runProtected
```

This first started appearing after https://github.com/dependabot/dependabot-core/pull/5102

**Comment by mctofu** [comment]
@sigurdm @jonasfj: We've started to see this again after merging https://github.com/dependabot/dependabot-core/pull/5207. Are we missing the patch that was in https://github.com/dependabot/dependabot-core/pull/5203?

**Comment by mctofu** [comment]
Here's a recent example:
```
[dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb pub TheAlgorithms/Dart
warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
=> cloning into /home/dependabot/dependabot-core/tmp/TheAlgorithms/Dart
=> parsing dependency files
Traceback (most recent call last):
        14: from bin/dry-run.rb:538:in `<main>'
        13: from bin/dry-run.rb:282:in `cached_read'
        12: from bin/dry-run.rb:538:in `block in <main>'
        11: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/file_parser.rb:17:in `parse'
        10: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/file_parser.rb:30:in `list'
         9: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:32:in `dependency_services_list'
         8: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:149:in `run_dependency_services'
         7: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_directory'
         6: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `chdir'
         5: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `block in in_a_temporary_directory'
         4: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:156:in `block in run_dependency_services'
         3: from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
         2: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:166:in `block (2 levels) in run_dependency_services'
         1: from /home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:166:in `chdir'
/home/dependabot/dependabot-core/pub/lib/dependabot/pub/helpers.rb:173:in `block (3 levels) in run_dependency_services': dependency_services failed: Unsupported operation: Trying to serialize a root package description. (Dependabot::DependabotError)
package:pub/src/source/root.dart 69                   ResolvedRootDescription.serializeForLockfile
package:pub/src/command/dependency_services.dart 241  _source
package:pub/src/command/dependency_services.dart 290  DependencyServicesListCommand.runProtected
This is an unexpected error. The full log and other details are collected in:

    /opt/dart/pub-cache/log/pub_log.txt

Consider creating an issue on https://github.com/dart-lang/pub/issues/new
and attaching the relevant parts of that log file.
```

**Comment by sigurdm** [comment]
Yeah - it seems I locked to the wrong git commit here: https://github.com/dependabot/dependabot-core/pull/5207/files#diff-a9ddb73f3c35aff08fccb15ca9aed64e11bd809bb9b6c5cb87618dabae28d776R15 will make a follow-up

**Comment by mctofu** [comment]
@sigurdm I went ahead and made that update via https://github.com/dependabot/dependabot-core/pull/5263 to get a head start on our release process. If there's any additional changes you would make we can follow up with those as well. Thanks for the pointer!

**Comment by mctofu** [comment]
No longer seeing this error after deploying https://github.com/dependabot/dependabot-core/pull/5263.
