### ISSUE TITLE
Add support for Python Poetry dependency groups

### ISSUE THREAD

**Issue by fproulx-boostsecurity** [dependabot/dependabot-core#5296]
Poetry added support for management different dependency groups (https://python-poetry.org/docs/master/managing-dependencies/) and at the moment manifests with those fail to work with Dependabot's automatic PR creation. It works for detecting dependencies, but not for updating them.

Logs
```
 proxy | time="2022-06-14T18:47:12Z" level=info msg="proxy starting" commit=XXXXX
  proxy | 2022/06/14 18:47:12 Listening (:1080)
updater | 2022-06-14T18:47:12.252024859 [anonymous-instance:main:WARN:src/firecracker/src/main.rs:370] You are using a deprecated parameter: --seccomp-level 2, that will be removed in a future version.
updater | 2022-06-14T18:47:12.275644686 [391957818:main:WARN:src/devices/src/legacy/serial.rs:432] Detached the serial input due to peer close/error.
updater | time="2022-06-14T18:47:13Z" level=info msg="guest starting" commit=XXXXX
updater | time="2022-06-14T18:47:13Z" level=info msg="starting job..." fetcher_timeout=5m0s job_id=391957818 updater_timeout=30m0s updater_version=0.191.1-bb1ecaa6e64156d7cda0aee1baa122b96694ad1a
updater | I, [2022-06-14T18:47:15.122040 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
updater | Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_391957818> Starting job processing
  proxy | 2022/06/14 18:47:17 [002] GET https://api.github.com:443/repos/XXXXXXX
  ...
  proxy | 2022/06/14 18:47:17 [002] * authenticating github api request
  ...
updater | INFO <job_391957818> Finished job processing
updater | time="2022-06-14T18:47:19Z" level=info msg="task complete" container_id=job-391957818-file-fetcher exit_code=0 job_id=391957818 step=fetcher
updater | I, [2022-06-14T18:47:20.041356 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | warning: parser/current is loading parser/ruby27, which recognizes2.7.6-compliant syntax, but you are running 2.7.5.
updater | Please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
updater | INFO <job_391957818> Starting job processing
updater | INFO <job_391957818> Starting update job for XXXXXX
updater | INFO <job_391957818> Checking if pywin32 227 needs updating
  proxy | 2022/06/14 18:47:23 [028] GET https://pypi.org:443/simple/pywin32/
  proxy | 2022/06/14 18:47:23 [028] 200 https://pypi.org:443/simple/pywin32/
updater | INFO <job_391957818> Latest version is 304
updater | I, [2022-06-14T18:47:30.184779 #8]  INFO -- sentry: ** [Raven] Sending event 209b1e70ac16406899bfb85044610ef9 to Sentry
  proxy | 2022/06/14 18:47:30 [030] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/06/14 18:47:30 [030] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_391957818> Error processing pywin32 (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_391957818> RuntimeError
updater | <job_391957818> 
updater | <job_391957818>   The Poetry configuration is invalid:
updater | <job_391957818>     - Additional properties are not allowed ('group' was unexpected)
updater | <job_391957818>   
updater | <job_391957818> 
updater | <job_391957818>   at /usr/local/.pyenv/versions/3.10.4/lib/python3.10/site-packages/poetry/core/factory.py:43 in create_poetry
updater | <job_391957818>        39│             message = ""
updater | <job_391957818>        40│             for error in check_result["errors"]:
updater | <job_391957818>        41│                 message += "  - {}\n".format(error)
updater | <job_391957818>        42│ 
updater | <job_391957818>     →  43│             raise RuntimeError("The Poetry configuration is invalid:\n" + message)
updater | <job_391957818>        44│ 
updater | <job_391957818>        45│         # Load package
updater | <job_391957818>        46│         name = local_config["name"]
updater | <job_391957818>        47│         version = local_config["version"]
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.191.1/lib/dependabot/python/update_checker/poetry_version_resolver.rb:325:in `run_poetry_command'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.191.1/lib/dependabot/python/update_checker/poetry_version_resolver.rb:91:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.191.1/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.191.1/lib/dependabot/python/update_checker/poetry_version_resolver.rb:77:in `block in fetch_latest_resolvable_version_string'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.191.1/lib/dependabot/shared_helpers.rb:49:in `block in in_a_temporary_directory'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.191.1/lib/dependabot/shared_helpers.rb:49:in `chdir'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.191.1/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_directory'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.191.1/lib/dependabot/python/update_checker/poetry_version_resolver.rb:76:in `fetch_latest_resolvable_version_string'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.191.1/lib/dependabot/python/update_checker/poetry_version_resolver.rb:58:in `resolvable?'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.191.1/lib/dependabot/python/update_checker.rb:135:in `fetch_lowest_resolvable_security_fix_version'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-python-0.191.1/lib/dependabot/python/update_checker.rb:87:in `lowest_resolvable_security_fix_version'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.191.1/lib/dependabot/update_checkers/base.rb:72:in `preferred_resolvable_version'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.191.1/lib/dependabot/update_checkers/base.rb:257:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.191.1/lib/dependabot/update_checkers/base.rb:249:in `numeric_version_can_update?'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.191.1/lib/dependabot/update_checkers/base.rb:199:in `version_can_update?'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-common-0.191.1/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:454:in `requirements_to_unlock'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:232:in `check_and_create_pull_request'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_391957818> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:35:in `run'
updater | ERROR <job_391957818> bin/update_files.rb:22:in `<main>'
updater | INFO <job_391957818> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2022-06-14T18:47:30Z" level=info msg="task complete" container_id=job-391957818-updater exit_code=0 job_id=391957818 step=updater
```

**Comment by fproulx-boostsecurity** [comment]
cc @lindycoder , @SUSTAPLE117

**Comment by jeffwidman** [comment]
What was the manifest file that generated this error?

Because looking at the backtrace it looks like we shell out to `poetry` itself, which in turn is complaining about an unexpected config key called `group`.

So I'm wondering if the root cause here is a malformed manifest file? Are you able to run poetry natively on this manifest file with no issues?

**Comment by lindycoder** [comment]
@jeffwidman yes our manifest work as expected, but with poetry>=1.2

**Comment by jeffwidman** [comment]
Ah, I see... the doc linked in the OP was from `master`, not a published release. 

Looks like `1.2` dropped 7 minutes ago, so no wonder Dependabot hasn't opened the PR to bump it... I just manually trigged a Dependabot run, so I expect it'll open a PR shortly.

We have a short code freeze on this repo until the end of this week, so once that is over one of us will merge the PR bumping poetry and that should hopefully resolve this.

**Comment by levrik** [comment]
@jeffwidman Good to know so I'll stay away from upgrading Poetry to 1.2.x until Dependabot has catched up.

**Comment by jeffwidman** [comment]
Closing now that #5599 has been deployed.
