### ISSUE TITLE
RuntimeError when updating Terraform provider version

### ISSUE THREAD

**Issue by larsakerlund** [dependabot/dependabot-core#5361]
When Dependabot is trying to update the `required_providers` block of a Terraform module, it fails if the provider `version` key precedes `source`. Simply changing the order of the two keys solves this issue and lets Dependabot run without errors.

**Package ecosystem**

Terraform

**Package manager version**

N/A

**Language version**

Terraform 1.2.2

**Manifest location and content before the Dependabot update**

`main.tf`
```terraform
terraform {
  required_providers {
    azurerm = {
      version = "~> 3.4.0"
      source  = "hashicorp/azurerm"
    }
  }
}
```

**dependabot.yml content**

```yaml
---
version: 2

updates:
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "daily"

```

**Updated dependency**

From `3.4.0` to `3.13.0`.

**What you expected to see, versus what you actually saw**

Expected Dependabot to open a PR with the updates. Instead, it throws a RuntimeError since the content is not updated. See the log below.

**Native package manager behavior**

**Images of the diff or a link to the PR, issue, or logs**

```
updater | INFO <job_416661560> Starting job processing
updater | INFO <job_416661560> Starting update job for RedeployAB/dependabot-troubleshoot-2
updater | INFO <job_416661560> Checking if hashicorp/azurerm  needs updating
  proxy | 2022/07/12 09:37:48 [015] GET https://registry.terraform.io:443/.well-known/terraform.json
  proxy | 2022/07/12 09:37:48 [015] 200 https://registry.terraform.io:443/.well-known/terraform.json
  proxy | 2022/07/12 09:37:48 [017] GET https://registry.terraform.io:443/v1/providers/hashicorp/azurerm/versions
  proxy | 2022/07/12 09:37:48 [017] 200 https://registry.terraform.io:443/v1/providers/hashicorp/azurerm/versions
updater | INFO <job_416661560> Latest version is 3.13.0
updater | INFO <job_416661560> Requirements to unlock own
updater | INFO <job_416661560> Requirements update strategy 
updater | INFO <job_416661560> Updating hashicorp/azurerm from  to 3.13.0
updater | I, [2022-07-12T09:37:49.011766 #7]  INFO -- sentry: ** [Raven] Sending event cb94106c41a74549aab8e20503b018db to Sentry
  proxy | 2022/07/12 09:37:49 [019] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/07/12 09:37:49 [019] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_416661560> Error processing hashicorp/azurerm (RuntimeError)
updater | ERROR <job_416661560> Content didn't change!
updater | ERROR <job_416661560> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.196.3/lib/dependabot/terraform/file_updater.rb:30:in `block in updated_dependency_files'
updater | ERROR <job_416661560> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.196.3/lib/dependabot/terraform/file_updater.rb:25:in `each'
updater | ERROR <job_416661560> /home/dependabot/dependabot-updater/vendor/ruby/2.7.0/gems/dependabot-terraform-0.196.3/lib/dependabot/terraform/file_updater.rb:25:in `updated_dependency_files'
updater | ERROR <job_416661560> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:706:in `generate_dependency_files_for'
updater | ERROR <job_416661560> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:280:in `check_and_create_pull_request'
updater | ERROR <job_416661560> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_416661560> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `block in run'
updater | ERROR <job_416661560> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `each'
updater | ERROR <job_416661560> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:56:in `run'
updater | ERROR <job_416661560> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_416661560> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:35:in `run'
updater | ERROR <job_416661560> bin/update_files.rb:22:in `<main>'
updater | INFO <job_416661560> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2022-07-12T09:37:49Z" level=info msg="task complete" container_id=job-416661560-updater exit_code=0 job_id=416661560 step=updater
```

**🕹 Bonus points: Smallest manifest that reproduces the issue**

The manifest above is the only thing you need in `main.tf` to cause the error.

**Comment by jeffwidman** [comment]
Oof, definitely sounds like a bug! Care to submit a PR? My guess is it should be relatively straightforward to track down if it's doing a linear lookup rather than a hash lookup.

**Comment by mkemmerz** [comment]
Any update on this?

**Comment by mkemmerz** [comment]
I opened a PR for this issue. Locally I was able to fix this by enhancing the regex a bit that checks for the `required_providers` block.

**Comment by jeffwidman** [comment]
@mkemmerz should we re-open this based on your findings in:
* https://github.com/dependabot/dependabot-core/issues/5772#issuecomment-1441363512

?

**Comment by mkemmerz** [comment]
> @mkemmerz should we re-open this based on your findings in:
> 
> * [Terraform provider versions are sometimes parsed as empty string "" #5772 (comment)](https://github.com/dependabot/dependabot-core/issues/5772#issuecomment-1441363512)
> 
> ?

Yeah, probably makes sense. It seems there are still cases where this issue is occuring.
