### ISSUE TITLE
Go test suite is flaky

### ISSUE THREAD

**Issue by deivid-rodriguez** [dependabot/dependabot-core#5551]
I believe these flaky specs are frequent enough to warrant an issue to track them.

Some instances:

### From main as of https://github.com/dependabot/dependabot-core/commit/72f033389f9b7db8a722e4c58a495dd013c993d0.

Failed job logs: https://github.com/dependabot/dependabot-core/runs/7884144237?check_suite_focus=true.

```
Failures:

  1) Dependabot::GoModules::FileUpdater::GoModUpdater#updated_go_mod_content when module major version doesn't match (v1) raises the correct error
     Failure/Error:
       expect { updater.updated_go_sum_content }.
         to raise_error(error_class) do |error|
         expect(error.message).to include("go.mod has post-v1 module path")
       end

       expected Dependabot::DependencyFileNotResolvable, got #<Dependabot::GitDependenciesNotReachable: The following git URLs could not be retrieved: github.com/jenkins-x/jx-api> with backtrace:
         # ./lib/dependabot/go_modules/resolvability_errors.rb:29:in `block (2 levels) in handle'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
         # ./lib/dependabot/go_modules/resolvability_errors.rb:15:in `block in handle'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `block in in_a_temporary_directory'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `chdir'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_directory'
         # ./lib/dependabot/go_modules/resolvability_errors.rb:14:in `handle'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:247:in `handle_subprocess_error'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:176:in `run_go_get'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:94:in `block in update_files'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:192:in `block (2 levels) in in_repo_path'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:191:in `block in in_repo_path'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:36:in `block in in_a_temporary_repo_directory'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:36:in `chdir'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:36:in `in_a_temporary_repo_directory'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:190:in `in_repo_path'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:81:in `update_files'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:77:in `updated_files'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:68:in `updated_go_sum_content'
         # ./spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb:515:in `block (5 levels) in <top (required)>'
         # ./spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb:515:in `block (4 levels) in <top (required)>'
         # /home/dependabot/dependabot-core/common/spec/spec_helper.rb:55:in `block (2 levels) in <top (required)>'
         # ./.bundle/ruby/2.7.0/gems/webmock-3.17.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # ./spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb:515:in `block (4 levels) in <top (required)>'
     # /home/dependabot/dependabot-core/common/spec/spec_helper.rb:55:in `block (2 levels) in <top (required)>'
     # ./.bundle/ruby/2.7.0/gems/webmock-3.17.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

  2) Dependabot::GoModules::FileUpdater::GoModUpdater#updated_go_mod_content for a top level dependency when the requirement has changed with a go.sum a dependency that has no top-level package does not raise an error
     Failure/Error: expect { updater.updated_go_sum_content }.to_not raise_error

       expected no Exception, got #<Dependabot::DependencyFileNotResolvable: go: github.com/prometheus/client_golang@v0.9.3 requires
       	github.com/prometheus/common@v0.4.0 requires
       	gopkg.in/yaml.v2@v2.2.1: unrecognized import path> with backtrace:
         # ./lib/dependabot/go_modules/resolvability_errors.rb:27:in `block (2 levels) in handle'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
         # ./lib/dependabot/go_modules/resolvability_errors.rb:15:in `block in handle'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `block in in_a_temporary_directory'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `chdir'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_directory'
         # ./lib/dependabot/go_modules/resolvability_errors.rb:14:in `handle'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:247:in `handle_subprocess_error'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:176:in `run_go_get'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:94:in `block in update_files'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:192:in `block (2 levels) in in_repo_path'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:191:in `block in in_repo_path'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:36:in `block in in_a_temporary_repo_directory'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:36:in `chdir'
         # /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:36:in `in_a_temporary_repo_directory'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:190:in `in_repo_path'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:81:in `update_files'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:77:in `updated_files'
         # ./lib/dependabot/go_modules/file_updater/go_mod_updater.rb:68:in `updated_go_sum_content'
         # ./spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb:249:in `block (8 levels) in <top (required)>'
         # ./spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb:249:in `block (7 levels) in <top (required)>'
         # /home/dependabot/dependabot-core/common/spec/spec_helper.rb:55:in `block (2 levels) in <top (required)>'
         # ./.bundle/ruby/2.7.0/gems/webmock-3.17.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # ./spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb:249:in `block (7 levels) in <top (required)>'
     # /home/dependabot/dependabot-core/common/spec/spec_helper.rb:55:in `block (2 levels) in <top (required)>'
     # ./.bundle/ruby/2.7.0/gems/webmock-3.17.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 5 minutes 4 seconds (files took 1.23 seconds to load)
255 examples, 2 failures, 8 pending

Failed examples:

rspec ./spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb:513 # Dependabot::GoModules::FileUpdater::GoModUpdater#updated_go_mod_content when module major version doesn't match (v1) raises the correct error
rspec ./spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb:248 # Dependabot::GoModules::FileUpdater::GoModUpdater#updated_go_mod_content for a top level dependency when the requirement has changed with a go.sum a dependency that has no top-level package does not raise an error
```

### From https://github.com/dependabot/dependabot-core/pull/5513 as of https://github.com/dependabot/dependabot-core/commit/8cb6493132bd474ccdf3805d1203546494f3ae6e.

Failed job logs: https://github.com/dependabot/dependabot-core/runs/7884333948?check_suite_focus=true.

```
Failures:

  1) Dependabot::GoModules::FileUpdater::GoModUpdater#updated_go_mod_content when module major version doesn't match (v1) raises the correct error
     Failure/Error:
       expect { updater.updated_go_sum_content }.
         to raise_error(error_class) do |error|
         expect(error.message).to include("go.mod has post-v1 module path")
       end

       expected "go: github.com/jenkins-x/jx-api@v0.0.24 requires\n\tgithub.com/spf13/cobra@v1.0.0 requires\n\tgithub...pkg/mod/cache/vcs/748bced43cf7672b862fbc52430e98581510f4f2c34fb30c0064b7102a68ae2c: exit status 128" to include "go.mod has post-v1 module path"
       Diff:
       @@ -1,5 +1,9 @@
       -go.mod has post-v1 module path
       +go: github.com/jenkins-x/jx-api@v0.0.24 requires
       +	github.com/spf13/cobra@v1.0.0 requires
       +	github.com/spf13/viper@v1.4.0 requires
       +	github.com/grpc-ecosystem/grpc-gateway@v1.9.0 requires
       +	gopkg.in/yaml.v2@v2.0.0-20170812160011-eb3733d160e7: invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/dependabot/go/pkg/mod/cache/vcs/748bced43cf7672b862fbc52430e98581510f4f2c34fb30c0064b7102a68ae2c: exit status 128
     # ./spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb:515:in `block (4 levels) in <top (required)>'
     # /home/dependabot/dependabot-core/common/spec/spec_helper.rb:55:in `block (2 levels) in <top (required)>'
     # ./.bundle/ruby/2.7.0/gems/webmock-3.17.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'

Finished in 6 minutes 2 seconds (files took 1.19 seconds to load)
255 examples, 1 failure, 8 pending

Failed examples:

rspec ./spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb:513 # Dependabot::GoModules::FileUpdater::GoModUpdater#updated_go_mod_content when module major version doesn't match (v1) raises the correct error

Randomized with seed 36577
```

### Observations

* I think they all come dow to the same underlying issue because running running `rspec spec/dependabot/go_modules/file_updater/go_mod_updater_spec.rb:513` locally I've seen all three errors (`gopkg.in/yaml.v2@v2.2.1: unrecognized import path` and `The following git URLs could not be retrieved: github.com/jenkins-x/jx-api`, `invalid version: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/dependabot/go/pkg/mod/cache/vcs/748bced43cf7672b862fbc52430e98581510f4f2c34fb30c0064b7102a68ae2c`).

* Locally, issue is reproducible consistently when first running the spec in the dev shell. After that it seems to no longer reproduce. So the first run must be leaving some artifacts around that make subsequent runs pass?

**Comment by jeffwidman** [comment]
Are you still seeing these? I haven't seen them at all the past few weeks (not that I noticed them before either).

I know enough about go packaging that i could probably dig in if needed but wanted to first check if still happening...

**Comment by deivid-rodriguez** [comment]
Never saw those again.
