### ISSUE TITLE
New RuntimeError exposed after removing guard from sanitize links

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#5789]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

This PR https://github.com/dependabot/dependabot-core/pull/5739 removed a guard on the sanitize metadata links... the sanitization now happens regardless of where Dependabot is running.

However, we saw in our internal exception logger a `RuntimeError`:
```
`Server error at https://gitlab.com/oauth-xx/oauth2/-tree/v2.0.9/: Internal server error`
```
thrown by this block:
https://github.com/dependabot/dependabot-core/blob/478b65eabf0f5af3500f875e8d766a2ec724d5c9/updater/lib/dependabot/updater.rb#L979-L994
and crashed at line 982... that eventually gets passed down to this `santitize_links_and_mentions` method:
https://github.com/dependabot/dependabot-core/blob/9b3375078fd01ab0c8dec69fa8c67e3a70065c2d/common/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb#L247-L251

So need to catch that RuntimeError so that it doesn't crash Dependabot.

**Comment by ybiquitous** [comment]
I also see a similar error about the [oauth2](https://rubygems.org/gems/oauth2) gem. The following is a part of log in my project: ⬇️ 

```
updater | ERROR <job_485110073> Error processing oauth2 (RuntimeError)
updater | ERROR <job_485110073> Server error at https://gitlab.com/oauth-xx/oauth2/-/tree/v2.0.9/: Internal server error
updater | 
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/git_metadata_fetcher.rb:68:in `fetch_upload_pack_for'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/git_metadata_fetcher.rb:17:in `upload_pack'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/git_metadata_fetcher.rb:23:in `tags'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/metadata_finders/base/commits_finder.rb:177:in `fetch_dependency_tags'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/metadata_finders/base/commits_finder.rb:169:in `dependency_tags'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/metadata_finders/base/commits_finder.rb:60:in `new_tag'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/metadata_finders/base/changelog_finder.rb:151:in `tag_for_new_version'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/metadata_finders/base/changelog_finder.rb:106:in `relevant_tag_changelog'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/metadata_finders/base/changelog_finder.rb:70:in `changelog'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/metadata_finders/base/changelog_finder.rb:33:in `changelog_url'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/metadata_finders/base.rb:40:in `changelog_url'
updater | ERROR <job_485110073> /usr/local/lib/ruby/3.1.0/forwardable.rb:238:in `changelog_url'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb:81:in `changelog_cascade'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder/metadata_presenter.rb:39:in `to_s'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:395:in `metadata_cascades_for_dep'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:365:in `metadata_cascades'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:50:in `pr_message'
updater | ERROR <job_485110073> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:64:in `message'
updater | ERROR <job_485110073> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:988:in `pr_message'
updater | ERROR <job_485110073> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:312:in `check_and_create_pull_request'
updater | ERROR <job_485110073> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:103:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_485110073> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `block in run'
updater | ERROR <job_485110073> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `each'
updater | ERROR <job_485110073> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `run'
updater | ERROR <job_485110073> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_485110073> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_485110073> bin/update_files.rb:23:in `<main>'
```

**Comment by ybiquitous** [comment]
@deivid-rodriguez Thanks for the quick fix! 👏🏼

**Comment by deivid-rodriguez** [comment]
No problem!
