### ISSUE TITLE
Actions updates failing with error `fatal: '{some version}' does not appear to be a git repository`

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#6045]
Got an internal report that an actions update is now failing after https://github.com/dependabot/dependabot-core/pull/5951 was deployed.

Logs:
```
updater | ERROR <job_495965143> Error processing tibdex/github-app-token (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_495965143> fatal: '1.6.0' does not appear to be a git repository
updater | <job_495965143> fatal: Could not read from remote repository.
updater | <job_495965143> 
updater | <job_495965143> Please make sure you have the correct access rights
updater | <job_495965143> and the repository exists.
updater | ERROR <job_495965143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:314:in `run_shell_command'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:187:in `find_container_branch'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:88:in `block in latest_commit_for_pinned_ref'
updater | ERROR <job_495965143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `block in in_a_temporary_repo_directory'
updater | ERROR <job_495965143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `chdir'
updater | ERROR <job_495965143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `in_a_temporary_repo_directory'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:87:in `latest_commit_for_pinned_ref'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:75:in `fetch_latest_version_for_git_dependency'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:58:in `fetch_latest_version'
updater | ERROR <job_495965143> /home/dependabot/github_actions/lib/dependabot/github_actions/update_checker.rb:13:in `latest_version'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:518:in `all_versions_ignored?'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:217:in `check_and_create_pull_request'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:103:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `block in run'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `each'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `run'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_495965143> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_495965143> bin/update_files.rb:23:in `<main>'
```

And here's the line that mentions the `tibdex/github-app-token` action:
```
uses: tibdex/github-app-token@f717b5ecd4534d3c4df4ce9b5c1c2214f0f7cd06
```

**Comment by deivid-rodriguez** [comment]
I got into this same thing yesterday and I suspect it may actually be a problem of https://github.com/dependabot/dependabot-core/pull/5576, and #5951 just made the issue surface. I'll update this when I know more.
