### ISSUE TITLE
Unable to update docker version in K8s yaml file 

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#6048]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

I'm testing the docker version bumps of the k8s yaml file and hit a problem where the update job realizes an update is necessary, but hits a problem when trying to update the YAML file.

Job config:
https://github.com/jeffwidman/secrets-store-csi-driver-provider-azure/blob/c1bfda632840f9d44605e726167f24664ab3ceab/.github/dependabot.yml#L30-L35

Image it realizes is outdated and would like to update:
https://github.com/jeffwidman/secrets-store-csi-driver-provider-azure/blob/c1bfda632840f9d44605e726167f24664ab3ceab/manifest_staging/charts/csi-secrets-store-provider-azure/arc-values.yaml#L126-L129

Here's the log:
```
updater | INFO <job_499679275> Starting update job for jeffwidman/secrets-store-csi-driver-provider-azure
updater | INFO <job_499679275> Checking if oss/kubernetes-csi/secrets-store/driver-crds v1.2.3 needs updating
  proxy | 2022/11/04 08:34:36 [016] GET https://mcr.microsoft.com:443/v2/oss/kubernetes-csi/secrets-store/driver-crds/tags/list
  proxy | 2022/11/04 08:34:36 [016] 200 https://mcr.microsoft.com:443/v2/oss/kubernetes-csi/secrets-store/driver-crds/tags/list
updater | INFO <job_499679275> Latest version is v1.2.4
updater | INFO <job_499679275> Requirements to unlock own
updater | INFO <job_499679275> Requirements update strategy 
updater | INFO <job_499679275> Updating oss/kubernetes-csi/secrets-store/driver-crds from v1.2.3 to v1.2.4
updater | I, [2022-11-04T08:34:36.163786 #7]  INFO -- sentry: ** [Raven] Sending event 0ab83d20a60c4252b3a108fe5d30dbf3 to Sentry
  proxy | 2022/11/04 08:34:36 [018] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/11/04 08:34:36 [018] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_499679275> Error processing oss/kubernetes-csi/secrets-store/driver-crds (RuntimeError)
updater | ERROR <job_499679275> Expected content to change!
updater | ERROR <job_499679275> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:157:in `updated_yaml_content'
updater | ERROR <job_499679275> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:27:in `block in updated_dependency_files'
updater | ERROR <job_499679275> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:21:in `each'
updater | ERROR <job_499679275> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:21:in `updated_dependency_files'
updater | ERROR <job_499679275> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:741:in `generate_dependency_files_for'
updater | ERROR <job_499679275> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:305:in `check_and_create_pull_request'
updater | ERROR <job_499679275> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:103:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_499679275> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `block in run'
updater | ERROR <job_499679275> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `each'
updater | ERROR <job_499679275> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `run'
updater | ERROR <job_499679275> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_499679275> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_499679275> bin/update_files.rb:23:in `<main>'
```

**Comment by jeffwidman** [comment]
Resolved by #6096 and #6097
