### ISSUE TITLE
Exception if 'Directory.Build.props' contains 'PropertyGroup' named 'PackageReference...'

### ISSUE THREAD

**Issue by Tripletri** [dependabot/dependabot-core#6139]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### dependabot.yml content

```
version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
```

### What you expected to see, versus what you actually saw

Dependabot throws `undefined method 'attribute' for nil:NilClass` if `Directory.Build.props` contains `PropertyGroup` named `PackageReference*`. For example:
```
<PropertyGroup>
    <PackageReferenceQWERTY>ZXCVB</PackageReferenceQWERTY>
</PropertyGroup>
```

### Smallest manifest that reproduces the issue

1. Add Directory.Build.props in repo
2. Add next lines to it:
```
<PropertyGroup>
    <PackageReferenceQWERTY>ZXCVB</PackageReferenceQWERTY>
</PropertyGroup>
 ```
 
 ### Additional information
 For more details you can look at [test repository](https://github.com/Tripletri/dependabot-build-props-bug).
#### Update logs
Short:
```
updater | ERROR <job_513038140> undefined method `attribute' for nil:NilClass
updater | <job_513038140> 
updater | <job_513038140>             node_name = node.attribute("Include")&.value&.strip ||
updater | <job_513038140>                             ^^^^^^^^^^
```
<details>
<summary>Full logs</summary>

```
  proxy | time="2022-11-15T16:45:49Z" level=info msg="proxy starting" commit=843c0928fee6f7a20d835e4f6c436aa7c1567af9
  proxy | 2022/11/15 16:45:49 Listening (:1080)
updater | 2022-11-15T16:45:49.785117607 [513038140:main:WARN:src/devices/src/legacy/serial.rs:214] Detached the serial input due to peer close/error.
updater | time="2022-11-15T16:45:51Z" level=info msg="guest starting" commit=ed384b44fcafed3f83e13235c1143eb2afa85db1
updater | time="2022-11-15T16:45:51Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=513038140 updater_timeout=45m0s updater_version=305f8025b0eaa2a86586286dbe23da475c0a3fbc
updater | I, [2022-11-15T16:45:52.904729 #7]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_513038140> Starting job processing
  proxy | 2022/11/15 16:45:55 [002] GET https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug
  proxy | 2022/11/15 16:45:55 [002] * authenticating github api request
  proxy | 2022/11/15 16:45:55 [002] 200 https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug
  proxy | 2022/11/15 16:45:55 [004] GET https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/git/refs/heads/master
  proxy | 2022/11/15 16:45:55 [004] * authenticating github api request
  proxy | 2022/11/15 16:45:55 [004] 200 https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/git/refs/heads/master
  proxy | 2022/11/15 16:45:55 [006] GET https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/contents/?ref=894213d0dc1ad64dcf08a7f7575be678c57d55f0
  proxy | 2022/11/15 16:45:55 [006] * authenticating github api request
  proxy | 2022/11/15 16:45:55 [006] 200 https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/contents/?ref=894213d0dc1ad64dcf08a7f7575be678c57d55f0
  proxy | 2022/11/15 16:45:55 [008] GET https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/contents/dependabot-build-props-bug.sln?ref=894213d0dc1ad64dcf08a7f7575be678c57d55f0
  proxy | 2022/11/15 16:45:55 [008] * authenticating github api request
  proxy | 2022/11/15 16:45:55 [008] 200 https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/contents/dependabot-build-props-bug.sln?ref=894213d0dc1ad64dcf08a7f7575be678c57d55f0
  proxy | 2022/11/15 16:45:55 [010] GET https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/contents/dependabot-build-props-bug/dependabot-build-props-bug.csproj?ref=894213d0dc1ad64dcf08a7f7575be678c57d55f0
  proxy | 2022/11/15 16:45:55 [010] * authenticating github api request
  proxy | 2022/11/15 16:45:55 [010] 200 https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/contents/dependabot-build-props-bug/dependabot-build-props-bug.csproj?ref=894213d0dc1ad64dcf08a7f7575be678c57d55f0
  proxy | 2022/11/15 16:45:55 [012] GET https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/contents/dependabot-build-props-bug?ref=894213d0dc1ad64dcf08a7f7575be678c57d55f0
  proxy | 2022/11/15 16:45:55 [012] * authenticating github api request
  proxy | 2022/11/15 16:45:55 [012] 200 https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/contents/dependabot-build-props-bug?ref=894213d0dc1ad64dcf08a7f7575be678c57d55f0
  proxy | 2022/11/15 16:45:55 [014] GET https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/contents/Directory.Build.props?ref=894213d0dc1ad64dcf08a7f7575be678c57d55f0
  proxy | 2022/11/15 16:45:55 [014] * authenticating github api request
  proxy | 2022/11/15 16:45:55 [014] 200 https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/contents/Directory.Build.props?ref=894213d0dc1ad64dcf08a7f7575be678c57d55f0
updater | INFO <job_513038140> Finished job processing
updater | time="2022-11-15T16:45:55Z" level=info msg="task complete" container_id=job-513038140-file-fetcher exit_code=0 job_id=513038140 step=fetcher
updater | I, [2022-11-15T16:45:56.886203 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_513038140> Starting job processing
updater | INFO <job_513038140> Starting update job for Tripletri/dependabot-build-props-bug
updater | INFO <job_513038140> Checking if Serilog 2.10.0 needs updating
  proxy | 2022/11/15 16:45:58 [018] GET https://azuresearch-usnc.nuget.org:443/query?q=serilog&prerelease=true&semVerLevel=2.0.0
  proxy | 2022/11/15 16:45:59 [018] 200 https://azuresearch-usnc.nuget.org:443/query?q=serilog&prerelease=true&semVerLevel=2.0.0
updater | INFO <job_513038140> Latest version is 2.12.0
updater | INFO <job_513038140> Requirements to unlock own
updater | INFO <job_513038140> Requirements update strategy 
updater | INFO <job_513038140> Updating Serilog from 2.10.0 to 2.12.0
  proxy | 2022/11/15 16:45:59 [020] GET https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/commits?per_page=100
  proxy | 2022/11/15 16:45:59 [020] * authenticating github api request
  proxy | 2022/11/15 16:45:59 [020] 200 https://api.github.com:443/repos/Tripletri/dependabot-build-props-bug/commits?per_page=100
  proxy | 2022/11/15 16:45:59 [022] GET https://api.nuget.org:443/v3-flatcontainer/serilog/2.12.0/serilog.nuspec
  proxy | 2022/11/15 16:45:59 [022] 200 https://api.nuget.org:443/v3-flatcontainer/serilog/2.12.0/serilog.nuspec
  proxy | 2022/11/15 16:45:59 [024] GET https://api.github.com:443/repos/serilog/serilog/releases?per_page=100
  proxy | 2022/11/15 16:45:59 [024] * authenticating github api request
  proxy | 2022/11/15 16:45:59 [024] 200 https://api.github.com:443/repos/serilog/serilog/releases?per_page=100
  proxy | 2022/11/15 16:45:59 [026] GET https://api.github.com:443/repos/serilog/serilog/contents/
  proxy | 2022/11/15 16:45:59 [026] * authenticating github api request
  proxy | 2022/11/15 16:46:00 [026] 200 https://api.github.com:443/repos/serilog/serilog/contents/
  proxy | 2022/11/15 16:46:00 [028] GET https://api.github.com:443/repos/serilog/serilog/contents/CHANGES.md?ref=dev
  proxy | 2022/11/15 16:46:00 [028] * authenticating github api request
  proxy | 2022/11/15 16:46:00 [028] 200 https://api.github.com:443/repos/serilog/serilog/contents/CHANGES.md?ref=dev
  proxy | 2022/11/15 16:46:00 [030] GET https://github.com:443/serilog/serilog.git/info/refs?service=git-upload-pack
  proxy | 2022/11/15 16:46:00 [030] * authenticating git server request (host: github.com)
  proxy | 2022/11/15 16:46:00 [030] 200 https://github.com:443/serilog/serilog.git/info/refs?service=git-upload-pack
  proxy | 2022/11/15 16:46:00 [032] GET https://api.github.com:443/repos/serilog/serilog/contents/?ref=v2.12.0
  proxy | 2022/11/15 16:46:00 [032] * authenticating github api request
  proxy | 2022/11/15 16:46:00 [032] 200 https://api.github.com:443/repos/serilog/serilog/contents/?ref=v2.12.0
  proxy | 2022/11/15 16:46:00 [034] GET https://api.github.com:443/repos/serilog/serilog/contents/CHANGES.md?ref=v2.12.0
  proxy | 2022/11/15 16:46:00 [034] * authenticating github api request
  proxy | 2022/11/15 16:46:00 [034] 200 https://api.github.com:443/repos/serilog/serilog/contents/CHANGES.md?ref=v2.12.0
  proxy | 2022/11/15 16:46:00 [036] GET https://github.com:443/serilog/serilog.git/info/refs?service=git-upload-pack
  proxy | 2022/11/15 16:46:00 [036] * authenticating git server request (host: github.com)
  proxy | 2022/11/15 16:46:00 [036] 200 https://github.com:443/serilog/serilog.git/info/refs?service=git-upload-pack
  proxy | 2022/11/15 16:46:00 [038] GET https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.10.0
  proxy | 2022/11/15 16:46:00 [038] * authenticating github api request
  proxy | 2022/11/15 16:46:01 [038] 200 https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.10.0
  proxy | 2022/11/15 16:46:01 [040] GET https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.12.0
  proxy | 2022/11/15 16:46:01 [040] * authenticating github api request
  proxy | 2022/11/15 16:46:01 [040] 200 https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.12.0
  proxy | 2022/11/15 16:46:01 [042] GET https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.10.0
  proxy | 2022/11/15 16:46:01 [042] * authenticating github api request
  proxy | 2022/11/15 16:46:01 [042] 200 https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.10.0
  proxy | 2022/11/15 16:46:01 [044] GET https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.12.0
  proxy | 2022/11/15 16:46:01 [044] * authenticating github api request
  proxy | 2022/11/15 16:46:01 [044] 200 https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.12.0
  proxy | 2022/11/15 16:46:02 [046] GET https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.10.0
  proxy | 2022/11/15 16:46:02 [046] * authenticating github api request
  proxy | 2022/11/15 16:46:02 [046] 200 https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.10.0
  proxy | 2022/11/15 16:46:02 [048] GET https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.12.0
  proxy | 2022/11/15 16:46:02 [048] * authenticating github api request
  proxy | 2022/11/15 16:46:02 [048] 200 https://api.github.com:443/repos/serilog/serilog/commits?sha=v2.12.0
updater | INFO <job_513038140> Submitting Serilog pull request for creation
updater | INFO <job_513038140> Checking if Newtonsoft.Json 12.0.3 needs updating
  proxy | 2022/11/15 16:46:02 [052] GET https://azuresearch-usnc.nuget.org:443/query?q=newtonsoft.json&prerelease=true&semVerLevel=2.0.0
  proxy | 2022/11/15 16:46:03 [052] 200 https://azuresearch-usnc.nuget.org:443/query?q=newtonsoft.json&prerelease=true&semVerLevel=2.0.0
updater | INFO <job_513038140> Latest version is 13.0.1
updater | INFO <job_513038140> Requirements to unlock own
updater | INFO <job_513038140> Requirements update strategy 
updater | INFO <job_513038140> Updating Newtonsoft.Json from 12.0.3 to 13.0.1
updater | I, [2022-11-15T16:46:03.027099 #8]  INFO -- sentry: ** [Raven] Sending event e4b32a67bd54464e9ff2efd72e004b13 to Sentry
  proxy | 2022/11/15 16:46:03 [054] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/11/15 16:46:03 [054] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_513038140> Error processing Newtonsoft.Json (NoMethodError)
  proxy | 2022/11/15 16:46:03 [058] GET https://azuresearch-usnc.nuget.org:443/query?q=automapper&prerelease=true&semVerLevel=2.0.0
updater | ERROR <job_513038140> undefined method `attribute' for nil:NilClass
updater | <job_513038140> 
updater | <job_513038140>             node_name = node.attribute("Include")&.value&.strip ||
updater | <job_513038140>                             ^^^^^^^^^^
  proxy | 2022/11/15 16:46:03 [058] 200 https://azuresearch-usnc.nuget.org:443/query?q=automapper&prerelease=true&semVerLevel=2.0.0
  proxy | 2022/11/15 16:46:03 [060] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/11/15 16:46:03 [060] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater/project_file_declaration_finder.rb:74:in `block in fetch_declaration_strings'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater/project_file_declaration_finder.rb:69:in `select'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater/project_file_declaration_finder.rb:69:in `fetch_declaration_strings'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater/project_file_declaration_finder.rb:46:in `declaration_strings'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:132:in `original_declarations'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:109:in `update_declaration'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:84:in `block in update_files_for_dependency'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:74:in `each'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:74:in `update_files_for_dependency'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:32:in `block in updated_dependency_files'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:31:in `each'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:31:in `updated_dependency_files'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:739:in `generate_dependency_files_for'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:303:in `check_and_create_pull_request'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:101:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `block in run'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `each'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `run'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_513038140> bin/update_files.rb:23:in `<main>'
updater | INFO <job_513038140> Checking if AutoMapper 10.1.1 needs updating
updater | INFO <job_513038140> Latest version is 12.0.0
updater | INFO <job_513038140> Requirements to unlock own
updater | INFO <job_513038140> Requirements update strategy 
updater | INFO <job_513038140> Updating AutoMapper from 10.1.1 to 12.0.0
updater | I, [2022-11-15T16:46:03.599123 #8]  INFO -- sentry: ** [Raven] Sending event 63a35ea9e3f84e328a78f50f156491f4 to Sentry
updater | ERROR <job_513038140> Error processing AutoMapper (NoMethodError)
updater | ERROR <job_513038140> undefined method `attribute' for nil:NilClass
updater | <job_513038140> 
updater | <job_513038140>             node_name = node.attribute("Include")&.value&.strip ||
updater | <job_513038140>                             ^^^^^^^^^^
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater/project_file_declaration_finder.rb:74:in `block in fetch_declaration_strings'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater/project_file_declaration_finder.rb:69:in `select'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater/project_file_declaration_finder.rb:69:in `fetch_declaration_strings'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater/project_file_declaration_finder.rb:46:in `declaration_strings'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:132:in `original_declarations'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:109:in `update_declaration'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:84:in `block in update_files_for_dependency'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:74:in `each'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:74:in `update_files_for_dependency'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:32:in `block in updated_dependency_files'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:31:in `each'
updater | ERROR <job_513038140> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:31:in `updated_dependency_files'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:739:in `generate_dependency_files_for'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:303:in `check_and_create_pull_request'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:101:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `block in run'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `each'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:74:in `run'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_513038140> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_513038140> bin/update_files.rb:23:in `<main>'
updater | INFO <job_513038140> Finished job processing
updater | INFO Results:
updater | +---------------------------------------------+
updater | |     Changes to Dependabot Pull Requests     |
updater | +---------+-----------------------------------+
updater | | created | Serilog ( from 2.10.0 to 2.12.0 ) |
updater | +---------+-----------------------------------+
updater | Dependabot encountered '2' error(s) during execution, please check the logs for more details.
updater | time="2022-11-15T16:46:03Z" level=info msg="task complete" container_id=job-513038140-updater exit_code=0 job_id=513038140 step=updater
```
</details>

**Comment by Tripletri** [comment]
I updated the [test repository](https://github.com/Tripletri/dependabot-build-props-bug), let's see if the issue is reproducible.

**Comment by Tripletri** [comment]
The issues is fixed now.
