### ISSUE TITLE
Error when checking Gemfile

### ISSUE THREAD

**Issue by makrsmark** [dependabot/dependabot-core#6333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

bundler

### Package manager version

2.3.17

### Language version

2.7.7

### Manifest location and content before the Dependabot update

/Gemfile (in private repo. do not want to link/attach)

### dependabot.yml content

in private repo, do not want to link/attach. It contains 2 addtional repos
1. github (type: git)
2. private repo (type: rubygems-server)

### What you expected to see, versus what you actually saw

Dependabot is no longer successfully scanning my private ruby repository. I *think* it may be due to a ruby upgrade from `2.6.5` to `2.7.7` as that is the only significant change since the last update. It also upgraded bundler from `1.17.3` to `2.3.17`. I was able to run dependabot locally using https://github.com/dependabot/dependabot-script hoping to reproduce, but it ran successfully.

### Images of the diff or a link to the PR, issue, or logs

log snippet:
```
updater | I, [2022-12-19T14:33:47.730995 #7]  INFO -- sentry: ** [Raven] Sending event efcb8d51264e4f2d88d6d3394fdcb7ba to Sentry
  proxy | 2022/12/19 14:33:47 [026] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/12/19 14:33:47 [026] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_553180398> Error processing rails-html-sanitizer (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_553180398> undefined class/module YAML::
updater | ERROR <job_553180398> /home/dependabot/common/lib/dependabot/shared_helpers.rb:122:in `run_helper_subprocess'
updater | ERROR <job_553180398> /home/dependabot/bundler/lib/dependabot/bundler/native_helpers.rb:43:in `block in run_bundler_subprocess'
updater | ERROR <job_553180398> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler.rb:392:in `block in with_original_env'
updater | ERROR <job_553180398> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler.rb:708:in `with_env'
updater | ERROR <job_553180398> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.3.25/lib/bundler.rb:392:in `with_original_env'
updater | ERROR <job_553180398> /home/dependabot/bundler/lib/dependabot/bundler/native_helpers.rb:39:in `run_bundler_subprocess'
updater | ERROR <job_553180398> /home/dependabot/bundler/lib/dependabot/bundler/update_checker/version_resolver.rb:83:in `block (2 levels) in fetch_latest_resolvable_version_details'
updater | ERROR <job_553180398> /home/dependabot/bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb:52:in `block in in_a_native_bundler_context'
updater | ERROR <job_553180398> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `block in in_a_temporary_directory'
updater | ERROR <job_553180398> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `chdir'
updater | ERROR <job_553180398> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_directory'
updater | ERROR <job_553180398> /home/dependabot/common/lib/dependabot/shared_helpers.rb:38:in `in_a_temporary_repo_directory'
updater | ERROR <job_553180398> /home/dependabot/bundler/lib/dependabot/bundler/update_checker/shared_bundler_helpers.rb:48:in `in_a_native_bundler_context'
updater | ERROR <job_553180398> /home/dependabot/bundler/lib/dependabot/bundler/update_checker/version_resolver.rb:82:in `block in fetch_latest_resolvable_version_details'
updater | ERROR <job_553180398> /home/dependabot/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
updater | ERROR <job_553180398> /home/dependabot/bundler/lib/dependabot/bundler/update_checker/version_resolver.rb:78:in `fetch_latest_resolvable_version_details'
updater | ERROR <job_553180398> /home/dependabot/bundler/lib/dependabot/bundler/update_checker/version_resolver.rb:44:in `latest_resolvable_version_details'
updater | ERROR <job_553180398> /home/dependabot/bundler/lib/dependabot/bundler/update_checker.rb:197:in `latest_resolvable_version_details'
updater | ERROR <job_553180398> /home/dependabot/bundler/lib/dependabot/bundler/update_checker.rb:27:in `latest_resolvable_version'
updater | ERROR <job_553180398> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | ERROR <job_553180398> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:260:in `preferred_version_resolvable_with_unlock?'
updater | ERROR <job_553180398> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:252:in `numeric_version_can_update?'
updater | ERROR <job_553180398> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:202:in `version_can_update?'
updater | ERROR <job_553180398> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | ERROR <job_553180398> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:486:in `requirements_to_unlock'
updater | ERROR <job_553180398> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:259:in `check_and_create_pull_request'
updater | ERROR <job_553180398> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:109:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_553180398> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `block in run'
updater | ERROR <job_553180398> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `each'
updater | ERROR <job_553180398> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `run'
updater | ERROR <job_553180398> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_553180398> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_553180398> bin/update_files.rb:23:in `<main>'
updater | INFO <job_553180398> Checking if sidekiq 6.5.8 needs updating
```

**Comment by deivid-rodriguez** [comment]
Hei!

Thanks for reporting this. It definitely seems related to the Ruby upgrade indeed. I do recall similar issues recently in the rubygems repository, for example, https://github.com/rubygems/rubygems/issues/5608. And those issues were present in the RubyGems version we are using.

So I'm confident that upgrading to Ruby 3.1.3 (which includes RubyGems 3.3.26, which does not have these issues), should make the problem go away.

So please subscribe to https://github.com/dependabot/dependabot-core/pull/6257 :)

**Comment by makrsmark** [comment]
Subscribed. Thank you!
