### ISSUE TITLE
Dependabot fails to update

### ISSUE THREAD

**Issue by lucacome** [dependabot/dependabot-core#6336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### Manifest location and content before the Dependabot update

https://github.com/nginxinc/kubernetes-ingress/blob/main/tests/docker/Dockerfile

### dependabot.yml content

https://github.com/nginxinc/kubernetes-ingress/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Seems like dependabot thinks `python:3.11` needs updating (it doesn't) and it fails to do the update.

A couple of things stand out:
```
updater | INFO <job_553296576> Ignored versions:
updater | INFO <job_553296576>   < 3.11, > 3.10 - from @dependabot ignore command
```
I don't remember ignoring a version, how do I remove that if it's actually there? `< 3.11, > 3.10` seems odd anyways

and the actual error that seems to be about the digest
```
updater | ERROR <job_553296576> Error processing python (NoMethodError)
updater | ERROR <job_553296576> undefined method `split' for nil:NilClass
updater | <job_553296576> 
updater | <job_553296576>           "`#{digest.split(':').last[0..6]}`"
updater | <job_553296576>                     ^^^^^^
updater | ERROR <job_553296576> 
```

### Images of the diff or a link to the PR, issue, or logs

```
updater | INFO <job_553296576> Checking if python 3.11 needs updating
updater | INFO <job_553296576> Ignored versions:
updater | INFO <job_553296576>   < 3.11, > 3.10 - from @dependabot ignore command
  proxy | 2022/12/19 17:02:20 [020] GET https://registry.hub.docker.com:443/v2/library/python/tags/list
  proxy | 2022/12/19 17:02:20 [020] 401 https://registry.hub.docker.com:443/v2/library/python/tags/list
  proxy | 2022/12/19 17:02:20 [022] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:20 [022] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:20 [024] GET https://registry.hub.docker.com:443/v2/library/python/tags/list
  proxy | 2022/12/19 17:02:21 [024] 200 https://registry.hub.docker.com:443/v2/library/python/tags/list
  proxy | 2022/12/19 17:02:21 [026] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/latest
  proxy | 2022/12/19 17:02:21 [026] 401 https://registry.hub.docker.com:443/v2/library/python/manifests/latest
  proxy | 2022/12/19 17:02:21 [028] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:21 [028] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:21 [030] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/latest
  proxy | 2022/12/19 17:02:21 [030] 200 https://registry.hub.docker.com:443/v2/library/python/manifests/latest
  proxy | 2022/12/19 17:02:21 [032] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a3
  proxy | 2022/12/19 17:02:21 [032] 401 https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a3
  proxy | 2022/12/19 17:02:21 [034] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:21 [034] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:21 [036] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a3
  proxy | 2022/12/19 17:02:21 [036] 200 https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a3
  proxy | 2022/12/19 17:02:21 [038] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a2
  proxy | 2022/12/19 17:02:21 [038] 401 https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a2
  proxy | 2022/12/19 17:02:21 [040] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:21 [040] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:21 [042] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a2
  proxy | 2022/12/19 17:02:21 [042] 200 https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a2
  proxy | 2022/12/19 17:02:21 [044] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a1
  proxy | 2022/12/19 17:02:21 [044] 401 https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a1
  proxy | 2022/12/19 17:02:21 [046] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:21 [046] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:21 [048] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a1
  proxy | 2022/12/19 17:02:21 [048] 200 https://registry.hub.docker.com:443/v2/library/python/manifests/3.12.0a1
  proxy | 2022/12/19 17:02:21 [050] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/3.11.1
  proxy | 2022/12/19 17:02:21 [050] 401 https://registry.hub.docker.com:443/v2/library/python/manifests/3.11.1
  proxy | 2022/12/19 17:02:21 [052] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:21 [052] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:21 [054] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/3.11.1
  proxy | 2022/12/19 17:02:21 [054] 200 https://registry.hub.docker.com:443/v2/library/python/manifests/3.11.1
  proxy | 2022/12/19 17:02:22 [056] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/3.11
  proxy | 2022/12/19 17:02:22 [056] 401 https://registry.hub.docker.com:443/v2/library/python/manifests/3.11
  proxy | 2022/12/19 17:02:22 [058] GET https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:22 [058] 200 https://auth.docker.io:443/token?service=registry.docker.io&scope=repository%3Alibrary%2Fpython%3Apull
  proxy | 2022/12/19 17:02:22 [060] HEAD https://registry.hub.docker.com:443/v2/library/python/manifests/3.11
  proxy | 2022/12/19 17:02:22 [060] 200 https://registry.hub.docker.com:443/v2/library/python/manifests/3.11
updater | INFO <job_553296576> Latest version is 3.11
updater | INFO <job_553296576> Requirements to unlock own
updater | INFO <job_553296576> Requirements update strategy 
updater | INFO <job_553296576> Updating python from 3.11 to 3.11
  proxy | 2022/12/19 17:02:35 [062] GET https://api.github.com:443/repos/nginxinc/kubernetes-ingress/commits?per_page=100
  proxy | 2022/12/19 17:02:35 [062] * authenticating github api request
  proxy | 2022/12/19 17:02:36 [062] 200 https://api.github.com:443/repos/nginxinc/kubernetes-ingress/commits?per_page=100
updater | I, [2022-12-19T17:02:36.288988 #8]  INFO -- sentry: ** [Raven] Sending event 6615da3b805b4c269846ee5af4ba5099 to Sentry
  proxy | 2022/12/19 17:02:36 [064] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/12/19 17:02:36 [064] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_553296576> Error processing python (NoMethodError)
updater | ERROR <job_553296576> undefined method `split' for nil:NilClass
updater | <job_553296576> 
updater | <job_553296576>           "`#{digest.split(':').last[0..6]}`"
updater | <job_553296576>                     ^^^^^^
updater | ERROR <job_553296576> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:480:in `previous_version'
updater | ERROR <job_553296576> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:563:in `block in library?'
updater | ERROR <job_553296576> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:563:in `any?'
updater | ERROR <job_553296576> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:563:in `library?'
updater | ERROR <job_553296576> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:48:in `pr_name'
updater | ERROR <job_553296576> /home/dependabot/common/lib/dependabot/pull_request_creator/message_builder.rb:77:in `message'
updater | ERROR <job_553296576> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:982:in `pr_message'
updater | ERROR <job_553296576> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:318:in `check_and_create_pull_request'
updater | ERROR <job_553296576> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:109:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_553296576> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `block in run'
updater | ERROR <job_553296576> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `each'
updater | ERROR <job_553296576> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `run'
updater | ERROR <job_553296576> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_553296576> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_553296576> bin/update_files.rb:23:in `<main>'
updater | INFO <job_553296576> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2022-12-19T17:02:37Z" level=info msg="task complete" container_id=job-553296576-updater exit_code=0 job_id=553296576 step=updater

```

**Comment by deivid-rodriguez** [comment]
Hei @lucacome! Thanks for reporting this issue.

There's several separate issues here:

* Dependabot communicates that it's trying to update your main Dockerfile to `python:3.11` when it's already using that version. In reality, it's trying to update your secondary `gitlab.dockerfile` from `python:3.9` to `python:3.11`. This should get fixed by #6082.
* Dependabot crashes when dealing with an ignore condition created from a `@dependabot ignore` chatop. I don't know what's going on there, will try to reproduce and have a look.
* It's not straightforward to "un-ignore" a dependency. There's some tricks [presented here](https://github.com/dependabot/dependabot-core/issues/1384), but ideally we should have some chatop to undo this.

**Comment by deivid-rodriguez** [comment]
@lucacome I have fixed the particular crash reported here, so closing this issue. Please try again and let me know if you find any issues. You may still run into ignore issues. If that's the case, please subscribe to #6489!

**Comment by lucacome** [comment]
@deivid-rodriguez it's not crashing anymore, thanks! 🎉 

I noticed something weird though
```
updater | INFO <job_613240466> Checking if python 3.9 needs updating
updater | INFO <job_613240466> Ignored versions:
updater | INFO <job_613240466>   < 3.11, > 3.10 - from @dependabot ignore command
....

updater | INFO <job_613240466> Latest version is 3.11
updater | INFO <job_613240466> Requirements to unlock own
updater | INFO <job_613240466> Requirements update strategy 
updater | INFO <job_613240466> Updating python from 3.9 to 3.11
```

so it seems like it's ignoring the ignore? 😄

**Comment by deivid-rodriguez** [comment]
Indeed, lucky that's what you needed here, right? 😆 

I suspect this is an issue with `@dependabot ignore` commands that when used on a Docker PR will add an incorrect ignore that ends up not ignoring anything?
