### ISSUE TITLE
Yarn classic private registry authentication not working as expected

### ISSUE THREAD

**Issue by rufushonour** [dependabot/dependabot-core#6352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

v1

### dependabot.yml content

```
version: 2
registries:
  npm-github:
    type: npm-registry
    url: npm.pkg.github.com
    token: ${{ secrets.GH_TOKEN }}
updates:
  - package-ecosystem: 'npm'
    open-pull-requests-limit: 0
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    registries:
      - npm-github
    labels:
      - dependencies
      - dependabot
```

### What you expected to see, versus what you actually saw

I am trying to run security only dependabot updates and authenticate against the GitHub package registry, as a npm registry, with a token within `dependabot.yml`. This token appears to be ignored if a .yarnrc file exists in the repo without an auth token embedded in it. 

The contents yarnrc file are: 
```
"@org1:registry" "https://npm.pkg.github.com"
"@org2:registry" "https://npm.pkg.github.com"
```

The logs I get from dependabot in the security section is as follows:
```
 proxy | time="2022-12-22T09:04:29Z" level=info msg="proxy starting" commit=a44dbeb1ae91856f5c5e9445bb0a0ea39f59a60e
  proxy | 2022/12/22 09:04:29 Listening (:1080)
updater | 2022-12-22T09:04:29.200744546 [555982386:main:WARN:src/devices/src/legacy/serial.rs:214] Detached the serial input due to peer close/error.
updater | time="2022-12-22T09:04:31Z" level=info msg="guest starting" commit=40ff6e03fca84ad9a8eaa73c63f7bec092c87e92
updater | time="2022-12-22T09:04:31Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=555982386 updater_timeout=45m0s updater_version=cc8afc3c798fd7238f36f550bda2c7366fa3dc62
updater | I, [2022-12-22T09:04:32.470445 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_555982386> Starting job processing
  proxy | 2022/12/22 09:04:34 [002] GET https://github.com:443/org/repo/info/refs?service=git-upload-pack
  proxy | 2022/12/22 09:04:34 [002] * authenticating git server request (host: github.com)
  proxy | 2022/12/22 09:04:34 [002] 200 https://github.com:443/org/repo/info/refs?service=git-upload-pack
  proxy | 2022/12/22 09:04:35 [004] POST https://github.com:443/org/repo/git-upload-pack
  proxy | 2022/12/22 09:04:35 [004] * authenticating git server request (host: github.com)
  proxy | 2022/12/22 09:04:35 [004] 200 https://github.com:443/org/repo/git-upload-pack
  proxy | 2022/12/22 09:04:35 [006] POST https://github.com:443/org/repo/git-upload-pack
  proxy | 2022/12/22 09:04:35 [006] * authenticating git server request (host: github.com)
  proxy | 2022/12/22 09:04:35 [006] 200 https://github.com:443/org/repo/git-upload-pack
updater | INFO <job_555982386> Finished job processing
updater | time="2022-12-22T09:04:44Z" level=info msg="task complete" container_id=job-555982386-file-fetcher exit_code=0 job_id=555982386 step=fetcher
updater | I, [2022-12-22T09:04:45.716717 #8]  INFO -- sentry: ** [Raven] Raven 3.1.2 ready to catch errors
updater | INFO <job_555982386> Starting job processing
updater | INFO <job_555982386> Starting update job for org/repo
updater | INFO <job_555982386> Checking if loader-utils 1.4.0 needs updating
  proxy | 2022/12/22 09:05:35 [012] GET https://registry.yarnpkg.com:443/loader-utils
  proxy | 2022/12/22 09:05:35 [012] 200 https://registry.yarnpkg.com:443/loader-utils
  proxy | 2022/12/22 09:05:35 [014] GET https://registry.yarnpkg.com:443/loader-utils/3.2.1
  proxy | 2022/12/22 09:05:35 [014] 200 https://registry.yarnpkg.com:443/loader-utils/3.2.1
updater | INFO <job_555982386> Latest version is 3.2.1
  proxy | 2022/12/22 09:05:35 [016] GET https://registry.yarnpkg.com:443/loader-utils/1.4.2
  proxy | 2022/12/22 09:05:36 [016] 200 https://registry.yarnpkg.com:443/loader-utils/1.4.2
updater | INFO <job_555982386> Requirements to unlock own
updater | INFO <job_555982386> Requirements update strategy widen_ranges
updater | INFO <job_555982386> Updating loader-utils from 1.4.0 to 1.4.2
  // Snipped the typical yarn registry log lines
  proxy | 2022/12/22 09:05:49 [160] GET https://registry.yarnpkg.com:443/@jest%2fcreate-cache-key-function
  proxy | 2022/12/22 09:05:49 [160] 200 https://registry.yarnpkg.com:443/@jest%2fcreate-cache-key-function
  proxy | 2022/12/22 09:05:49 [162] GET https://npm.pkg.github.com:443/@org%2fpackage
  proxy | 2022/12/22 09:05:49 [162] 401 https://npm.pkg.github.com:443/@org%2fpackage
updater | I, [2022-12-22T09:05:49.485975 #8]  INFO -- sentry: ** [Raven] Sending event dcd1147db39d44b0b0b4423ae113de36 to Sentry
  proxy | 2022/12/22 09:05:49 [164] POST https://sentry.io:443/api/1451818/store/
  proxy | 2022/12/22 09:05:49 [164] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_555982386> Error processing loader-utils (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_555982386> https://npm.pkg.github.com/@org%2fpackage: authentication token not provided
updater | ERROR <job_555982386> /home/dependabot/common/lib/dependabot/shared_helpers.rb:122:in `run_helper_subprocess'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:191:in `run_yarn_top_level_updater'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:114:in `block (2 levels) in run_yarn_updater'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:107:in `chdir'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:107:in `block in run_yarn_updater'
updater | ERROR <job_555982386> /home/dependabot/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:106:in `run_yarn_updater'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:79:in `run_current_yarn_update'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:60:in `block in updated_yarn_lock'
updater | ERROR <job_555982386> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `block in in_a_temporary_repo_directory'
updater | ERROR <job_555982386> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `chdir'
updater | ERROR <job_555982386> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `in_a_temporary_repo_directory'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:56:in `updated_yarn_lock'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:32:in `updated_yarn_lock_content'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:218:in `updated_yarn_lock_content'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:162:in `yarn_lock_changed?'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:186:in `block in updated_lockfiles'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:185:in `each'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:185:in `updated_lockfiles'
updater | ERROR <job_555982386> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:40:in `updated_dependency_files'
updater | ERROR <job_555982386> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:747:in `generate_dependency_files_for'
updater | ERROR <job_555982386> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:311:in `check_and_create_pull_request'
updater | ERROR <job_555982386> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:109:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_555982386> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `block in run'
updater | ERROR <job_555982386> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `each'
updater | ERROR <job_555982386> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `run'
updater | ERROR <job_555982386> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_555982386> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_555982386> bin/update_files.rb:23:in `<main>'
updater | INFO <job_555982386> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2022-12-22T09:05:50Z" level=info msg="task complete" container_id=job-555982386-updater exit_code=0 job_id=555982386 step=updater
````

I would expect the token in dependabot.yml to overwrite any other file and be the single source of truth for a token.

**Comment by jakecoffman** [comment]
To get security updates to pick up credentials from the dependabot.yml, the directory needs to match, and there needs to be no target branch. It defaults to the default branch, and even if you've set the target-branch setting to the default branch, it won't find it. This is a known issue we hope to address it soon. 

Could you try setting the correct directory, if it's not right, and removing the target-branch? It should work!
