### ISSUE TITLE
File paths on bitbucket.org with spaces not escaped causing Bad URI messages

### ISSUE THREAD

**Issue by jmartens** [dependabot/dependabot-core#6381]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

docker

### Package manager version

nuget

### Language version

C#, .NET Framework 4.6.2

### What you expected to see, versus what you actually saw

I am trying to see if I can get dependabot working using dependabot-script from a local docker instance following instructions at https://github.com/dependabot/dependabot-script#running-script-with-dependabot-script-dockerfile, but for the project under test I get the following failure:

```
docker run -it --rm --env "PROJECT_DIRECTORY=/" --env "PROJECT_PATH=maastro/eclipse-plan-check" --env "PACKAGE_MANAGER=nuget" --env "BITBUCKET_ACCESS_TOKEN=***REDACTED***" --env "DIRECTORY_PATH=/" --env "BRANCH=develop" dependabot/dependabot-script
To use retry middleware with Faraday v2.0+, install `faraday-retry` gem
Running with options: {}
Fetching nuget dependency files for maastro/eclipse-plan-check
Traceback (most recent call last):
        21: from ./generic-update-script.rb:161:in `<main>'
        20: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.209.0/lib/dependabot/file_fetchers/base.rb:68:in `files'
        19: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.209.0/lib/dependabot/nuget/file_fetcher.rb:28:in `fetch_files'
        18: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.209.0/lib/dependabot/nuget/file_fetcher.rb:59:in `project_files'
        17: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.209.0/lib/dependabot/nuget/file_fetcher.rb:150:in `sln_project_files'
        16: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.209.0/lib/dependabot/nuget/file_fetcher.rb:177:in `sln_files'
        15: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.209.0/lib/dependabot/nuget/file_fetcher.rb:177:in `map'
        14: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-nuget-0.209.0/lib/dependabot/nuget/file_fetcher.rb:177:in `block in sln_files'
        13: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.209.0/lib/dependabot/file_fetchers/base.rb:143:in `fetch_file_from_host'
        12: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.209.0/lib/dependabot/file_fetchers/base.rb:402:in `_fetch_file_content'
        11: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.209.0/lib/dependabot/file_fetchers/base.rb:425:in `_fetch_file_content_fully_specified'
        10: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.209.0/lib/dependabot/clients/bitbucket_with_retries.rb:36:in `method_missing'
         9: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.209.0/lib/dependabot/clients/bitbucket_with_retries.rb:54:in `retry_connection_failures'
         8: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.209.0/lib/dependabot/clients/bitbucket_with_retries.rb:39:in `block in method_missing'
         7: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.209.0/lib/dependabot/clients/bitbucket_with_retries.rb:39:in `public_send'
         6: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.209.0/lib/dependabot/clients/bitbucket.rb:64:in `fetch_file_contents'
         5: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/dependabot-common-0.209.0/lib/dependabot/clients/bitbucket.rb:177:in `get'
         4: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/excon-0.92.4/lib/excon.rb:250:in `get'
         3: from /home/dependabot/dependabot-script/vendor/ruby/2.7.0/gems/excon-0.92.4/lib/excon.rb:121:in `new'
         2: from /usr/local/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
         1: from /usr/local/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
/usr/local/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "https://api.bitbucket.org/2.0/repositories/maastro/eclipse-plan-check/src/a025cc4a6e8c18778f36e0c7e5e68ed44f8a769c/Eclipse Plan Check.sln" (URI::InvalidURIError)
```

If I try another project with a solution file without spaces it seems to work OK this far.

**Comment by jmartens** [comment]
I think I noticed where it might need a fix at https://github.com/dependabot/dependabot-core/blob/main/common/lib/dependabot/clients/bitbucket.rb#L64-L69.

In `fetch_file_contents(repo, commit, path)` It adds the path to the URL but does not escape the path.

**Comment by jmartens** [comment]
I found there are more locations in this client where this might give problems, I think the most universal fix is making sure the URL will be encoded properly in the `get()` function. I will try and submit a fix.

**Comment by jeffwidman** [comment]
Thanks for debugging! Support for bitbucket is community-driven, we're thrilled folks are using it, but not able to spend the time to debug issues ourselves, so always appreciate when folks like yourself go the extra mile to submit a fix.

**Comment by jmartens** [comment]
You're welcome. I like to contribute when I have issues/itches like this and this seemed a pretty easy fix. And thought that the issue might stand out more and get more attention if I could provide a (proper) fix.
