### ISSUE TITLE
Dependabot does not update yarn.lock when dependency fails to pack

### ISSUE THREAD

**Issue by KholdStare** [dependabot/dependabot-core#6432]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

yarn

### Package manager version

yarn 3.3.1

### Language version

nodejs 14

### Manifest location and content before the Dependabot update

See https://github.com/KholdStare/yarn-dependabot-bug

### dependabot.yml content

https://github.com/KholdStare/yarn-dependabot-bug/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

I expect to see `yarn.lock` updated along with `package.json` changes. This does not happen.

This is most likely due to a particular indirect dependency that has nothing to do with what is being updated: `gluegun@https://github.com/edgeandnode/gluegun.git#commit=b34b9003d7bf556836da41b57ef36eb21570620a`

Running `yarn install` locally works fine, however it seems however dependabot runs yarn, it fails to pack this package.

### Images of the diff or a link to the PR, issue, or logs

See pull request: https://github.com/KholdStare/yarn-dependabot-bug/pull/1

In the dependabot logs I see: 

![image](https://user-images.githubusercontent.com/836110/212412796-ec4f4c67-8674-46b2-9c5e-0bfd7cacbf23.png)

```
updater | ERROR <job_578437417> Error processing @graphprotocol/graph-cli (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | ERROR <job_578437417> ➤ YN0000: ┌ Resolution step
```

...

```
updater | <job_578464486> ➤ YN0058: │ gluegun@https://github.com/edgeandnode/gluegun.git#commit=b34b9003d7bf556836da41b57ef36eb21570620a: Packing the package failed (exit code 1, logs can be found here: /tmp/xfs-6ee29d89/pack.log)
updater | <job_578464486> ➤ YN0000: └ Completed in 24s 871ms
updater | <job_578464486> ➤ YN0000: Failed with errors in 29s 449ms
updater | ERROR <job_578464486> /home/dependabot/common/lib/dependabot/shared_helpers.rb:316:in `run_shell_command'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb:94:in `run_yarn_command'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:153:in `run_yarn_berry_top_level_updater'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:110:in `block (2 levels) in run_yarn_updater'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:107:in `chdir'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:107:in `block in run_yarn_updater'
updater | ERROR <job_578464486> /home/dependabot/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:106:in `run_yarn_updater'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:79:in `run_current_yarn_update'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:60:in `block in updated_yarn_lock'
updater | ERROR <job_578464486> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `block in in_a_temporary_repo_directory'
updater | ERROR <job_578464486> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `chdir'
updater | ERROR <job_578464486> /home/dependabot/common/lib/dependabot/shared_helpers.rb:36:in `in_a_temporary_repo_directory'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:56:in `updated_yarn_lock'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:32:in `updated_yarn_lock_content'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:218:in `updated_yarn_lock_content'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:162:in `yarn_lock_changed?'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:186:in `block in updated_lockfiles'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:185:in `each'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:185:in `updated_lockfiles'
updater | ERROR <job_578464486> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:40:in `updated_dependency_files'
updater | ERROR <job_578464486> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:747:in `generate_dependency_files_for'
updater | ERROR <job_578464486> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:311:in `check_and_create_pull_request'
updater | ERROR <job_578464486> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:109:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_578464486> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `block in run'
updater | ERROR <job_578464486> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `each'
updater | ERROR <job_578464486> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:82:in `run'
updater | ERROR <job_578464486> /home/dependabot/dependabot-updater/lib/dependabot/update_files_job.rb:17:in `perform_job'
updater | ERROR <job_578464486> /home/dependabot/dependabot-updater/lib/dependabot/base_job.rb:50:in `run'
updater | ERROR <job_578464486> bin/update_files.rb:23:in `<main>'
updater | INFO <job_578464486> Checking if @types/lodash 4.14.189 needs updating
  proxy | 2023/01/13 20:22:47 [160] GET https://registry.npmjs.org:443/@types%2Flodash/4.14.191
  proxy | 2023/01/13 20:22:52 [160] 200 https://registry.npmjs.org:443/@types%2Flodash/4.14.191
updater | INFO <job_578464486> Latest version is 4.14.191
updater | INFO <job_578464486> Pull request already exists for @types/lodash with latest version 4.14.191
updater | INFO <job_578464486> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2023-01-13T20:22:53Z" level=info msg="task complete" container_id=job-578464486-updater exit_code=0 
```

### Smallest manifest that reproduces the issue

Tiny public repository reproducing this issue: https://github.com/KholdStare/yarn-dependabot-bug

The dependabot pull request without the `yarn.lock` file: https://github.com/KholdStare/yarn-dependabot-bug/pull/1

**Comment by deivid-rodriguez** [comment]
It seems related to upstream issue https://github.com/yarnpkg/berry/issues/1915 and issues linked from there?

Apparently newer versions of `yarn` run build scripts of git dependencies, which requires installing dev dependencies of the git dependency itself, and I'm guessing that's failing for some reason. Regardless of the outcome of those issues, we should do something about this (maybe swallowing the errors is fine) since Dependabot just needs dependencies to resolve properly and shouldn't care about installation issues.

**Comment by deivid-rodriguez** [comment]
Thanks not only for reporting the issue but also for providing a small public repro. That makes it much easier for us to figure this out.

**Comment by KholdStare** [comment]
@deivid-rodriguez @jeffwidman Apologies for poking. Any update on this? If the fix is simple-ish I could also take a look if someone points me in the right direction :)

**Comment by deivid-rodriguez** [comment]
Something I noticed is that `yarn install` on your project also fails in a similar way

```
✗ yarn install
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0013: │ yallist@npm:4.0.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yaml@npm:1.10.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yaml@npm:1.9.2 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ yargs-parser@npm:16.1.0 can't be found in the cache and will be fetched from the remote registry
➤ YN0013: │ gluegun@https://github.com/edgeandnode/gluegun.git#commit=b34b9003d7bf556836da41b57ef36eb21570620a can't be found in the cache and will be fetched from the remote
➤ YN0018: │ gluegun@https://github.com/edgeandnode/gluegun.git#commit=b34b9003d7bf556836da41b57ef36eb21570620a: The remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 19s 396ms
➤ YN0000: Failed with errors in 19s 458ms
```

You may want to investigate what's wrong with yarn/berry and that particular dependency. I found https://github.com/yarnpkg/berry/issues/1142 that will probably help.

**Comment by deivid-rodriguez** [comment]
I see.

I investigated a bit more and found some issues. Trying to fix this at #6516.

**Comment by KholdStare** [comment]
@deivid-rodriguez That's great! I will try today.

**Comment by KholdStare** [comment]
The original bug repository was successful: https://github.com/KholdStare/yarn-dependabot-bug/pull/2 . It updated the yarn.lock file 👍 

Also re-ran dependabot on our repository and everything works now. Thank you! 👍

**Comment by deivid-rodriguez** [comment]
No problem, glad this is now working for you!
