### ISSUE TITLE
Initial dry-run in docker produces permission error, root owns ~/dependabot-core/tmp

### ISSUE THREAD

**Issue by sparr** [dependabot/dependabot-core#6452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### What you expected to see, versus what you actually saw

I am attempting to follow the Setup instructions from README.md and encounter a permission error within the Docker container environment.

The tmp/ and dry-run/ directories do not exist after checking out the repo. They seem to be created by the docker-dev-shell script. Both are created with root:root ownership instead of dependabot:dependabot ownership within the container or myuser:mygroup outside the container.

Changing permissions on the directory within or without the container, or ownership within the container, works around this problem.

Versions/hashes:
Docker 20.10.17
Amazon Linux 2.0.20221210.0
dependabot-core a5e540517b8a5c7e2356ae538e9a4597098479a3

```
~/src/dependabot/dependabot-core.git $ bin/docker-dev-shell                                       
 > image dependabot/dependabot-core-development already exists

=> running docker development shell
```
```
[dependabot-core-dev] ~/dependabot-core $ bin/dry-run.rb go_modules rsc/quote
/usr/local/lib/ruby/3.1.0/fileutils.rb:243:in `mkdir': Permission denied @ dir_s_mkdir - /home/dependabot/dependabot-core/tmp/rsc (Errno::EACCES)
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:243:in `fu_mkdir'
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:221:in `block (2 levels) in mkdir_p'
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:219:in `reverse_each'
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:219:in `block in mkdir_p'
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:211:in `each'
        from /usr/local/lib/ruby/3.1.0/fileutils.rb:211:in `mkdir_p'
        from /home/dependabot/dependabot-core/common/lib/dependabot/file_fetchers/base.rb:591:in `block in _clone_repo_contents'
        from /home/dependabot/dependabot-core/common/lib/dependabot/shared_helpers.rb:168:in `with_git_configured'
        from /home/dependabot/dependabot-core/common/lib/dependabot/file_fetchers/base.rb:585:in `_clone_repo_contents'
        from /home/dependabot/dependabot-core/common/lib/dependabot/file_fetchers/base.rb:94:in `clone_repo_contents'
        from /home/dependabot/dependabot-core/common/lib/dependabot/file_fetchers/base.rb:131:in `load_cloned_file_if_present'
        from /home/dependabot/dependabot-core/common/lib/dependabot/file_fetchers/base.rb:152:in `fetch_file_from_host'
        from /home/dependabot/dependabot-core/common/lib/dependabot/config/file_fetcher.rb:32:in `block in fetch_files'
        from /home/dependabot/dependabot-core/common/lib/dependabot/config/file_fetcher.rb:28:in `each'
        from /home/dependabot/dependabot-core/common/lib/dependabot/config/file_fetcher.rb:28:in `fetch_files'
        from /home/dependabot/dependabot-core/common/lib/dependabot/file_fetchers/base.rb:75:in `files'
        from /home/dependabot/dependabot-core/common/lib/dependabot/config/file_fetcher.rb:20:in `config_file'
        from bin/dry-run.rb:510:in `<main>'
```
```
[dependabot-core-dev] ~/dependabot-core $ ls -ld ~/dependabot-core/tmp/
drwxr-xr-x 2 root root 4096 Jan 17 19:54 /home/dependabot/dependabot-core/tmp/
```
```
[dependabot-core-dev] ~/dependabot-core $ whoami
dependabot
```

**Comment by deivid-rodriguez** [comment]
Did you try rebuilding?

```
$ bin/docker-dev-shell --rebuild
```

**Comment by sparr** [comment]
I have removed the two directories owned by root, run the rebuild, and the directories are re-created, still owned by root.

**Comment by deivid-rodriguez** [comment]
Does this fix things?

```diff
diff --git a/bin/docker-dev-shell b/bin/docker-dev-shell
index d5b5e391f..90ceda6d4 100755
--- a/bin/docker-dev-shell
+++ b/bin/docker-dev-shell
@@ -101,6 +101,7 @@ fi
 echo "$(tput setaf 2)=> running docker development shell$(tput sgr0)"
 CODE_DIR="/home/dependabot/dependabot-core"
 touch .core-bash_history
+mkdir -p dry-run tmp
 docker run --rm -ti \
   -v "$(pwd)/.core-bash_history:/home/dependabot/.bash_history" \
   -v "$(pwd)/.rubocop.yml:$CODE_DIR/.rubocop.yml" \
```

**Comment by sparr** [comment]
Yes, that appears to resolve the issue.
