### ISSUE TITLE
Unit test failure present on `main`

### ISSUE THREAD

**Issue by jeffwidman** [dependabot/dependabot-core#6573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code improvement description

I can reproduce https://github.com/dependabot/dependabot-core/actions/runs/4069620621/jobs/7009563558 on `main`:
```ruby
Failures:

  1) Dependabot::NpmAndYarn::FileFetcher with .yarn data stored in git-lfs pulls files from lfs after cloning
     Failure/Error:
       expect(
         File.read(
           File.join(repo_contents_path, ".yarn", "releases", "yarn-3.2.4.cjs")
         )
       ).to start_with("#!/usr/bin/env node")

       expected "version [https://git-lfs.github.com/spec/v1\noid](https://git-lfs.github.com/spec/v1/noid) sha256:ca1a380d840c676152fbf8635a82d838113fe77e1665466699a4e106df4930d2\nsize 2194904\n" to start with "#!/usr/bin/env node"
     # ./spec/dependabot/npm_and_yarn/file_fetcher_spec.rb:85:in `block (3 levels) in <top (required)>'
     # /home/dependabot/common/spec/spec_helper.rb:63:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 28.5 seconds (files took 0.95993 seconds to load)
303 examples, 1 failure

Failed examples:

rspec ./spec/dependabot/npm_and_yarn/file_fetcher_spec.rb:82 # Dependabot::NpmAndYarn::FileFetcher with .yarn data stored in git-lfs pulls files from lfs after cloning

Randomized with seed 50820
```

**Comment by jeffwidman** [comment]
I've never seen it before today, and seen it a couple of times so far on PR's that are completely unrelated to this. Nothing we've merged today (or even yesterday for that matter) seem like they'd trigger it, so perhaps something changed under our feet?

**Comment by jeffwidman** [comment]
As explained in https://github.com/dependabot/dependabot-core/pull/6583#issuecomment-1416953105, this was a rate limiting issue with git LFS on our test fixture org. We got the quota bumped up from 1gb to 250gb, so this is fixed and shouldn't affect us for the forseeable future. More debugging details in:
* #6583
