### ISSUE TITLE
Runtime error on terraform updating a private github terraform module

### ISSUE THREAD

**Issue by mkemmerz** [dependabot/dependabot-core#6716]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

terraform

### Language version

1.3.9

### Manifest location and content before the Dependabot update

```
module "terraform_azure_loganalytics_module" {
  source  = "git::https://github.com/xxx-gh-org/terraform-azure-loganalytics-module.git?ref=tags%2F4.0.3"
  ...
}
```

### dependabot.yml content
```
version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/test"
    schedule:
      interval: "daily"
    target-branch: "main"
```

### Updated dependency

The dependency is an internal Terraform Module of an enterprise Github Organization. Dependabot has receives the permission on this repository. In this case the Terraform Module is not publicly available.

Stacktrace: 
```
updater | INFO <job_611807405> Starting update job for xxx-Group/xxx-dependabot-test
updater | INFO <job_611807405> Checking if terraform_azure_loganalytics_module::github::xxx-Group/terraform-azure-loganalytics-module::tags/4.0.3 4.0.3 needs updating
  proxy | 2023/02/23 09:28:21 [010] GET https://github.com:443/xxx-Group/terraform-azure-loganalytics-module.git/info/refs?service=git-upload-pack
  proxy | 2023/02/23 09:28:21 [010] * authenticating git server request (host: github.com)
  proxy | 2023/02/23 09:28:21 [010] 200 https://github.com:443/xxx-Group/terraform-azure-loganalytics-module.git/info/refs?service=git-upload-pack
updater | INFO <job_611807405> Latest version is 4.0.5
updater | INFO <job_611807405> Requirements to unlock own
updater | INFO <job_611807405> Requirements update strategy 
updater | INFO <job_611807405> Updating terraform_azure_loganalytics_module::github::xxx-Group/terraform-azure-loganalytics-module::tags/4.0.3 from 4.0.3 to 4.0.5
updater | I, [2023-02-23T09:28:21.209739 #7]  INFO -- sentry: ** [Raven] Sending event 5af9c231e65f4ab89b61c16f15077962 to Sentry
  proxy | 2023/02/23 09:28:21 [012] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/02/23 09:28:21 [012] 200 https://sentry.io:443/api/1451818/store/
updater | ERROR <job_611807405> Error processing terraform_azure_loganalytics_module::github::xxx-Group/terraform-azure-loganalytics-module::tags/4.0.3 (RuntimeError)
updater | ERROR <job_611807405> Content didn't change!
updater | ERROR <job_611807405> /home/dependabot/terraform/lib/dependabot/terraform/file_updater.rb:30:in `block in updated_dependency_files'
updater | ERROR <job_611807405> /home/dependabot/terraform/lib/dependabot/terraform/file_updater.rb:25:in `each'
updater | ERROR <job_611807405> /home/dependabot/terraform/lib/dependabot/terraform/file_updater.rb:25:in `updated_dependency_files'
updater | ERROR <job_611807405> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:739:in `generate_dependency_files_for'
updater | ERROR <job_611807405> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:303:in `check_and_create_pull_request'
updater | ERROR <job_611807405> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:101:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_611807405> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:77:in `block in run'
updater | ERROR <job_611807405> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:77:in `each'
updater | ERROR <job_611807405> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:77:in `run'
updater | ERROR <job_611807405> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:17:in `perform_job'
updater | ERROR <job_611807405> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:50:in `run'
updater | ERROR <job_611807405> bin/update_files.rb:23:in `<main>'
updater | INFO <job_611807405> Finished job processing
updater | INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | time="2023-02-23T09:28:22Z" level=info msg="task complete" container_id=job-611807405-updater exit_code=0 job_id=611807405 step=updater
```

### What you expected to see, versus what you actually saw

The dependecy of the Terraform module should be updated.

`ref=tags%2F4.0.3` => `ref=tags%2F4.0.4` or any higher version

Updated dependency:
```
module "terraform_azure_loganalytics_module" {
  source  = "git::https://github.com/xxx-gh-org/terraform-azure-loganalytics-module.git?ref=tags%2F4.0.4"
  ...
}
```

### Native package manager behavior

Just a guess but it could be that the regex is not covering this case: 
https://github.com/dependabot/dependabot-core/blob/0672e3b867bb1959d3b57dd8f543f932cc1febf0/terraform/lib/dependabot/terraform/file_updater.rb#L103
or
https://github.com/dependabot/dependabot-core/blob/0672e3b867bb1959d3b57dd8f543f932cc1febf0/terraform/lib/dependabot/terraform/file_updater.rb#L346

### Smallest manifest that reproduces the issue

Can't be reused as this is a private repo of an enterprise. The source URL should be enough to reproduce the issue I think.
```
module "terraform_azure_loganalytics_module" {
  source  = "git::https://github.com/xxx-gh-org/terraform-azure-loganalytics-module.git?ref=tags%2F4.0.3"
  ...
}
```

**Comment by mkemmerz** [comment]
I could verify that removing the "tags%2F" from the source fixes this issue:
`source  = "git::https://github.com/xxx-gh-org/terraform-azure-loganalytics-module.git?ref=4.0.4"`

**Comment by deivid-rodriguez** [comment]
It sound like you've mostly figured out where the problem lies, we just need to expand the regex to cover your use case?

**Comment by mkemmerz** [comment]
Yes, exactly. I don't think this task has a high priority as it is mostly an edge case on how people reference the modules.
