### ISSUE TITLE
Backslash in path causes npm update failures

### ISSUE THREAD

**Issue by mctofu** [dependabot/dependabot-core#6744]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### What you expected to see, versus what you actually saw

There's two issues related to a backslash in the filepath in `package.json`.

In one instance Dependabot removed a backslash which broke the `package.json`: https://github.com/nfriedly/node-unblocker/pull/218/files#diff-726ef79b870f218c9b9c1bffe0ff61ad0ea473b4677885d7d207270e73fe4ea5

I attempted to reproduce this but now get this failure instead:
```
updater | ERROR <job_613495639> Error processing qs (Errno::ENOENT)
updater | ERROR <job_613495639> No such file or directory @ rb_sysopen - "examples/whitelist/..\\../package.json"
updater | ERROR <job_613495639> /home/dependabot/common/lib/dependabot/file_updaters/vendor_updater.rb:39:in `read'
updater | ERROR <job_613495639> /home/dependabot/common/lib/dependabot/file_updaters/vendor_updater.rb:39:in `block (2 levels) in updated_vendor_cache_files'
updater | ERROR <job_613495639> /home/dependabot/common/lib/dependabot/file_updaters/vendor_updater.rb:30:in `map'
updater | ERROR <job_613495639> /home/dependabot/common/lib/dependabot/file_updaters/vendor_updater.rb:30:in `block in updated_vendor_cache_files'
updater | ERROR <job_613495639> /home/dependabot/common/lib/dependabot/file_updaters/vendor_updater.rb:20:in `chdir'
updater | ERROR <job_613495639> /home/dependabot/common/lib/dependabot/file_updaters/vendor_updater.rb:20:in `updated_vendor_cache_files'
updater | ERROR <job_613495639> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:64:in `vendor_updated_files'
updater | ERROR <job_613495639> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:57:in `updated_dependency_files'
updater | ERROR <job_613495639> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:739:in `generate_dependency_files_for'
updater | ERROR <job_613495639> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:303:in `check_and_create_pull_request'
updater | ERROR <job_613495639> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:101:in `check_and_create_pr_with_error_handling'
updater | ERROR <job_613495639> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:77:in `block in run'
updater | ERROR <job_613495639> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:77:in `each'
updater | ERROR <job_613495639> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:77:in `run'
updater | ERROR <job_613495639> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:17:in `perform_job'
updater | ERROR <job_613495639> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:50:in `run'
updater | ERROR <job_613495639> bin/update_files.rb:23:in `<main>'
updater | INFO <job_613495639> Finished job processing
```

### Native package manager behavior

I was able to successfully perform the update with the npm cli on Linux without any changes to the backslash. This indicates the problem may be specific to Dependabot.

Dependabot does work properly if the backslash in the path is replaced with a forward slash.

**Comment by GarryHurleyJr** [comment]
This is no longer reproducible, and was not affecting any other user.  Closing issue due to lack of feedback on frequency of issue.
