### ISSUE TITLE
Update error: Directory <poetry path dependency> does not exist

### ISSUE THREAD

**Issue by MatejKastak** [dependabot/dependabot-core#6927]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip (poetry)

### Package manager version

1.4.0

### Language version

Python 3.10

### Manifest location and content before the Dependabot update

https://github.com/MatejKastak/yls/blob/master/pyproject.toml

### dependabot.yml content

https://github.com/MatejKastak/yls/blob/master/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Hello and thanks for dependabot :slightly_smiling_face: 

I tried to integrate dependabot into new repository, where I have one main project and two sub-projects. Dependabot works well for the two sub-projects but it fails to update dependencies in the main project. I am working in my [fork](https://github.com/matejkastak/yls) of the original repository.

Relevant part of the logs:
```
updater | 2023/03/28 10:43:02 ERROR <job_634741690> Error processing pytest-asyncio (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/03/28 10:43:02 ERROR <job_634741690> Directory plugins/yls-yara does not exist
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:349:in `run_poetry_command'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:99:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/common/lib/dependabot/shared_helpers.rb:181:in `with_git_configured'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:91:in `block in fetch_latest_resolvable_version_string'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `block in in_a_temporary_directory'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `chdir'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_directory'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:90:in `fetch_latest_resolvable_version_string'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:62:in `latest_resolvable_version'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/python/lib/dependabot/python/update_checker.rb:42:in `latest_resolvable_version'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:260:in `preferred_version_resolvable_with_unlock?'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:252:in `numeric_version_can_update?'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:202:in `version_can_update?'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:282:in `requirements_to_unlock'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:90:in `check_and_create_pull_request'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:61:in `check_and_create_pr_with_error_handling'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:27:in `block in perform'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:27:in `each'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:27:in `perform'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:70:in `run'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:36:in `perform_job'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/03/28 10:43:02 ERROR <job_634741690> bin/update_files.rb:23:in `<main>'
```

It always fails with the `Directory .* does not exist` error message, even though locally the path dependencies work as expected. Plus they are also working in Github actions when testing the PRs for example.

I am not familiar with ruby and project architecture that much, but there seems to be additional information that we unfortunately don't see in the logs ([source_code](https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb#L351)).

I tried using relative paths, default paths (without `./` prefix) that poetry generated into pyproject.toml.
I tried to rename the directory from `pytest-yls` to `pytest_yls` to see if the dash is not problematic.
I tried to use completely different directory `plugins/yls-yara` (this is in logs above)

Can you point me into a right direction on how to debug this issue, please?

Hopefully, I am not missing something obvious and this will be useful for others.

**Comment by jeffwidman** [comment]
Thanks for asking for debugging pointers, rather than just asking us to figure it out.

I just rewrote the README earlier this week to try to clarify the debugging instructions: https://github.com/dependabot/dependabot-core#debugging-problems

If you spin through that, you should be able to reproduce the problems locally and also see any output from `poetry` and even drop debugger statements in at any point.

Does that help?
