### ISSUE TITLE
Grouped updates for npm transitive dependencies raise NoChangeErrors

### ISSUE THREAD

**Issue by Nishnha** [dependabot/dependabot-core#7238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### What you expected to see, versus what you actually saw

Grouped updates that involve npm transitive dependencies will sometimes raise a NoChangeError

```
2023/05/04 18:56:01 INFO Checking if @typescript-eslint/scope-manager 5.27.1 needs updating
2023/05/04 18:56:01 INFO Latest version is 5.59.2
2023/05/04 18:56:03 INFO Requirements to unlock own
2023/05/04 18:56:03 INFO Requirements update strategy widen_ranges
2023/05/04 18:56:03 INFO Updating @typescript-eslint/scope-manager from 5.27.1 to 5.59.1
2023/05/04 18:56:03 ERROR Error processing @typescript-eslint/scope-manager (Dependabot::NpmAndYarn::FileUpdater::NoChangeError)
2023/05/04 18:56:03 ERROR No files were updated!
2023/05/04 18:56:03 ERROR /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:45:in `updated_dependency_files'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:85:in `generate_dependency_files'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:36:in `run'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:25:in `create_from'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:70:in `create_change_for'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:33:in `block in compile_all_dependency_changes_for'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:23:in `each'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:23:in `compile_all_dependency_changes_for'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:78:in `block in run_grouped_dependency_updates'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:75:in `each'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:75:in `run_grouped_dependency_updates'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:43:in `perform'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:72:in `run'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
2023/05/04 18:56:03 ERROR /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
```

This error will also be shown as an `unknown_error` in the job summary. While these errors don't prevent a PR from being generated, they are unexpected since the updated lockfile should contain an updated version of the transitive dependency.

The cause is currently unknown, but there are transitive dependencies that successfully update without generating this error. It may be that a direct dependency (or other transitive dependency) that was updated earlier in the grouped update already contains an updated version of the erroring dependency, so the lockfile does not appear to change.

We should add a check to see if the transitive dependency is already up-to-date and skip over it if that is the case.

**Comment by Nishnha** [comment]
I set up https://github.com/dependabot/smoke-tests/pull/70 to test out a grouped update that contains a NoChangeError, but the diff for the job is so large that I can't view the PR job summary that lists the PRs created and the errors!

Either way, the fix shipped in https://github.com/dependabot/dependabot-core/pull/7276 should help prevent this error by now re-parsing all of the dependencies from all of the dependency files between each grouped update dependency update.

This also revealed a new bug (which I will file a separate issue for) where some dependencies are not being added to the `all_updated_dependencies` list in `GroupUpdateCreation` because their requirements haven't changed in the `package.json` file since the requirements listed there are wide enough to satisfy the updated version changed in the `package-lock.json`

We will probably need to add a separate check for dependencies unlocking `:all` requirements or just their `:own` when updating

**Comment by sQVe** [comment]
Is this issue fixed or not? 🤔 

I'm confused since I'm getting a lot of these errors as soon as I group any of my dependencies.

**Comment by deivid-rodriguez** [comment]
@sQVe The could be different root causes that result in this kind of error being raised. I recommend you report a separate issue explaining your problem, ideally with a link to a public repository where the issue can be reproduced.
