### ISSUE TITLE
Path dependencies not found if defined in `tool.poetry.group.dev.dependencies` of `pyproject.toml`

### ISSUE THREAD

**Issue by simensol** [dependabot/dependabot-core#7363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip (poetry)

### Package manager version

Poetry 1.4.2

### Language version

Python 3.11

### Manifest location and content before the Dependabot update

```/backend/pyproject.toml``` *not* working:

```yml
[tool.poetry]
name = "my-package"
version = "0.1.0"
description = ""
authors = ["..."]
readme = "README.md"

[tool.poetry.dependencies]
...

[tool.poetry.group.dev.dependencies]
my-package = { path = "packages/my_package", develop = true }
...
```

Working ```/backend/pyproject.toml```:

```yml
[tool.poetry]
name = "my-package"
version = "0.1.0"
description = ""
authors = ["..."]
readme = "README.md"

[tool.poetry.dependencies]
my-package = { path = "packages/my_package", develop = true }
...

[tool.poetry.group.dev.dependencies]
...
```

### dependabot.yml content

```yml
version: 2
updates:
    - package-ecosystem: "pip"
      directory: "/backend"
      open-pull-requests-limit: 1
      schedule:
          interval: "daily"
          time: "05:00"
          timezone: "Europe/Oslo"
      allow:
          - dependency-type: "all"
      commit-message:
          prefix: "pip backend prod"
          prefix-development: "pip backend dev"
          include: "scope"
```

### Updated dependency

`my-package`

### What you expected to see, versus what you actually saw

I expected Dependabot to successfully check for updates. Here is an anonymised and shortened Dependabot output when the `my-package` dependency is defined in `tool.poetry.group.dev.dependencies` of `pyproject.toml`:

```bash
  proxy | 2023/05/23 11:40:57 proxy starting, commit: d719b9b9871e853c5fd63bf3552f3f857d979f3c
  proxy | 2023/05/23 11:40:57 Listening (:1080)
updater | 2023-05-23T11:40:58.701485136 [666882095:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-05-23T11:41:00Z" level=info msg="guest starting" commit=8ab4a20db815b67034070152643b9878c12b051d
updater | time="2023-05-23T11:41:00Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=666882095 updater_timeout=45m0s updater_version=49704c16cb0893c0ab8c5f884471c324baf39b83-pip
updater | 2023/05/23 11:41:02 INFO Raven 3.1.2 ready to catch errors
updater | 2023/05/23 11:41:04 INFO <job_666882095> Starting job processing
  proxy | 2023/05/23 11:41:04 [002] GET https://api.github.com:443/repos/username/reproname
  proxy | 2023/05/23 11:41:04 [002] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:05 [002] 200 https://api.github.com:443/repos/username/reproname
  proxy | 2023/05/23 11:41:05 [004] GET https://api.github.com:443/repos/username/reproname/git/refs/heads/main
  proxy | 2023/05/23 11:41:05 [004] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:05 [004] 200 https://api.github.com:443/repos/username/reproname/git/refs/heads/main
  proxy | 2023/05/23 11:41:05 [006] GET https://api.github.com:443/repos/username/reproname/contents/backend?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [006] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:05 [006] 200 https://api.github.com:443/repos/username/reproname/contents/backend?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [008] GET https://api.github.com:443/repos/username/reproname/contents/backend/pyproject.toml?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [008] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:05 [008] 200 https://api.github.com:443/repos/username/reproname/contents/backend/pyproject.toml?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [010] GET https://api.github.com:443/repos/username/reproname/contents/backend/poetry.lock?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [010] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:05 [010] 200 https://api.github.com:443/repos/username/reproname/contents/backend/poetry.lock?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [012] GET https://api.github.com:443/repos/username/reproname/contents/backend/.media?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [012] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:05 [012] 200 https://api.github.com:443/repos/username/reproname/contents/backend/.media?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [014] GET https://api.github.com:443/repos/username/reproname/contents/backend/.vscode?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [014] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:05 [014] 200 https://api.github.com:443/repos/username/reproname/contents/backend/.vscode?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [016] GET https://api.github.com:443/repos/username/reproname/contents/backend/authorizations?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [016] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:05 [016] 200 https://api.github.com:443/repos/username/reproname/contents/backend/authorizations?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [018] GET https://api.github.com:443/repos/username/reproname/contents/backend/bin?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:05 [018] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:06 [018] 200 https://api.github.com:443/repos/username/reproname/contents/backend/bin?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [020] GET https://api.github.com:443/repos/username/reproname/contents/backend/claimrequests?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [020] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:06 [020] 200 https://api.github.com:443/repos/username/reproname/contents/backend/claimrequests?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [022] GET https://api.github.com:443/repos/username/reproname/contents/backend/claims?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [022] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:06 [022] 200 https://api.github.com:443/repos/username/reproname/contents/backend/claims?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [024] GET https://api.github.com:443/repos/username/reproname/contents/backend/config?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [024] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:06 [024] 200 https://api.github.com:443/repos/username/reproname/contents/backend/config?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [026] GET https://api.github.com:443/repos/username/reproname/contents/backend/creditors?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [026] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:06 [026] 200 https://api.github.com:443/repos/username/reproname/contents/backend/creditors?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [028] GET https://api.github.com:443/repos/username/reproname/contents/backend/manager?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [028] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:06 [028] 200 https://api.github.com:443/repos/username/reproname/contents/backend/manager?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [030] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [030] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:06 [030] 200 https://api.github.com:443/repos/username/reproname/contents/backend/packages?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [032] GET https://api.github.com:443/repos/username/reproname/contents/backend/tasks?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [032] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:06 [032] 200 https://api.github.com:443/repos/username/reproname/contents/backend/tasks?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [034] GET https://api.github.com:443/repos/username/reproname/contents/backend/typings?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:06 [034] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:06 [034] 200 https://api.github.com:443/repos/username/reproname/contents/backend/typings?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [036] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/mytools/setup.py?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [036] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:07 [036] 404 https://api.github.com:443/repos/username/reproname/contents/backend/packages/mytools/setup.py?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [038] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/mytools?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [038] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:07 [038] 200 https://api.github.com:443/repos/username/reproname/contents/backend/packages/mytools?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [040] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/mytools/pyproject.toml?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [040] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:07 [040] 200 https://api.github.com:443/repos/username/reproname/contents/backend/packages/mytools/pyproject.toml?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [042] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/mytools/setup.cfg?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [042] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:07 [042] 404 https://api.github.com:443/repos/username/reproname/contents/backend/packages/mytools/setup.cfg?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [044] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/sms/setup.py?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [044] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:07 [044] 404 https://api.github.com:443/repos/username/reproname/contents/backend/packages/sms/setup.py?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [046] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/sms?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [046] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:07 [046] 200 https://api.github.com:443/repos/username/reproname/contents/backend/packages/sms?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [048] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/sms/pyproject.toml?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [048] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:07 [048] 200 https://api.github.com:443/repos/username/reproname/contents/backend/packages/sms/pyproject.toml?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [050] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/sms/setup.cfg?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [050] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:07 [050] 404 https://api.github.com:443/repos/username/reproname/contents/backend/packages/sms/setup.cfg?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [052] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/dev_dependencies/setup.py?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:07 [052] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:08 [052] 404 https://api.github.com:443/repos/username/reproname/contents/backend/packages/dev_dependencies/setup.py?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:08 [054] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/dev_dependencies?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:08 [054] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:08 [054] 200 https://api.github.com:443/repos/username/reproname/contents/backend/packages/dev_dependencies?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:08 [056] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/dev_dependencies/pyproject.toml?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:08 [056] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:08 [056] 200 https://api.github.com:443/repos/username/reproname/contents/backend/packages/dev_dependencies/pyproject.toml?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:08 [058] GET https://api.github.com:443/repos/username/reproname/contents/backend/packages/dev_dependencies/setup.cfg?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:08 [058] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:08 [058] 404 https://api.github.com:443/repos/username/reproname/contents/backend/packages/dev_dependencies/setup.cfg?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:08 [060] GET https://api.github.com:443/repos/username/reproname/contents/?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
  proxy | 2023/05/23 11:41:08 [060] * authenticating github api request with token for api.github.com
  proxy | 2023/05/23 11:41:08 [060] 200 https://api.github.com:443/repos/username/reproname/contents/?ref=fb31a2963d76cf99a9e1ddea11c1adff53d370f7
updater | 2023/05/23 11:41:08 INFO <job_666882095> Finished job processing
updater | time="2023-05-23T11:41:08Z" level=info msg="task complete" container_id=job-666882095-file-fetcher exit_code=0 job_id=666882095 step=fetcher
updater | 2023/05/23 11:41:10 INFO Raven 3.1.2 ready to catch errors
updater | 2023/05/23 11:41:11 INFO <job_666882095> Starting job processing
updater | 2023/05/23 11:41:15 INFO <job_666882095> Starting update job for username/reproname
updater | 2023/05/23 11:41:15 INFO <job_666882095> Checking all dependencies for version updates...
updater | 2023/05/23 11:41:15 INFO <job_666882095> Checking if requests 2.30.0 needs updating
  proxy | 2023/05/23 11:41:16 [066] GET https://pypi.org:443/simple/requests/
  proxy | 2023/05/23 11:41:16 [066] 200 https://pypi.org:443/simple/requests/
updater | 2023/05/23 11:41:16 INFO <job_666882095> Latest version is 2.31.0
updater | 2023/05/23 11:41:28 INFO <job_666882095> Sending event 06d861a4fab7478186479c6e9a19584e to Sentry
  proxy | 2023/05/23 11:41:29 [068] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/05/23 11:41:29 [068] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/05/23 11:41:29 ERROR <job_666882095> Error processing requests (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/05/23 11:41:29 ERROR <job_666882095> Directory packages/my_package does not exist
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:349:in `run_poetry_command'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:99:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/shared_helpers.rb:181:in `with_git_configured'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:91:in `block in fetch_latest_resolvable_version_string'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `block in in_a_temporary_directory'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `chdir'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_directory'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:90:in `fetch_latest_resolvable_version_string'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:62:in `latest_resolvable_version'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker.rb:42:in `latest_resolvable_version'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:260:in `preferred_version_resolvable_with_unlock?'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:252:in `numeric_version_can_update?'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:202:in `version_can_update?'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:204:in `requirements_to_unlock'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:88:in `check_and_create_pull_request'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `check_and_create_pr_with_error_handling'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `block in perform'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `each'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `perform'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:72:in `run'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/05/23 11:41:29 ERROR <job_666882095> bin/update_files.rb:23:in `<main>'

...

updater | 2023/05/23 11:42:31 INFO <job_666882095> Checking if py-moneyed 2.0 needs updating
  proxy | 2023/05/23 11:42:32 [222] GET https://pypi.org:443/simple/py-moneyed/
  proxy | 2023/05/23 11:42:32 [222] 200 https://pypi.org:443/simple/py-moneyed/
updater | 2023/05/23 11:42:32 INFO <job_666882095> Latest version is 3.0
updater | 2023/05/23 11:42:44 INFO <job_666882095> Sending event 64aa3c870b494259902914747d3898d0 to Sentry
  proxy | 2023/05/23 11:42:44 [224] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/05/23 11:42:44 [224] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/05/23 11:42:44 ERROR <job_666882095> Error processing py-moneyed (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/05/23 11:42:44 ERROR <job_666882095> Directory packages/my_package does not exist
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:349:in `run_poetry_command'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:99:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/shared_helpers.rb:181:in `with_git_configured'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:91:in `block in fetch_latest_resolvable_version_string'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `block in in_a_temporary_directory'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `chdir'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_directory'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:90:in `fetch_latest_resolvable_version_string'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb:62:in `latest_resolvable_version'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/python/lib/dependabot/python/update_checker.rb:42:in `latest_resolvable_version'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:260:in `preferred_version_resolvable_with_unlock?'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:252:in `numeric_version_can_update?'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:202:in `version_can_update?'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:204:in `requirements_to_unlock'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:88:in `check_and_create_pull_request'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `check_and_create_pr_with_error_handling'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `block in perform'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `each'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:34:in `perform'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:72:in `run'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/05/23 11:42:44 ERROR <job_666882095> bin/update_files.rb:23:in `<main>'
updater | 2023/05/23 11:42:44 INFO <job_666882095> Checking if tqdm 4.65.0 needs updating
  proxy | 2023/05/23 11:42:44 [228] GET https://pypi.org:443/simple/tqdm/
  proxy | 2023/05/23 11:42:44 [228] 200 https://pypi.org:443/simple/tqdm/
updater | 2023/05/23 11:42:45 INFO <job_666882095> Latest version is 4.65.0
updater | 2023/05/23 11:42:45 INFO <job_666882095> No update needed for tqdm 4.65.0
updater | 2023/05/23 11:42:45 INFO <job_666882095> Checking if djangorestframework-types 0.8.0 needs updating
  proxy | 2023/05/23 11:42:45 [230] GET https://pypi.org:443/simple/djangorestframework-types/
  proxy | 2023/05/23 11:42:45 [230] 200 https://pypi.org:443/simple/djangorestframework-types/

...

updater | 2023/05/23 11:42:52 INFO <job_666882095> Finished job processing
updater | 2023/05/23 11:42:52 INFO Results:
updater | Dependabot encountered '3' error(s) during execution, please check the logs for more details.
updater | +-----------------------------------+
updater | |   Dependencies failed to update   |
updater | +-------------------+---------------+
updater | | requests          | unknown_error |
updater | | typing-extensions | unknown_error |
updater | | py-moneyed        | unknown_error |
updater | +-------------------+---------------+
updater | time="2023-05-23T11:42:52Z" level=info msg="task complete" container_id=job-666882095-updater exit_code=0 job_id=666882095 step=updater
```

### Native package manager behavior

Poetry behavior when the `my-package` dependency is defined in `tool.poetry.group.dev.dependencies` of `pyproject.toml`:

```bash
poetry update
Updating dependencies
Resolving dependencies... (3.4s)

Writing lock file

Package operations: 0 installs, 2 updates, 0 removals

  • Updating requests (2.30.0 -> 2.31.0)
  • Updating typing-extensions (4.5.0 -> 4.6.0)
```

**Comment by pavera** [comment]
It appears poetry does some verification of path based dev dependencies when config options are set. The error is being raised when we call `poetry config experimental.system-git-client true` [here](https://github.com/dependabot/dependabot-core/blob/main/python/lib/dependabot/python/update_checker/poetry_version_resolver.rb#LL99C50-L99C99). Dependabot does not currently clone full python repos, hence the relative path not existing. I believe we'd need to start cloning the full repo to start down the path to supporting path based dependencies.

**Comment by simensol** [comment]
Thanks for investigating the bug, @pavera. Then I guess the only workaround until this is fixed is to list all path dependencies in the `tool.poetry.dependencies` section of `pyproject.toml`?

**Comment by lg-kialo** [comment]
I think this is the same as #6927.
Also, it seems like in versions of `poetry` >=1.4.0, which use `poetry-core` >= 1.5.1 (the error originates from `poetry-core`), the missing directory just generates a warning an exits with code 0, rather than causing an unhandled exception and exit code 1.
So my hopes for getting #7350 merged soon are high :)
