### ISSUE TITLE
[Cargo] failed to load manifest for workspace member: No such file or directory

### ISSUE THREAD

**Issue by FirelightFlagboy** [dependabot/dependabot-core#7545]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

cargo

### Package manager version

1.68.0

### Language version

1.68.0

### Manifest location and content before the Dependabot update

```
Cargo.toml
bindings/android/libparsec/rust/Cargo.toml
bindings/electron/Cargo.toml
bindings/web/Cargo.toml
libparsec/Cargo.toml
libparsec/crates/client/Cargo.toml
libparsec/crates/client_connection/Cargo.toml
libparsec/crates/client_high_level_api/Cargo.toml
libparsec/crates/crypto/Cargo.toml
libparsec/crates/platform_async/Cargo.toml
libparsec/crates/platform_device_loader/Cargo.toml
libparsec/crates/platform_http_proxy/Cargo.toml
libparsec/crates/platform_storage/Cargo.toml
libparsec/crates/protocol/Cargo.toml
libparsec/crates/serialization_format/Cargo.toml
libparsec/crates/testbed/Cargo.toml
libparsec/crates/tests_fixtures/Cargo.toml
libparsec/crates/tests_macros/Cargo.toml
libparsec/crates/types/Cargo.toml
server/Cargo.toml
```

All those manifests can be found on the public repo <https://github.com/Scille/parsec-cloud>

### dependabot.yml content

[.github/dependabot.yml](https://github.com/Scille/parsec-cloud/blob/0e7c74f76d74998857d7bd39266f700fa1a3cb7b/.github/dependabot.yml)

### What you expected to see, versus what you actually saw

I expected `dependabot` to be able to update our dependencies without an error.

Instead I have this error message that appear multiple times in the log `dependabot.log`:

<details>

<summary><code>error: failed to load manifest for workspace member `/home/dependabot/dependabot-updater/dependabot_tmp_dir/server`</code></summary>

```txt
updater | 2023/07/11 07:30:36 ERROR <job_691982143> Error processing diesel (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/07/11 07:30:36 ERROR <job_691982143> error: failed to load manifest for workspace member `/home/dependabot/dependabot-updater/dependabot_tmp_dir/server`
updater | 
updater | Caused by:
updater |   failed to load manifest for dependency `libparsec`
updater | 
updater | Caused by:
updater |   failed to load manifest for dependency `libparsec_client_high_level_api`
updater | 
updater | Caused by:
updater |   failed to load manifest for dependency `libparsec_platform_async`
updater | 
updater | Caused by:
updater |   failed to load manifest for dependency `libparsec_tests_fixtures`
updater | 
updater | Caused by:
updater |   failed to load manifest for dependency `libparsec_client_connection`
updater | 
updater | Caused by:
updater |   failed to load manifest for dependency `libparsec_platform_http_proxy`
updater | 
updater | Caused by:
updater |   failed to read `/home/dependabot/dependabot-updater/dependabot_tmp_dir/libparsec/crates/platform_http_proxy/Cargo.toml`
updater | 
updater | Caused by:
updater |   No such file or directory (os error 2)
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:152:in `run_cargo_command'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:136:in `run_cargo_update_command'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:306:in `block (2 levels) in original_requirements_resolvable?'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:187:in `with_git_configured'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:305:in `block in original_requirements_resolvable?'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:55:in `block in in_a_temporary_directory'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:55:in `chdir'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/common/lib/dependabot/shared_helpers.rb:55:in `in_a_temporary_directory'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:302:in `original_requirements_resolvable?'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:297:in `resolvability_error?'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:244:in `handle_cargo_errors'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:58:in `rescue in fetch_latest_resolvable_version'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:40:in `fetch_latest_resolvable_version'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/version_resolver.rb:32:in `latest_resolvable_version'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker.rb:219:in `fetch_latest_resolvable_version'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/cargo/lib/dependabot/cargo/update_checker.rb:41:in `latest_resolvable_version'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:74:in `preferred_resolvable_version'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:260:in `preferred_version_resolvable_with_unlock?'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:252:in `numeric_version_can_update?'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:202:in `version_can_update?'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:44:in `can_update?'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:208:in `requirements_to_unlock'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:128:in `compile_updates_for'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:40:in `block in compile_all_dependency_changes_for'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:28:in `each'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:28:in `compile_all_dependency_changes_for'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:41:in `perform'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:97:in `run_update_for'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:82:in `block in run_grouped_dependency_updates'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:73:in `each'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:73:in `run_grouped_dependency_updates'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:41:in `perform'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:62:in `run'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:38:in `perform_job'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/07/11 07:30:36 ERROR <job_691982143> bin/update_files.rb:23:in `<main>'
```

</details>

That error is strange, because on my side the member `server` can be verified using the following command without any problem :thinking: :

```shell
cargo check -p parsec
```

> The package on the workspace member `server` is called `parsec` 

### Native package manager behavior

<details>

<summary>Using the command <code>cargo update --verbose</code></summary>

```txt
    Updating crates.io index
    Updating addr2line v0.19.0 -> v0.20.0
    Updating aead v0.5.1 -> v0.5.2
    Updating aho-corasick v1.0.1 -> v1.0.2
    Updating backtrace v0.3.67 -> v0.3.68
    Updating base64ct v1.5.3 -> v1.6.0
      Adding bitflags v2.3.3
    Removing block-buffer v0.7.3
    Removing block-buffer v0.10.2
      Adding block-buffer v0.10.4
    Removing block-padding v0.1.5
    Updating bumpalo v3.12.0 -> v3.13.0
    Removing byte-tools v0.3.1
    Updating cc v1.0.73 -> v1.0.79
    Updating chacha20 v0.9.0 -> v0.9.1
    Updating cipher v0.4.3 -> v0.4.4
    Updating combine v4.6.4 -> v4.6.6
    Updating const-oid v0.9.1 -> v0.9.4
    Updating core-foundation-sys v0.8.3 -> v0.8.4
    Updating cpufeatures v0.2.2 -> v0.2.9
    Removing ctor v0.1.22
    Updating curve25519-dalek v4.0.0-rc.2 -> v4.0.0-rc.3
      Adding curve25519-dalek-derive v0.1.0
    Updating darling v0.14.1 -> v0.20.1
    Updating darling_core v0.14.1 -> v0.20.1
    Updating darling_macro v0.14.1 -> v0.20.1
    Updating diesel v2.0.3 -> v2.1.0
    Updating diesel_derives v2.0.2 -> v2.1.0
      Adding diesel_table_macro_syntax v0.1.0
    Updating diff v0.1.12 -> v0.1.13
    Removing digest v0.8.1
    Removing digest v0.10.6
      Adding digest v0.10.7
    Updating ed25519 v1.5.2 -> v1.5.3
    Updating either v1.7.0 -> v1.8.1
    Updating encoding_rs v0.8.31 -> v0.8.32
    Removing errno v0.2.8
    Removing fake-simd v0.1.2
    Updating fastrand v1.7.0 -> v1.9.0
    Updating form_urlencoded v1.1.0 -> v1.2.0
    Updating futures-lite v1.12.0 -> v1.13.0
    Removing generic-array v0.12.4
    Updating getrandom v0.2.6 -> v0.2.10
    Removing ghost v0.1.9
    Updating gimli v0.27.2 -> v0.27.3
    Updating h2 v0.3.17 -> v0.3.20
    Updating hashbrown v0.12.1 -> v0.12.3
    Removing hermit-abi v0.1.19
    Removing hermit-abi v0.3.1
      Adding hermit-abi v0.3.2
    Updating http v0.2.8 -> v0.2.9
    Updating hyper v0.14.26 -> v0.14.27
    Updating iana-time-zone v0.1.47 -> v0.1.57
      Adding iana-time-zone-haiku v0.1.2
    Updating idna v0.3.0 -> v0.4.0
    Updating indexmap v1.9.1 -> v1.9.3
    Updating inventory v0.3.6 -> v0.3.8
    Updating io-lifetimes v1.0.3 -> v1.0.11
    Updating ipnet v2.5.0 -> v2.8.0
    Updating is-terminal v0.4.7 -> v0.4.9
    Updating itoa v1.0.2 -> v1.0.8
    Updating js-sys v0.3.63 -> v0.3.64
    Updating libc v0.2.140 -> v0.2.147
    Removing libm v0.1.4
    Removing libm v0.2.6
      Adding libm v0.2.7
    Updating linux-raw-sys v0.1.3 -> v0.4.3
    Updating lock_api v0.4.7 -> v0.4.10
    Updating log v0.4.17 -> v0.4.19
    Removing maplit v1.0.2
    Updating mime v0.3.16 -> v0.3.17
    Updating mini-internal v0.1.30 -> v0.1.31
    Updating miniserde v0.1.30 -> v0.1.31
    Removing miniz_oxide v0.6.2
    Updating mio v0.8.4 -> v0.8.8
    Updating native-tls v0.2.10 -> v0.2.11
    Updating num-bigint-dig v0.8.2 -> v0.8.4
    Updating num_cpus v1.13.1 -> v1.16.0
    Removing num_threads v0.1.6
    Updating object v0.30.3 -> v0.31.1
    Updating once_cell v1.17.1 -> v1.18.0
    Removing opaque-debug v0.2.3
    Updating openssl-macros v0.1.0 -> v0.1.1
    Updating openssl-src v111.25.0+1.1.1t -> v111.26.0+1.1.1u
    Removing output_vt100 v0.1.3
    Removing packed_simd_2 v0.3.8
    Updating parking v2.0.0 -> v2.1.0
    Updating parking_lot v0.12.0 -> v0.12.1
    Updating parking_lot_core v0.9.3 -> v0.9.8
    Updating paste v1.0.12 -> v1.0.13
    Updating percent-encoding v2.2.0 -> v2.3.0
    Updating pest v2.1.3 -> v2.7.0
    Updating pest_derive v2.1.0 -> v2.7.0
    Updating pest_generator v2.1.3 -> v2.7.0
    Updating pest_meta v2.1.3 -> v2.7.0
    Updating pin-project v1.0.10 -> v1.1.2
    Updating pin-project-internal v1.0.10 -> v1.1.2
    Updating pin-project-lite v0.2.9 -> v0.2.10
    Updating pkg-config v0.3.25 -> v0.3.27
    Updating ppv-lite86 v0.2.16 -> v0.2.17
    Updating pretty_assertions v1.3.0 -> v1.4.0
    Removing proc-macro-error v1.0.4
    Removing proc-macro-error-attr v1.0.4
    Updating proc-macro2 v1.0.56 -> v1.0.64
    Updating quote v1.0.28 -> v1.0.29
    Updating redox_syscall v0.2.13 -> v0.3.5
    Updating regex v1.8.4 -> v1.9.1
      Adding regex-automata v0.3.2
    Updating regex-syntax v0.7.2 -> v0.7.4
    Updating reqwest v0.11.17 -> v0.11.18
    Removing rustix v0.36.4
    Removing rustix v0.37.7
      Adding rustix v0.37.23
      Adding rustix v0.38.3
    Updating ryu v1.0.10 -> v1.0.14
    Updating schannel v0.1.20 -> v0.1.22
    Updating scoped-tls v1.0.0 -> v1.0.1
    Updating security-framework v2.6.1 -> v2.9.1
    Updating security-framework-sys v2.6.1 -> v2.9.0
    Updating semver v1.0.9 -> v1.0.17
    Updating serde v1.0.164 -> v1.0.171
    Updating serde_bytes v0.11.9 -> v0.11.11
    Updating serde_derive v1.0.164 -> v1.0.171
    Updating serde_json v1.0.96 -> v1.0.100
    Updating serde_test v1.0.159 -> v1.0.171
    Updating serde_with v2.3.2 -> v2.3.3
    Updating serde_with_macros v2.3.2 -> v2.3.3
    Removing sha-1 v0.8.2
    Updating sha2 v0.10.6 -> v0.10.7
    Updating signal-hook-registry v1.4.0 -> v1.4.1
    Updating slab v0.4.6 -> v0.4.8
    Updating smallvec v1.10.0 -> v1.11.0
    Updating spin v0.9.3 -> v0.9.8
    Updating subtle v2.4.1 -> v2.5.0
    Updating syn v2.0.13 -> v2.0.25
    Updating syn-mid v0.5.3 -> v0.5.4
    Removing synstructure v0.12.6
    Updating target-lexicon v0.12.7 -> v0.12.8
    Updating tempfile v3.4.0 -> v3.6.0
    Updating termcolor v1.1.3 -> v1.2.0
    Updating thiserror v1.0.40 -> v1.0.43
    Updating thiserror-impl v1.0.40 -> v1.0.43
    Removing time v0.1.44
    Removing time v0.3.14
      Adding time v0.1.45
      Adding time v0.3.23
      Adding time-core v0.1.1
      Adding time-macros v0.2.10
    Updating tinyvec_macros v0.1.0 -> v0.1.1
    Updating tokio v1.28.1 -> v1.29.1
    Updating tokio-native-tls v0.3.0 -> v0.3.1
    Updating tokio-util v0.7.2 -> v0.7.8
    Updating tower-service v0.3.1 -> v0.3.2
    Updating tracing v0.1.34 -> v0.1.37
    Removing tracing-attributes v0.1.21
    Updating tracing-core v0.1.26 -> v0.1.31
    Updating try-lock v0.2.3 -> v0.2.4
    Updating typenum v1.15.0 -> v1.16.0
    Updating ucd-trie v0.1.4 -> v0.1.6
    Updating unicode-bidi v0.3.8 -> v0.3.13
    Updating unicode-ident v1.0.5 -> v1.0.10
    Removing unicode-xid v0.2.3
    Updating universal-hash v0.5.0 -> v0.5.1
    Updating url v2.3.1 -> v2.4.0
    Updating uuid v1.3.0 -> v1.4.0
    Updating walkdir v2.3.2 -> v2.3.3
    Updating want v0.3.0 -> v0.3.1
    Updating wasm-bindgen v0.2.86 -> v0.2.87
    Updating wasm-bindgen-backend v0.2.86 -> v0.2.87
    Updating wasm-bindgen-futures v0.4.33 -> v0.4.37
    Updating wasm-bindgen-macro v0.2.86 -> v0.2.87
    Updating wasm-bindgen-macro-support v0.2.86 -> v0.2.87
    Updating wasm-bindgen-shared v0.2.86 -> v0.2.87
    Updating wasm-bindgen-test v0.3.33 -> v0.3.37
    Updating wasm-bindgen-test-macro v0.3.33 -> v0.3.37
    Updating web-sys v0.3.63 -> v0.3.64
      Adding windows v0.48.0
    Removing windows-sys v0.36.1
    Removing windows-sys v0.42.0
    Updating windows-targets v0.48.0 -> v0.48.1
    Removing windows_aarch64_msvc v0.36.1
    Removing windows_i686_gnu v0.36.1
    Removing windows_i686_msvc v0.36.1
    Removing windows_x86_64_gnu v0.36.1
    Removing windows_x86_64_msvc v0.36.1
    Updating x25519-dalek v2.0.0-rc.2 -> v2.0.0-rc.3
    Updating xsalsa20poly1305 v0.9.0 -> v0.9.1
    Updating zeroize_derive v1.3.2 -> v1.4.2
```

</details>

### Images of the diff or a link to the PR, issue, or logs

The log of `dependabot`: [dependabot.log](https://github.com/dependabot/dependabot-core/files/12012497/dependabot.log)

`dependabot` stopped working when we merge the PR Scille/parsec-cloud#4704

**Comment by FirelightFlagboy** [comment]
Fixed by #7649
