### ISSUE TITLE
pnpm-lock.yaml not parseable (Dependabot::DependencyFileNotParseable)

### ISSUE THREAD

**Issue by titouan-joseph** [dependabot/dependabot-core#7584]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pnpm

### Package manager version

8.6.9

### Language version

Node v20.4.0

### Manifest location and content before the Dependabot update

I use the dependabot-script with local update version (`"dependabot-omnibus", "~> 0.221.0"`)
I try to run with theses env var :
```bash
GITHUB_ACCESS_TOKEN=<TOKEN>
GITLAB_ACCESS_TOKEN=<TOKEN>
PACKAGE_MANAGER=npm_and_yarn
PROJECT_PATH=titouan-joseph/overbookd
```
Link of project [here](https://gitlab.com/titouan-joseph/overbookd)

Link of the forked dependabot-script [here](https://gitlab.com/24-heures-insa/dependabot/-/tree/v0.221.0?ref_type=heads) in branch `v0.221.0`

### What you expected to see, versus what you actually saw

Error 

```bash
Fetching npm_and_yarn dependency files for titouan-joseph/overbookd
Parsing dependencies information
/home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb:23:in `rescue in block in parsed': /pnpm-lock.yaml not parseable (Dependabot::DependencyFileNotParseable)
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb:15:in `block in parsed'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:55:in `block in in_a_temporary_directory'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:55:in `chdir'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:55:in `in_a_temporary_directory'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb:14:in `parsed'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb:55:in `details'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb:39:in `block in lockfile_details'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb:38:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb:38:in `lockfile_details'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:93:in `build_dependency'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:71:in `block (3 levels) in manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:67:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:67:in `block (2 levels) in manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:65:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:65:in `block in manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:59:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:59:in `manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:37:in `parse'
        from ./generic-update-script.rb:178:in `<main>'
/home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:138:in `rescue in run_helper_subprocess': Dependabot::SharedHelpers::HelperSubprocessFailed
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:84:in `run_helper_subprocess'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb:17:in `block in parsed'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:55:in `block in in_a_temporary_directory'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:55:in `chdir'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:55:in `in_a_temporary_directory'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb:14:in `parsed'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb:55:in `details'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb:39:in `block in lockfile_details'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb:38:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb:38:in `lockfile_details'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:93:in `build_dependency'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:71:in `block (3 levels) in manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:67:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:67:in `block (2 levels) in manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:65:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:65:in `block in manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:59:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:59:in `manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:37:in `parse'
        from ./generic-update-script.rb:178:in `<main>'
/usr/local/lib/ruby/3.1.0/json/common.rb:216:in `parse': 859: unexpected token at '' (JSON::ParserError)
        from /usr/local/lib/ruby/3.1.0/json/common.rb:216:in `parse'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:128:in `run_helper_subprocess'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb:17:in `block in parsed'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:55:in `block in in_a_temporary_directory'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:55:in `chdir'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.221.0/lib/dependabot/shared_helpers.rb:55:in `in_a_temporary_directory'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb:14:in `parsed'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/pnpm_lock.rb:55:in `details'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb:39:in `block in lockfile_details'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb:38:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser/lockfile_parser.rb:38:in `lockfile_details'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:93:in `build_dependency'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:71:in `block (3 levels) in manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:67:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:67:in `block (2 levels) in manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:65:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:65:in `block in manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:59:in `each'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:59:in `manifest_dependencies'
        from /home/dependabot/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-npm_and_yarn-0.221.0/lib/dependabot/npm_and_yarn/file_parser.rb:37:in `parse'
        from ./generic-update-script.rb:178:in `<main>'
```

**Comment by mburumaxwell** [comment]
This is likely because the helpers for required for pnpm are missing. The docker image (ghcr.io/dependabot/dependabot-updater-npm) contains them. It looks like you are using the scripts (https://github.com/dependabot/dependabot-script) repo but it still hasn't been upgraded to use an image per ecosystem.

**Comment by titouan-joseph** [comment]
Ok thanks !
