### ISSUE TITLE
Swift: Dependabot encountered an unknown error when using scp-style URIs

### ISSUE THREAD

**Issue by MarcoEidinger** [dependabot/dependabot-core#7709]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

swift

### Manifest location and content before the Dependabot update

https://github.com/MarcoEidinger/swift-package-monitored-by-dependabot/blob/main/Package.swift

https://github.com/MarcoEidinger/swift-package-monitored-by-dependabot/blob/main/Package.resolved

### dependabot.yml content

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "swift" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
```

Source: https://github.com/MarcoEidinger/swift-package-monitored-by-dependabot/blob/main/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Expected that Dependabot will create a pull request to update dependency but I see an error "Dependabot failed to update your dependencies because an unexpected error occurred"

<img width="1292" alt="Screenshot 2023-08-03 at 6 52 47 AM" src="https://github.com/dependabot/dependabot-core/assets/4176826/376b0023-34e4-40ce-b24a-805ad19cc949">

<img width="1278" alt="Screenshot 2023-08-03 at 6 52 39 AM" src="https://github.com/dependabot/dependabot-core/assets/4176826/1de288fb-f9b8-4271-bd1d-641c7ed4f0a0">

### Native package manager behavior

`swift package resolve` results in `Working copy of git@github.com:MarcoEidinger/DummySwiftPackage.git resolved at 1.0.2`

### Images of the diff or a link to the PR, issue, or logs

```
 proxy | 2023/08/03 13:40:12 proxy starting, commit: 8aba72d0d1eb8980902a2f77186864557052e473
  proxy | 2023/08/03 13:40:12 Listening (:1080)
updater | 2023-08-03T13:40:13.898934346 [704669287:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-08-03T13:40:16Z" level=info msg="guest starting" commit=756d581f6429d760b4a66024eab17c42362b28e1
updater | time="2023-08-03T13:40:16Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=704669287 updater_timeout=45m0s updater_version=5330c5d80849b587c37da86c644681ce81e8edac-swift
updater | 2023/08/03 13:40:18 INFO Raven 3.1.2 ready to catch errors
updater | 2023/08/03 13:40:19 INFO <job_704669287> Starting job processing
  proxy | 2023/08/03 13:40:20 [002] GET https://github.com:443/MarcoEidinger/swift-package-monitored-by-dependabot/info/refs?service=git-upload-pack
  proxy | 2023/08/03 13:40:20 [002] * authenticating git server request (host: github.com)
  proxy | 2023/08/03 13:40:20 [002] 200 https://github.com:443/MarcoEidinger/swift-package-monitored-by-dependabot/info/refs?service=git-upload-pack
  proxy | 2023/08/03 13:40:20 [004] POST https://github.com:443/MarcoEidinger/swift-package-monitored-by-dependabot/git-upload-pack
  proxy | 2023/08/03 13:40:20 [004] * authenticating git server request (host: github.com)
  proxy | 2023/08/03 13:40:20 [004] 200 https://github.com:443/MarcoEidinger/swift-package-monitored-by-dependabot/git-upload-pack
  proxy | 2023/08/03 13:40:20 [006] POST https://github.com:443/MarcoEidinger/swift-package-monitored-by-dependabot/git-upload-pack
  proxy | 2023/08/03 13:40:20 [006] * authenticating git server request (host: github.com)
  proxy | 2023/08/03 13:40:20 [006] 200 https://github.com:443/MarcoEidinger/swift-package-monitored-by-dependabot/git-upload-pack
updater | 2023/08/03 13:40:20 INFO <job_704669287> Finished job processing
updater | time="2023-08-03T13:40:20Z" level=info msg="task complete" container_id=job-704669287-file-fetcher exit_code=0 job_id=704669287 step=fetcher
updater | 2023/08/03 13:40:22 INFO Raven 3.1.2 ready to catch errors
updater | 2023/08/03 13:40:23 INFO <job_704669287> Starting job processing
  proxy | 2023/08/03 13:40:25 [008] GET https://github.com:443/MarcoEidinger/DummySwiftPackage.git/info/refs?service=git-upload-pack
  proxy | 2023/08/03 13:40:25 [008] * authenticating git server request (host: github.com)
  proxy | 2023/08/03 13:40:25 [008] 200 https://github.com:443/MarcoEidinger/DummySwiftPackage.git/info/refs?service=git-upload-pack
  proxy | 2023/08/03 13:40:25 [010] POST https://github.com:443/MarcoEidinger/DummySwiftPackage.git/git-upload-pack
  proxy | 2023/08/03 13:40:25 [010] * authenticating git server request (host: github.com)
  proxy | 2023/08/03 13:40:25 [010] 200 https://github.com:443/MarcoEidinger/DummySwiftPackage.git/git-upload-pack
updater | 2023/08/03 13:40:26 ERROR <job_704669287> bad URI(is not URI?): "git@github.com:marcoeidinger/dummyswiftpackage.git"
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /usr/local/lib/ruby/3.1.0/uri/rfc3986_parser.rb:66:in `split'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /usr/local/lib/ruby/3.1.0/uri/rfc3986_parser.rb:71:in `parse'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /usr/local/lib/ruby/3.1.0/uri/common.rb:193:in `parse'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:72:in `normalize'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:53:in `all_dependencies'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:47:in `block in subdependencies'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:47:in `each'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:47:in `flat_map'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:47:in `subdependencies'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:24:in `block (2 levels) in parse'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/common/lib/dependabot/shared_helpers.rb:187:in `with_git_configured'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:23:in `block in parse'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/common/lib/dependabot/shared_helpers.rb:41:in `block in in_a_temporary_repo_directory'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/common/lib/dependabot/shared_helpers.rb:41:in `chdir'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/common/lib/dependabot/shared_helpers.rb:41:in `in_a_temporary_repo_directory'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/swift/lib/dependabot/swift/file_parser/dependency_parser.rb:20:in `parse'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/swift/lib/dependabot/swift/file_parser.rb:17:in `parse'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:97:in `parse_files!'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:86:in `initialize'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:21:in `new'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:21:in `create_from_job_definition'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:16:in `perform_job'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/08/03 13:40:26 ERROR <job_704669287> bin/update_files.rb:23:in `<main>'
updater | 2023/08/03 13:40:26 INFO <job_704669287> Sending event 00d9d39f2705432c8c9aaa7be9e4ecab to Sentry
  proxy | 2023/08/03 13:40:26 [012] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/08/03 13:40:26 [012] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/08/03 13:40:26 INFO <job_704669287> Finished job processing
updater | 2023/08/03 13:40:26 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------+
updater | |    Errors     |
updater | +---------------+
updater | | unknown_error |
updater | +---------------+
updater | time="2023-08-03T13:40:26Z" level=info msg="task complete" container_id=job-704669287-updater exit_code=0 job_id=704669287 step=updater
```

### Smallest manifest that reproduces the issue

Use https://github.com/MarcoEidinger/swift-package-monitored-by-dependabot

**Comment by deivid-rodriguez** [comment]
Thanks for the report!

It seems related to scp-style URIs, @mctofu actually warned me about this, but I forgot to follow up on it! I'll fix it.

For now you can probably workaround the issue by using an `https://` URI in your `Package.swift` file instead.

**Comment by deivid-rodriguez** [comment]
Did you use `https://github.com/marcoeidinger/dummyswiftpackage.git`?

**Comment by MarcoEidinger** [comment]
Found the issue. Changing `Package.swif`t is not enough but also https URI needs to be used in `Package.resolved`. Interestingly SPM seems to change that so `swift package resolve` does not do that.

I setup a new example repo and pull request was created (https://github.com/MarcoEidinger/swift-package-monitored-by-dependabot-https/pull/1). Interestingly a pull request was opened to update to next major version while `swift package update` would bump it up to next minor version and honor package version requirements. I consider this a bug.
@deivid-rodriguez Should I create a new issue or is the behavior intentional?

**Comment by deivid-rodriguez** [comment]
So, your expectation is that only the `Package.resolved` file was updated and the `Package.swift` file was left unchanged?

If that's it, that'll be available once we add support for [versioning-strategies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy).

**Comment by MarcoEidinger** [comment]
The current Depandabot logic for Swift is different than SPM.

For

```
dependencies: [.package(url: "https://github.com/MarcoEidinger/DummySwiftPackage.git", .upToNextMajor(from: "1.0.0"))
```

Swift package manager will update `Package.resolved` only to uptake patches and minor releases.

I like the Depandabot logic to offer bumping up to next major version including the necessary `Package.swift` file change but it was unexpected.

> If that's it, that'll be available once we add support for [versioning-strategies](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#versioning-strategy).

Yeah, multiple versioning strategies make sense. If that's on the roadmap then I don't have to create an issue

**Comment by deivid-rodriguez** [comment]
I see. It's definitely on the roadmap, and I already have it implemented, I just need to prepare a PR. But let me create an issue about it, since I may forget.
