### ISSUE TITLE
Updating dependencies fails with "Dependabot encountered an unknown error"

### ISSUE THREAD

**Issue by xmatthias** [dependabot/dependabot-core#7855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

python

### Package manager version

pip

### dependabot.yml content

https://github.com/freqtrade/freqtrade/blob/develop/.github/dependabot.yml

### What you expected to see, versus what you actually saw

Dependabot should not fail, but instead update dependencies as it did last week.

The update logic itself is using github actions - so i don't think there's much to intervene for me.

### Images of the diff or a link to the PR, issue, or logs

![image](https://github.com/dependabot/dependabot-core/assets/5024695/c7fa6881-0bf1-4df1-8808-b991be1763a8)

```
  proxy | 2023/08/21 04:39:15 proxy starting, commit: 7a5d8c20c9a94f571abb6857bf47b26103757412
  proxy | 2023/08/21 04:39:15 Listening (:1080)
updater | 2023-08-21T04:39:15.975255330 [711496623:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-08-21T04:39:18Z" level=info msg="guest starting" commit=b17e36388dd0b708be7e6a27f7422f1da5fccfd8
updater | time="2023-08-21T04:39:18Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=711496623 updater_timeout=45m0s updater_version=488179bbdb771171d0d5eafd879bead8643b0e10-pip
updater | 2023/08/21 04:39:19 INFO Raven 3.1.2 ready to catch errors
updater | 2023/08/21 04:39:20 INFO <job_711496623> Starting job processing
  proxy | 2023/08/21 04:39:21 [002] GET https://api.github.com:443/repos/freqtrade/freqtrade/git/refs/heads/develop
  proxy | 2023/08/21 04:39:21 [002] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:21 [002] 200 https://api.github.com:443/repos/freqtrade/freqtrade/git/refs/heads/develop
  proxy | 2023/08/21 04:39:21 [004] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [004] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:21 [004] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [006] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/pyproject.toml?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [006] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:21 [006] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/pyproject.toml?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [008] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/MANIFEST.in?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [008] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:21 [008] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/MANIFEST.in?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [010] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements-dev.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [010] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:21 [010] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements-dev.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [012] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements-freqai-rl.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [012] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:21 [012] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements-freqai-rl.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [014] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements-freqai.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [014] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:21 [014] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements-freqai.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [016] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements-hyperopt.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [016] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:21 [016] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements-hyperopt.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [018] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements-plot.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [018] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:21 [018] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements-plot.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [020] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:21 [020] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:22 [020] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/requirements.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [022] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/.devcontainer?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [022] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:22 [022] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/.devcontainer?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [024] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/.github?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [024] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:22 [024] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/.github?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [026] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/build_helpers?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [026] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:22 [026] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/build_helpers?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [028] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/config_examples?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [028] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:22 [028] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/config_examples?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [030] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/docker?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [030] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:22 [030] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/docker?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [032] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/docs?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [032] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:22 [032] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/docs?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [034] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/docs/requirements-docs.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [034] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:22 [034] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/docs/requirements-docs.txt?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [036] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/freqtrade?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [036] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:22 [036] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/freqtrade?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [038] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/scripts?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:22 [038] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:22 [038] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/scripts?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:23 [040] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/tests?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:23 [040] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:23 [040] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/tests?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:23 [042] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/user_data?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:23 [042] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:23 [042] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/user_data?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:23 [044] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/setup.py?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:23 [044] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:23 [044] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/setup.py?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:23 [046] GET https://api.github.com:443/repos/freqtrade/freqtrade/contents/setup.cfg?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
  proxy | 2023/08/21 04:39:23 [046] * authenticating github api request with token for api.github.com
  proxy | 2023/08/21 04:39:23 [046] 200 https://api.github.com:443/repos/freqtrade/freqtrade/contents/setup.cfg?ref=4c5f9926707c2df430855dc356b107d47a2c3b46
updater | 2023/08/21 04:39:23 ERROR <job_711496623> Error during file fetching; aborting
updater | 2023/08/21 04:39:23 ERROR <job_711496623> uninitialized constant Dependabot::Python::LanguageVersionManager::PythonVersions
updater | 
updater |           PythonVersions::PRE_INSTALLED_PYTHON_VERSIONS.first
updater |           ^^^^^^^^^^^^^^
updater | 2023/08/21 04:39:23 ERROR <job_711496623> /home/dependabot/python/lib/dependabot/python/language_version_manager.rb:49:in `python_requirement_string'
updater | 2023/08/21 04:39:23 ERROR <job_711496623> /home/dependabot/python/lib/dependabot/python/language_version_manager.rb:54:in `python_version_from_supported_versions'
updater | 2023/08/21 04:39:23 ERROR <job_711496623> /home/dependabot/python/lib/dependabot/python/language_version_manager.rb:35:in `python_version'
updater | 2023/08/21 04:39:23 ERROR <job_711496623> /home/dependabot/python/lib/dependabot/python/language_version_manager.rb:31:in `python_major_minor'
updater | 2023/08/21 04:39:23 ERROR <job_711496623> /home/dependabot/python/lib/dependabot/python/file_fetcher.rb:56:in `ecosystem_versions'
updater | 2023/08/21 04:39:23 ERROR <job_711496623> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:26:in `perform_job'
updater | 2023/08/21 04:39:23 ERROR <job_711496623> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:52:in `run'
updater | 2023/08/21 04:39:23 ERROR <job_711496623> bin/fetch_files.rb:23:in `<main>'
updater | 2023/08/21 04:39:23 INFO <job_711496623> Sending event c0d3be54d69b4cdbada29b3dda35da90 to Sentry
  proxy | 2023/08/21 04:39:23 [048] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/08/21 04:39:23 [048] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/08/21 04:39:24 INFO <job_711496623> Finished job processing
updater | 2023/08/21 04:39:24 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------+
updater | |    Errors     |
updater | +---------------+
updater | | unknown_error |
updater | +---------------+
updater | time="2023-08-21T04:39:24Z" level=info msg="task complete" container_id=job-711496623-file-fetcher exit_code=0 job_id=711496623 step=fetcher
updater | time="2023-08-21T04:39:24Z" level=warning msg="failed during fetch, skipping updater" job_id=711496623
```

**Comment by deivid-rodriguez** [comment]
Thanks for your report @xmatthias. This should be fixed now!

**Comment by xmatthias** [comment]
Can confirm, it's working again now.

Thanks for the quick fix :+1:4

**Comment by deivid-rodriguez** [comment]
No problem!
