### ISSUE TITLE
"Dependabot encountered an unknown error" due to `crates_listing()` not handling HTTP 503s

### ISSUE THREAD

**Issue by edmorley** [dependabot/dependabot-core#8230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Cargo

### Package manager version

1.73

### Language version

1.73

### Manifest location and content before the Dependabot update

https://github.com/heroku/languages-github-actions/blob/5dde4b7d832209dc8d6862d083a41a18d72c7c32/Cargo.toml
https://github.com/heroku/languages-github-actions/blob/5dde4b7d832209dc8d6862d083a41a18d72c7c32/Cargo.lock

### dependabot.yml content

https://github.com/heroku/languages-github-actions/blob/5dde4b7d832209dc8d6862d083a41a18d72c7c32/.github/dependabot.yml

### Updated dependency

N/A

### What you expected to see, versus what you actually saw

If requests to `https://crates.io/api/...` fail with HTTP 503s (or similar non-HTTP-200 status codes), then I would expect that:
1. Dependabot does not try to JSON parse the body of an HTTP 503 response, but instead retries the request a couple of times with back-off, aiming for an HTTP 200
2. If all the retries fail, then a user-friendly error message be shown in the Dependabot logs (such as "Unable to fetch Dependency information from registry ..." or similar), rather than an unhandled "Dependabot encountered an unknown error"

Instead, the Dependabot run failed with an unhandled error...

The red banner at the top of the page says:

```
Dependabot encountered an unknown error

Dependabot failed to update your dependencies because an unexpected error occurred. See the logs for more details.
[Troubleshoot Dependabot errors](https://docs.github.com/github/managing-security-vulnerabilities/troubleshooting-dependabot-errors)
```

The logs themselves say:

```

updater | 2023/10/18 18:47:54 INFO <job_737488060> Starting job processing
updater | 2023/10/18 18:47:55 INFO <job_737488060> Starting grouped update job for heroku/languages-github-actions
updater | 2023/10/18 18:47:55 INFO <job_737488060> Found 2 group(s).
updater | 2023/10/18 18:47:55 INFO <job_737488060> Starting update group for 'libcnb'
updater | 2023/10/18 18:47:55 INFO <job_737488060> Checking if libcnb-common 0.15.0 needs updating
  proxy | 2023/10/18 18:47:56 [018] GET https://crates.io:443/api/v1/crates/libcnb-common
  proxy | 2023/10/18 18:47:56 [018] 200 https://crates.io:443/api/v1/crates/libcnb-common
updater | 2023/10/18 18:47:56 INFO <job_737488060> Latest version is 0.15.0
updater | 2023/10/18 18:47:56 INFO <job_737488060> No update needed for libcnb-common 0.15.0
updater | 2023/10/18 18:47:56 INFO <job_737488060> Checking if libcnb-data 0.15.0 needs updating
  proxy | 2023/10/18 18:47:56 [020] GET https://crates.io:443/api/v1/crates/libcnb-data
  proxy | 2023/10/18 18:47:56 [020] 503 https://crates.io:443/api/v1/crates/libcnb-data
updater | 2023/10/18 18:47:56 INFO <job_737488060> Sending event 8641a94d44bd4a77884235fc249134d4 to Sentry
  proxy | 2023/10/18 18:47:57 [022] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/10/18 18:47:57 [022] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/10/18 18:47:57 ERROR <job_737488060> Error processing libcnb-data (JSON::ParserError)
updater | 2023/10/18 18:47:57 ERROR <job_737488060> unexpected token at '<!DOCTYPE html>
updater | 	<html>
updater | 	  <head>
updater | 		<meta name="viewport" content="width=device-width, initial-scale=1">
updater | 		<meta charset="utf-8">
updater | 		<title>Application Error</title>
updater | 		<style media="screen">
updater | 		  html,body,iframe {
updater | 			margin: 0;
updater | 			padding: 0;
updater | 		  }
updater | 		  html,body {
updater | 			height: 100%;
updater | 			overflow: hidden;
updater | 		  }
updater | 		  iframe {
updater | 			width: 100%;
updater | 			height: 100%;
updater | 			border: 0;
updater | 		  }
updater | 		</style>
updater | 	  </head>
updater | 	  <body>
updater | 		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
updater | 	  </body>
updater | 	</html>'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
  proxy | 2023/10/18 18:47:58 [030] GET https://crates.io:443/api/v1/crates/libcnb-package
  proxy | 2023/10/18 18:47:58 [030] 200 https://crates.io:443/api/v1/crates/libcnb-package
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb:89:in `crates_listing'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb:79:in `available_versions'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb:38:in `fetch_latest_version'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb:25:in `latest_version'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/cargo/lib/dependabot/cargo/update_checker.rb:27:in `latest_version'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:209:in `all_versions_ignored?'
  proxy | 2023/10/18 18:47:58 [032] GET https://crates.io:443/api/v1/crates/chrono
  proxy | 2023/10/18 18:47:58 [032] 503 https://crates.io:443/api/v1/crates/chrono
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:134:in `compile_updates_for'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:48:in `block in compile_all_dependency_changes_for'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `each'
  proxy | 2023/10/18 18:47:58 [034] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/10/18 18:47:58 [034] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `compile_all_dependency_changes_for'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:44:in `perform'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:114:in `run_update_for'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:96:in `block in run_grouped_dependency_updates'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:95:in `each'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:95:in `run_grouped_dependency_updates'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:45:in `perform'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/10/18 18:47:57 ERROR <job_737488060> bin/update_files.rb:24:in `<main>'
```

### Images of the diff or a link to the PR, issue, or logs

Run logs:
https://github.com/heroku/languages-github-actions/network/updates/737488060

Relevant Dependabot implementation:
https://github.com/dependabot/dependabot-core/blob/63977df77903e646c52f88eef803b29c4f805fd2/cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb#L85C22-L90

**Comment by edmorley** [comment]
This happened again, in:
https://github.com/heroku/libcnb.rs/network/updates/756815210

```

updater | 2023/12/01 03:40:14 INFO <job_756815210> Checking if ureq  needs updating
  proxy | 2023/12/01 03:40:14 [839] GET https://crates.io:443/api/v1/crates/ureq
  proxy | 2023/12/01 03:40:14 [839] 503 https://crates.io:443/api/v1/crates/ureq
updater | 2023/12/01 03:40:14 INFO <job_756815210> Sending event a7b668c88fb249808c6c632ca75f80f1 to Sentry
  proxy | 2023/12/01 03:40:14 [841] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/12/01 03:40:14 [841] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/12/01 03:40:14 ERROR <job_756815210> Error processing ureq (JSON::ParserError)
updater | 2023/12/01 03:40:14 ERROR <job_756815210> unexpected token at '<!DOCTYPE html>
updater | 	<html>
updater | 	  <head>
updater | 		<meta name="viewport" content="width=device-width, initial-scale=1">
updater | 		<meta charset="utf-8">
updater | 		<title>Application Error</title>
updater | 		<style media="screen">
updater | 		  html,body,iframe {
updater | 			margin: 0;
updater | 			padding: 0;
updater | 		  }
updater | 		  html,body {
updater | 			height: 100%;
updater | 			overflow: hidden;
updater | 		  }
updater | 		  iframe {
updater | 			width: 100%;
updater | 			height: 100%;
updater | 			border: 0;
updater | 		  }
updater | 		</style>
updater | 	  </head>
updater | 	  <body>
updater | 		<iframe src="//www.herokucdn.com/error-pages/application-error.html"></iframe>
updater | 	  </body>
updater | 	</html>'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/json-2.6.3/lib/json/common.rb:216:in `parse'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb:89:in `crates_listing'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb:79:in `available_versions'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb:38:in `fetch_latest_version'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/cargo/lib/dependabot/cargo/update_checker/latest_version_finder.rb:25:in `latest_version'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/cargo/lib/dependabot/cargo/update_checker.rb:27:in `latest_version'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:177:in `all_versions_ignored?'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:80:in `check_and_create_pull_request'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/12/01 03:40:14 ERROR <job_756815210> bin/update_files.rb:24:in `<main>'
```

**Comment by deivid-rodriguez** [comment]
Right!

I'm been going through this kind of errors recently, but did not go through `rust` yet. In the meantime, happy to take PRs!  Your proposal makes perfect sense to me.
