### ISSUE TITLE
SPM: Package.resolved not found when SPM package is part of an Xcode workspace

### ISSUE THREAD

**Issue by tiwoc** [dependabot/dependabot-core#8350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Swift

### Package manager version

5.9

### Language version

5.9

### Manifest location and content before the Dependabot update

- [/MyLibrary/Package.swift](https://github.com/tiwoc/dependabot-spm-workspace-test/blob/1ca56abdd908194950ee0557df122b65926a4760/MyLibrary/Package.swift)
- [/DependabotDemo.xcworkspace/xcshareddata/swiftpm/Package.resolved](https://github.com/tiwoc/dependabot-spm-workspace-test/blob/1ca56abdd908194950ee0557df122b65926a4760/DependabotDemo.xcworkspace/xcshareddata/swiftpm/Package.resolved)

### dependabot.yml content

```yml
version: 2
updates:
  - package-ecosystem: "swift"
    schedule:
      interval: "daily"
    directory: "/MyLibrary"
```

([source](https://github.com/tiwoc/dependabot-spm-workspace-test/blob/1ca56abdd908194950ee0557df122b65926a4760/.github/dependabot.yml))

### Updated dependency

[swift-algorithms](https://github.com/apple/swift-algorithms) should be updated to 1.1.0

### What you expected to see, versus what you actually saw

I expected Dependabot to open a PR for the swift-algorithms update from 1.0.0 to 1.1.0.

Dependabot doesn't seem to find the lockfile (Package.resolved) though:

```
updater | 2023/11/07 10:27:30 INFO <job_746432055> Starting update job for tiwoc/dependabot-spm-workspace-test
updater | 2023/11/07 10:27:30 INFO <job_746432055> Checking all dependencies for version updates...
updater | 2023/11/07 10:27:30 INFO <job_746432055> Checking if github.com/apple/swift-algorithms 1.0.0 needs updating
updater | 2023/11/07 10:27:31 INFO <job_746432055> Latest version is 1.1.0
updater | 2023/11/07 10:27:36 INFO <job_746432055> Sending event 06ca2e094c094cadaa6438cc222156dc to Sentry
updater | 2023/11/07 10:27:36 ERROR <job_746432055> Error processing github.com/apple/swift-algorithms (NoMethodError)
updater | 2023/11/07 10:27:36 ERROR <job_746432055> undefined method `content' for nil:NilClass
updater | 
updater |           return if updated_lockfile_content == lockfile.content
updater |                                                         ^^^^^^^^
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/swift/lib/dependabot/swift/update_checker/version_resolver.rb:34:in `fetch_latest_resolvable_version'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/swift/lib/dependabot/swift/update_checker/version_resolver.rb:21:in `latest_resolvable_version'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/swift/lib/dependabot/swift/update_checker.rb:67:in `fetch_latest_resolvable_version'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/swift/lib/dependabot/swift/update_checker.rb:22:in `latest_resolvable_version'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:76:in `preferred_resolvable_version'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:266:in `preferred_version_resolvable_with_unlock?'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:258:in `numeric_version_can_update?'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:208:in `version_can_update?'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:46:in `can_update?'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:211:in `requirements_to_unlock'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:90:in `check_and_create_pull_request'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/07 10:27:36 ERROR <job_746432055> bin/update_files.rb:24:in `<main>'
updater | 2023/11/07 10:27:36 INFO <job_746432055> Finished job processing
```

(filtered out any proxy logs, [full logs](https://github.com/dependabot/dependabot-core/files/13278857/dependabot-log.txt))

The issue here seems to be in the project structure. When you create a plain SPM package without an attached Xcode project or workspace, the Package.resolved will be placed in the same folder as the Package.swift, which is probably what Dependabot is assuming.

When you're creating an SPM package that is integrated with an Xcode project or workspace though, Xcode takes over the lockfile and places it within the project or workspace instead.

![Project structure](https://github.com/dependabot/dependabot-core/assets/1260821/d2a84d02-50b3-405a-911a-568479974a98)

Note that this is distinct from https://github.com/dependabot/dependabot-core/issues/7694, where no Package.swift exists in the first place. The issue I'm having is about projects with a Package.swift file, but integrated with an Xcode project so that Xcode takes over the lockfile. The scenario would be the development of internal libraries (SPM) side by side with an app project (Xcode project) that makes use of the packages.

### Failed workarounds
- symlink `Package.resolved` into `/MyLibrary/` (Dependabot detected the change correctly, but silently failed to create a PR)
- symlink `Package.swift` into `/DependabotDemo.xcworkspace/xcshareddata/swiftpm/` and adjust `directory` in `dependabot.yml` accordingly (Dependabot couldn't parse the package because the relative paths to the source files in the package were now all relative to the workspace dir and therefore all broken, but adjusting them would break the Package.swift in the original location)
- move `Package.swift` to repo root so that `Package.resolved` is in a subdir of `directory` (Dependabot still didn't find the `Package.resolved`)

Copying `Package.resolved` to `/MyLibrary/` works, but then we'd have to copy it back to the workspace dir after each update PR.

### Potential fixes
Dependabot could either search the .xcworkspace hierarchy for a Package.resolved file, or offer a configuration option to add an additional search path for the lockfile, separate from the `directory` setting.

**Comment by deivid-rodriguez** [comment]
Thanks, this is a bug. Fix at #8352.

**Comment by deivid-rodriguez** [comment]
Ah I see. Yeah, we don't currently support that and I see it as part of #7694. Currently we support whatever [swiftPM](https://www.swift.org/package-manager/) supports, and I don't think it can handle what you need?

We could potentially try handle the symlink case (first workaround). Can you copy the logs when using that workaround?

**Comment by tiwoc** [comment]
Sure! There's no error message though, GitHub just silently fails to create a PR.

The logs claim that a PR is created:

```
updater | 2023/11/07 15:39:38 INFO <job_746546002> Finished job processing
updater | 2023/11/07 15:39:38 INFO Results:
updater | +---------------------------------------------------------------------+
updater | |                 Changes to Dependabot Pull Requests                 |
updater | +---------+-----------------------------------------------------------+
updater | | created | github.com/apple/swift-algorithms ( from 1.0.0 to 1.1.0 ) |
updater | +---------+-----------------------------------------------------------+
```

But the job status (and the list of PRs in GitHub) contradict that:

<img src="https://github.com/dependabot/dependabot-core/assets/1260821/f2b02b26-bb34-47f6-a0c8-672a3a3b06c9" width="400">

Interestingly, once I replace the symlink with an actual copy of `Package.resolved`, Dependabot does create a PR, so it just seems to be choking on the symlink somehow.

----

<details><summary>Full logs</summary>

```

  proxy | 2023/11/07 15:39:17 proxy starting, commit: 720801aa060f51bd9dc8b5753a6045ec3d7f5321
  proxy | 2023/11/07 15:39:17 Listening (:1080)
updater | 2023-11-07T15:39:17.753804805 [746546002:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-11-07T15:39:19Z" level=info msg="guest starting" commit=480200678d7877c9eb94d16566d7ee0d2e75c9bf
updater | time="2023-11-07T15:39:19Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=746546002 updater_timeout=45m0s updater_version=6c4675c7d545ba1a23b0b2b10991e7793a3015f8-swift
updater | 2023/11/07 15:39:21 INFO Raven 3.1.2 ready to catch errors
updater | 2023/11/07 15:39:21 INFO <job_746546002> Starting job processing
  proxy | 2023/11/07 15:39:22 [002] GET https://github.com:443/tiwoc/dependabot-spm-workspace-test/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:22 [002] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:22 [002] 200 https://github.com:443/tiwoc/dependabot-spm-workspace-test/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:22 [003] POST https://github.com:443/tiwoc/dependabot-spm-workspace-test/git-upload-pack
  proxy | 2023/11/07 15:39:22 [003] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:22 [003] 200 https://github.com:443/tiwoc/dependabot-spm-workspace-test/git-upload-pack
  proxy | 2023/11/07 15:39:22 [004] POST https://github.com:443/tiwoc/dependabot-spm-workspace-test/git-upload-pack
  proxy | 2023/11/07 15:39:22 [004] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:22 [004] 200 https://github.com:443/tiwoc/dependabot-spm-workspace-test/git-upload-pack
updater | 2023/11/07 15:39:22 INFO <job_746546002> Finished job processing
updater | time="2023-11-07T15:39:22Z" level=info msg="task complete" container_id=job-746546002-file-fetcher exit_code=0 job_id=746546002 step=fetcher
updater | 2023/11/07 15:39:23 INFO Raven 3.1.2 ready to catch errors
updater | 2023/11/07 15:39:24 INFO <job_746546002> Starting job processing
  proxy | 2023/11/07 15:39:26 [007] GET https://github.com:443/apple/swift-algorithms/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:26 [007] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:26 [008] GET https://github.com:443/apple/swift-numerics/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:26 [008] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:26 [008] 200 https://github.com:443/apple/swift-numerics/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:26 [009] POST https://github.com:443/apple/swift-numerics/git-upload-pack
  proxy | 2023/11/07 15:39:26 [009] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:26 [007] 200 https://github.com:443/apple/swift-algorithms/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:26 [010] POST https://github.com:443/apple/swift-algorithms/git-upload-pack
  proxy | 2023/11/07 15:39:26 [010] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:26 [009] 200 https://github.com:443/apple/swift-numerics/git-upload-pack
  proxy | 2023/11/07 15:39:26 [011] POST https://github.com:443/apple/swift-numerics/git-upload-pack
  proxy | 2023/11/07 15:39:26 [011] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:26 [010] 200 https://github.com:443/apple/swift-algorithms/git-upload-pack
  proxy | 2023/11/07 15:39:26 [012] POST https://github.com:443/apple/swift-algorithms/git-upload-pack
  proxy | 2023/11/07 15:39:26 [012] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:27 [012] 200 https://github.com:443/apple/swift-algorithms/git-upload-pack
  proxy | 2023/11/07 15:39:28 [011] 200 https://github.com:443/apple/swift-numerics/git-upload-pack
updater | 2023/11/07 15:39:31 INFO <job_746546002> Starting update job for tiwoc/dependabot-spm-workspace-test
updater | 2023/11/07 15:39:31 INFO <job_746546002> Checking all dependencies for version updates...
updater | 2023/11/07 15:39:31 INFO <job_746546002> Checking if github.com/apple/swift-algorithms 1.0.0 needs updating
  proxy | 2023/11/07 15:39:31 [018] GET https://github.com:443/apple/swift-algorithms.git/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:31 [018] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:31 [018] 200 https://github.com:443/apple/swift-algorithms.git/info/refs?service=git-upload-pack
updater | 2023/11/07 15:39:31 INFO <job_746546002> Latest version is 1.1.0
  proxy | 2023/11/07 15:39:32 [021] GET https://github.com:443/apple/swift-algorithms/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:32 [021] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:32 [022] GET https://github.com:443/apple/swift-numerics/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:32 [022] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:32 [021] 200 https://github.com:443/apple/swift-algorithms/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:32 [023] POST https://github.com:443/apple/swift-algorithms/git-upload-pack
  proxy | 2023/11/07 15:39:32 [023] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:32 [022] 200 https://github.com:443/apple/swift-numerics/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:32 [024] POST https://github.com:443/apple/swift-numerics/git-upload-pack
  proxy | 2023/11/07 15:39:32 [024] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:32 [023] 200 https://github.com:443/apple/swift-algorithms/git-upload-pack
  proxy | 2023/11/07 15:39:32 [024] 200 https://github.com:443/apple/swift-numerics/git-upload-pack
updater | 2023/11/07 15:39:34 INFO <job_746546002> Requirements to unlock own
updater | 2023/11/07 15:39:34 INFO <job_746546002> Requirements update strategy 
updater | 2023/11/07 15:39:34 INFO <job_746546002> Updating github.com/apple/swift-algorithms from 1.0.0 to 1.1.0
  proxy | 2023/11/07 15:39:35 [026] GET https://github.com:443/apple/swift-algorithms/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:35 [026] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:35 [028] GET https://github.com:443/apple/swift-numerics/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:35 [028] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:35 [026] 200 https://github.com:443/apple/swift-algorithms/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:35 [029] POST https://github.com:443/apple/swift-algorithms/git-upload-pack
  proxy | 2023/11/07 15:39:35 [029] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:35 [028] 200 https://github.com:443/apple/swift-numerics/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:35 [030] POST https://github.com:443/apple/swift-numerics/git-upload-pack
  proxy | 2023/11/07 15:39:35 [030] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:35 [029] 200 https://github.com:443/apple/swift-algorithms/git-upload-pack
  proxy | 2023/11/07 15:39:35 [030] 200 https://github.com:443/apple/swift-numerics/git-upload-pack
updater | 2023/11/07 15:39:35 INFO <job_746546002> Submitting github.com/apple/swift-algorithms pull request for creation
  proxy | 2023/11/07 15:39:35 [032] GET https://api.github.com:443/repos/tiwoc/dependabot-spm-workspace-test/commits?per_page=100
  proxy | 2023/11/07 15:39:35 [032] * authenticating github api request with token for api.github.com
  proxy | 2023/11/07 15:39:35 [032] 200 https://api.github.com:443/repos/tiwoc/dependabot-spm-workspace-test/commits?per_page=100
  proxy | 2023/11/07 15:39:35 [034] GET https://api.github.com:443/repos/apple/swift-algorithms/releases?per_page=100
  proxy | 2023/11/07 15:39:35 [034] * authenticating github api request with token for api.github.com
  proxy | 2023/11/07 15:39:36 [034] 200 https://api.github.com:443/repos/apple/swift-algorithms/releases?per_page=100
  proxy | 2023/11/07 15:39:36 [036] GET https://github.com:443/apple/swift-algorithms.git/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:36 [036] * authenticating git server request (host: github.com)
  proxy | 2023/11/07 15:39:36 [036] 200 https://github.com:443/apple/swift-algorithms.git/info/refs?service=git-upload-pack
  proxy | 2023/11/07 15:39:36 [038] GET https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.0.0
  proxy | 2023/11/07 15:39:36 [038] * authenticating github api request with token for api.github.com
  proxy | 2023/11/07 15:39:36 [038] 200 https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.0.0
  proxy | 2023/11/07 15:39:36 [040] GET https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.1.0
  proxy | 2023/11/07 15:39:36 [040] * authenticating github api request with token for api.github.com
  proxy | 2023/11/07 15:39:36 [040] 200 https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.1.0
  proxy | 2023/11/07 15:39:36 [042] GET https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.0.0
  proxy | 2023/11/07 15:39:36 [042] * authenticating github api request with token for api.github.com
  proxy | 2023/11/07 15:39:37 [042] 200 https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.0.0
  proxy | 2023/11/07 15:39:37 [044] GET https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.1.0
  proxy | 2023/11/07 15:39:37 [044] * authenticating github api request with token for api.github.com
  proxy | 2023/11/07 15:39:37 [044] 200 https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.1.0
  proxy | 2023/11/07 15:39:37 [046] GET https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.0.0
  proxy | 2023/11/07 15:39:37 [046] * authenticating github api request with token for api.github.com
  proxy | 2023/11/07 15:39:37 [046] 200 https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.0.0
  proxy | 2023/11/07 15:39:37 [048] GET https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.1.0
  proxy | 2023/11/07 15:39:37 [048] * authenticating github api request with token for api.github.com
  proxy | 2023/11/07 15:39:37 [048] 200 https://api.github.com:443/repos/apple/swift-algorithms/commits?sha=1.1.0
updater | 2023/11/07 15:39:38 INFO <job_746546002> Finished job processing
updater | 2023/11/07 15:39:38 INFO Results:
updater | +---------------------------------------------------------------------+
updater | |                 Changes to Dependabot Pull Requests                 |
updater | +---------+-----------------------------------------------------------+
updater | | created | github.com/apple/swift-algorithms ( from 1.0.0 to 1.1.0 ) |
updater | +---------+-----------------------------------------------------------+
updater | time="2023-11-07T15:39:38Z" level=info msg="task complete" container_id=job-746546002-updater exit_code=0 job_id=746546002 step=updater
```

</details>
