### ISSUE TITLE
Dependabot failing to update pnpm monorepo when using groups (NoChangeError)

### ISSUE THREAD

**Issue by sQVe** [dependabot/dependabot-core#8351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

pnpm 8.10.2

### Language version

Node v18.18.2

### Manifest location and content before the Dependabot update

https://github.com/sQVe/dependabot-repro/blob/d73f9bff80de95a3396fed291c5932fa42572e32/package.json
https://github.com/sQVe/dependabot-repro/blob/d73f9bff80de95a3396fed291c5932fa42572e32/packages/config/package.json

### dependabot.yml content

https://github.com/sQVe/dependabot-repro/blob/d73f9bff80de95a3396fed291c5932fa42572e32/.github/dependabot.yml

### What you expected to see, versus what you actually saw

**Expected**

The expected behavior is for Dependabot to open PRs for the relevant dependencies, while following the grouping provided in the config.

**Actual**

It successfully opens PRs, and correctly groups them, but it's failing to check multiple dependencies for updates due to a `NoChangeError`. The following is an example of the output under **Dependency graph > Dependabot**:

```
updater | 2023/11/07 12:05:29 ERROR <job_746468137> Error processing @rushstack/eslint-patch (Dependabot::NpmAndYarn::FileUpdater::NoChangeError)
updater | 2023/11/07 12:05:29 ERROR <job_746468137> No files were updated!
updater | 2023/11/07 12:05:29 ERROR <job_746468137> 
```

### Smallest manifest that reproduces the issue

https://github.com/sQVe/dependabot-repro/tree/d73f9bff80de95a3396fed291c5932fa42572e32

**Comment by sQVe** [comment]
This seems to be somewhat related to: https://github.com/dependabot/dependabot-core/issues/7238

**Comment by abdulapopoola** [comment]
@sQVe does this still repro? The team has shipped quite a few fixes in this area

**Comment by abdulapopoola** [comment]
oh my :( ; would you be willing to try out Dependabot now that we've made more fixes? :) 

cc: @carlincherry

**Comment by freeqaz-figma** [comment]
FYI we're seeing this issue with our pnpm setup as well.

Not sure what additional context that I can add, but I'm happy to paste the error we're seeing:

```
updater | 2024/06/12 22:53:24 ERROR <job_841223162> Error processing diff (Dependabot::NpmAndYarn::FileUpdater::NoChangeError)
updater | 2024/06/12 22:53:24 ERROR <job_841223162> No files were updated!
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:52:in `updated_dependency_files'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:135:in `generate_dependency_files'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:68:in `run'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:42:in `create_from'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:149:in `check_and_create_pull_request'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:64:in `check_and_create_pr_with_error_handling'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `block in perform'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `each'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `perform'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:44:in `block in perform_job'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `block in with_span'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/context.rb:87:in `with_value'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `with_span'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:18:in `perform_job'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/06/12 22:53:24 ERROR <job_841223162> bin/update_files.rb:46:in `<main>'
updater | 2024/06/12 22:53:24 INFO <job_841223162> Finished job processing
updater | 2024/06/12 22:53:24 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------------------------+
updater | | Dependencies failed to update |
updater | +---------------+---------------+
updater | | diff          | unknown_error |
updater | +---------------+---------------+
```

**Comment by kahagerman** [comment]
I can confirm this is still an issue.

Shortly after a line like:
```
updater | 2024/08/20 12:35:24 INFO <job_871757203> Updating i18next from 23.12.2 to 23.14.0
```

I'm seeing:
```
  proxy | 2024/08/20 12:35:31 [624] POST /update_jobs/871757203/record_update_job_unknown_error
  proxy | 2024/08/20 12:35:31 [624] 204 /update_jobs/871757203/record_update_job_unknown_error
  proxy | 2024/08/20 12:35:31 [626] POST /update_jobs/871757203/record_update_job_error
  proxy | 2024/08/20 12:35:32 [626] 204 /update_jobs/871757203/record_update_job_error
  proxy | 2024/08/20 12:35:32 [628] POST /update_jobs/871757203/increment_metric
  proxy | 2024/08/20 12:35:32 [628] 204 /update_jobs/871757203/increment_metric
  proxy | 2024/08/20 12:35:32 [630] POST /update_jobs/871757203/record_update_job_unknown_error
  proxy | 2024/08/20 12:35:32 [630] 204 /update_jobs/871757203/record_update_job_unknown_error
updater | 2024/08/20 12:35:32 ERROR <job_871757203> Error processing i18next (Dependabot::NpmAndYarn::FileUpdater::NoChangeError)
2024/08/20 12:35:32 ERROR <job_871757203> No files were updated!
2024/08/20 12:35:32 ERROR <job_871757203> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:54:in `updated_dependency_files'
2024/08/20 12:35:32 ERROR <job_871757203> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'
```
Followed by a stack trace.

Here are the full logs; this error occurred a total of five times during the run (on different dependencies):
[logs_27377378659.zip](https://github.com/user-attachments/files/16677644/logs_27377378659.zip)

**Comment by TheJokersThief** [comment]
Just ran into this today ourselves - does anyone know if there's a workaround? Does ungrouping the dependencies work fine?

**Comment by dhavv** [comment]
I had this issue, but apparently deleting node_modules and pnpm-lock.yaml, then regenerating (pnpm install) it again seems to "fix" this issue for me.

**Comment by abdulapopoola** [comment]
Is this still occurring? We've shipped a couple of improvements recently.

**Comment by kbukum1** [comment]
@sQVe, @freeqaz-figma, @kahagerman, @TheJokersThief

Could you check if the issue is still occurring? Let us know if you’re still experiencing any problems. Thanks! 🙏

**Comment by bm77525-kr** [comment]
@kbukum1  I'm still seeing this error  in our pnpm repo

```
2025-08-04T17:56:53.5498819Z updater | 2025/08/04 17:56:53 ERROR <job_1068096422> Error processing @rushstack/eslint-patch (Dependabot::NpmAndYarn::FileUpdater::NoChangeError)
2025-08-04T17:56:53.5508621Z 2025/08/04 17:56:53 ERROR <job_1068096422> No files were updated!
2025-08-04T17:56:53.5510241Z updater | 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:70:in 'Dependabot::NpmAndYarn::FileUpdater#updated_dependency_files'
2025-08-04T17:56:53.5514395Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:919:in 'UnboundMethod#bind_call'
2025-08-04T17:56:53.5521346Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:919:in 'block in Dependabot::NpmAndYarn::FileUpdater#create_validator_method_medium0'
2025-08-04T17:56:53.5524114Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:144:in 'Dependabot::DependencyChangeBuilder#generate_dependency_files'
2025-08-04T17:56:53.5526328Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:919:in 'UnboundMethod#bind_call'
2025-08-04T17:56:53.5528912Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:919:in 'block in Dependabot::DependencyChangeBuilder#create_validator_method_medium0'
2025-08-04T17:56:53.5531216Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:72:in 'Dependabot::DependencyChangeBuilder#run'
2025-08-04T17:56:53.5533451Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:59:in 'UnboundMethod#bind_call'
2025-08-04T17:56:53.5536044Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:59:in 'block in Dependabot::DependencyChangeBuilder#create_validator_method_fast0'
2025-08-04T17:56:53.5538670Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:44:in 'Dependabot::DependencyChangeBuilder.create_from'
2025-08-04T17:56:53.5540680Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:179:in 'UnboundMethod#bind_call'
2025-08-04T17:56:53.5543237Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:179:in 'T::Private::Methods::CallValidation.validate_call_skip_block_type'
2025-08-04T17:56:53.5546091Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:121:in 'block in Dependabot::DependencyChangeBuilder.create_validator_slow_skip_block_type'
2025-08-04T17:56:53.5548701Z updater | 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:245:in 'Dependabot::Updater::GroupUpdateCreation#create_change_for'
2025-08-04T17:56:53.5551078Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:1187:in 'UnboundMethod#bind_call'
2025-08-04T17:56:53.5557174Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation_2_7.rb:1187:in 'block in Dependabot::Updater::GroupUpdateCreation#create_validator_method_medium4'
2025-08-04T17:56:53.5559987Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:133:in 'block in Dependabot::Updater::GroupUpdateCreation#compile_all_dependency_changes_for'
2025-08-04T17:56:53.5562034Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:100:in 'Array#each'
2025-08-04T17:56:53.5564212Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:100:in 'Dependabot::Updater::GroupUpdateCreation#compile_all_dependency_changes_for'
2025-08-04T17:56:53.5566814Z updater | 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-08-04T17:56:53.5569314Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-08-04T17:56:53.5571939Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::Updater::GroupUpdateCreation#_on_method_added'
2025-08-04T17:56:53.5574941Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:118:in 'block in Dependabot::Updater::Operations::CreateGroupUpdatePullRequest#dependency_change'
2025-08-04T17:56:53.5577297Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:115:in 'Array#each'
2025-08-04T17:56:53.5579266Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:115:in 'Enumerable#filter_map'
2025-08-04T17:56:53.5581660Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:115:in 'Dependabot::Updater::Operations::CreateGroupUpdatePullRequest#dependency_change'
2025-08-04T17:56:53.5584489Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-08-04T17:56:53.5586914Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-08-04T17:56:53.5589640Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::Updater::Operations::CreateGroupUpdatePullRequest#_on_method_added'
2025-08-04T17:56:53.5592391Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:62:in 'Dependabot::Updater::Operations::CreateGroupUpdatePullRequest#perform'
2025-08-04T17:56:53.5595026Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-08-04T17:56:53.5597400Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-08-04T17:56:53.5600036Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::Updater::Operations::CreateGroupUpdatePullRequest#_on_method_added'
2025-08-04T17:56:53.5602763Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:118:in 'Dependabot::Updater::Operations::GroupUpdateAllVersions#run_grouped_update_for'
2025-08-04T17:56:53.5605388Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-08-04T17:56:53.5607920Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-08-04T17:56:53.5610707Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::Updater::Operations::GroupUpdateAllVersions#_on_method_added'
2025-08-04T17:56:53.5613681Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:104:in 'block in Dependabot::Updater::Operations::GroupUpdateAllVersions#run_grouped_dependency_updates'
2025-08-04T17:56:53.5616015Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:103:in 'Array#each'
2025-08-04T17:56:53.5618293Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:103:in 'Dependabot::Updater::Operations::GroupUpdateAllVersions#run_grouped_dependency_updates'
2025-08-04T17:56:53.5620746Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-08-04T17:56:53.5623485Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-08-04T17:56:53.5626430Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::Updater::Operations::GroupUpdateAllVersions#_on_method_added'
2025-08-04T17:56:53.5629039Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:65:in 'Dependabot::Updater::Operations::GroupUpdateAllVersions#perform'
2025-08-04T17:56:53.5631355Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'UnboundMethod#bind_call'
2025-08-04T17:56:53.5633953Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/call_validation.rb:282:in 'T::Private::Methods::CallValidation.validate_call'
2025-08-04T17:56:53.5636738Z updater | 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/sorbet-runtime-0.5.11952/lib/types/private/methods/_methods.rb:277:in 'block in Dependabot::Updater::Operations::GroupUpdateAllVersions#_on_method_added'
2025-08-04T17:56:53.5638942Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in 'Dependabot::Updater#run'
2025-08-04T17:56:53.5640649Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:45:in 'block in Dependabot::UpdateFilesCommand#perform_job'
2025-08-04T17:56:53.5642794Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace/tracer.rb:37:in 'block in OpenTelemetry::Trace::Tracer#in_span'
2025-08-04T17:56:53.5646046Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace.rb:70:in 'block in OpenTelemetry::Trace#with_span'
2025-08-04T17:56:53.5648474Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/context.rb:88:in 'OpenTelemetry::Context.with_value'
2025-08-04T17:56:53.5650559Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace.rb:70:in 'OpenTelemetry::Trace#with_span'
2025-08-04T17:56:53.5652730Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/vendor/ruby/3.4.0/gems/opentelemetry-api-1.5.0/lib/opentelemetry/trace/tracer.rb:37:in 'OpenTelemetry::Trace::Tracer#in_span'
2025-08-04T17:56:53.5655216Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:18:in 'Dependabot::UpdateFilesCommand#perform_job'
2025-08-04T17:56:53.5656932Z 2025/08/04 17:56:53 ERROR <job_1068096422> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in 'Dependabot::BaseCommand#run'
2025-08-04T17:56:53.5658072Z 2025/08/04 17:56:53 ERROR <job_1068096422> bin/update_files.rb:44:in '<main>'
2025-08-04T17:56:53.5659068Z 2025/08/04 17:56:53 INFO <job_1068096422> Skipping @rushstack/eslint-patch in group version: No dependency change was created
```
