### ISSUE TITLE
Dependabot attempts to fetch an ignored local dependency

### ISSUE THREAD

**Issue by fistaco** [dependabot/dependabot-core#8376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

Yarn Berry (3.3.1)

### Language version

Node.js 16.20.2 (lts/gallium)

### Manifest location and content before the Dependabot update

Our monorepo root (`/`) contains `/package.json` and `yarn.lock`, as well as a `.yarnrc` file for configuration. The configuration in `dependabot.yml` only specifies `directory: "/"`, but the list of monitored manifest files at "Insights -> Dependency Graph -> Dependabot" also shows the `/**/yarn.lock` and `/**/package.json` files from the repository's sub-directories.

The contents of `/package.json` looks something like this:
```json
  "name": "ourprojectname-server-root",
  "private": true,
  "workspaces": [
    "packages/ourprojectname-hub-sdk/clients/js",
    "packages/ourprojectname-hub-test",
    "packages/ourprojectname-mock-server",
    "packages/ourprojectname-server"
  ],
  "scripts": {
    ...
  },
  "devDependencies": {
    "@ourprojectname/utils": "0.6.1-develop-44.0",
    "chai": "^4.3.6",
    "chai-as-promised": "^7.1.1",
    "chai-exclude": "*",
    "chai-string": "*",
    "nock": "^13.2.8",
    ...
  },
  "resolutions": {
    ...
  }
}

```

### dependabot.yml content

Our `dependabot.yml` file looks as follows:
```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "08:00"
    open-pull-requests-limit: 5
    allow:
    - dependency-type: "direct"
    ignore:
    # Ignore dependencies that we manage locally
    - dependency-name: "@ourprojectname*"
    - dependency-name: "ourprojectname*"
    - dependency-name: "*"
      update-types: ["version-update:semver-major", version-update:semver-minor] # Only perform patch updates
    assignees:
    - "My_Name_myorg"
    reviewers:
    - "My_Name_myorg"
    # Note that the target-branch setting affects version updates, but not security updates
    target-branch: "ci/OURPROJECTNAME-8734-dependabot-version-updates-configuration"
    groups:
      minor-updates:
        update-types:
        - "minor"
      patch-updates:
        update-types:
        - "patch"
      dev-dependency-updates:
        dependency-type: "development"
    versioning-strategy: auto

```

### Updated dependency

Chai succesfully received a PR for its update: `chai ( from 4.3.1 to 4.3.10 )`
Nock failed to update with an`unknown_error`

### What you expected to see, versus what you actually saw

I expected a PR to be opened for a Nock update from 13.3.7 to 13.3.8, which could result in `updated | nock ( from 13.3.7 to 13.3.8 ) |` to be printed in the logs.

The update logs I saw were as follows:
```
...
...
updater | 2023/11/06 13:26:41 INFO <job_745882301> Starting job processing
updater | 2023/11/06 13:26:42 INFO <job_745882301> All versions of @ourprojectname/utils ignored, no update allowed
...
...
updater | 2023/11/06 13:29:30 INFO <job_745882301> Checking if nock 13.3.7 needs updating
updater | 2023/11/06 13:29:30 INFO <job_745882301> Ignored versions:
updater | 2023/11/06 13:29:30 INFO <job_745882301>   version-update:semver-major - from .github/dependabot.yml
updater | 2023/11/06 13:29:30 INFO <job_745882301>   version-update:semver-minor - from .github/dependabot.yml
  proxy | 2023/11/06 13:29:30 [182] GET https://registry.npmjs.org:443/nock
  proxy | 2023/11/06 13:29:30 [182] 200 https://registry.npmjs.org:443/nock
  proxy | 2023/11/06 13:29:30 [184] GET https://registry.npmjs.org:443/nock/13.3.8
  proxy | 2023/11/06 13:29:30 [184] 200 https://registry.npmjs.org:443/nock/13.3.8
updater | 2023/11/06 13:29:30 INFO <job_745882301> Latest version is 13.3.8
  proxy | 2023/11/06 13:29:39 [186] GET https://registry.yarnpkg.com:443/nock
  proxy | 2023/11/06 13:29:39 [186] 200 https://registry.yarnpkg.com:443/nock
  proxy | 2023/11/06 13:29:39 [188] GET https://registry.yarnpkg.com:443/nock/-/nock-13.3.8.tgz
  proxy | 2023/11/06 13:29:39 [188] 200 https://registry.yarnpkg.com:443/nock/-/nock-13.3.8.tgz
updater | 2023/11/06 13:29:40 INFO <job_745882301> Requirements to unlock own
updater | 2023/11/06 13:29:40 INFO <job_745882301> Requirements update strategy widen_ranges
updater | 2023/11/06 13:29:40 INFO <job_745882301> Updating nock from 13.3.7 to 13.3.8
  proxy | 2023/11/06 13:29:48 [190] GET https://registry.yarnpkg.com:443/nock
  proxy | 2023/11/06 13:29:48 [190] 200 https://registry.yarnpkg.com:443/nock
  proxy | 2023/11/06 13:29:48 [223] GET https://registry.yarnpkg.com:443/@aashutoshrathi%2fword-wrap/-/word-wrap-1.2.6.tgz
  proxy | 2023/11/06 13:29:48 [224] GET https://registry.yarnpkg.com:443/@ampproject%2fremapping/-/remapping-2.2.1.tgz
  proxy | 2023/11/06 13:29:48 [225] GET https://registry.yarnpkg.com:443/@artilleryio%2fint-commons/-/int-commons-2.0.2-ef9d096.tgz
...
...
  proxy | 2023/11/06 13:29:56 [956] GET https://nexus.devnet.klm.com:443/repository/npm/@aircon%2futils/-/utils-0.3.1-develop-44.0.tgz
  proxy | 2023/11/06 13:29:56 [188] WARN: Cannot read TLS response from mitm'd server lookup nexus.devnet.klm.com on 8.8.8.8:53: no such host
  proxy | 2023/11/06 13:29:56 [958] GET https://nexus.devnet.klm.com:443/repository/npm/@aircon/utils/-/utils-0.3.1-develop-44.0.tgz
  proxy | 2023/11/06 13:29:56 [190] WARN: Cannot read TLS response from mitm'd server lookup nexus.devnet.klm.com on 8.8.8.8:53: no such host
...
...
  proxy | 2023/11/06 13:29:57 [023] GET https://nexus.devnet.klm.com:443/repository/npm/@aircon/utils/-/utils-0.3.1-develop-44.0.tgz
    proxy | 2023/11/06 13:29:57 [255] WARN: Cannot read TLS response from mitm'd server lookup nexus.devnet.klm.com on 8.8.8.8:53: no such host
...
...

updater | 2023/11/06 13:31:15 INFO <job_745882301> Sending event f51028eb29b940588a8a3c1e96b7211c to Sentry
  proxy | 2023/11/06 13:31:15 [672] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/11/06 13:31:15 [672] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/11/06 13:31:16 ERROR <job_745882301> Error processing nock (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/11/06 13:31:16 ERROR <job_745882301> ➤ YN0000: ┌ Resolution step
updater | ➤ YN0002: │ @lerna/version@npm:5.6.2 doesn't provide nx (p7a6e2), requested by @nrwl/devkit
updater | ➤ YN0002: │ @oclif/core@npm:2.15.0 doesn't provide @types/node (pd4647), requested by ts-node
...
...
updater | ➤ YN0013: │ bindings@npm:1.5.0 can't be found in the cache and will be fetched from the remote registry
updater | ➤ YN0013: │ bintrees@npm:1.0.2 can't be found in the cache and will be fetched from the remote registry
updater | ➤ YN0013: │ bl@npm:4.1.0 can't be found in the cache and will be fetched from the remote registry
updater | ➤ YN0001: │ RequestError: socket hang up
updater |     at ClientRequest.<anonymous> (/home/dependabot/.cache/node/corepack/yarn/3.6.4/yarn.js:195:14340)
updater |     at Object.onceWrapper (node:events:632:26)
updater |     at ClientRequest.emit (node:events:529:35)
updater |     at o.emit (/home/dependabot/.cache/node/corepack/yarn/3.6.4/yarn.js:190:90286)
updater |     at TLSSocket.socketOnEnd (node:_http_client:525:9)
updater |     at TLSSocket.emit (node:events:529:35)
updater |     at endReadableNT (node:internal/streams/readable:1368:12)
updater |     at connResetException (node:internal/errors:720:14)
updater |     at TLSSocket.socketOnEnd (node:_http_client:525:23)
updater |     at TLSSocket.emit (node:events:529:35)
updater |     at endReadableNT (node:internal/streams/readable:1368:12)
updater |     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
updater | ➤ YN0013: │ bluebird@npm:3.7.2 can't be found in the cache and will be fetched from the remote registry
updater | ➤ YN0013: │ body-parser@npm:1.20.1 can't be found in the cache and will be fetched from the remote registry
...
...
updater | ➤ YN0013: │ zip-stream@npm:4.1.1 can't be found in the cache and will be fetched from the remote registry
updater | ➤ YN0000: └ Completed in 1m 27s
updater | ➤ YN0000: Failed with errors in 1m 28s
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/common/lib/dependabot/shared_helpers.rb:427:in `run_shell_command'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:153:in `bind_call'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb:123:in `run_yarn_command'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:161:in `run_yarn_berry_top_level_updater'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:112:in `block (2 levels) in run_yarn_updater'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:109:in `chdir'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:109:in `block in run_yarn_updater'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/common/lib/dependabot/shared_helpers.rb:264:in `with_git_configured'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:177:in `block in create_validator_slow'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:108:in `run_yarn_updater'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:81:in `run_current_yarn_update'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:62:in `block in updated_yarn_lock'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/common/lib/dependabot/workspace/base.rb:51:in `block in change'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/common/lib/dependabot/workspace/base.rb:51:in `chdir'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/common/lib/dependabot/workspace/base.rb:51:in `change'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:177:in `block in create_validator_slow'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/common/lib/dependabot/shared_helpers.rb:49:in `in_a_temporary_repo_directory'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:177:in `block in create_validator_slow'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:58:in `updated_yarn_lock'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:34:in `updated_yarn_lock_content'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:241:in `updated_yarn_lock_content'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:172:in `yarn_lock_changed?'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:200:in `block in updated_lockfiles'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:199:in `each'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:199:in `updated_lockfiles'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:44:in `updated_dependency_files'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:87:in `generate_dependency_files'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:37:in `run'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:95:in `create_change_for'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:56:in `block in compile_all_dependency_changes_for'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `each'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `compile_all_dependency_changes_for'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb:90:in `perform'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/06 13:31:22 ERROR <job_745882301> bin/update_files.rb:24:in `<main>'
...
...

updater | 2023/11/06 13:33:34 INFO <job_745882301> Finished job processing
updater | 2023/11/06 13:33:34 INFO Results:
updater | +-----------------------------------------+
updater | |   Changes to Dependabot Pull Requests   |
updater | +---------+-------------------------------+
updater | | updated | chai ( from 4.3.1 to 4.3.10 ) |
updater | +---------+-------------------------------+
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------------------------+
updater | | Dependencies failed to update |
updater | +---------------+---------------+
updater | | nock          | unknown_error |
updater | +---------------+---------------+
...
```
The logs indicate that, upon attempting to update Nock, the updater also attempts to fetch the other dependencies from the Yarn registry. Eventually, we observe attempts to fetch our local dependency "@ourprojectname/utils" from a Nexus registry in our local network, but these attempts fail, which makes sense. **Given our configuration, I expect this fetch attempt not to occur.** 

I believe the `RequestError` in the logs to be caused by our local dependency, because other failed runs display the error right after its name is mentioned for a fetch attempt. Furthermore, Dependabot completes successfully when the dependency is removed from `/package.json`.

### Native package manager behavior

Locally, Yarn 3.3.1 has no issues reaching our local registry and successfully updates the deprecated dependencies.

**Comment by Lonli-Lokli** [comment]
Have same issue with nx monorepo and npm
