### ISSUE TITLE
Rebases and Recreates failing on nuget grouped dependencies

### ISSUE THREAD

**Issue by joaorosado** [dependabot/dependabot-core#8391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### What you expected to see, versus what you actually saw

Creating the grouped PR or closing the current PR and creating new one works, but updating the current PR fails with "Dependabot encountered an unknown error"
Cannot share the urls since it's a private repo.

It also fails again even with recreate and rebase commands.

The project does have both Directory.Build.props (on the root) and multiple csproj files (in subdirectories) that I can see being downloaded in the logs.

This case was replicated by having changes in the repo, not versions related and just asking the bot to recreate or rebase the branch to get it up to date on the PR.

Rebase update 749840359

### Images of the diff or a link to the PR, issue, or logs

```
updater | 2023/11/14 16:42:04 INFO <job_749840359> Updating the 'testingframeworks' group
updater | 2023/11/14 16:42:04 ERROR <job_749840359> No project file or packages.config!
updater | 2023/11/14 16:42:04 ERROR <job_749840359> /home/dependabot/nuget/lib/dependabot/nuget/file_parser.rb:113:in `check_required_files'
updater | 2023/11/14 16:42:04 ERROR <job_749840359> /home/dependabot/common/lib/dependabot/file_parsers/base.rb:18:in `initialize'
updater | 2023/11/14 16:42:04 ERROR <job_749840359> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:80:in `new'
updater | 2023/11/14 16:42:04 ERROR <job_749840359> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:80:in `dependency_file_parser'
updater | 2023/11/14 16:42:04 ERROR <job_749840359> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:41:in `block in compile_all_dependency_changes_for'
updater | 2023/11/14 16:42:04 ERROR <job_749840359> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `each'
updater | 2023/11/14 16:42:04 ERROR <job_749840359> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `compile_all_dependency_changes_for'
updater | 2023/11/14 16:42:04 ERROR <job_749840359> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/refresh_group_update_pull_request.rb:90:in `perform'
updater | 2023/11/14 16:42:04 ERROR <job_749840359> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/11/14 16:42:04 ERROR <job_749840359> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/11/14 16:42:04 ERROR <job_749840359> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/14 16:42:04 ERROR <job_749840359> bin/update_files.rb:24:in `<main>'
updater | 2023/11/14 16:42:04 INFO <job_749840359> Sending event 3392bd046bd248e08f38fd2c71481992 to Sentry
  proxy | 2023/11/14 16:42:04 [304] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/11/14 16:42:04 [304] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/11/14 16:42:04 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------+
updater | |    Errors     |
updater | +---------------+
updater | | unknown_error |
updater | +---------------+
```

**Comment by abdulapopoola** [comment]
@joaorosado ; @landongrindheim just shipped improvements to this. Does this still occur for you?
