### ISSUE TITLE
Error while updating Python dependencies (missing pkg-config for mysqlclient)

### ISSUE THREAD

**Issue by vitaliyf** [dependabot/dependabot-core#8395]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

python

### Package manager version

pip-tools==7.3.0

### Language version

3.11

### What you expected to see, versus what you actually saw

We noticed that Dependabot stopped running in a few of our Python repos - I found the error below in its logs.

Perhaps this is related to pkg-config requirement that mysqlclient uses since v2.2.0 to detect MySQL libraries installed on the OS: https://github.com/PyMySQL/mysqlclient?tab=readme-ov-file#linux and https://github.com/PyMySQL/mysqlclient/discussions/639

### Images of the diff or a link to the PR, issue, or logs

```
updater | 2023/11/14 19:51:31 ERROR <job_749901490> Using pip-tools configuration defaults found in 'pyproject.toml'.
updater | Using indexes:
updater |   https://pypi.org/simple
updater | 
updater |                           ROUND 1                           
updater |   Collecting Django==4.2.4 (from -r requirements.in (line 1))
updater |     Using cached Django-4.2.4-py3-none-any.whl.metadata
...
updater |   Collecting mysqlclient==2.2.0 (from -r requirements.in (line 22))
updater |     Using cached mysqlclient-2.2.0.tar.gz
updater |     Preparing metadata (pyproject.toml): started
updater |     Preparing metadata (pyproject.toml): finished with status 'error'
updater |     error: subprocess-exited-with-error
updater |     
updater |     × Preparing metadata (pyproject.toml) did not run successfully.
updater |     │ exit code: 1
updater |     ╰─> [24 lines of output]
updater |         /bin/sh: 1: pkg-config: not found
updater |         /bin/sh: 1: pkg-config: not found
updater |         Trying pkg-config --exists mysqlclient
updater |         Command 'pkg-config --exists mysqlclient' returned non-zero exit status 127.
updater |         Trying pkg-config --exists mariadb
updater |         Command 'pkg-config --exists mariadb' returned non-zero exit status 127.
updater |         Traceback (most recent call last):
updater |           File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
updater |             main()
updater |           File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
updater |             json_out['return_val'] = hook(**hook_input['kwargs'])
updater |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |           File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
updater |             return hook(metadata_directory, config_settings)
updater |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |           File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/setuptools/build_meta.py", line 396, in prepare_metadata_for_build_wheel
updater |             self.run_setup()
updater |           File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
updater |             exec(code, locals())
updater |           File "<string>", line 154, in <module>
updater |           File "<string>", line 48, in get_config_posix
updater |           File "<string>", line 27, in find_package_name
updater |         Exception: Can not find valid pkg-config name.
updater |         Specify MYSQLCLIENT_CFLAGS and MYSQLCLIENT_LDFLAGS env vars manually
updater |         [end of output]
updater |     
updater |     note: This error originates from a subprocess, and is likely not a problem with pip.
updater | Traceback (most recent call last):
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
updater |     distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
updater |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 772, in prepare_metadata_for_build_wheel
updater |     return super().prepare_metadata_for_build_wheel(
updater |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
updater |     return self._call_hook('prepare_metadata_for_build_wheel', {
updater |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 311, in _call_hook
updater |     self._subprocess_runner(
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/utils/subprocess.py", line 252, in runner
updater |     call_subprocess(
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
updater |     raise error
updater | pip._internal.exceptions.InstallationSubprocessError: Preparing metadata (pyproject.toml) exited with 1
updater | 
updater | The above exception was the direct cause of the following exception:
updater | 
updater | Traceback (most recent call last):
updater |   File "/usr/local/.pyenv/versions/3.11.5/bin/pip-compile", line 8, in <module>
updater |     sys.exit(cli())
updater |              ^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
updater |     return self.main(*args, **kwargs)
updater |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/click/core.py", line 1078, in main
updater |     rv = self.invoke(ctx)
updater |          ^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
updater |     return ctx.invoke(self.callback, **ctx.params)
updater |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/click/core.py", line 783, in invoke
updater |     return __callback(*args, **kwargs)
updater |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/click/decorators.py", line 33, in new_func
updater |     return f(get_current_context(), *args, **kwargs)
updater |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/piptools/scripts/compile.py", line 659, in cli
updater |     results = resolver.resolve(max_rounds=max_rounds)
updater |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/piptools/resolver.py", line 604, in resolve
updater |     is_resolved = self._do_resolve(
updater |                   ^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/piptools/resolver.py", line 636, in _do_resolve
updater |     resolver.resolve(
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
updater |     result = self._result = resolver.resolve(
updater |                             ^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
updater |     state = resolution.resolve(requirements, max_rounds=max_rounds)
updater |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
updater |     self._add_to_criteria(self.state.criteria, r, parent=None)
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
updater |     if not criterion.candidates:
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
updater |     return bool(self._sequence)
updater |            ^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
updater |     return any(self)
updater |            ^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
updater |     return (c for c in iterator if id(c) not in self._incompatible_ids)
updater |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
updater |     candidate = func()
updater |                 ^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 211, in _make_candidate_from_link
updater |     self._link_candidate_cache[link] = LinkCandidate(
updater |                                        ^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 293, in __init__
updater |     super().__init__(
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
updater |     self.dist = self._prepare()
updater |                 ^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
updater |     dist = self._prepare_distribution()
updater |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in _prepare_distribution
updater |     return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
updater |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
updater |     return self._prepare_linked_requirement(req, parallel_builds)
updater |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
updater |     dist = _get_prepared_distribution(
updater |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
updater |     abstract_dist.prepare_distribution_metadata(
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 67, in prepare_distribution_metadata
updater |     self.req.prepare_metadata()
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 577, in prepare_metadata
updater |     self.metadata_directory = generate_metadata(
updater |                               ^^^^^^^^^^^^^^^^^^
updater |   File "/usr/local/.pyenv/versions/3.11.5/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 37, in generate_metadata
updater |     raise MetadataGenerationFailed(package_details=details) from error
updater | pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/common/lib/dependabot/shared_helpers.rb:427:in `run_shell_command'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:153:in `bind_call'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:227:in `run_command'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:274:in `run_pip_compile_command'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:94:in `compile_file'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:77:in `block (3 levels) in fetch_latest_resolvable_version_string'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:76:in `each'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:76:in `block (2 levels) in fetch_latest_resolvable_version_string'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/common/lib/dependabot/shared_helpers.rb:264:in `with_git_configured'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:72:in `block in fetch_latest_resolvable_version_string'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/common/lib/dependabot/shared_helpers.rb:80:in `block in in_a_temporary_directory'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/common/lib/dependabot/shared_helpers.rb:80:in `chdir'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/common/lib/dependabot/shared_helpers.rb:80:in `in_a_temporary_directory'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11094/lib/types/private/methods/call_validation.rb:177:in `block in create_validator_slow'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:71:in `fetch_latest_resolvable_version_string'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:51:in `latest_resolvable_version'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/python/lib/dependabot/python/update_checker/pip_compile_version_resolver.rb:61:in `resolvable?'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/python/lib/dependabot/python/update_checker.rb:40:in `latest_resolvable_version'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:76:in `preferred_resolvable_version'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:266:in `preferred_version_resolvable_with_unlock?'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:258:in `numeric_version_can_update?'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:208:in `version_can_update?'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:46:in `can_update?'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:211:in `requirements_to_unlock'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:90:in `check_and_create_pull_request'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/14 19:51:31 ERROR <job_749901490> bin/update_files.rb:24:in `<main>'
```

### Smallest manifest that reproduces the issue

```console
$ cat requirements.in

Django==4.2.4
...
mysqlclient==2.2.0
```

**Comment by gegoune** [comment]
Not an OP, but I experienced the same issue and can confirm that it is all resolved now. Thank you!

**Comment by vitaliyf** [comment]
Thank you - confirmed fixed.
