### ISSUE TITLE
Latest release not respecting nuget.config sources and not resolving variables correctly

### ISSUE THREAD

**Issue by joaorosado** [dependabot/dependabot-core#8470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### dependabot.yml content

version: 2
registries:
  nuget-feed-pkgs-dev-azure-com-redactedorgname-packaging-artifactrep:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json
    username: "${{secrets.NUGET_FEED_PKGS_DEV_AZURE_COM_PACKAGING_ARTIFACTREP_USERNAME}}"
    password: "${{secrets.NUGET_FEED_PKGS_DEV_AZURE_COM_PACKAGING_ARTIFACTREP_PASSWORD}}"

updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "dependencies"
  open-pull-requests-limit: 25
  rebase-strategy: disabled
  registries:
    - nuget-feed-pkgs-dev-azure-com-redactedorgname-packaging-artifactrep

### What you expected to see, versus what you actually saw

The repository also includes the NuGet.config as such (renamed accordingly the org part in all files on the issue):
```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <clear />
    <add key="Azure" value="https://pkgs.dev.azure.com/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json" />
  </packageSources>
</configuration>
```

3 days ago (on 24 November 2023) the output of one of the dependency checks, for example Newtonsoft.Json was correctly:
```
updater | 2023/11/24 19:26:27 INFO <job_754141353> Checking if Newtonsoft.Json 13.0.3 needs updating
  proxy | 2023/11/24 19:26:27 [376] GET https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/24 19:26:27 [376] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/24 19:26:27 [376] 200 https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/24 19:26:28 [378] GET https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
  proxy | 2023/11/24 19:26:28 [378] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/24 19:26:28 [378] 200 https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
updater | 2023/11/24 19:26:28 INFO <job_754141353> Latest version is 13.0.3
updater | 2023/11/24 19:26:28 INFO <job_754141353> No update needed for Newtonsoft.Json 13.0.3
updater | 2023/11/24 19:26:28 INFO <job_754141353> Finished job processing
```

Now today (on 27 November 2023) the output is:
```
updater | 2023/11/27 17:28:47 INFO <job_754874199> Checking if Newtonsoft.Json $NewtonsoftJsonVersion needs updating
  proxy | 2023/11/27 17:28:47 [878] GET https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/27 17:28:47 [878] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/27 17:28:47 [878] 200 https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/27 17:28:47 [880] GET https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
  proxy | 2023/11/27 17:28:47 [880] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/27 17:28:48 [880] 200 https://pkgs.dev.azure.com:443/RedactedOrgName/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
  proxy | 2023/11/27 17:28:48 [882] GET https://api.nuget.org:443/v3-flatcontainer/newtonsoft.json/$NewtonsoftJsonVersion/newtonsoft.json.nuspec
  proxy | 2023/11/27 17:28:48 [882] 404 https://api.nuget.org:443/v3-flatcontainer/newtonsoft.json/$NewtonsoftJsonVersion/newtonsoft.json.nuspec
  proxy | 2023/11/27 17:28:48 [884] GET https://pkgs.dev.azure.com:443/RedactedOrgName/_apis/packaging/feeds/ArtifactRepository/nuget/packages/Newtonsoft.Json/versions/$NewtonsoftJsonVersion/content?sourceProtocolVersion=nuget&api-version=7.0-preview
  proxy | 2023/11/27 17:28:48 [884] 401 https://pkgs.dev.azure.com:443/RedactedOrgName/_apis/packaging/feeds/ArtifactRepository/nuget/packages/Newtonsoft.Json/versions/$NewtonsoftJsonVersion/content?sourceProtocolVersion=nuget&api-version=7.0-preview
  proxy | 2023/11/27 17:28:48 [884] Remote response: {"$id":"1","innerException":null,"message":"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
updater | 2023/11/27 17:28:48 INFO <job_754874199> Latest version is 13.0.3
updater | 2023/11/27 17:28:48 INFO <job_754874199> No update needed for Newtonsoft.Json $NewtonsoftJsonVersion
```

So it not only is not able to search for the correct version numbers that are defined in Directory.Build.prop files in the root of the repository, but it is also completely ignoring the </ clear> instruction on the nuget sources, making it search directly on nuget.org.

![image](https://github.com/dependabot/dependabot-core/assets/5313340/fea72dfb-bc30-4e82-935e-c4eb25bd1ecc)

This is specially bad on private nugets that are only available on the private source, leaking information on requests to nuget.org and bypassing any gatekeeping of versions that may exist on the private source.

It also has the side effect of having closed all the PR's that already existed for libraries in this situation (at least for the private artifacts, not sure why it did not do the same for libraries that were also available on nuget.org, probably it did not close the ones that were not using Variables to define the versions, but all my private ones have that pattern):
![image](https://github.com/dependabot/dependabot-core/assets/5313340/5021fa57-5a5b-4cb7-b39f-f55a351f12d0)

Id's of the version update operations
 - Working: 754141353
 - Not Working: 754874199

**Comment by brettfo** [comment]
@joaorosado Can you share the repo where you're seeing these issues?  Testing locally the `<clear />` directive seems to work, but I'm obviously missing something.

Otherwise I'm also looking into the bad variable interpolation (e.g., `$NewtonsoftJsonVersion` appearing directly in a URL.)

**Comment by joaorosado** [comment]
Here is my sample repository that I created and was able to replicate the issue.
Also including the logs. All the files have the org name replaced with "RedactedOrg", but apart from that there are no other changes.

repo contents:
[jmr-dependabot8470.zip](https://github.com/dependabot/dependabot-core/files/13479911/jmr-dependabot8470.zip)

logs:
```
  proxy | 2023/11/27 20:18:17 proxy starting, commit: 6cffd6fae1b2f713f2d837bc45fe916f855c821d
  proxy | 2023/11/27 20:18:17 * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/27 20:18:17 Listening (:1080)
updater | 2023-11-27T20:18:18.193800803 [754962154:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-11-27T20:18:21Z" level=info msg="guest starting" commit=17df297b9449ef5936111b658329653bcfc0c9bc
updater | time="2023-11-27T20:18:21Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=754962154 updater_timeout=45m0s updater_version=16d9093a5d466356ce70e49608c627cfa4cfdcb7-nuget
updater | 2023/11/27 20:18:23 INFO Raven 3.1.2 ready to catch errors
updater | 2023/11/27 20:18:25 INFO <job_754962154> Starting job processing
  proxy | 2023/11/27 20:18:26 [002] GET https://github.com:443/RedactedOrg/jmr-dependabot8470/info/refs?service=git-upload-pack
  proxy | 2023/11/27 20:18:26 [002] * authenticating git server request (host: github.com)
  proxy | 2023/11/27 20:18:26 [002] 200 https://github.com:443/RedactedOrg/jmr-dependabot8470/info/refs?service=git-upload-pack
  proxy | 2023/11/27 20:18:26 [003] POST https://github.com:443/RedactedOrg/jmr-dependabot8470/git-upload-pack
  proxy | 2023/11/27 20:18:26 [003] * authenticating git server request (host: github.com)
  proxy | 2023/11/27 20:18:26 [003] 200 https://github.com:443/RedactedOrg/jmr-dependabot8470/git-upload-pack
  proxy | 2023/11/27 20:18:26 [004] POST https://github.com:443/RedactedOrg/jmr-dependabot8470/git-upload-pack
  proxy | 2023/11/27 20:18:26 [004] * authenticating git server request (host: github.com)
  proxy | 2023/11/27 20:18:26 [004] 200 https://github.com:443/RedactedOrg/jmr-dependabot8470/git-upload-pack
updater | 2023/11/27 20:18:26 INFO <job_754962154> Finished job processing
updater | time="2023-11-27T20:18:26Z" level=info msg="task complete" container_id=job-754962154-file-fetcher exit_code=0 job_id=754962154 step=fetcher
updater | 2023/11/27 20:18:29 INFO Raven 3.1.2 ready to catch errors
updater | 2023/11/27 20:18:30 INFO <job_754962154> Starting job processing
  proxy | 2023/11/27 20:18:30 [006] GET https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/27 20:18:30 [006] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/27 20:18:30 [006] 200 https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/27 20:18:31 [008] GET https://api.nuget.org:443/v3-flatcontainer/newtonsoft.json/$NewtonsoftJsonVersion/newtonsoft.json.nuspec
  proxy | 2023/11/27 20:18:31 [008] 404 https://api.nuget.org:443/v3-flatcontainer/newtonsoft.json/$NewtonsoftJsonVersion/newtonsoft.json.nuspec
  proxy | 2023/11/27 20:18:31 [010] GET https://pkgs.dev.azure.com:443/RedactedOrg/_apis/packaging/feeds/ArtifactRepository/nuget/packages/Newtonsoft.Json/versions/$NewtonsoftJsonVersion/content?sourceProtocolVersion=nuget&api-version=7.0-preview
  proxy | 2023/11/27 20:18:31 [010] 401 https://pkgs.dev.azure.com:443/RedactedOrg/_apis/packaging/feeds/ArtifactRepository/nuget/packages/Newtonsoft.Json/versions/$NewtonsoftJsonVersion/content?sourceProtocolVersion=nuget&api-version=7.0-preview
  proxy | 2023/11/27 20:18:31 [010] Remote response: {"$id":"1","innerException":null,"message":"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
updater | 2023/11/27 20:18:32 INFO <job_754962154> Starting update job for RedactedOrg/jmr-dependabot8470
updater | 2023/11/27 20:18:32 INFO <job_754962154> Checking all dependencies for version updates...
updater | 2023/11/27 20:18:32 INFO <job_754962154> Checking if Newtonsoft.Json $NewtonsoftJsonVersion needs updating
  proxy | 2023/11/27 20:18:32 [016] GET https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/27 20:18:32 [016] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/27 20:18:32 [016] 200 https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/ArtifactRepository/nuget/v3/index.json
  proxy | 2023/11/27 20:18:32 [018] GET https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
  proxy | 2023/11/27 20:18:32 [018] * authenticating nuget feed request (host: pkgs.dev.azure.com, basic auth)
  proxy | 2023/11/27 20:18:33 [018] 200 https://pkgs.dev.azure.com:443/RedactedOrg/_packaging/d8b4d1eb-aeb3-4b5b-9b43-37b4fc985e2f/nuget/v3/flat2/newtonsoft.json/index.json
  proxy | 2023/11/27 20:18:33 [020] GET https://api.nuget.org:443/v3-flatcontainer/newtonsoft.json/$NewtonsoftJsonVersion/newtonsoft.json.nuspec
  proxy | 2023/11/27 20:18:33 [020] 404 https://api.nuget.org:443/v3-flatcontainer/newtonsoft.json/$NewtonsoftJsonVersion/newtonsoft.json.nuspec
  proxy | 2023/11/27 20:18:33 [022] GET https://pkgs.dev.azure.com:443/RedactedOrg/_apis/packaging/feeds/ArtifactRepository/nuget/packages/Newtonsoft.Json/versions/$NewtonsoftJsonVersion/content?sourceProtocolVersion=nuget&api-version=7.0-preview
  proxy | 2023/11/27 20:18:33 [022] 401 https://pkgs.dev.azure.com:443/RedactedOrg/_apis/packaging/feeds/ArtifactRepository/nuget/packages/Newtonsoft.Json/versions/$NewtonsoftJsonVersion/content?sourceProtocolVersion=nuget&api-version=7.0-preview
  proxy | 2023/11/27 20:18:33 [022] Remote response: {"$id":"1","innerException":null,"message":"TF400813: The user 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' is not authorized to access this resource.","typeName":"Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server","typeKey":"UnauthorizedRequestException","errorCode":0,"eventId":3000}
updater | 2023/11/27 20:18:33 INFO <job_754962154> Latest version is 13.0.3
updater | 2023/11/27 20:18:33 INFO <job_754962154> No update needed for Newtonsoft.Json $NewtonsoftJsonVersion
updater | 2023/11/27 20:18:33 INFO <job_754962154> Finished job processing
updater | time="2023-11-27T20:18:33Z" level=info msg="task complete" container_id=job-754962154-updater exit_code=0 job_id=754962154 step=updater
```

We can see both issues of requests to nuget.org and the versions not working correctly.
Also note that the current version in the Directory.Build.props is set to 13.0.2 and up until last week dependabot was correctly updating this pattern.

**Comment by brettfo** [comment]
@joaorosado Thank you!  I know exactly what's happening with the `api.nuget.org`/`<clear />` issue and I'm working on a fix now.  (Actually, the fix was really easy, I just want to make sure it's well tested.)

**Comment by danmoseley** [comment]
I appear to be hitting something similar (not resolving variables) in https://github.com/dotnet/aspire as of the latest release. 

```
updater | 2023/11/28 03:01:48 ERROR <job_755234367> Malformed version number string $MicrosoftAspNetCoreOpenApiPackageVersion
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /usr/local/lib/ruby/3.1.0/rubygems/version.rb:223:in `initialize'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/common/lib/dependabot/version.rb:9:in `initialize'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/version.rb:27:in `initialize'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /usr/local/lib/ruby/3.1.0/rubygems/version.rb:204:in `new'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /usr/local/lib/ruby/3.1.0/rubygems/version.rb:204:in `new'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb:313:in `block (2 levels) in package_versions'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/nokogiri-1.15.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:235:in `block in each'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/nokogiri-1.15.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `upto'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/nokogiri-1.15.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `each'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb:308:in `block in package_versions'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb:305:in `each'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb:305:in `package_versions'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb:296:in `find_package_version'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb:286:in `dependency_requirement'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb:87:in `block in parse_dependencies'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/nokogiri-1.15.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:235:in `block in each'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/nokogiri-1.15.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `upto'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/nokogiri-1.15.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `each'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb:85:in `parse_dependencies'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser/project_file_parser.rb:52:in `dependency_set'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser.rb:39:in `block in project_file_dependencies'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser.rb:37:in `each'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser.rb:37:in `project_file_dependencies'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/nuget/lib/dependabot/nuget/file_parser.rb:25:in `parse'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:101:in `parse_files!'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:92:in `initialize'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:24:in `new'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:24:in `create_from_job_definition'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:17:in `perform_job'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/11/28 03:01:48 ERROR <job_755234367> bin/update_files.rb:24:in `<main>'
updater | 2023/11/28 03:01:48 INFO <job_755234367> Sending event 3b8639905565458ea589f47c335affdb to Sentry
  proxy | 2023/11/28 03:01:48 [934] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/11/28 03:01:48 [934] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/11/28 03:01:49 INFO <job_755234367> Finished job processing
updater | 2023/11/28 03:01:49 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
```

config
https://github.com/dotnet/aspire/blob/main/.github/dependabot.yml
where property is set
https://github.com/dotnet/aspire/blob/c6545a2b60213d3095865b9dda60553aaef63aed/eng/Versions.props#L37
where property is consumed
https://github.com/dotnet/aspire/blob/c6545a2b60213d3095865b9dda60553aaef63aed/Directory.Packages.props#L26  

it seems to be not correctly discovering that versions.props is getting imported into the project along with directory.packages.props. This was working until 11 hours ago, and I don't see any relevant changes in our repo. So I came to look here and I see a lot of changes in the last few hours in what seems like relevant code
https://github.com/dependabot/dependabot-core/commits/main/nuget/lib/dependabot/nuget
and then I found this issue.

@brettfo should I open a separate issue? 

(Aside, it might help in cases like this if the Github dependabot log included the SHA of the dependabot-core code? I am only guessing what is deployed by the date.)

**Comment by danmoseley** [comment]
@brettfo  thoughts - should I open a separate issue? Is there a way to use the old dependabot version?

**Comment by brettfo** [comment]
If you could open a separate issue that would be great.  I'm working on a fix now that _might_ cover your scenario, but I'd rather deal with a duplicate issue than lose track of it.

As for using the old version, I'm not sure how the images are stored and retrieved, so short of resetting your sources and building the old image and using that local copy, I'm not sure how to use the old one.

**Comment by danmoseley** [comment]
thanks, opened https://github.com/dependabot/dependabot-core/issues/8490
