### ISSUE TITLE
i have get some error on gihub nuget

### ISSUE THREAD

**Issue by firatoltulu** [dependabot/dependabot-core#8503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Language version

net6

### dependabot.yml content

i trying two options.

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/UI" 
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
      time: "09:00"
    allow:
      - dependency-name: "ShopExpress*"

OR

version: 2
registries:
  github:
    type: nuget-feed
    url: https://nuget.pkg.github.com/LivasoftConnector/index.json
    username: firatoltulu
    password: ${{ secrets.CLEARPASSWORD }}
    replaces-base: true
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries:
    - github
    open-pull-requests-limit: 50
    allow:
      - dependency-name: "ShopExpress*"
    schedule:
      interval: "daily"
      time: "09:00"
  - package-ecosystem: "github-actions"

### What you expected to see, versus what you actually saw

  proxy | 2023/12/01 07:14:29 [913] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 07:14:29 [913] 200 https://dc.services.visualstudio.com:443/v2/track
updater |   No global.json files found.
updater |   No dotnet-tools.json files found.
updater | Running for project [/home/dependabot/dependabot-updater/repo/ShopExpress.Module.Catalog.csproj]
updater |   Running for SDK-style project
updater |     Root package [ShopExpress.Module.Core/1.0.7] was not updated; skipping dependencies.
updater | Update complete.
updater | 2023/12/01 07:14:31 INFO <job_756956239> Sending event cfebd611665d4d94aa34d3e92f970943 to Sentry
  proxy | 2023/12/01 07:14:31 [919] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/12/01 07:14:31 [919] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/12/01 07:14:31 ERROR <job_756956239> Error processing ShopExpress.Module.Core (RuntimeError)
updater | 2023/12/01 07:14:31 ERROR <job_756956239> UpdateChecker found viable dependencies to be updated, but FileUpdater failed to update any files
updater | 2023/12/01 07:14:31 ERROR <job_756956239> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:136:in `check_and_create_pull_request'
updater | 2023/12/01 07:14:31 ERROR <job_756956239> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2023/12/01 07:14:31 ERROR <job_756956239> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2023/12/01 07:14:31 ERROR <job_756956239> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2023/12/01 07:14:31 ERROR <job_756956239> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2023/12/01 07:14:31 ERROR <job_756956239> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/12/01 07:14:31 ERROR <job_756956239> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/12/01 07:14:31 ERROR <job_756956239> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/12/01 07:14:31 ERROR <job_756956239> bin/update_files.rb:24:in `<main>'
updater | 2023/12/01 07:14:31 INFO <job_756956239> Checking if ShopExpress.Module.Infrastructure 1.0.3 needs updating
  proxy | 2023/12/01 07:14:31 [927] GET https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:31 [927] 200 https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:31 [929] GET https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.module.infrastructure&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:31 [929] 200 https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.module.infrastructure&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:31 [931] GET https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.module.infrastructure&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:32 [931] 200 https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.module.infrastructure&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:32 [933] GET https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.module.infrastructure/1.0.3/shopexpress.module.infrastructure.nuspec
  proxy | 2023/12/01 07:14:32 [933] 404 https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.module.infrastructure/1.0.3/shopexpress.module.infrastructure.nuspec
  proxy | 2023/12/01 07:14:32 [935] GET https://api.nuget.org:443/v3-flatcontainer/shopexpress.module.infrastructure/1.0.3/shopexpress.module.infrastructure.nuspec
  proxy | 2023/12/01 07:14:32 [935] 404 https://api.nuget.org:443/v3-flatcontainer/shopexpress.module.infrastructure/1.0.3/shopexpress.module.infrastructure.nuspec
updater | 2023/12/01 07:14:32 INFO <job_756956239> Latest version is 1.0.3
updater | 2023/12/01 07:14:32 INFO <job_756956239> No update needed for ShopExpress.Module.Infrastructure 1.0.3
updater | 2023/12/01 07:14:32 INFO <job_756956239> Checking if ShopExpress.Module.API 1.0.1 needs updating
  proxy | 2023/12/01 07:14:32 [937] GET https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:32 [937] 200 https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:32 [939] GET https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.module.api&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:32 [939] 200 https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.module.api&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:32 [941] GET https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.module.api&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:32 [941] 200 https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.module.api&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:32 [943] GET https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.module.api/1.0.1/shopexpress.module.api.nuspec
  proxy | 2023/12/01 07:14:32 [943] 404 https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.module.api/1.0.1/shopexpress.module.api.nuspec
  proxy | 2023/12/01 07:14:32 [945] GET https://api.nuget.org:443/v3-flatcontainer/shopexpress.module.api/1.0.1/shopexpress.module.api.nuspec
  proxy | 2023/12/01 07:14:32 [945] 404 https://api.nuget.org:443/v3-flatcontainer/shopexpress.module.api/1.0.1/shopexpress.module.api.nuspec
updater | 2023/12/01 07:14:32 INFO <job_756956239> Latest version is 1.0.1
updater | 2023/12/01 07:14:32 INFO <job_756956239> No update needed for ShopExpress.Module.API 1.0.1
updater | 2023/12/01 07:14:32 INFO <job_756956239> Checking if ShopExpress.QueryBuilderExecute 1.0.1 needs updating
  proxy | 2023/12/01 07:14:32 [947] GET https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:32 [947] 200 https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:32 [949] GET https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.querybuilderexecute&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:32 [949] 200 https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.querybuilderexecute&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:33 [951] GET https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.querybuilderexecute&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:33 [951] 200 https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.querybuilderexecute&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:33 [953] GET https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.querybuilderexecute/1.0.1/shopexpress.querybuilderexecute.nuspec
  proxy | 2023/12/01 07:14:33 [953] 404 https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.querybuilderexecute/1.0.1/shopexpress.querybuilderexecute.nuspec
  proxy | 2023/12/01 07:14:33 [955] GET https://api.nuget.org:443/v3-flatcontainer/shopexpress.querybuilderexecute/1.0.1/shopexpress.querybuilderexecute.nuspec
  proxy | 2023/12/01 07:14:33 [955] 404 https://api.nuget.org:443/v3-flatcontainer/shopexpress.querybuilderexecute/1.0.1/shopexpress.querybuilderexecute.nuspec
updater | 2023/12/01 07:14:33 INFO <job_756956239> Latest version is 1.0.1
updater | 2023/12/01 07:14:33 INFO <job_756956239> No update needed for ShopExpress.QueryBuilderExecute 1.0.1
updater | 2023/12/01 07:14:33 INFO <job_756956239> Checking if ShopExpress.Module.Shipping 1.0.2 needs updating
  proxy | 2023/12/01 07:14:33 [957] GET https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:33 [957] 200 https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:33 [959] GET https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.module.shipping&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:33 [959] 200 https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.module.shipping&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:33 [961] GET https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.module.shipping&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:33 [961] 200 https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.module.shipping&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:33 [963] GET https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.module.shipping/1.0.2/shopexpress.module.shipping.nuspec
  proxy | 2023/12/01 07:14:33 [963] 404 https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.module.shipping/1.0.2/shopexpress.module.shipping.nuspec
  proxy | 2023/12/01 07:14:33 [965] GET https://api.nuget.org:443/v3-flatcontainer/shopexpress.module.shipping/1.0.2/shopexpress.module.shipping.nuspec
  proxy | 2023/12/01 07:14:33 [965] 404 https://api.nuget.org:443/v3-flatcontainer/shopexpress.module.shipping/1.0.2/shopexpress.module.shipping.nuspec
updater | 2023/12/01 07:14:33 INFO <job_756956239> Latest version is 1.0.2
updater | 2023/12/01 07:14:33 INFO <job_756956239> No update needed for ShopExpress.Module.Shipping 1.0.2
updater | 2023/12/01 07:14:33 INFO <job_756956239> Checking if ShopExpress.Module.Discounts 1.0.2 needs updating
  proxy | 2023/12/01 07:14:33 [967] GET https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:33 [967] 200 https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:33 [969] GET https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.module.discounts&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:33 [969] 200 https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.module.discounts&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:34 [971] GET https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.module.discounts&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:34 [971] 200 https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.module.discounts&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:34 [973] GET https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.module.discounts/1.0.2/shopexpress.module.discounts.nuspec
  proxy | 2023/12/01 07:14:34 [973] 404 https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.module.discounts/1.0.2/shopexpress.module.discounts.nuspec
  proxy | 2023/12/01 07:14:34 [975] GET https://api.nuget.org:443/v3-flatcontainer/shopexpress.module.discounts/1.0.2/shopexpress.module.discounts.nuspec
  proxy | 2023/12/01 07:14:34 [975] 404 https://api.nuget.org:443/v3-flatcontainer/shopexpress.module.discounts/1.0.2/shopexpress.module.discounts.nuspec
updater | 2023/12/01 07:14:34 INFO <job_756956239> Latest version is 1.0.2
updater | 2023/12/01 07:14:34 INFO <job_756956239> No update needed for ShopExpress.Module.Discounts 1.0.2
updater | 2023/12/01 07:14:34 INFO <job_756956239> Checking if ShopExpress.Core 1.0.8 needs updating
  proxy | 2023/12/01 07:14:34 [977] GET https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:34 [977] 200 https://nuget.pkg.github.com:443/LivasoftConnector/index.json
  proxy | 2023/12/01 07:14:34 [979] GET https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.core&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:34 [979] 200 https://nuget.pkg.github.com:443/LivasoftConnector/query?q=shopexpress.core&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:34 [981] GET https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.core&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:34 [981] 200 https://azuresearch-usnc.nuget.org:443/query?q=shopexpress.core&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 07:14:34 [983] GET https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.core/1.0.8/shopexpress.core.nuspec
  proxy | 2023/12/01 07:14:34 [983] 404 https://nuget.pkg.github.com:443/LivasoftConnector-flatcontainer/shopexpress.core/1.0.8/shopexpress.core.nuspec
  proxy | 2023/12/01 07:14:34 [985] GET https://api.nuget.org:443/v3-flatcontainer/shopexpress.core/1.0.8/shopexpress.core.nuspec
  proxy | 2023/12/01 07:14:34 [985] 404 https://api.nuget.org:443/v3-flatcontainer/shopexpress.core/1.0.8/shopexpress.core.nuspec
updater | 2023/12/01 07:14:34 INFO <job_756956239> Latest version is 1.0.8
updater | 2023/12/01 07:14:34 INFO <job_756956239> No update needed for ShopExpress.Core 1.0.8
updater | 2023/12/01 07:14:34 INFO <job_756956239> Finished job processing
updater | 2023/12/01 07:14:34 INFO Results:
updater | Dependabot encountered '2' error(s) during execution, please check the logs for more details.
updater | +-----------------------------------------+
updater | |      Dependencies failed to update      |
updater | +-------------------------+---------------+
updater | | ShopExpress.Framework   | unknown_error |
updater | | ShopExpress.Module.Core | unknown_error |
updater | +-------------------------+---------------+
updater | time="2023-12-01T07:14:34Z" level=info msg="task complete" container_id=job-756956239-updater exit_code=0 job_id=756956239 step=updater

**Comment by JamieMagee** [comment]
@firatoltulu is this still occuring? We've made many improvements to the NuGet updater recently.
