### ISSUE TITLE
Error updating NuGet - Package does not exist as a dependency

### ISSUE THREAD

**Issue by eduherminio** [dependabot/dependabot-core#8505]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Language version

.NET 8

### Manifest location and content before the Dependabot update

https://github.com/eduherminio/AdventOfCode.Template/blob/main/AdventOfCode/AdventOfCode.csproj

### dependabot.yml content

https://github.com/eduherminio/AdventOfCode.Template/blob/main/.github/dependabot.yml

### Updated dependency

https://www.nuget.org/packages/AoCHelper from v3.0.0 to v3.1.0

### What you expected to see, versus what you actually saw

Please note that **last change in the repository was also performed by Dependabot, so no changes in configuration have taken place since then**

Dependabot is failing to update the single dependency he's monitoring in my repo

![image](https://github.com/dependabot/dependabot-core/assets/11148519/1fff1e31-a498-42e8-ab7b-98b557a0410e)

### Native package manager behavior

New packaged is restored correctly, as expected

### Images of the diff or a link to the PR, issue, or logs

<details>
<Summary>Dependabot logs</Summary>

```bash

  proxy | 2023/12/01 13:37:04 proxy starting, commit: 6cffd6fae1b2f713f2d837bc45fe916f855c821d
  proxy | 2023/12/01 13:37:04 Listening (:1080)
updater | 2023-12-01T13:37:04.666055833 [757147332:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-12-01T13:37:06Z" level=info msg="guest starting" commit=17df297b9449ef5936111b658329653bcfc0c9bc
updater | time="2023-12-01T13:37:06Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=757147332 updater_timeout=45m0s updater_version=650e132a94478a92e282498de9510fb8396960cc-nuget
updater | 2023/12/01 13:37:08 INFO Raven 3.1.2 ready to catch errors
updater | 2023/12/01 13:37:09 INFO <job_757147332> Starting job processing
  proxy | 2023/12/01 13:37:09 [002] GET https://github.com:443/eduherminio/AdventOfCode.Template/info/refs?service=git-upload-pack
  proxy | 2023/12/01 13:37:09 [002] * authenticating git server request (host: github.com)
  proxy | 2023/12/01 13:37:09 [002] 200 https://github.com:443/eduherminio/AdventOfCode.Template/info/refs?service=git-upload-pack
  proxy | 2023/12/01 13:37:09 [003] POST https://github.com:443/eduherminio/AdventOfCode.Template/git-upload-pack
  proxy | 2023/12/01 13:37:09 [003] * authenticating git server request (host: github.com)
  proxy | 2023/12/01 13:37:09 [003] 200 https://github.com:443/eduherminio/AdventOfCode.Template/git-upload-pack
  proxy | 2023/12/01 13:37:09 [004] POST https://github.com:443/eduherminio/AdventOfCode.Template/git-upload-pack
  proxy | 2023/12/01 13:37:09 [004] * authenticating git server request (host: github.com)
  proxy | 2023/12/01 13:37:09 [004] 200 https://github.com:443/eduherminio/AdventOfCode.Template/git-upload-pack
updater | 2023/12/01 13:37:10 INFO <job_757147332> Finished job processing
updater | time="2023-12-01T13:37:10Z" level=info msg="task complete" container_id=job-757147332-file-fetcher exit_code=0 job_id=757147332 step=fetcher
updater | 2023/12/01 13:37:11 INFO Raven 3.1.2 ready to catch errors
updater | 2023/12/01 13:37:12 INFO <job_757147332> Starting job processing
  proxy | 2023/12/01 13:37:12 [006] GET https://api.nuget.org:443/v3-flatcontainer/aochelper/3.0.0/aochelper.nuspec
  proxy | 2023/12/01 13:37:12 [006] 200 https://api.nuget.org:443/v3-flatcontainer/aochelper/3.0.0/aochelper.nuspec
  proxy | 2023/12/01 13:37:12 [008] GET https://api.nuget.org:443/v3-flatcontainer/spectre.console/0.48.0/spectre.console.nuspec
  proxy | 2023/12/01 13:37:12 [008] 200 https://api.nuget.org:443/v3-flatcontainer/spectre.console/0.48.0/spectre.console.nuspec
  proxy | 2023/12/01 13:37:12 [010] GET https://api.nuget.org:443/v3-flatcontainer/system.memory/4.5.5/system.memory.nuspec
  proxy | 2023/12/01 13:37:12 [010] 200 https://api.nuget.org:443/v3-flatcontainer/system.memory/4.5.5/system.memory.nuspec
  proxy | 2023/12/01 13:37:12 [012] GET https://api.nuget.org:443/v3-flatcontainer/system.buffers/4.5.1/system.buffers.nuspec
  proxy | 2023/12/01 13:37:12 [012] 200 https://api.nuget.org:443/v3-flatcontainer/system.buffers/4.5.1/system.buffers.nuspec
  proxy | 2023/12/01 13:37:12 [014] GET https://api.nuget.org:443/v3-flatcontainer/system.runtime/4.3.0/system.runtime.nuspec
  proxy | 2023/12/01 13:37:12 [014] 200 https://api.nuget.org:443/v3-flatcontainer/system.runtime/4.3.0/system.runtime.nuspec
  proxy | 2023/12/01 13:37:12 [016] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.netcore.platforms/1.1.0/microsoft.netcore.platforms.nuspec
  proxy | 2023/12/01 13:37:12 [016] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.netcore.platforms/1.1.0/microsoft.netcore.platforms.nuspec
  proxy | 2023/12/01 13:37:13 [018] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.netcore.targets/1.1.0/microsoft.netcore.targets.nuspec
  proxy | 2023/12/01 13:37:13 [018] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.netcore.targets/1.1.0/microsoft.netcore.targets.nuspec
  proxy | 2023/12/01 13:37:13 [020] GET https://api.nuget.org:443/v3-flatcontainer/system.runtime.compilerservices.unsafe/4.5.3/system.runtime.compilerservices.unsafe.nuspec
  proxy | 2023/12/01 13:37:13 [020] 200 https://api.nuget.org:443/v3-flatcontainer/system.runtime.compilerservices.unsafe/4.5.3/system.runtime.compilerservices.unsafe.nuspec
  proxy | 2023/12/01 13:37:13 [022] GET https://api.nuget.org:443/v3-flatcontainer/system.numerics.vectors/4.5.0/system.numerics.vectors.nuspec
  proxy | 2023/12/01 13:37:13 [022] 200 https://api.nuget.org:443/v3-flatcontainer/system.numerics.vectors/4.5.0/system.numerics.vectors.nuspec
  proxy | 2023/12/01 13:37:13 [024] GET https://api.nuget.org:443/v3-flatcontainer/netstandard.library/1.6.1/netstandard.library.nuspec
  proxy | 2023/12/01 13:37:13 [024] 200 https://api.nuget.org:443/v3-flatcontainer/netstandard.library/1.6.1/netstandard.library.nuspec
  proxy | 2023/12/01 13:37:13 [026] GET https://api.nuget.org:443/v3-flatcontainer/system.collections/4.3.0/system.collections.nuspec
  proxy | 2023/12/01 13:37:13 [026] 200 https://api.nuget.org:443/v3-flatcontainer/system.collections/4.3.0/system.collections.nuspec
  proxy | 2023/12/01 13:37:13 [028] GET https://api.nuget.org:443/v3-flatcontainer/system.diagnostics.debug/4.3.0/system.diagnostics.debug.nuspec
  proxy | 2023/12/01 13:37:13 [028] 200 https://api.nuget.org:443/v3-flatcontainer/system.diagnostics.debug/4.3.0/system.diagnostics.debug.nuspec
  proxy | 2023/12/01 13:37:13 [030] GET https://api.nuget.org:443/v3-flatcontainer/system.diagnostics.tools/4.3.0/system.diagnostics.tools.nuspec
  proxy | 2023/12/01 13:37:13 [030] 200 https://api.nuget.org:443/v3-flatcontainer/system.diagnostics.tools/4.3.0/system.diagnostics.tools.nuspec
  proxy | 2023/12/01 13:37:13 [032] GET https://api.nuget.org:443/v3-flatcontainer/system.globalization/4.3.0/system.globalization.nuspec
  proxy | 2023/12/01 13:37:13 [032] 200 https://api.nuget.org:443/v3-flatcontainer/system.globalization/4.3.0/system.globalization.nuspec
  proxy | 2023/12/01 13:37:13 [034] GET https://api.nuget.org:443/v3-flatcontainer/system.io/4.3.0/system.io.nuspec
  proxy | 2023/12/01 13:37:13 [034] 200 https://api.nuget.org:443/v3-flatcontainer/system.io/4.3.0/system.io.nuspec
  proxy | 2023/12/01 13:37:13 [036] GET https://api.nuget.org:443/v3-flatcontainer/system.text.encoding/4.3.0/system.text.encoding.nuspec
  proxy | 2023/12/01 13:37:13 [036] 200 https://api.nuget.org:443/v3-flatcontainer/system.text.encoding/4.3.0/system.text.encoding.nuspec
  proxy | 2023/12/01 13:37:13 [038] GET https://api.nuget.org:443/v3-flatcontainer/system.threading.tasks/4.3.0/system.threading.tasks.nuspec
  proxy | 2023/12/01 13:37:13 [038] 200 https://api.nuget.org:443/v3-flatcontainer/system.threading.tasks/4.3.0/system.threading.tasks.nuspec
  proxy | 2023/12/01 13:37:13 [040] GET https://api.nuget.org:443/v3-flatcontainer/system.linq/4.3.0/system.linq.nuspec
  proxy | 2023/12/01 13:37:13 [040] 200 https://api.nuget.org:443/v3-flatcontainer/system.linq/4.3.0/system.linq.nuspec
  proxy | 2023/12/01 13:37:13 [042] GET https://api.nuget.org:443/v3-flatcontainer/system.linq.expressions/4.3.0/system.linq.expressions.nuspec
  proxy | 2023/12/01 13:37:13 [042] 200 https://api.nuget.org:443/v3-flatcontainer/system.linq.expressions/4.3.0/system.linq.expressions.nuspec
  proxy | 2023/12/01 13:37:13 [044] GET https://api.nuget.org:443/v3-flatcontainer/system.reflection/4.3.0/system.reflection.nuspec
  proxy | 2023/12/01 13:37:13 [044] 200 https://api.nuget.org:443/v3-flatcontainer/system.reflection/4.3.0/system.reflection.nuspec
  proxy | 2023/12/01 13:37:13 [046] GET https://api.nuget.org:443/v3-flatcontainer/system.reflection.primitives/4.3.0/system.reflection.primitives.nuspec
  proxy | 2023/12/01 13:37:13 [046] 200 https://api.nuget.org:443/v3-flatcontainer/system.reflection.primitives/4.3.0/system.reflection.primitives.nuspec
  proxy | 2023/12/01 13:37:13 [048] GET https://api.nuget.org:443/v3-flatcontainer/system.net.primitives/4.3.0/system.net.primitives.nuspec
  proxy | 2023/12/01 13:37:13 [048] 200 https://api.nuget.org:443/v3-flatcontainer/system.net.primitives/4.3.0/system.net.primitives.nuspec
  proxy | 2023/12/01 13:37:14 [050] GET https://api.nuget.org:443/v3-flatcontainer/system.runtime.handles/4.3.0/system.runtime.handles.nuspec
  proxy | 2023/12/01 13:37:14 [050] 200 https://api.nuget.org:443/v3-flatcontainer/system.runtime.handles/4.3.0/system.runtime.handles.nuspec
  proxy | 2023/12/01 13:37:14 [052] GET https://api.nuget.org:443/v3-flatcontainer/system.objectmodel/4.3.0/system.objectmodel.nuspec
  proxy | 2023/12/01 13:37:14 [052] 200 https://api.nuget.org:443/v3-flatcontainer/system.objectmodel/4.3.0/system.objectmodel.nuspec
  proxy | 2023/12/01 13:37:14 [054] GET https://api.nuget.org:443/v3-flatcontainer/system.reflection.extensions/4.3.0/system.reflection.extensions.nuspec
  proxy | 2023/12/01 13:37:14 [054] 200 https://api.nuget.org:443/v3-flatcontainer/system.reflection.extensions/4.3.0/system.reflection.extensions.nuspec
  proxy | 2023/12/01 13:37:14 [056] GET https://api.nuget.org:443/v3-flatcontainer/system.resources.resourcemanager/4.3.0/system.resources.resourcemanager.nuspec
  proxy | 2023/12/01 13:37:14 [056] 200 https://api.nuget.org:443/v3-flatcontainer/system.resources.resourcemanager/4.3.0/system.resources.resourcemanager.nuspec
  proxy | 2023/12/01 13:37:14 [058] GET https://api.nuget.org:443/v3-flatcontainer/system.runtime.extensions/4.3.0/system.runtime.extensions.nuspec
  proxy | 2023/12/01 13:37:14 [058] 200 https://api.nuget.org:443/v3-flatcontainer/system.runtime.extensions/4.3.0/system.runtime.extensions.nuspec
  proxy | 2023/12/01 13:37:14 [060] GET https://api.nuget.org:443/v3-flatcontainer/system.text.encoding.extensions/4.3.0/system.text.encoding.extensions.nuspec
  proxy | 2023/12/01 13:37:14 [060] 200 https://api.nuget.org:443/v3-flatcontainer/system.text.encoding.extensions/4.3.0/system.text.encoding.extensions.nuspec
  proxy | 2023/12/01 13:37:14 [062] GET https://api.nuget.org:443/v3-flatcontainer/system.text.regularexpressions/4.3.0/system.text.regularexpressions.nuspec
  proxy | 2023/12/01 13:37:14 [062] 200 https://api.nuget.org:443/v3-flatcontainer/system.text.regularexpressions/4.3.0/system.text.regularexpressions.nuspec
  proxy | 2023/12/01 13:37:14 [064] GET https://api.nuget.org:443/v3-flatcontainer/system.threading/4.3.0/system.threading.nuspec
  proxy | 2023/12/01 13:37:14 [064] 200 https://api.nuget.org:443/v3-flatcontainer/system.threading/4.3.0/system.threading.nuspec
  proxy | 2023/12/01 13:37:14 [066] GET https://api.nuget.org:443/v3-flatcontainer/system.xml.readerwriter/4.3.0/system.xml.readerwriter.nuspec
  proxy | 2023/12/01 13:37:14 [066] 200 https://api.nuget.org:443/v3-flatcontainer/system.xml.readerwriter/4.3.0/system.xml.readerwriter.nuspec
  proxy | 2023/12/01 13:37:14 [068] GET https://api.nuget.org:443/v3-flatcontainer/system.xml.xdocument/4.3.0/system.xml.xdocument.nuspec
  proxy | 2023/12/01 13:37:14 [068] 200 https://api.nuget.org:443/v3-flatcontainer/system.xml.xdocument/4.3.0/system.xml.xdocument.nuspec
  proxy | 2023/12/01 13:37:14 [070] GET https://api.nuget.org:443/v3-flatcontainer/system.collections.concurrent/4.3.0/system.collections.concurrent.nuspec
  proxy | 2023/12/01 13:37:14 [070] 200 https://api.nuget.org:443/v3-flatcontainer/system.collections.concurrent/4.3.0/system.collections.concurrent.nuspec
  proxy | 2023/12/01 13:37:14 [072] GET https://api.nuget.org:443/v3-flatcontainer/system.diagnostics.tracing/4.3.0/system.diagnostics.tracing.nuspec
  proxy | 2023/12/01 13:37:14 [072] 200 https://api.nuget.org:443/v3-flatcontainer/system.diagnostics.tracing/4.3.0/system.diagnostics.tracing.nuspec
  proxy | 2023/12/01 13:37:14 [074] GET https://api.nuget.org:443/v3-flatcontainer/system.io.compression/4.3.0/system.io.compression.nuspec
  proxy | 2023/12/01 13:37:14 [074] 200 https://api.nuget.org:443/v3-flatcontainer/system.io.compression/4.3.0/system.io.compression.nuspec
  proxy | 2023/12/01 13:37:14 [076] GET https://api.nuget.org:443/v3-flatcontainer/system.net.http/4.3.0/system.net.http.nuspec
  proxy | 2023/12/01 13:37:14 [076] 200 https://api.nuget.org:443/v3-flatcontainer/system.net.http/4.3.0/system.net.http.nuspec
  proxy | 2023/12/01 13:37:14 [078] GET https://api.nuget.org:443/v3-flatcontainer/system.security.cryptography.x509certificates/4.3.0/system.security.cryptography.x509certificates.nuspec
  proxy | 2023/12/01 13:37:14 [078] 200 https://api.nuget.org:443/v3-flatcontainer/system.security.cryptography.x509certificates/4.3.0/system.security.cryptography.x509certificates.nuspec
  proxy | 2023/12/01 13:37:14 [080] GET https://api.nuget.org:443/v3-flatcontainer/system.security.cryptography.algorithms/4.3.0/system.security.cryptography.algorithms.nuspec
  proxy | 2023/12/01 13:37:14 [080] 200 https://api.nuget.org:443/v3-flatcontainer/system.security.cryptography.algorithms/4.3.0/system.security.cryptography.algorithms.nuspec
  proxy | 2023/12/01 13:37:15 [082] GET https://api.nuget.org:443/v3-flatcontainer/system.security.cryptography.primitives/4.3.0/system.security.cryptography.primitives.nuspec
  proxy | 2023/12/01 13:37:15 [082] 200 https://api.nuget.org:443/v3-flatcontainer/system.security.cryptography.primitives/4.3.0/system.security.cryptography.primitives.nuspec
  proxy | 2023/12/01 13:37:15 [084] GET https://api.nuget.org:443/v3-flatcontainer/system.security.cryptography.encoding/4.3.0/system.security.cryptography.encoding.nuspec
  proxy | 2023/12/01 13:37:15 [084] 200 https://api.nuget.org:443/v3-flatcontainer/system.security.cryptography.encoding/4.3.0/system.security.cryptography.encoding.nuspec
  proxy | 2023/12/01 13:37:15 [086] GET https://api.nuget.org:443/v3-flatcontainer/system.runtime.interopservices/4.3.0/system.runtime.interopservices.nuspec
  proxy | 2023/12/01 13:37:15 [086] 200 https://api.nuget.org:443/v3-flatcontainer/system.runtime.interopservices/4.3.0/system.runtime.interopservices.nuspec
  proxy | 2023/12/01 13:37:15 [088] GET https://api.nuget.org:443/v3-flatcontainer/system.runtime.interopservices.runtimeinformation/4.3.0/system.runtime.interopservices.runtimeinformation.nuspec
  proxy | 2023/12/01 13:37:15 [088] 200 https://api.nuget.org:443/v3-flatcontainer/system.runtime.interopservices.runtimeinformation/4.3.0/system.runtime.interopservices.runtimeinformation.nuspec
  proxy | 2023/12/01 13:37:15 [090] GET https://api.nuget.org:443/v3-flatcontainer/system.runtime.numerics/4.3.0/system.runtime.numerics.nuspec
  proxy | 2023/12/01 13:37:15 [090] 200 https://api.nuget.org:443/v3-flatcontainer/system.runtime.numerics/4.3.0/system.runtime.numerics.nuspec
  proxy | 2023/12/01 13:37:15 [092] GET https://api.nuget.org:443/v3-flatcontainer/system.threading.timer/4.3.0/system.threading.timer.nuspec
  proxy | 2023/12/01 13:37:15 [092] 200 https://api.nuget.org:443/v3-flatcontainer/system.threading.timer/4.3.0/system.threading.timer.nuspec
  proxy | 2023/12/01 13:37:15 [094] GET https://api.nuget.org:443/v3-flatcontainer/microsoft.win32.primitives/4.3.0/microsoft.win32.primitives.nuspec
  proxy | 2023/12/01 13:37:15 [094] 200 https://api.nuget.org:443/v3-flatcontainer/microsoft.win32.primitives/4.3.0/microsoft.win32.primitives.nuspec
  proxy | 2023/12/01 13:37:15 [096] GET https://api.nuget.org:443/v3-flatcontainer/system.appcontext/4.3.0/system.appcontext.nuspec
  proxy | 2023/12/01 13:37:15 [096] 200 https://api.nuget.org:443/v3-flatcontainer/system.appcontext/4.3.0/system.appcontext.nuspec
  proxy | 2023/12/01 13:37:15 [098] GET https://api.nuget.org:443/v3-flatcontainer/system.console/4.3.0/system.console.nuspec
  proxy | 2023/12/01 13:37:15 [098] 200 https://api.nuget.org:443/v3-flatcontainer/system.console/4.3.0/system.console.nuspec
  proxy | 2023/12/01 13:37:15 [100] GET https://api.nuget.org:443/v3-flatcontainer/system.globalization.calendars/4.3.0/system.globalization.calendars.nuspec
  proxy | 2023/12/01 13:37:15 [100] 200 https://api.nuget.org:443/v3-flatcontainer/system.globalization.calendars/4.3.0/system.globalization.calendars.nuspec
  proxy | 2023/12/01 13:37:15 [102] GET https://api.nuget.org:443/v3-flatcontainer/system.io.compression.zipfile/4.3.0/system.io.compression.zipfile.nuspec
  proxy | 2023/12/01 13:37:15 [102] 200 https://api.nuget.org:443/v3-flatcontainer/system.io.compression.zipfile/4.3.0/system.io.compression.zipfile.nuspec
  proxy | 2023/12/01 13:37:15 [104] GET https://api.nuget.org:443/v3-flatcontainer/system.io.filesystem/4.3.0/system.io.filesystem.nuspec
  proxy | 2023/12/01 13:37:15 [104] 200 https://api.nuget.org:443/v3-flatcontainer/system.io.filesystem/4.3.0/system.io.filesystem.nuspec
  proxy | 2023/12/01 13:37:15 [106] GET https://api.nuget.org:443/v3-flatcontainer/system.io.filesystem.primitives/4.3.0/system.io.filesystem.primitives.nuspec
  proxy | 2023/12/01 13:37:15 [106] 200 https://api.nuget.org:443/v3-flatcontainer/system.io.filesystem.primitives/4.3.0/system.io.filesystem.primitives.nuspec
  proxy | 2023/12/01 13:37:15 [108] GET https://api.nuget.org:443/v3-flatcontainer/system.net.sockets/4.3.0/system.net.sockets.nuspec
  proxy | 2023/12/01 13:37:15 [108] 200 https://api.nuget.org:443/v3-flatcontainer/system.net.sockets/4.3.0/system.net.sockets.nuspec
  proxy | 2023/12/01 13:37:15 [110] GET https://api.nuget.org:443/v3-flatcontainer/system.threading.tasks.extensions/4.5.4/system.threading.tasks.extensions.nuspec
  proxy | 2023/12/01 13:37:15 [110] 200 https://api.nuget.org:443/v3-flatcontainer/system.threading.tasks.extensions/4.5.4/system.threading.tasks.extensions.nuspec
updater | 2023/12/01 13:37:16 INFO <job_757147332> Starting update job for eduherminio/AdventOfCode.Template
updater | 2023/12/01 13:37:16 INFO <job_757147332> Checking all dependencies for version updates...
updater | 2023/12/01 13:37:16 INFO <job_757147332> Checking if AoCHelper 3.0.0 needs updating
  proxy | 2023/12/01 13:37:16 [116] GET https://azuresearch-usnc.nuget.org:443/query?q=aochelper&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 13:37:18 [116] 200 https://azuresearch-usnc.nuget.org:443/query?q=aochelper&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/01 13:37:18 [118] GET https://api.nuget.org:443/v3-flatcontainer/aochelper/3.0.0/aochelper.nuspec
  proxy | 2023/12/01 13:37:18 [118] 200 https://api.nuget.org:443/v3-flatcontainer/aochelper/3.0.0/aochelper.nuspec
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli framework-check --project-tfms net8.0 --package-tfms net6.0 net7.0 net8.0 .NETStandard2.0 .NETStandard2.1 --verbose
updater | The package is compatible.
  proxy | 2023/12/01 13:37:18 [120] GET https://api.nuget.org:443/v3-flatcontainer/aochelper/3.1.0/aochelper.nuspec
  proxy | 2023/12/01 13:37:18 [120] 200 https://api.nuget.org:443/v3-flatcontainer/aochelper/3.1.0/aochelper.nuspec
updater | 2023/12/01 13:37:18 INFO <job_757147332> Latest version is 3.1.0
updater | 2023/12/01 13:37:18 INFO <job_757147332> Requirements to unlock all
updater | 2023/12/01 13:37:18 INFO <job_757147332> Requirements update strategy 
updater | Finding updated dependencies for AoCHelper.
  proxy | 2023/12/01 13:37:18 [122] GET https://api.nuget.org:443/v3-flatcontainer/aochelper/3.1.0/aochelper.nuspec
  proxy | 2023/12/01 13:37:18 [122] 200 https://api.nuget.org:443/v3-flatcontainer/aochelper/3.1.0/aochelper.nuspec
updater | 2023/12/01 13:37:18 INFO <job_757147332> Updating AoCHelper from 3.0.0 to 3.1.0
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/AdventOfCode/AdventOfCode.csproj --dependency AoCHelper --new-version 3.1.0 --previous-version 3.0.0  --verbose
  proxy | 2023/12/01 13:37:20 [126] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [127] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [128] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [128] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [126] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [129] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [130] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [130] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [131] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [129] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [132] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [127] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [133] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [131] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [134] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [132] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [135] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [133] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [136] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [134] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [137] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [135] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [136] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [137] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [138] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [139] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [140] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [138] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [141] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [139] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [142] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [141] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [143] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [142] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [140] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [144] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [145] POST https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [143] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [144] 200 https://dc.services.visualstudio.com:443/v2/track
  proxy | 2023/12/01 13:37:20 [145] 200 https://dc.services.visualstudio.com:443/v2/track
updater |   No global.json files found.
updater |   No dotnet-tools.json files found.
updater | Running for project [/home/dependabot/dependabot-updater/repo/AdventOfCode/AdventOfCode.csproj]
updater |   Running for SDK-style project
updater |     Package [AoCHelper] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/AdventOfCode/AdventOfCode.csproj].
updater | Update complete.
updater | 2023/12/01 13:37:20 INFO <job_757147332> Sending event 68d5b76830774cef8f5d5ca4430b8186 to Sentry
  proxy | 2023/12/01 13:37:21 [147] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/12/01 13:37:21 [147] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/12/01 13:37:21 ERROR <job_757147332> Error processing AoCHelper (RuntimeError)
updater | 2023/12/01 13:37:21 ERROR <job_757147332> UpdateChecker found viable dependencies to be updated, but FileUpdater failed to update any files
updater | 2023/12/01 13:37:21 ERROR <job_757147332> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:136:in `check_and_create_pull_request'
updater | 2023/12/01 13:37:21 ERROR <job_757147332> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2023/12/01 13:37:21 ERROR <job_757147332> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2023/12/01 13:37:21 ERROR <job_757147332> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2023/12/01 13:37:21 ERROR <job_757147332> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2023/12/01 13:37:21 ERROR <job_757147332> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/12/01 13:37:21 ERROR <job_757147332> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/12/01 13:37:21 ERROR <job_757147332> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/12/01 13:37:21 ERROR <job_757147332> bin/update_files.rb:24:in `<main>'
updater | 2023/12/01 13:37:21 INFO <job_757147332> Finished job processing
updater | 2023/12/01 13:37:21 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------------------------+
updater | | Dependencies failed to update |
updater | +---------------+---------------+
updater | | AoCHelper     | unknown_error |
updater | +---------------+---------------+
updater | time="2023-12-01T13:37:21Z" level=info msg="task complete" container_id=job-757147332-updater exit_code=0 job_id=757147332 step=updater

```
</details>

**Comment by eduherminio** [comment]
Duplicate/related to https://github.com/dependabot/dependabot-core/issues/8483?

**Comment by brettfo** [comment]
Running with the latest changes in `main` the only issue I'm seeing is that the updater doesn't yet support `net8.0`; that work is being tracked in #8530.
