### ISSUE TITLE
Microsoft.WebApplication.targets was not found

### ISSUE THREAD

**Issue by marco-carvalho** [dependabot/dependabot-core#8532]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Language version

.NET Framework 4.8

### What you expected to see, versus what you actually saw

My `.csproj` requires to have this:
```xml
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">10.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
  <Import Project="$(VSToolsPath)\WebApplications\Microsoft.WebApplication.targets" Condition="'$(VSToolsPath)' != ''" />
```

But it's returning this:
```sh
proxy | 2023/12/05 03:33:09 proxy starting, commit: 6cffd6fae1b2f713f2d837bc45fe916f855c821d
  proxy | 2023/12/05 03:33:09 Listening (:1080)
updater | 2023-12-05T03:33:09.359875555 [758398868:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-12-05T03:33:11Z" level=info msg="guest starting" commit=17df297b9449ef5936111b658329653bcfc0c9bc
updater | time="2023-12-05T03:33:11Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=758398868 updater_timeout=45m0s updater_version=02799aaab42129022507c66f73504ddaec7c0e74-nuget
updater | 2023/12/05 03:33:12 INFO Raven 3.1.2 ready to catch errors
updater | 2023/12/05 03:33:14 INFO <job_758398868> Starting job processing
  proxy | 2023/12/05 03:33:14 [002] GET https://github.com:443/turimmfo/turim-sistemas/info/refs?service=git-upload-pack
  proxy | 2023/12/05 03:33:14 [002] * authenticating git server request (host: github.com)
  proxy | 2023/12/05 03:33:14 [002] 200 https://github.com:443/turimmfo/turim-sistemas/info/refs?service=git-upload-pack
  proxy | 2023/12/05 03:33:14 [003] POST https://github.com:443/turimmfo/turim-sistemas/git-upload-pack
  proxy | 2023/12/05 03:33:14 [003] * authenticating git server request (host: github.com)
  proxy | 2023/12/05 03:33:14 [003] 200 https://github.com:443/turimmfo/turim-sistemas/git-upload-pack
  proxy | 2023/12/05 03:33:14 [004] POST https://github.com:443/turimmfo/turim-sistemas/git-upload-pack
  proxy | 2023/12/05 03:33:14 [004] * authenticating git server request (host: github.com)
  proxy | 2023/12/05 03:33:14 [004] 200 https://github.com:443/turimmfo/turim-sistemas/git-upload-pack
updater | 2023/12/05 03:33:15 INFO <job_758398868> Finished job processing
updater | time="2023-12-05T03:33:15Z" level=info msg="task complete" container_id=job-758398868-file-fetcher exit_code=0 job_id=758398868 step=fetcher
updater | 2023/12/05 03:33:16 INFO Raven 3.1.2 ready to catch errors
updater | 2023/12/05 03:33:17 INFO <job_758398868> Starting job processing
updater | 2023/12/05 03:33:17 INFO <job_758398868> Starting PR update job for turimmfo/turim-sistemas
updater | 2023/12/05 03:33:17 INFO <job_758398868> Checking if Turim.Log.Client 2.0.2 needs updating
  proxy | 2023/12/05 03:33:17 [010] GET https://nuget.pkg.github.com:443/turimmfo/index.json
  proxy | 2023/12/05 03:33:17 [010] 200 https://nuget.pkg.github.com:443/turimmfo/index.json
  proxy | 2023/12/05 03:33:18 [012] GET https://azuresearch-usnc.nuget.org:443/query?q=turim.log.client&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/05 03:33:18 [012] 200 https://azuresearch-usnc.nuget.org:443/query?q=turim.log.client&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/05 03:33:18 [014] GET https://nuget.pkg.github.com:443/turimmfo/query?q=turim.log.client&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/05 03:33:18 [014] 200 https://nuget.pkg.github.com:443/turimmfo/query?q=turim.log.client&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/05 03:33:18 [016] GET https://api.nuget.org:443/v3-flatcontainer/turim.log.client/2.0.2/turim.log.client.nuspec
  proxy | 2023/12/05 03:33:18 [016] 404 https://api.nuget.org:443/v3-flatcontainer/turim.log.client/2.0.2/turim.log.client.nuspec
  proxy | 2023/12/05 03:33:18 [018] GET https://nuget.pkg.github.com:443/turimmfo-flatcontainer/turim.log.client/2.0.2/turim.log.client.nuspec
  proxy | 2023/12/05 03:33:18 [018] 404 https://nuget.pkg.github.com:443/turimmfo-flatcontainer/turim.log.client/2.0.2/turim.log.client.nuspec
updater | 2023/12/05 03:33:18 INFO <job_758398868> Latest version is 2.0.8
updater | 2023/12/05 03:33:18 INFO <job_758398868> Requirements to unlock all
updater | 2023/12/05 03:33:18 INFO <job_758398868> Requirements update strategy 
updater | Finding updated dependencies for Turim.Log.Client.
  proxy | 2023/12/05 03:33:18 [020] GET https://nuget.pkg.github.com:443/turimmfo/index.json
  proxy | 2023/12/05 03:33:18 [020] 200 https://nuget.pkg.github.com:443/turimmfo/index.json
  proxy | 2023/12/05 03:33:18 [022] GET https://api.nuget.org:443/v3-flatcontainer/turim.log.client/2.0.8/turim.log.client.nuspec
  proxy | 2023/12/05 03:33:18 [022] 404 https://api.nuget.org:443/v3-flatcontainer/turim.log.client/2.0.8/turim.log.client.nuspec
  proxy | 2023/12/05 03:33:19 [024] GET https://nuget.pkg.github.com:443/turimmfo-flatcontainer/turim.log.client/2.0.8/turim.log.client.nuspec
  proxy | 2023/12/05 03:33:19 [024] 404 https://nuget.pkg.github.com:443/turimmfo-flatcontainer/turim.log.client/2.0.8/turim.log.client.nuspec
updater | 2023/12/05 03:33:19 INFO <job_758398868> Updating Turim.Log.Client from 2.0.2 to 2.0.8
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/Turim.Intranet.Web/TurimIntranet.csproj --dependency Turim.Log.Client --new-version 2.0.8 --previous-version 2.0.2  --verbose
updater | 2023/12/05 03:33:20 INFO <job_758398868> Sending event 154b6bb66bc646fb959a0bd2fe779cf7 to Sentry
  proxy | 2023/12/05 03:33:20 [026] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/12/05 03:33:20 [026] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/12/05 03:33:21 ERROR <job_758398868> Error processing Turim.Log.Client (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2023/12/05 03:33:21 ERROR <job_758398868> No global.json files found.
updater |   No dotnet-tools.json files found.
updater | Running for project [/home/dependabot/dependabot-updater/repo/Turim.Intranet.Web/TurimIntranet.csproj]
updater |   Found packages.config; running with NuGet.exe
updater |     Using packages directory [..\packages] for project [/home/dependabot/dependabot-updater/repo/Turim.Intranet.Web/TurimIntranet.csproj].
updater |     Finding MSBuild...
updater |     Running NuGet.exe with args: update /home/dependabot/dependabot-updater/repo/Turim.Intranet.Web/packages.config -Id Turim.Log.Client -Version 2.0.8 -RepositoryPath /home/dependabot/dependabot-updater/repo/Turim.Intranet.Web/..\packages -NonInteractive -MSBuildPath /usr/local/dotnet/current/sdk/7.0.305
updater |     Result: 1
updater |     Output:
updater | Using Msbuild from '/usr/local/dotnet/current/sdk/7.0.305'.
updater | The imported project "/usr/local/dotnet/current/sdk/7.0.305/Microsoft/VisualStudio/v17.0/WebApplications/Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "/usr/local/dotnet/current/sdk/7.0.305/Microsoft/VisualStudio/v17.0/WebApplications/Microsoft.WebApplication.targets" is correct, and that the file exists on disk.  /home/dependabot/dependabot-updater/repo/Turim.Intranet.Web/TurimIntranet.csproj
updater | 
updater | Error: System.Exception: Using Msbuild from '/usr/local/dotnet/current/sdk/7.0.305'.
updater | The imported project "/usr/local/dotnet/current/sdk/7.0.305/Microsoft/VisualStudio/v17.0/WebApplications/Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "/usr/local/dotnet/current/sdk/7.0.305/Microsoft/VisualStudio/v17.0/WebApplications/Microsoft.WebApplication.targets" is correct, and that the file exists on disk.  /home/dependabot/dependabot-updater/repo/Turim.Intranet.Web/TurimIntranet.csproj
updater | 
updater |    at NuGetUpdater.Core.PackagesConfigUpdater.RunNuget(List`1 args, String packagesDirectory, Logger logger) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs:line 93
updater | Unhandled exception: System.Exception: Using Msbuild from '/usr/local/dotnet/current/sdk/7.0.305'.
updater | The imported project "/usr/local/dotnet/current/sdk/7.0.305/Microsoft/VisualStudio/v17.0/WebApplications/Microsoft.WebApplication.targets" was not found. Confirm that the expression in the Import declaration "/usr/local/dotnet/current/sdk/7.0.305/Microsoft/VisualStudio/v17.0/WebApplications/Microsoft.WebApplication.targets" is correct, and that the file exists on disk.  /home/dependabot/dependabot-updater/repo/Turim.Intranet.Web/TurimIntranet.csproj
updater | 
updater |    at NuGetUpdater.Core.PackagesConfigUpdater.RunNuget(List`1 args, String packagesDirectory, Logger logger) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs:line 93
updater |    at NuGetUpdater.Core.PackagesConfigUpdater.UpdateDependencyAsync(String repoRootPath, String projectPath, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Boolean isTransitive, Logger logger) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/PackagesConfigUpdater.cs:line 59
updater |    at NuGetUpdater.Core.UpdaterWorker.RunForProjectAsync(String repoRootPath, String projectPath, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Boolean isTransitive) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs:line 77
updater |    at NuGetUpdater.Core.UpdaterWorker.RunAsync(String repoRootPath, String filePath, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Boolean isTransitive) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs:line 42
updater |    at NuGetUpdater.Cli.Commands.UpdateCommand.<>c__DisplayClass7_0.<<GetCommand>b__0>d.MoveNext() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/UpdateCommand.cs:line 37
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
updater |    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/common/lib/dependabot/shared_helpers.rb:427:in `run_shell_command'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/_methods.rb:275:in `block in _on_method_added'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/nuget/lib/dependabot/nuget/native_helpers.rb:87:in `run_nuget_updater_tool'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:65:in `block in try_update_projects'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:59:in `each'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:59:in `try_update_projects'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:31:in `block in updated_dependency_files'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:30:in `each'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/nuget/lib/dependabot/nuget/file_updater.rb:30:in `updated_dependency_files'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:89:in `generate_dependency_files'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:37:in `run'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb:94:in `check_and_update_pull_request'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/refresh_version_update_pull_request.rb:38:in `perform'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:39:in `perform_job'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/12/05 03:33:21 ERROR <job_758398868> bin/update_files.rb:24:in `<main>'
updater | 2023/12/05 03:33:21 INFO <job_758398868> Finished job processing
updater | 2023/12/05 03:33:21 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +----------------------------------+
updater | |  Dependencies failed to update   |
updater | +------------------+---------------+
updater | | Turim.Log.Client | unknown_error |
updater | +------------------+---------------+
updater | time="2023-12-05T03:33:21Z" level=info msg="task complete" container_id=job-758398868-updater exit_code=0 job_id=758398868 step=updater
```

**Comment by marco-carvalho** [comment]
I created https://github.com/dependabot/dependabot-core/pull/8531 to showcase the error
![image](https://github.com/dependabot/dependabot-core/assets/15821724/9ac6aa09-d5d7-4b5e-aad4-02834ffd0b2f)

**Comment by marco-carvalho** [comment]
I managed to make it work after installing this package:
https://www.nuget.org/packages/MSBuild.Microsoft.VisualStudio.Web.targets

**Comment by brettfo** [comment]
Thinking out loud here for a minute: adding an extra package seems out-of-scope for the NuGet updater, but that targets file is conditioned on `Condition="'$(VSToolsPath)' != ''"`, so perhaps if we can force-unset that variable after MSBuild starts up, we could avoid the issue all together.
