### ISSUE TITLE
Dependabot throws `dependency_file_not_resolvable` related to GitHub Packages NuGet feed

### ISSUE THREAD

**Issue by austindrenski** [dependabot/dependabot-core#8573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Language version

dotnet 8.0

### Manifest location and content before the Dependabot update

```console
$ tree
.
├── Directory.Build.props
├── Directory.Packages.props
├── SomeSolution.sln
├── global.json
└── src
    ├── Directory.Build.props
    └── SomeProject
        └── SomeProject.csproj
└── tests
    ├── Directory.Build.props
    └── SomeProject.Tests
        └── SomeProject.Tests.csproj

3 directories, 10 files
```

```csproj
<!-- Directory.Build.props -->
<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

</Project>
```

```csproj
<!-- Directory.Packages.props -->
<Project>

  <ItemGroup>
    <PackageVersion Include="AWSSDK.Core" Version="3.7.300.16" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageVersion Include="xunit" Version="2.6.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.5.4" />
  </ItemGroup>

</Project>
```

```csproj
<!-- src/Directory.Packages.props -->
<Project>

  <Import Project="../Directory.Build.props" />

</Project>
```

```csproj
<!-- src/SomeProject/SomeProject.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AWSSDK.Core" />
  </ItemGroup>

</Project>
```

```csproj
<!-- tests/Directory.Packages.props -->
<Project>

  <Import Project="../Directory.Build.props" />

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>

</Project>
```

```csproj
<!-- tests/SomeProject.Tests/SomeProject.Tests.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/SomeProject/SomeProject.csproj" />
  </ItemGroup>

</Project>
```

### dependabot.yml content

```yaml
version: 2

registries:

  github-nuget:
    type: nuget-feed
    url: https://nuget.pkg.github.com/{ORG}/index.json
    token: ***

updates:

- package-ecosystem: "nuget"
  directory: "/"
  registries:
  - github-nuget
  schedule:
    interval: "daily"
  groups:
    aws:
      patterns:
      - AWSSDK.*
    xunit:
      patterns:
      - xunit
      - xunit.*
```

_N.B. private organization name sanitized above as `{ORG}`._

### What you expected to see, versus what you actually saw

```
updater | 2023/12/08 17:11:52 INFO <job_760129926> Handled error whilst updating xunit: dependency_file_not_resolvable {:message=>"Unexpected NuGet feed format: https://nuget.pkg.github.com/{ORG}/index.json"}
```

https://github.com/dependabot/dependabot-core/blob/7fe92020c2dab8228b62644ddcd3c447ad02e316/nuget/lib/dependabot/nuget/update_checker/nupkg_fetcher.rb#L29-L37

_N.B. private organization name sanitized above as `{ORG}`._

### Images of the diff or a link to the PR, issue, or logs

```
updater | 2023/12/08 17:11:38 INFO <job_760129926> Starting update group for 'aws'
updater | 2023/12/08 17:11:38 INFO <job_760129926> Checking if AWSSDK.Core 3.7.300.16 needs updating
  proxy | 2023/12/08 17:11:38 [784] GET https://nuget.pkg.github.com:443/{ORG}/index.json
  proxy | 2023/12/08 17:11:38 [784] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2023/12/08 17:11:38 [784] 200 https://nuget.pkg.github.com:443/{ORG}/index.json
  proxy | 2023/12/08 17:11:38 [788] GET https://nuget.pkg.github.com:443/{ORG}/query?q=awssdk.core&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:38 [788] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2023/12/08 17:11:38 [788] 200 https://nuget.pkg.github.com:443/{ORG}/query?q=awssdk.core&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:38 [790] GET https://azuresearch-usnc.nuget.org:443/query?q=awssdk.core&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:38 [790] 200 https://azuresearch-usnc.nuget.org:443/query?q=awssdk.core&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:38 [792] GET https://nuget.pkg.github.com:443/{ORG}-flatcontainer/awssdk.core/3.7.300.16/awssdk.core.nuspec
  proxy | 2023/12/08 17:11:38 [792] 404 https://nuget.pkg.github.com:443/{ORG}-flatcontainer/awssdk.core/3.7.300.16/awssdk.core.nuspec
  proxy | 2023/12/08 17:11:38 [794] GET https://api.nuget.org:443/v3-flatcontainer/awssdk.core/3.7.300.16/awssdk.core.nuspec
  proxy | 2023/12/08 17:11:38 [794] 200 https://api.nuget.org:443/v3-flatcontainer/awssdk.core/3.7.300.16/awssdk.core.nuspec
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli framework-check --project-tfms netstandard2.0 net8.0 --package-tfms .NETFramework3.5 .NETFramework4.5 .NETStandard2.0 .NETCoreApp3.1 .NETCoreApp8.0 --verbose
updater | The package is compatible.
  proxy | 2023/12/08 17:11:39 [796] GET https://nuget.pkg.github.com:443/{ORG}-flatcontainer/awssdk.core/3.7.300.16/awssdk.core.nuspec
  proxy | 2023/12/08 17:11:39 [796] 404 https://nuget.pkg.github.com:443/{ORG}-flatcontainer/awssdk.core/3.7.300.16/awssdk.core.nuspec
  proxy | 2023/12/08 17:11:39 [798] GET https://api.nuget.org:443/v3-flatcontainer/awssdk.core/3.7.300.16/awssdk.core.nuspec
  proxy | 2023/12/08 17:11:39 [798] 200 https://api.nuget.org:443/v3-flatcontainer/awssdk.core/3.7.300.16/awssdk.core.nuspec
updater | 2023/12/08 17:11:39 INFO <job_760129926> Latest version is 3.7.300.16
updater | 2023/12/08 17:11:39 INFO <job_760129926> No update needed for AWSSDK.Core 3.7.300.16
updater | 2023/12/08 17:11:39 INFO <job_760129926> Nothing to update for Dependency Group: 'aws'
```

```
updater | 2023/12/08 17:11:51 INFO <job_760129926> Starting update group for 'xunit'
updater | 2023/12/08 17:11:51 INFO <job_760129926> Checking if xunit 2.6.2 needs updating
  proxy | 2023/12/08 17:11:51 [968] GET https://nuget.pkg.github.com:443/{ORG}/index.json
  proxy | 2023/12/08 17:11:51 [968] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2023/12/08 17:11:51 [968] 200 https://nuget.pkg.github.com:443/{ORG}/index.json
  proxy | 2023/12/08 17:11:51 [970] GET https://nuget.pkg.github.com:443/{ORG}/query?q=xunit&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:51 [970] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2023/12/08 17:11:51 [970] 200 https://nuget.pkg.github.com:443/{ORG}/query?q=xunit&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:51 [972] GET https://azuresearch-usnc.nuget.org:443/query?q=xunit&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:52 [972] 200 https://azuresearch-usnc.nuget.org:443/query?q=xunit&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:52 [974] GET https://nuget.pkg.github.com:443/{ORG}-flatcontainer/xunit/2.6.2/xunit.nuspec
  proxy | 2023/12/08 17:11:52 [974] 404 https://nuget.pkg.github.com:443/{ORG}-flatcontainer/xunit/2.6.2/xunit.nuspec
  proxy | 2023/12/08 17:11:52 [976] GET https://api.nuget.org:443/v3-flatcontainer/xunit/2.6.2/xunit.nuspec
  proxy | 2023/12/08 17:11:52 [976] 200 https://api.nuget.org:443/v3-flatcontainer/xunit/2.6.2/xunit.nuspec
updater | 2023/12/08 17:11:52 INFO <job_760129926> Handled error whilst updating xunit: dependency_file_not_resolvable {:message=>"Unexpected NuGet feed format: https://nuget.pkg.github.com/{ORG}/index.json"}
updater | 2023/12/08 17:11:52 INFO <job_760129926> Checking if xunit.runner.visualstudio 2.5.4 needs updating
  proxy | 2023/12/08 17:11:52 [980] GET https://nuget.pkg.github.com:443/{ORG}/index.json
  proxy | 2023/12/08 17:11:52 [980] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2023/12/08 17:11:52 [980] 200 https://nuget.pkg.github.com:443/{ORG}/index.json
  proxy | 2023/12/08 17:11:52 [983] GET https://nuget.pkg.github.com:443/{ORG}/query?q=xunit.runner.visualstudio&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:52 [983] * authenticating nuget feed request (host: nuget.pkg.github.com, bearer auth)
  proxy | 2023/12/08 17:11:52 [983] 200 https://nuget.pkg.github.com:443/{ORG}/query?q=xunit.runner.visualstudio&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:52 [985] GET https://azuresearch-usnc.nuget.org:443/query?q=xunit.runner.visualstudio&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:52 [985] 200 https://azuresearch-usnc.nuget.org:443/query?q=xunit.runner.visualstudio&prerelease=true&semVerLevel=2.0.0
  proxy | 2023/12/08 17:11:52 [987] GET https://nuget.pkg.github.com:443/{ORG}-flatcontainer/xunit.runner.visualstudio/2.5.4/xunit.runner.visualstudio.nuspec
  proxy | 2023/12/08 17:11:52 [987] 404 https://nuget.pkg.github.com:443/{ORG}-flatcontainer/xunit.runner.visualstudio/2.5.4/xunit.runner.visualstudio.nuspec
  proxy | 2023/12/08 17:11:52 [989] GET https://api.nuget.org:443/v3-flatcontainer/xunit.runner.visualstudio/2.5.4/xunit.runner.visualstudio.nuspec
  proxy | 2023/12/08 17:11:52 [989] 200 https://api.nuget.org:443/v3-flatcontainer/xunit.runner.visualstudio/2.5.4/xunit.runner.visualstudio.nuspec
  proxy | 2023/12/08 17:11:52 [991] GET https://nuget.pkg.github.com:443/{ORG}-flatcontainer/xunit.runner.visualstudio/2.5.4/xunit.runner.visualstudio.nuspec
  proxy | 2023/12/08 17:11:52 [991] 404 https://nuget.pkg.github.com:443/{ORG}-flatcontainer/xunit.runner.visualstudio/2.5.4/xunit.runner.visualstudio.nuspec
  proxy | 2023/12/08 17:11:52 [993] GET https://api.nuget.org:443/v3-flatcontainer/xunit.runner.visualstudio/2.5.4/xunit.runner.visualstudio.nuspec
  proxy | 2023/12/08 17:11:52 [993] 200 https://api.nuget.org:443/v3-flatcontainer/xunit.runner.visualstudio/2.5.4/xunit.runner.visualstudio.nuspec
updater | 2023/12/08 17:11:52 INFO <job_760129926> Latest version is 2.5.4
updater | 2023/12/08 17:11:52 INFO <job_760129926> No update needed for xunit.runner.visualstudio 2.5.4
updater | 2023/12/08 17:11:53 INFO <job_760129926> Nothing to update for Dependency Group: 'xunit'
```

_N.B. private organization name sanitized above as `{ORG}`._

**Comment by jakecoffman** [comment]
@austindrenski can you verify that #8575 fixed this issue?

**Comment by brettfo** [comment]
Yesterday I identified another issue around the github package feeds.  I'm working on a fix now and should have it ready by the end of the week if not sooner.

Notes for myself so I dont forget: GitHub package feeds don't allow direct querying of `.nuspec` files; the `.nupkg` needs to be downloaded and expanded.

**Comment by mjfpalmer** [comment]
I'm getting similar issues with dependabot attempting to read the nuspec files of packages hosted in GitHub. Is this what you're looking to fix @brettfo?

```
updater | 2024/01/19 11:54:12 INFO <job_776251840> Checking all dependencies for version updates...
updater | 2024/01/19 11:54:12 INFO <job_776251840> Checking if Neo.Analysers 6.2.106 needs updating
updater | 2024/01/19 11:54:12 INFO <job_776251840> Latest version is 
updater | 2024/01/19 11:54:12 INFO <job_776251840> Requirements to unlock all
updater | 2024/01/19 11:54:12 INFO <job_776251840> Requirements update strategy 
updater | Finding updated dependencies for Neo.Analysers.
updater | 2024/01/19 11:54:12 INFO <job_776251840> Sending event cc3a362841da4e16adedc7212e9b9090 to Sentry
  proxy | 2024/01/19 11:54:12 [144] POST https://sentry.io:443/api/1451818/store/
  proxy | 2024/01/19 11:54:12 [144] 200 https://sentry.io:443/api/1451818/store/
updater | 2024/01/19 11:54:12 ERROR <job_776251840> Error processing Neo.Analysers (NoMethodError)
updater | 2024/01/19 11:54:12 ERROR <job_776251840> undefined method `fetch' for nil:NilClass
updater | 
updater |           latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s,
updater |                                                               ^^^^^^
updater | 2024/01/19 11:54:12 ERROR <job_776251840> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:47:in `updated_requirements'
updater | 2024/01/19 11:54:12 ERROR <job_776251840> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:101:in `updated_dependencies_after_full_unlock'
updater | 2024/01/19 11:54:12 ERROR <job_776251840> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:61:in `updated_dependencies'
updater | 2024/01/19 11:54:12 ERROR <job_776251840> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:99:in `check_and_create_pull_request'
updater | 2024/01/19 11:54:12 ERROR <job_776251840> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/19 11:54:12 ERROR <job_776251840> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/19 11:54:12 ERROR <job_776251840> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/19 11:54:12 ERROR <job_776251840> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/19 11:54:12 ERROR <job_776251840> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2024/01/19 11:54:12 ERROR <job_776251840> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/19 11:54:12 ERROR <job_776251840> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2024/01/19 11:54:12 ERROR <job_776251840> bin/update_files.rb:24:in `<main>'
```

**Comment by brettfo** [comment]
Yes, this appears to be the same issue. There were some other higher priority items that came up last week so I wasn't able to get the fix in, but it's something I'm still tracking and will be able to fix soon.

**Comment by jeffzickgraf** [comment]
@brettfo - We are using private nuget feeds hosted on Github and I am seeing the same issue @mjfpalmer is seeing when we are trying to use dependabot to create update PRs for our private repos. Is there an open issue we can track?

 Seeing same or similar failure:
 
`
updater | 2024/01/19 20:22:40 INFO <job_776426093> Checking all dependencies for version updates...
updater | 2024/01/19 20:22:40 INFO <job_776426093> Checking if PRIVATENAMESPACE.Service.Rest.Api 2.2.21 needs updating
updater | 2024/01/19 20:22:40 INFO <job_776426093> Latest version is 
updater | 2024/01/19 20:22:40 INFO <job_776426093> Requirements to unlock all
updater | 2024/01/19 20:22:40 INFO <job_776426093> Requirements update strategy 
updater | Finding updated dependencies for PRIVATENAMESPACE.Service.Rest.Api.
updater | 2024/01/19 20:22:40 INFO <job_776426093> Sending event be9ff95816d14d13b1a663afc6a6d89e to Sentry
  proxy | 2024/01/19 20:22:41 [032] POST https://sentry.io:443/api/1451818/store/
  proxy | 2024/01/19 20:22:41 [032] 200 https://sentry.io:443/api/1451818/store/
updater | 2024/01/19 20:22:41 ERROR <job_776426093> Error processing PRIVATENAMESPACE.Service.Rest.Api (NoMethodError)
updater | 2024/01/19 20:22:41 ERROR <job_776426093> undefined method fetch for nil:NilClass
updater | 
updater |           latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s,
updater |                                                               ^^^^^^
updater | 2024/01/19 20:22:41 ERROR <job_776426093> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:47:in updated_requirements
updater | 2024/01/19 20:22:41 ERROR <job_776426093> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:101:in updated_dependencies_after_full_unlock
updater | 2024/01/19 20:22:41 ERROR <job_776426093> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:61:in updated_dependencies
updater | 2024/01/19 20:22:41 ERROR <job_776426093> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:99:in check_and_create_pull_request
updater | 2024/01/19 20:22:41 ERROR <job_776426093> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in check_and_create_pr_with_error_handling
updater | 2024/01/19 20:22:41 ERROR <job_776426093> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in block in perform
updater | 2024/01/19 20:22:41 ERROR <job_776426093> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in each
updater | 2024/01/19 20:22:41 ERROR <job_776426093> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in perform
updater | 2024/01/19 20:22:41 ERROR <job_776426093> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in run
updater | 2024/01/19 20:22:41 ERROR <job_776426093> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in perform_job
updater | 2024/01/19 20:22:41 ERROR <job_776426093> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in run
updater | 2024/01/19 20:22:41 ERROR <job_776426093> bin/update_files.rb:24:in <main>





updater | Dependabot encountered 1 error(s) during execution, please check the logs for more details.
updater | +--------------------------------------+
updater | |    Dependencies failed to update     |
updater | +----------------------+---------------+
updater | | PRIVATENAMESPACE.Service.Rest.Api | unknown_error |
updater | +----------------------+---------------+`

**Comment by brettfo** [comment]
@jeffzickgraf Thank you for the logs.  It appears that's the same issue I mentioned in [this comment](https://github.com/dependabot/dependabot-core/issues/8837#issuecomment-1898947710) in another issue.  The short version is that we're trying to directly query the `.nuspec` file and not all feeds support that, so we're working on instead using the `RegistrationsBaseUrl` endpoint which appears to be supported by all feeds and still has the information we need.

**Comment by brettfo** [comment]
Is this error still appearing?  We've recently (last few weeks) merged some PRs that improve GitHub package feeds.  Some local testing shows it working, but if this issue is still showing up, I'd like to investigate it further.
