### ISSUE TITLE
Grouped dependency updates for NuGet packages not working correctly

### ISSUE THREAD

**Issue by martincostello** [dependabot/dependabot-core#8576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Package manager version

.NET 8.0.100 SDK

### Language version

C# 12

### Manifest location and content before the Dependabot update

[Directory.Packages.props](https://github.com/martincostello/project-euler/blob/67df63a5b2d0dd5289de98c24deeb00a2e538811/Directory.Packages.props)

### dependabot.yml content

[dependabot.yml](https://github.com/martincostello/project-euler/blob/52b6e016f5fd8d19dcf7a702085775b943e6f855/.github/dependabot.yml)

### Updated dependency

- xunit 2.6.2 => 2.6.3
- xunit.runner.visualstudio 2.5.4 => 2.5.5

### What you expected to see, versus what you actually saw

Dependabot reports in the pull request (https://github.com/martincostello/project-euler/pull/315) and the commit message (https://github.com/martincostello/project-euler/pull/315/commits/741ea1e80fb1bd5c9ab6dbf24001860ccc62efaf) that it has updated both of the xunit and xunit.runner.visualstudio NuGet packages.

However, on inspecting the Git diff only xunit.runner.visualstudio has been updated.

### Images of the diff or a link to the PR, issue, or logs

https://github.com/martincostello/project-euler/pull/315

```text
// snipped
updater | Finding updated dependencies for xunit.
  proxy | 2023/12/09 10:14:12 [260] GET https://api.nuget.org:443/v3-flatcontainer/xunit/2.6.3/xunit.nuspec
  proxy | 2023/12/09 10:14:12 [260] 200 https://api.nuget.org:443/v3-flatcontainer/xunit/2.6.3/xunit.nuspec
updater | 2023/12/09 10:14:12 INFO <job_760251202> Updating xunit from 2.6.2 to 2.6.3
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/tests/ProjectEuler.Tests/ProjectEuler.Tests.csproj --dependency xunit --new-version 2.6.3 --previous-version 2.6.2  --verbose
// snipped
updater |   Updating global.json files.
updater |     Dependency [xunit] not found in any global.json files.
updater |   No dotnet-tools.json files found.
updater | Running for project [/home/dependabot/dependabot-updater/repo/tests/ProjectEuler.Tests/ProjectEuler.Tests.csproj]
updater |   Running for SDK-style project
updater |     Found incorrect [PackageVersion] version attribute in [Directory.Packages.props].
updater |     Saved [Directory.Packages.props].
updater | Update complete.
updater | The contents of file [Directory.Packages.props] were updated.
// snipped
updater | 2023/12/09 10:14:39 INFO <job_760251202> Updating xunit.runner.visualstudio from 2.5.4 to 2.5.5
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/tests/ProjectEuler.Tests/ProjectEuler.Tests.csproj --dependency xunit.runner.visualstudio --new-version 2.5.5 --previous-version 2.5.4  --verbose
// snipped
updater | 2023/12/09 10:15:39 INFO Results:
updater | +--------------------------------------------------------------------------------------------+
updater | |                            Changes to Dependabot Pull Requests                             |
updater | +---------+----------------------------------------------------------------------------------+
updater | | created | xunit ( from 2.6.2 to 2.6.3 ), xunit.runner.visualstudio ( from 2.5.4 to 2.5.5 ) |
updater | | created | BenchmarkDotNet ( from 0.13.10 to 0.13.11 )                                      |
updater | +---------+----------------------------------------------------------------------------------+
updater | time="2023-12-09T10:15:39Z" level=info msg="task complete" container_id=job-760251202-updater exit_code=0 job_id=760251202 step=updater
```

**Comment by martincostello** [comment]
Manually re-running dependabot after the incorrect pull request is merged generates a PR that does update xunit to 2.6.3: https://github.com/martincostello/project-euler/pull/317.

**Comment by martincostello** [comment]
Similar issue here, except the package that was updated and the package that wasn't are the other way around: https://github.com/martincostello/website/pull/1717

**Comment by martincostello** [comment]
Another example, but in this case the commit in the pull request is completely empty: https://github.com/App-vNext/Polly/pull/1848

**Comment by erri120** [comment]
Same issue: https://github.com/Nexus-Mods/NexusMods.App/pull/811

**Comment by psiservices-dbrink** [comment]
same as #8475?

**Comment by martincostello** [comment]
Not sure. 23 days ago the previous xunit grouped update worked as expected. The NuGet implementation had a big overhaul in the last few weeks.

**Comment by jevvo-trimble** [comment]
Hello, any updates on this?
Have the same issue:
![image](https://github.com/dependabot/dependabot-core/assets/107613400/8170fd00-be56-4f89-8a9b-c3e79157619f)
![image](https://github.com/dependabot/dependabot-core/assets/107613400/29ab8d98-1a71-4309-b0ff-d793d5a38ad7)
Looks like grouping is picking only last time.
I have it on multiple projects with different dependency

**Comment by samtrion** [comment]
Same issue here ...
https://github.com/dailydevops/healthchecks/pull/154

**Comment by alex289** [comment]
I can also confirm this
https://github.com/alex289/CleanArchitecture/pull/47

**Comment by watercable76** [comment]
Can confirm this has been happening since at least December 4th. On November 27th, one of my projects had a dependabot PR that referenced Microsoft.EntityFrameworkCore.Sqlite and Microsoft.EntityFrameworkCore.SqlServer, and both packages were updated. 

After December 4th, grouped updates stopped working properly for just Nuget packages

**Comment by xt0rted** [comment]
> Can confirm this has been happening since at least December 4th.

This has been happening since November 27th in some of my repos https://github.com/xt0rted/dotnet-rimraf/pull/267.

The issue is most likely a bug in the new .net based nuget updater. This and other issues all started when [that was announced](https://github.blog/changelog/2023-11-28-improvements-to-nuget-support-for-dependabot/). At that time my .net 8 projects started randomly failing to update which ended up being due to https://github.com/dependabot/dependabot-core/issues/8530, and I'm also seeing duplicate package details in the PR/commit body sometimes as seen here https://github.com/dependabot/dependabot-core/issues/8631#issuecomment-1872661910.

**Comment by IsaacMarovitz** [comment]
Any update to this? This is a pretty frustrating bug

**Comment by dorssel** [comment]
Same problem for centralized package versions (`Directory.Packages.props`): https://github.com/dorssel/dotnet-debounce/pull/168

**Comment by psiservices-dbrink** [comment]
I hate to do this, but @deivid-rodriguez, is your team tracking this?  Grouped nuget updates have been broken for almost two months.

**Comment by trejjam** [comment]
I prepared a PR #8908 that should solve the issue with NuGet grouped updates, a review of changes is welcomed

___
*I am not a project maintainer*

**Comment by sebasgomez238** [comment]
@martincostello Hello, a fix for this went out yesterday #9228 and some people have confirmed it is working as expected. Let us know if it is working for you as well. Thanks.

**Comment by fuzzzerd** [comment]
> @martincostello Hello, a fix for this went out yesterday #9228 and some people have confirmed it is working as expected. Let us know if it is working for you as well. Thanks.

Unsure if its related, but I am getting a lot of exceptions regarding .NET SDK installation failures on the dependabot update logs, here's a snip:

```

updater | 2024/03/08 15:49:58 INFO <job_797700327> Latest version is 2.7.0
updater | 2024/03/08 15:49:58 INFO <job_797700327> Requirements to unlock all
updater | 2024/03/08 15:49:58 INFO <job_797700327> Requirements update strategy 
updater | Finding updated dependencies for xunit.runner.console.
  proxy | 2024/03/08 15:49:58 [240] GET https://api.nuget.org:443/v3-flatcontainer/xunit.runner.console/2.7.0/xunit.runner.console.nuspec
  proxy | 2024/03/08 15:49:58 [240] 200 https://api.nuget.org:443/v3-flatcontainer/xunit.runner.console/2.7.0/xunit.runner.console.nuspec
updater | 2024/03/08 15:49:58 INFO <job_797700327> Updating xunit.runner.console from 2.6.6 to 2.7.0
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/tests/FMData.Rest.Tests/FMData.Rest.Tests.csproj --dependency xunit.runner.console --new-version 2.7.0 --previous-version 2.6.6 --verbose
updater | 2024/03/08 15:49:58 ERROR <job_797700327> Block argument of NuGetConfigCredentialHelpers::patch_nuget_config_for_action causes an exception A compatible .NET SDK was not found.
updater | 
updater | Requested SDK version: 8.0.101
updater | global.json file: /home/dependabot/dependabot-updater/repo/global.json
updater | 
updater | Installed SDKs:
updater | 
updater | Install the [8.0.101] .NET SDK or update [/home/dependabot/dependabot-updater/repo/global.json] to match an installed SDK.
updater | 
updater | Learn about SDK resolution:
updater | https://aka.ms/dotnet/sdk-not-found
updater | Unhandled exception: System.TypeInitializationException: The type initializer for 'NuGetUpdater.Core.MSBuildHelper' threw an exception.
updater |  ---> System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
updater |    at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
updater |    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
updater |    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
updater |    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
updater |    at NuGetUpdater.Core.MSBuildHelper.RegisterMSBuild() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 42
updater |    at NuGetUpdater.Core.MSBuildHelper..cctor() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 34
updater |    --- End of inner exception stack trace ---
updater |    at NuGetUpdater.Core.MSBuildHelper.RegisterMSBuild() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 40
updater |    at NuGetUpdater.Core.UpdaterWorker.RunAsync(String repoRootPath, String workspacePath, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Boolean isTransitive) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs:line 22
updater |    at NuGetUpdater.Cli.Commands.UpdateCommand.<>c__DisplayClass7_0.<<GetCommand>b__0>d.MoveNext() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/UpdateCommand.cs:line 37
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
updater |    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
updater | 8.0.100 [/usr/local/dotnet/current/sdk]:
updater | A compatible .NET SDK was not found.
updater | 
updater | Requested SDK version: 8.0.101
updater | global.json file: /home/dependabot/dependabot-updater/repo/global.json
updater | 
updater | Installed SDKs:
updater | 
updater | Install the [8.0.101] .NET SDK or update [/home/dependabot/dependabot-updater/repo/global.json] to match an installed SDK.
updater | 
updater | Learn about SDK resolution:
updater | https://aka.ms/dotnet/sdk-not-found
updater | Unhandled exception: System.TypeInitializationException: The type initializer for 'NuGetUpdater.Core.MSBuildHelper' threw an exception.
updater |  ---> System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
updater |    at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
updater |    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
updater |    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
updater |    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
updater |    at NuGetUpdater.Core.MSBuildHelper.RegisterMSBuild() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 42
updater |    at NuGetUpdater.Core.MSBuildHelper..cctor() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 34
updater |    --- End of inner exception stack trace ---
updater |    at NuGetUpdater.Core.MSBuildHelper.RegisterMSBuild() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 40
updater |    at NuGetUpdater.Core.UpdaterWorker.RunAsync(String repoRootPath, String workspacePath, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Boolean isTransitive) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs:line 22
updater |    at NuGetUpdater.Cli.Commands.UpdateCommand.<>c__DisplayClass7_0.<<GetCommand>b__0>d.MoveNext() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/UpdateCommand.cs:line 37
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
updater |    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
updater | 8.0.100 [/usr/local/dotnet/current/sdk]
updater | 
updater | running NuGet updater:
updater | /opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /home/dependabot/dependabot-updater/repo/tests/FMData.Xml.Tests/FMData.Xml.Tests.csproj --dependency xunit.runner.console --new-version 2.7.0 --previous-version 2.6.6 --verbose
updater | 2024/03/08 15:49:59 ERROR <job_797700327> Block argument of NuGetConfigCredentialHelpers::patch_nuget_config_for_action causes an exception A compatible .NET SDK was not found.
updater | 
updater | Requested SDK version: 8.0.101
updater | global.json file: /home/dependabot/dependabot-updater/repo/global.json
updater | 
updater | Installed SDKs:
updater | 
updater | Install the [8.0.101] .NET SDK or update [/home/dependabot/dependabot-updater/repo/global.json] to match an installed SDK.
updater | 
updater | Learn about SDK resolution:
updater | https://aka.ms/dotnet/sdk-not-found
updater | Unhandled exception: System.TypeInitializationException: The type initializer for 'NuGetUpdater.Core.MSBuildHelper' threw an exception.
updater |  ---> System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
updater |    at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
updater |    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
updater |    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
updater |    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
updater |    at NuGetUpdater.Core.MSBuildHelper.RegisterMSBuild() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 42
updater |    at NuGetUpdater.Core.MSBuildHelper..cctor() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 34
updater |    --- End of inner exception stack trace ---
updater |    at NuGetUpdater.Core.MSBuildHelper.RegisterMSBuild() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 40
updater |    at NuGetUpdater.Core.UpdaterWorker.RunAsync(String repoRootPath, String workspacePath, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Boolean isTransitive) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs:line 22
updater |    at NuGetUpdater.Cli.Commands.UpdateCommand.<>c__DisplayClass7_0.<<GetCommand>b__0>d.MoveNext() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/UpdateCommand.cs:line 37
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
updater |    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
updater | 8.0.100 [/usr/local/dotnet/current/sdk]:
updater | A compatible .NET SDK was not found.
updater | 
updater | Requested SDK version: 8.0.101
updater | global.json file: /home/dependabot/dependabot-updater/repo/global.json
updater | 
updater | Installed SDKs:
updater | 
updater | Install the [8.0.101] .NET SDK or update [/home/dependabot/dependabot-updater/repo/global.json] to match an installed SDK.
updater | 
updater | Learn about SDK resolution:
updater | https://aka.ms/dotnet/sdk-not-found
updater | Unhandled exception: System.TypeInitializationException: The type initializer for 'NuGetUpdater.Core.MSBuildHelper' threw an exception.
updater |  ---> System.InvalidOperationException: Failed to find all versions of .NET Core MSBuild. Call to hostfxr_resolve_sdk2. There may be more details in stderr.
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetSdkFromGlobalSettings(String workingDirectory)
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetDotNetBasePaths(String workingDirectory)+MoveNext()
updater |    at Microsoft.Build.Locator.DotNetSdkLocationHelper.GetInstances(String workingDirectory)+MoveNext()
updater |    at Microsoft.Build.Locator.MSBuildLocator.GetInstances(VisualStudioInstanceQueryOptions options)+MoveNext()
updater |    at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
updater |    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
updater |    at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
updater |    at NuGetUpdater.Core.MSBuildHelper.RegisterMSBuild() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 42
updater |    at NuGetUpdater.Core.MSBuildHelper..cctor() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 34
updater |    --- End of inner exception stack trace ---
updater |    at NuGetUpdater.Core.MSBuildHelper.RegisterMSBuild() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs:line 40
updater |    at NuGetUpdater.Core.UpdaterWorker.RunAsync(String repoRootPath, String workspacePath, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Boolean isTransitive) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs:line 22
updater |    at NuGetUpdater.Cli.Commands.UpdateCommand.<>c__DisplayClass7_0.<<GetCommand>b__0>d.MoveNext() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/UpdateCommand.cs:line 37
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
updater |    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
updater | 8.0.100 [/usr/local/dotnet/current/sdk]
updater | 
updater | 2024/03/08 15:49:59 ERROR <job_797700327> Error processing xunit.runner.console (Dependabot::DependabotError)
updater | 2024/03/08 15:49:59 ERROR <job_797700327> FileUpdater failed
updater | 2024/03/08 15:49:59 ERROR <job_797700327> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:69:in `run'
```

I'm seeing this across a few different repositories for different packages.

**Comment by abdulapopoola** [comment]
The crew has been shipping a lot of fixes in this area and this should have been addressed by #9228 ; can you confirm if this still repros?

**Comment by watercable76** [comment]
@sebasgomez238 just double checked the grouping. It seems to be working for packages, but the update message was displaying all packages, not just the ones matching the filter parameters. I have some rules in place to only get the updates for Microsoft packages, but I'm getting all packages in the update message.

For the actual file updates, I'm only seeing the packages matched by the grouping filers. Here is what my grouping looks like:  
```yaml
groups:
      microsoft:
        patterns:
          - 'Microsoft*'
      default:
        patterns:
          - '*'
        exclude-patterns:
          - 'Microsoft*'
```

**Comment by abdulapopoola** [comment]
@fuzzzerd , can you please file a new issue with this error to prevent bifurcating this thread 😄 ?

**Comment by abdulapopoola** [comment]
@watercable76 ; glad to hear this is now working. 

Regarding the update message issue; that seems to be a new and separate issue; could you please file a new issue with these details so it can be investigated?

**Comment by watercable76** [comment]
> @watercable76 ; glad to hear this is now working.
> 
> Regarding the update message issue; that seems to be a new and separate issue; could you please file a new issue with these details so it can be investigated?

Submitted the issue ticket, and it's #9248

**Comment by martincostello** [comment]
> @martincostello Hello, a fix for this went out yesterday #9228 and some people have confirmed it is working as expected. Let us know if it is working for you as well. Thanks.

I'm afraid I can't verify these issues at the moment as now I'm experiencing #9245.

**Comment by abdulapopoola** [comment]
@martincostello ; can you please try again? :)

**Comment by martincostello** [comment]
I've re-run dependabot on all my .NET repos and now there's only 3 that have some sort of error. I'll need to investigate a bit further as to if they're other specific existing issues or not.

I'll need to do a manual revert in a repo with a group defined later on today to see if this specific issue is resolved.

**Comment by martincostello** [comment]
Looks like it's behaving now 🥳

https://github.com/martincostello/alexa-london-travel/pull/1107
