### ISSUE TITLE
Helm Values error undefined method `named_captures' for nil:NilClass

### ISSUE THREAD

**Issue by caleblloyd** [dependabot/dependabot-core#8593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker (Helm)

### Manifest location and content before the Dependabot update

helm/charts/nats/values.yaml

### dependabot.yml content

https://github.com/nats-io/k8s/blob/c2df016039b443cef65d2bbacc2947ec7ed6dd4c/.github/dependabot.yml

### Updated dependency

Docker image `nats` should be updated from `2.10.5-alpine` to `2.10.6-alpine`

### What you expected to see, versus what you actually saw

On November 30, 2023 the Dependabot job ran fine.

On December 1, 2023, the Dependabot job started having errors with the Ruby exception in the logs.

There were no code changes committed to the repository on either of these dates.

### Images of the diff or a link to the PR, issue, or logs

```

  proxy | 2023/12/01 18:11:32 proxy starting, commit: 6cffd6fae1b2f713f2d837bc45fe916f855c821d
  proxy | 2023/12/01 18:11:32 Listening (:1080)
updater | 2023-12-01T18:11:32.904176528 [757272134:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2023-12-01T18:11:34Z" level=info msg="guest starting" commit=17df297b9449ef5936111b658329653bcfc0c9bc
updater | time="2023-12-01T18:11:34Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=757272134 updater_timeout=45m0s updater_version=e83cd566eb627cd83ed43645e38ef9caff47ed79-docker
updater | 2023/12/01 18:11:36 INFO Raven 3.1.2 ready to catch errors
updater | 2023/12/01 18:11:37 INFO <job_757272134> Starting job processing
  proxy | 2023/12/01 18:11:38 [002] GET https://api.github.com:443/repos/nats-io/k8s
  proxy | 2023/12/01 18:11:38 [002] * authenticating github api request with token for api.github.com
  proxy | 2023/12/01 18:11:38 [002] 200 https://api.github.com:443/repos/nats-io/k8s
  proxy | 2023/12/01 18:11:38 [004] GET https://api.github.com:443/repos/nats-io/k8s/git/refs/heads/main
  proxy | 2023/12/01 18:11:38 [004] * authenticating github api request with token for api.github.com
  proxy | 2023/12/01 18:11:38 [004] 200 https://api.github.com:443/repos/nats-io/k8s/git/refs/heads/main
  proxy | 2023/12/01 18:11:38 [006] GET https://api.github.com:443/repos/nats-io/k8s/contents/helm/charts/nats?ref=664ab971fa43f9418999cd942adab44e4068518a
  proxy | 2023/12/01 18:11:38 [006] * authenticating github api request with token for api.github.com
  proxy | 2023/12/01 18:11:38 [006] 200 https://api.github.com:443/repos/nats-io/k8s/contents/helm/charts/nats?ref=664ab971fa43f9418999cd942adab44e4068518a
  proxy | 2023/12/01 18:11:38 [008] GET https://api.github.com:443/repos/nats-io/k8s/contents/helm/charts/nats/Chart.yaml?ref=664ab971fa43f9418999cd942adab44e4068518a
  proxy | 2023/12/01 18:11:38 [008] * authenticating github api request with token for api.github.com
  proxy | 2023/12/01 18:11:38 [008] 200 https://api.github.com:443/repos/nats-io/k8s/contents/helm/charts/nats/Chart.yaml?ref=664ab971fa43f9418999cd942adab44e4068518a
  proxy | 2023/12/01 18:11:38 [010] GET https://api.github.com:443/repos/nats-io/k8s/contents/helm/charts/nats/values.yaml?ref=664ab971fa43f9418999cd942adab44e4068518a
  proxy | 2023/12/01 18:11:38 [010] * authenticating github api request with token for api.github.com
  proxy | 2023/12/01 18:11:38 [010] 200 https://api.github.com:443/repos/nats-io/k8s/contents/helm/charts/nats/values.yaml?ref=664ab971fa43f9418999cd942adab44e4068518a
updater | 2023/12/01 18:11:38 INFO <job_757272134> Finished job processing
updater | time="2023-12-01T18:11:38Z" level=info msg="task complete" container_id=job-757272134-file-fetcher exit_code=0 job_id=757272134 step=fetcher
updater | 2023/12/01 18:11:40 INFO Raven 3.1.2 ready to catch errors
updater | 2023/12/01 18:11:41 INFO <job_757272134> Starting job processing
updater | 2023/12/01 18:11:41 ERROR <job_757272134> undefined method `named_captures' for nil:NilClass
updater | 
updater |         tag_details = tag_value.to_s.match(TAG_WITH_DIGEST).named_captures
updater |                                                            ^^^^^^^^^^^^^^^
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:176:in `parse_helm'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:158:in `deep_fetch_images_from_hash'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:145:in `deep_fetch_images'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:163:in `block in deep_fetch_images_from_hash'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:163:in `each'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:163:in `flat_map'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:163:in `deep_fetch_images_from_hash'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:145:in `deep_fetch_images'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:110:in `block in workfile_file_dependencies'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:108:in `each'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:108:in `flat_map'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:108:in `workfile_file_dependencies'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:68:in `block in parse'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:67:in `each'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:67:in `parse'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:101:in `parse_files!'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:92:in `initialize'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:24:in `new'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:24:in `create_from_job_definition'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:17:in `perform_job'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2023/12/01 18:11:41 ERROR <job_757272134> bin/update_files.rb:24:in `<main>'
updater | 2023/12/01 18:11:41 INFO <job_757272134> Sending event ed1d7fb525004582877f2599fd4d4cfa to Sentry
  proxy | 2023/12/01 18:11:41 [012] POST https://sentry.io:443/api/1451818/store/
  proxy | 2023/12/01 18:11:41 [012] 200 https://sentry.io:443/api/1451818/store/
updater | 2023/12/01 18:11:41 INFO <job_757272134> Finished job processing
updater | 2023/12/01 18:11:41 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------+
updater | |       Errors       |
updater | +--------------------+
updater | | update_files_error |
updater | +--------------------+
updater | time="2023-12-01T18:11:41Z" level=info msg="task complete" container_id=job-757272134-updater exit_code=0 job_id=757272134 step=updater
```

### Smallest manifest that reproduces the issue

https://github.com/nats-io/k8s/blob/c2df016039b443cef65d2bbacc2947ec7ed6dd4c/helm/charts/nats/values.yaml

**Comment by caleblloyd** [comment]
Likely resolved by https://github.com/dependabot/dependabot-core/pull/6595

**Comment by caleblloyd** [comment]
Actually, the stack trace points to https://github.com/dependabot/dependabot-core/commit/18605c872e49fc33d691e3890b2e678d932bfab2#diff-bf60843c320a3c07f5ee0227493d35baea5b6ff42df9bfe0992f6cdfa26b3419R176 as the offending line

**Comment by tspascoal** [comment]
I was able to reproduce this as well.

I think @caleblloyd  is on the money the issue appears to have to be introduced on this [line](https://github.com/dependabot/dependabot-core/commit/18605c872e49fc33d691e3890b2e678d932bfab2#r136080229) 

It is now assuming the `tag` is always present when it's an optional attribute (`helm create` doesn't create a `Charts.yml` with a `tag` only `version` for example)

```
tag_details = tag_value.to_s.match(TAG_WITH_DIGEST).named_captures if tag
```

should fix it

**Comment by caleblloyd** [comment]
Thanks for fixing!  I can verify that Dependabot is running correctly again on that repo!
