### ISSUE TITLE
Updates fail if `vernier` is present in Gemfile

### ISSUE THREAD

**Issue by jdelStrother** [dependabot/dependabot-core#8731]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Bundler

### Package manager version

2.4.22

### Language version

ruby 3.2.2

### dependabot.yml content

```yaml
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "bundler" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    vendor: true
```

### What you expected to see, versus what you actually saw

I've recently added [vernier](https://github.com/jhawthorn/vernier/) to our Gemfile, which seems to be breaking all our dependabot bundler updates with `Could not find vernier-0.3.1 in any of the sources`. This prevents all gems in our Gemfile from updating, rather than just affecting Vernier.

I'm guessing that it's because vernier is only available for specific ruby versions, and dependabot is running a older ruby version?

```shell-session
$ curl https://index.rubygems.org:443/info/vernier
---
0.0.0 |checksum:dc7c9568f9d5852ef1bf305e04e415d891157c1b0f423fb810074073a4e20a41,ruby:>= 2.6.0
0.1.0 |checksum:d203a1271ef5ee3aefd182158a694a73493353911575008f973bb738a6f1af58,ruby:>= 2.6.0
0.1.1 |checksum:7bb12ea33a5be142e33a197ee95f5d0b4ff82face5038e3d72f2a03dc7cfd11f,ruby:>= 2.6.0
0.2.0 |checksum:f0f45d743daf3bf9ee74297311889d5c54324ca7db01c370effa96b1c4f69996,ruby:>= 3.2.0
0.2.1 |checksum:e1753307b49b36a37b0a34262bf85c66b927b60dadf09681fb4e3b93d17e485f,ruby:>= 3.2.0
0.3.0 |checksum:c22723fa0af45f5381cfb3690e12a0f66784b6c77d59c44cc228d052e8fdcd5b,ruby:>= 3.2.0
0.3.1 |checksum:5713b462b9ae09309673007277f0885201e6f7313d6b097dd9c50e571f4332b6,ruby:>= 3.2.1
```

I was hoping I might be able to sidestep the problem with something like `gem "vernier", install_if: -> { RUBY_VERSION >= '3.2.1' }`, but no such luck. Would love to hear of any other workarounds.

### Native package manager behavior

Updates gems as normal, doesn't complain about `Could not find vernier-0.3.1 in any of the sources`.

### Images of the diff or a link to the PR, issue, or logs

<summary>

Dependabot logs: [https://github.com/audioBoom/dependabot-vernier-test/network/updates/771198601](https://github.com/audioBoom/dependabot-vernier-test/network/updates/771198601)

<details>

```
proxy | 2024/01/08 15:49:21 proxy starting, commit: ebf3724b85167f0333b1131189a46fbdbda0c682
  proxy | 2024/01/08 15:49:21 Listening (:1080)
updater | 2024-01-08T15:49:21.712299410 [771198601:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-01-08T15:49:23Z" level=info msg="guest starting" commit=8a1b168c8ca08673d9dda4be763a54b3b64b5a0c
updater | time="2024-01-08T15:49:23Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=771198601 updater_timeout=45m0s updater_version=27ae3e1bb2847cf35d412bcc600f79a178f2c880-bundler
updater | 2024/01/08 15:49:25 INFO Raven 3.1.2 ready to catch errors
updater | 2024/01/08 15:49:26 INFO <job_771198601> Starting job processing
  proxy | 2024/01/08 15:49:27 [002] GET https://github.com:443/audioBoom/dependabot-vernier-test/info/refs?service=git-upload-pack
  proxy | 2024/01/08 15:49:27 [002] * authenticating git server request (host: github.com)
  proxy | 2024/01/08 15:49:27 [002] 200 https://github.com:443/audioBoom/dependabot-vernier-test/info/refs?service=git-upload-pack
  proxy | 2024/01/08 15:49:27 [004] POST https://github.com:443/audioBoom/dependabot-vernier-test/git-upload-pack
  proxy | 2024/01/08 15:49:27 [004] * authenticating git server request (host: github.com)
  proxy | 2024/01/08 15:49:27 [004] 200 https://github.com:443/audioBoom/dependabot-vernier-test/git-upload-pack
  proxy | 2024/01/08 15:49:27 [006] POST https://github.com:443/audioBoom/dependabot-vernier-test/git-upload-pack
  proxy | 2024/01/08 15:49:27 [006] * authenticating git server request (host: github.com)
  proxy | 2024/01/08 15:49:27 [006] 200 https://github.com:443/audioBoom/dependabot-vernier-test/git-upload-pack
updater | 2024/01/08 15:49:27 INFO <job_771198601> Finished job processing
updater | time="2024-01-08T15:49:27Z" level=info msg="task complete" container_id=job-771198601-file-fetcher exit_code=0 job_id=771198601 step=fetcher
updater | 2024/01/08 15:49:29 INFO Raven 3.1.2 ready to catch errors
updater | 2024/01/08 15:49:30 INFO <job_771198601> Starting job processing
updater | 2024/01/08 15:49:30 INFO <job_771198601> Starting update job for audioBoom/dependabot-vernier-test
updater | 2024/01/08 15:49:30 INFO <job_771198601> Checking all dependencies for version updates...
updater | 2024/01/08 15:49:30 INFO <job_771198601> Checking if vernier 0.3.1 needs updating
  proxy | 2024/01/08 15:49:31 [015] GET https://rubygems.org:443/api/v1/versions/vernier.json
  proxy | 2024/01/08 15:49:31 [015] 200 https://rubygems.org:443/api/v1/versions/vernier.json
updater | 2024/01/08 15:49:31 INFO <job_771198601> Latest version is 0.3.1
updater | 2024/01/08 15:49:31 INFO <job_771198601> No update needed for vernier 0.3.1
updater | 2024/01/08 15:49:31 INFO <job_771198601> Checking if rack-attack 6.6.1 needs updating
  proxy | 2024/01/08 15:49:31 [019] GET https://rubygems.org:443/api/v1/versions/rack-attack.json
  proxy | 2024/01/08 15:49:31 [019] 200 https://rubygems.org:443/api/v1/versions/rack-attack.json
updater | 2024/01/08 15:49:31 INFO <job_771198601> Latest version is 6.7.0
  proxy | 2024/01/08 15:49:32 [021] GET https://index.rubygems.org:443/versions
  proxy | 2024/01/08 15:49:32 [021] 200 https://index.rubygems.org:443/versions
  proxy | 2024/01/08 15:49:33 [024] GET https://index.rubygems.org:443/info/rack
  proxy | 2024/01/08 15:49:33 [024] 200 https://index.rubygems.org:443/info/rack
  proxy | 2024/01/08 15:49:33 [025] GET https://index.rubygems.org:443/info/rack-attack
  proxy | 2024/01/08 15:49:33 [025] 200 https://index.rubygems.org:443/info/rack-attack
  proxy | 2024/01/08 15:49:33 [027] GET https://index.rubygems.org:443/info/vernier
  proxy | 2024/01/08 15:49:33 [027] 200 https://index.rubygems.org:443/info/vernier
  proxy | 2024/01/08 15:49:33 [029] GET https://index.rubygems.org:443/info/json
  proxy | 2024/01/08 15:49:33 [029] 200 https://index.rubygems.org:443/info/json
updater | 2024/01/08 15:49:33 INFO <job_771198601> Requirements to unlock own
updater | 2024/01/08 15:49:33 INFO <job_771198601> Requirements update strategy bump_versions
updater | 2024/01/08 15:49:33 INFO <job_771198601> Updating rack-attack from 6.6.1 to 6.7.0
  proxy | 2024/01/08 15:49:34 [031] GET https://index.rubygems.org:443/versions
  proxy | 2024/01/08 15:49:34 [031] 206 https://index.rubygems.org:443/versions
  proxy | 2024/01/08 15:49:35 [033] GET https://index.rubygems.org:443/versions
  proxy | 2024/01/08 15:49:35 [033] 206 https://index.rubygems.org:443/versions
updater | 2024/01/08 15:49:36 INFO <job_771198601> Sending event d260d2bf34c34412824679fffe58b564 to Sentry
  proxy | 2024/01/08 15:49:36 [035] POST https://sentry.io:443/api/1451818/store/
  proxy | 2024/01/08 15:49:36 [035] 200 https://sentry.io:443/api/1451818/store/
updater | 2024/01/08 15:49:36 ERROR <job_771198601> Error processing rack-attack (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2024/01/08 15:49:36 ERROR <job_771198601> Could not find vernier-0.3.1 in any of the sources
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/common/lib/dependabot/shared_helpers.rb:188:in `run_helper_subprocess'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:153:in `bind_call'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/bundler/lib/dependabot/bundler/native_helpers.rb:64:in `block in run_bundler_subprocess'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.3/lib/bundler.rb:386:in `block in with_original_env'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.3/lib/bundler.rb:658:in `with_env'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.3/lib/bundler.rb:386:in `with_original_env'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/bundler/lib/dependabot/bundler/native_helpers.rb:60:in `run_bundler_subprocess'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:153:in `bind_call'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:153:in `validate_call_skip_block_type'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:95:in `block in create_validator_slow_skip_block_type'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb:69:in `block in build_updated_lockfile'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/common/lib/dependabot/shared_helpers.rb:57:in `block in in_a_temporary_repo_directory'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/common/lib/dependabot/shared_helpers.rb:57:in `chdir'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/common/lib/dependabot/shared_helpers.rb:57:in `in_a_temporary_repo_directory'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `bind_call'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:256:in `validate_call'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11142/lib/types/private/methods/call_validation.rb:177:in `block in create_validator_slow'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb:63:in `build_updated_lockfile'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb:47:in `updated_lockfile_content'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/bundler/lib/dependabot/bundler/file_updater.rb:158:in `updated_lockfile_content'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/bundler/lib/dependabot/bundler/file_updater.rb:42:in `updated_dependency_files'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:89:in `generate_dependency_files'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:37:in `run'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:128:in `check_and_create_pull_request'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2024/01/08 15:49:36 ERROR <job_771198601> bin/update_files.rb:24:in `<main>'
updater | 2024/01/08 15:49:36 INFO <job_771198601> Finished job processing
updater | 2024/01/08 15:49:36 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------------------------+
updater | | Dependencies failed to update |
updater | +---------------+---------------+
updater | | rack-attack   | unknown_error |
updater | +---------------+---------------+
updater | time="2024-01-08T15:49:36Z" level=info msg="task complete" container_id=job-771198601-updater exit_code=0 job_id=771198601 step=updater
```

</details>
</summary>

### Smallest manifest that reproduces the issue

I created a small reproduction here - 
https://github.com/audioBoom/dependabot-vernier-test

Note that having `vendor: true` in dependabot.yml seems necessary to trigger the issue.

**Comment by jdelStrother** [comment]
I also tried to avoid the issue by ignoring vernier in dependabot.yml - 

```yaml
  - package-ecosystem: bundler
    vendor: true
    ignore:
      - dependency-name: vernier
```

but that also fails when updating other gems:

```
updater | 2024/01/19 09:54:49 ERROR <job_776201363> Error processing blazer (Dependabot::SharedHelpers::HelperSubprocessFailed)
updater | 2024/01/19 09:54:49 ERROR <job_776201363> Could not find vernier-0.4.0 in any of the sources
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/common/lib/dependabot/shared_helpers.rb:188:in `run_helper_subprocess'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `bind_call'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `validate_call_skip_block_type'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:111:in `block in create_validator_slow_skip_block_type'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/bundler/lib/dependabot/bundler/native_helpers.rb:64:in `block in run_bundler_subprocess'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.3/lib/bundler.rb:386:in `block in with_original_env'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.3/lib/bundler.rb:658:in `with_env'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /usr/local/lib/ruby/gems/3.1.0/gems/bundler-2.5.3/lib/bundler.rb:386:in `with_original_env'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/bundler/lib/dependabot/bundler/native_helpers.rb:60:in `run_bundler_subprocess'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `bind_call'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `validate_call_skip_block_type'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:111:in `block in create_validator_slow_skip_block_type'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb:69:in `block in build_updated_lockfile'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/common/lib/dependabot/shared_helpers.rb:57:in `block in in_a_temporary_repo_directory'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/common/lib/dependabot/shared_helpers.rb:57:in `chdir'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/common/lib/dependabot/shared_helpers.rb:57:in `in_a_temporary_repo_directory'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:193:in `block in create_validator_slow'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb:63:in `build_updated_lockfile'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/bundler/lib/dependabot/bundler/file_updater/lockfile_updater.rb:47:in `updated_lockfile_content'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/bundler/lib/dependabot/bundler/file_updater.rb:158:in `updated_lockfile_content'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/bundler/lib/dependabot/bundler/file_updater.rb:42:in `updated_dependency_files'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:91:in `generate_dependency_files'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:37:in `run'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:128:in `check_and_create_pull_request'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:128:in `run_ungrouped_dependency_updates'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:63:in `perform'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:64:in `run'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:53:in `run'
updater | 2024/01/19 09:54:49 ERROR <job_776201363> bin/update_files.rb:24:in `<main>'
```

**Comment by jdelStrother** [comment]
Sounds like this might be blocked until Bundler 1 support gets dropped - https://github.com/dependabot/dependabot-core/issues/6457

**Comment by jeffwidman** [comment]
FYI: Bundler 1 was dropped:
* #6457
