### ISSUE TITLE
Private nuget feed is updated from nuget.org

### ISSUE THREAD

**Issue by Deif-Novotny** [dependabot/dependabot-core#8801]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### dependabot.yml content

``` yaml
version: 2
registries:
  nuget-azure-devops:
    type: nuget-feed
    url: https://pkgs.dev.azure.com/.../_packaging/.../nuget/v3/index.json
    token: PAT:value
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries:
      - nuget-azure-devops
    groups:
     my-group:
        patterns:
          - "myPackage*"
```

### What you expected to see, versus what you actually saw

Description:
I am trying to implement Azure Devops extension to create pipeline for automatic package update. 
I am using Azure DevOps Artifacts for my private packages. 
My private DevOps nuget package has same name as the existing package on public nuget.org.
I setup dependabot.yml register section with my private feed and provide newly generated PAT with full access.

Expected:
I am expecting that my package is checked and updated from my private feed.

Actual:
According to Dependabot logs the package is checked and updated from nuget.org 
I found that by difference in versoning number which I use for production (in logs=> below Found 32 version(s) in nuget.org [ Nearest version: 4.2.1 ]) and for my private feed (20240112.7.0).

Logs:
```
Found 1 dependency file(s) at commit ...
 - /MyProject.csproj
Parsing dependencies information
🌍 --> GET https://pkgs.dev.azure.com/../_packaging/.../nuget/v3/index.json
🌍 <-- 200 https://pkgs.dev.azure.com/.../_packaging/.../nuget/v3/index.json
🌍 --> GET https://pkgs.dev.azure.com/../_packaging/.../nuget/v3/query2/?q=idokladsdk&prerelease=true&semVerLevel=2.0.0
🌍 <-- 200 https://pkgs.dev.azure.com/.../_packaging/.../nuget/v3/query2/?q=idokladsdk&prerelease=true&semVerLevel=2.0.0
🌍 --> GET https://pkgs.dev.azure.com/.../_packaging/.../nuget/v3/index.json
🌍 <-- 200 https://pkgs.dev.azure.com/.../_packaging/.../nuget/v3/index.json
Found 1 dependencies
 - MyPackage (20240112.7.0)
🌍 --> GET https://dev.azure.com/.../_apis/connectionData
🌍 <-- 200 https://dev.azure.com/.../_apis/connectionData
🌍 --> GET https://dev.azure.com/.../_apis/git/repositories/Dependabot_private_sdk
🌍 <-- 200 https://dev.azure.com/.../_apis/git/repositories/Dependabot_private_sdk
🌍 --> GET https://dev.azure.com/.../_apis/git/repositories/Dependabot_private_sdk/pullrequests?api-version=6.0&searchCriteria.status=active&searchCriteria.creatorId=...&searchCriteria.targetRefName=refs/heads/main
🌍 <-- 200 https://dev.azure.com/.../_apis/git/repositories/Dependabot_private_sdk/pullrequests?api-version=6.0&searchCriteria.status=active&searchCriteria.creatorId=...&searchCriteria.targetRefName=refs/heads/main
Checking if MyPackage 20240112.7.0 needs updating
🌍 --> GET https://pkgs.dev.azure.com/.../_packaging/.../nuget/v3/index.json
🌍 <-- 200 https://pkgs.dev.azure.com/../_packaging/.../nuget/v3/index.json
🌍 --> GET https://pkgs.dev.azure.com/.../_packaging/.../nuget/v3/query2/?q=idokladsdk&prerelease=true&semVerLevel=2.0.0
🌍 <-- 200 https://pkgs.dev.azure.com/.../_packaging/.../nuget/v3/query2/?q=idokladsdk&prerelease=true&semVerLevel=2.0.0
Requirements to unlock all
Requirements update strategy 
Finding updated dependencies for MyPackage.
🌍 --> GET https://pkgs.dev.azure.com/.../_packaging/.../nuget/v3/index.json
🌍 <-- 200 https://pkgs.dev.azure.com/.../_packaging/.../nuget/v3/index.json
Updating MyPackage from 20240112.7.0 to 
running NuGet updater:
/opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --repo-root /home/dependabot/dependabot-updater/tmp/.../_git/Dependabot_private_sdk --solution-or-project /home/dependabot/dependabot-updater/tmp/.../_git/Dependabot_private_sdk/MyProject.csproj --dependency MyPackage--new-version 20240115.1.0 --previous-version 20240112.7.0  --verbose
  No global.json files found.
  No dotnet-tools.json files found.
Running for project [/home/dependabot/dependabot-updater/tmp/.../_git/Dependabot_private_sdk/MyProject.csproj]
  Running for SDK-style project
dotnet build in GetAllPackageDependenciesAsync failed. STDOUT: MSBuild version 17.8.3+195e7f5a3 for .NET
  Determining projects to restore...
/tmp/package-dependency-resolution_HxB7nd/Project.csproj : error NU1102: Unable to find package MyPackage with version (= 20240112.7.0)
/tmp/package-dependency-resolution_HxB7nd/Project.csproj : error NU1102:   - Found 32 version(s) in nuget.org [ Nearest version: 4.2.1 ]
  Failed to restore /tmp/package-dependency-resolution_HxB7nd/Project.csproj (in 1.08 sec).

Build FAILED.

/tmp/package-dependency-resolution_HxB7nd/Project.csproj : error NU1102: Unable to find package MyPackage with version (= 20240112.7.0)
/tmp/package-dependency-resolution_HxB7nd/Project.csproj : error NU1102:   - Found 32 version(s) in nuget.org [ Nearest version: 4.2.1 ]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:02.42

 STDERR: 

    Package [MyPackage] Does not exist as a dependency in [/home/dependabot/dependabot-updater/tmp/.../_git/Dependabot_private_sdk/MyProject.csproj].
Update complete.
Submitting MyPackage pull request for creation.
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11164/lib/types/_types.rb:222:in `must': Passed `nil` into T.must (TypeError)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.239.0/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb:41:in `prefixes'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.239.0/lib/dependabot/pull_request_creator/branch_namer/solo_strategy.rb:32:in `new_branch_name'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.239.0/lib/dependabot/pull_request_creator/branch_namer.rb:30:in `new_branch_name'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.239.0/lib/dependabot/pull_request_creator.rb:182:in `azure_creator'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.239.0/lib/dependabot/pull_request_creator.rb:118:in `create'
	from bin/update_script.rb:823:in `block in <main>'
	from bin/update_script.rb:539:in `each'
	from bin/update_script.rb:539:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1
```

**Comment by brettfo** [comment]
Recently #8748 was merged which should properly pass through the NuGet feeds (and not fall back to `nuget.org`); are you still seeing this failure?

**Comment by trejjam** [comment]
I hit the same issue with our private registry. I fixed it in this commit:
https://github.com/dependabot/dependabot-core/pull/8908/commits/d8abe8688c84cca9cb25abae37ac438cd05a521f

**Comment by trejjam** [comment]
It should be fixed by [PR 8908](https://github.com/dependabot/dependabot-core/pull/8908)

**Comment by Deif-Novotny** [comment]
Yes it looks like its fixed. Thank you.
