### ISSUE TITLE
NuGet. tfm_comparer.rb:18:in `sort': comparison of NilClass with Nokogiri::XML::Attr failed (ArgumentError)

### ISSUE THREAD

**Issue by evgenyvalavin** [dependabot/dependabot-core#8804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

NuGet

### Updated dependency

microsoft.appcenter.crashes 5.0.3 

### What you expected to see, versus what you actually saw

No issue while checking updates for microsoft.appcenter.crashes NuGet.

### Stack trace
```
Checking if Microsoft.AppCenter.Crashes 5.0.3 needs updating
🌍 --> GET https://pkgs.dev.azure.com/***/_packaging/***/nuget/v3/index.json
🌍 <-- 200 https://pkgs.dev.azure.com/***/_packaging/***/nuget/v3/index.json
🌍 --> GET https://pkgs.dev.azure.com/***/_packaging/3b290b05-0c7a-453e-83df-00b55b44e8ae/nuget/v3/query2/?q=microsoft.appcenter.crashes&prerelease=true&semVerLevel=2.0.0
🌍 <-- 200 https://pkgs.dev.azure.com/***/_packaging/3b290b05-0c7a-453e-83df-00b55b44e8ae/nuget/v3/query2/?q=microsoft.appcenter.crashes&prerelease=true&semVerLevel=2.0.0
🌍 --> GET https://azuresearch-usnc.nuget.org/query?q=microsoft.appcenter.crashes&prerelease=true&semVerLevel=2.0.0
🌍 <-- 200 https://azuresearch-usnc.nuget.org/query?q=microsoft.appcenter.crashes&prerelease=true&semVerLevel=2.0.0
🌍 --> GET https://api.nuget.org/v3-flatcontainer/microsoft.appcenter.crashes/5.0.3/microsoft.appcenter.crashes.nuspec
🌍 <-- 200 https://api.nuget.org/v3-flatcontainer/microsoft.appcenter.crashes/5.0.3/microsoft.appcenter.crashes.nuspec
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-nuget-0.239.0/lib/dependabot/nuget/update_checker/tfm_comparer.rb:18:in `sort': comparison of NilClass with Nokogiri::XML::Attr failed (ArgumentError)
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-nuget-0.239.0/lib/dependabot/nuget/update_checker/tfm_comparer.rb:18:in `are_frameworks_compatible?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-nuget-0.239.0/lib/dependabot/nuget/update_checker/compatibility_checker.rb:37:in `compatible?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-nuget-0.239.0/lib/dependabot/nuget/update_checker/version_finder.rb:93:in `str_version_compatible?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-nuget-0.239.0/lib/dependabot/nuget/update_checker/version_finder.rb:89:in `version_compatible?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-nuget-0.239.0/lib/dependabot/nuget/update_checker/version_finder.rb:82:in `find_compatible_version'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-nuget-0.239.0/lib/dependabot/nuget/update_checker/version_finder.rb:67:in `find_highest_compatible_version'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-nuget-0.239.0/lib/dependabot/nuget/update_checker/version_finder.rb:36:in `latest_version_details'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-nuget-0.239.0/lib/dependabot/nuget/update_checker.rb:122:in `latest_version_details'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-nuget-0.239.0/lib/dependabot/nuget/update_checker.rb:20:in `latest_version'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.239.0/lib/dependabot/update_checkers/base.rb:240:in `numeric_version_up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.239.0/lib/dependabot/update_checkers/base.rb:198:in `version_up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-common-0.239.0/lib/dependabot/update_checkers/base.rb:35:in `up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/dependabot-nuget-0.239.0/lib/dependabot/nuget/update_checker.rb:62:in `up_to_date?'
	from bin/update_script.rb:576:in `block in <main>'
	from bin/update_script.rb:539:in `each'
	from bin/update_script.rb:539:in `<main>'
```

### Smallest manifest that reproduces the issue

Just add microsoft.appcenter.crashes as a dependency and run Dependabot

**Comment by MichalTichy** [comment]
I'm facing the same issue (same package and everything).
We are using dependabot at Azure Devops
