### ISSUE TITLE
Nuget doesn't work with AWS Codeartifact private repo

### ISSUE THREAD

**Issue by Ronan-Landr** [dependabot/dependabot-core#8837]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Package manager version

3

### Manifest location and content before the Dependabot update

n/a

### dependabot.yml content

```
version: 2
registries:
  codeartifact:
    type: nuget-feed
    url: https://landr-**redacted**.d.codeartifact.us-east-1.amazonaws.com/nuget/landr/v3/index.json
    token: ${{secrets.CODEARTIFACT_TOKEN}}
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    registries:
      - codeartifact
    allow:
      - dependency-name: "LANDR.MicroServices.Core*"
    schedule:
      interval: "weekly"
```

### What you expected to see, versus what you actually saw

When running against an AWS Codeartifact nuget repository, dependabot fails to fetch `.nuspec` files, and ends up with 'unknown_error'.

``` 
  proxy | 2024/01/17 22:16:33 [034] GET https://landr-*redacted*.d.codeartifact.us-east-1.amazonaws.com:443/nuget/landr/v3/registration4/landr.microservices.core.servicebootstrapper/index.json
  proxy | 2024/01/17 22:16:33 [034] * authenticating nuget feed request (host: landr-*redacted*.d.codeartifact.us-east-1.amazonaws.com, bearer auth)
  proxy | 2024/01/17 22:16:33 [034] 200 https://landr-*redacted*.d.codeartifact.us-east-1.amazonaws.com:443/nuget/landr/v3/registration4/landr.microservices.core.servicebootstrapper/index.json
[...]
  proxy | 2024/01/17 22:16:38 [078] GET https://landr-*redacted*.d.codeartifact.us-east-1.amazonaws.com:443/nuget/landr/v3-flatcontainer/landr.microservices.core.servicebootstrapper/6.15.1/landr.microservices.core.servicebootstrapper.nuspec
  proxy | 2024/01/17 22:16:38 [078] 404 https://landr-*redacted*.d.codeartifact.us-east-1.amazonaws.com:443/nuget/landr/v3-flatcontainer/landr.microservices.core.servicebootstrapper/6.15.1/landr.microservices.core.servicebootstrapper.nuspec
[...]
updater | 2024/01/17 22:16:45 ERROR <job_775557849> Error processing LANDR.MicroServices.Core.Redis (NoMethodError)
updater | 2024/01/17 22:16:45 ERROR <job_775557849> undefined method `fetch' for nil:NilClass
updater | 
updater |           latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s,
updater |                                                               ^^^^^^
updater | 2024/01/17 22:16:45 ERROR <job_775557849> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:47:in `updated_requirements'
updater | 2024/01/17 22:16:45 ERROR <job_775557849> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:101:in `updated_dependencies_after_full_unlock'
updater | 2024/01/17 22:16:45 ERROR <job_775557849> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:61:in `updated_dependencies'
updater | 2024/01/17 22:16:45 ERROR <job_775557849> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:99:in `check_and_create_pull_request'
updater | 2024/01/17 22:16:45 ERROR <job_775557849> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/17 22:16:45 ERROR <job_775557849> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/17 22:16:45 ERROR <job_775557849> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/17 22:16:45 ERROR <job_775557849> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/17 22:16:45 ERROR <job_775557849> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/01/17 22:16:45 ERROR <job_775557849> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/17 22:16:45 ERROR <job_775557849> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/01/17 22:16:45 ERROR <job_775557849> bin/update_files.rb:24:in `<main>'
updater | 2024/01/17 22:16:45 INFO <job_775557849> Finished job processing
updater | 2024/01/17 22:16:45 INFO Results:
updater | Dependabot encountered '6' error(s) during execution, please check the logs for more details.
updater | +--------------------------------------------------------------+
updater | |                Dependencies failed to update                 |
updater | +----------------------------------------------+---------------+
updater | | LANDR.MicroServices.Core.ServiceBootstrapper | unknown_error |
updater | | LANDR.MicroServices.Core.Lambdas             | unknown_error |
updater | | LANDR.MicroServices.Core.EntityFrameworkCore | unknown_error |
updater | | LANDR.MicroServices.Core.TestHelpers         | unknown_error |
updater | | LANDR.MicroServices.Core.DataMigrator        | unknown_error |
updater | | LANDR.MicroServices.Core.Redis               | unknown_error |
updater | +----------------------------------------------+---------------+
```
(shown here only with `LANDR.MicroServices.Core.ServiceBootstrapper`, but all other packages exhibit the same 404 issue)

I believe this stems from https://github.com/dependabot/dependabot-core/blob/715b2548fd1792c85809a72bd1df7ab05a423b2b/nuget/lib/dependabot/nuget/update_checker/nuspec_fetcher.rb#L39, where the base URL is generated rather than being obtained from the `index.json` that we specify in dependabot.yml.

This index.json contains the following :
```
    {
      "@id": "https://landr-*redacted*.d.codeartifact.us-east-1.amazonaws.com/nuget/landr/v3/flatcontainer",
      "@type": "PackageBaseAddress/3.0.0"
    }
```
(note the `/flatcontainer`, vs `-flatcontainer`)

This might be related to other nuget issues, such as https://github.com/dependabot/dependabot-core/issues/8759

**Comment by brettfo** [comment]
Good find.  We have some scheduled work to stop querying the `.nuspec` files and instead use the `RegistrationsBaseUrl` endpoint which give us the same information (mainly because even if we were pulling from the proper URL, not all NuGet feeds support direct `.nuspec` access, so the registrations URL is better to use.)
