### ISSUE TITLE
Gitlab integration Problem with target_project_id not found

### ISSUE THREAD

**Issue by gemohr** [dependabot/dependabot-core#8846]
https://github.com/dependabot/dependabot-core/blob/5d94313a255299144fd3c597708f9b80080f72f5/common/lib/dependabot/pull_request_creator.rb#L297

I think you forgott the default value for the fetch.

Because gitlab produces error:
 /home/dependabot/dependabot-script/vendor/ruby/3.2.0/gems/dependabot-common-0.240.0/lib/dependabot/pull_request_creator.rb:297:in `fetch': key not found: :target_project_id (KeyError)
10:01:10  	from /home/dependabot/dependabot-script/vendor/ruby/3.2.0/gems/dependabot-common-0.240.0/lib/dependabot/pull_request_creator.rb:297:in `gitlab_creator'
10:01:10  	from /home/dependabot/dependabot-script/vendor/ruby/3.2.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
10:01:10  	from /home/dependabot/dependabot-script/vendor/ruby/3.2.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
10:01:10  	from /home/dependabot/dependabot-script/vendor/ruby/3.2.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
10:01:10  	from /home/dependabot/dependabot-script/vendor/ruby/3.2.0/gems/dependabot-common-0.240.0/lib/dependabot/pull_request_creator.rb:234:in `create'
10:01:10  	from /home/dependabot/dependabot-script/vendor/ruby/3.2.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
10:01:10  	from /home/dependabot/dependabot-script/vendor/ruby/3.2.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
10:01:10  	from /home/dependabot/dependabot-script/vendor/ruby/3.2.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
10:01:10  	from ./dependabot-script.rb:235:in `block (2 levels) in <main>'
10:01:10  	from ./dependabot-script.rb:158:in `each'
10:01:10  	from ./dependabot-script.rb:158:in `block in <main>'
10:01:10  	from ./dependabot-script.rb:101:in `each'
10:01:10  	from ./dependabot-script.rb:101:in `<main>'

**Comment by abdulapopoola** [comment]
Tagging @andrcuns
