### ISSUE TITLE
Dependabot encountered an unknown error when updating with a private packe set contains packages.config

### ISSUE THREAD

**Issue by probitdavid** [dependabot/dependabot-core#8900]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### dependabot.yml content

``` yaml
version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    registries: "*"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm" # See documentation for possible values
    registries:
      - probit-npm-registry
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
registries:
  probit-npm-registry:
    type: npm-registry
    url: https://npm.pkg.github.com
    token: xxxxxx
  probit-nuget-registry:
    type: nuget-feed
    url: https://nuget.pkg.github.com/probit-io/index.json
    username: xxxxx
    password: xxxxx
```

### What you expected to see, versus what you actually saw

Expected either a clean run or PR's to be created.
The same dependabot.yml on a project that just has only .csproject works successfully however if the project has both
a .csproject and packages.config then the message:
Errored with the message "Dependabot encountered an unknown error"
occurs every time dependabot tries to run.
Then npm update is fine

### Native package manager behavior

native package manager updates work fine

### Images of the diff or a link to the PR, issue, or logs

log output looks like this:
The failure is repeated for every package in packages.config
```
  proxy | 2024/01/25 20:30:05 proxy starting, commit: 07d59135734a484cdcd1b34f737c7bca281bcf94
  proxy | 2024/01/25 20:30:05 * authenticating nuget feed request (host: nuget.pkg.github.com, basic auth)
  proxy | 2024/01/25 20:30:05 Listening (:1080)
updater | 2024-01-25T20:30:05.899661371 [778885900:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-01-25T20:30:08Z" level=info msg="guest starting" commit=5265bc7c42825390c331713cef4ed23c69721bbb
updater | time="2024-01-25T20:30:08Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=778885900 updater_timeout=45m0s updater_version=d418474b7aeaa1d9a053796a144a8039fd8f9923-nuget
updater | 2024/01/25 20:30:12 INFO <job_778885900> Starting job processing
  proxy | 2024/01/25 20:30:12 [002] GET https://github.com:443/probit-io/aim4/info/refs?service=git-upload-pack
  proxy | 2024/01/25 20:30:12 [002] * authenticating git server request (host: github.com)
  proxy | 2024/01/25 20:30:12 [002] 200 https://github.com:443/probit-io/aim4/info/refs?service=git-upload-pack
  proxy | 2024/01/25 20:30:12 [004] POST https://github.com:443/probit-io/aim4/git-upload-pack
  proxy | 2024/01/25 20:30:12 [004] * authenticating git server request (host: github.com)
  proxy | 2024/01/25 20:30:12 [004] 200 https://github.com:443/probit-io/aim4/git-upload-pack
  proxy | 2024/01/25 20:30:12 [006] POST https://github.com:443/probit-io/aim4/git-upload-pack
  proxy | 2024/01/25 20:30:12 [006] * authenticating git server request (host: github.com)
  proxy | 2024/01/25 20:30:13 [006] 200 https://github.com:443/probit-io/aim4/git-upload-pack
updater | 2024/01/25 20:30:15 INFO <job_778885900> Finished job processing
updater | time="2024-01-25T20:30:15Z" level=info msg="task complete" container_id=job-778885900-file-fetcher exit_code=0 job_id=778885900 step=fetcher
updater | 2024/01/25 20:30:18 INFO <job_778885900> Starting job processing
updater | 2024/01/25 20:30:19 INFO <job_778885900> Starting update job for probit-io/aim4
updater | 2024/01/25 20:30:19 INFO <job_778885900> Checking all dependencies for version updates...
updater | 2024/01/25 20:30:19 INFO <job_778885900> Checking if WebGrease 1.6.0 needs updating
  proxy | 2024/01/25 20:30:19 [012] GET https://nuget.pkg.github.com:443/probit-io/index.json
  proxy | 2024/01/25 20:30:19 [012] * authenticating nuget feed request (host: nuget.pkg.github.com, basic auth)
  proxy | 2024/01/25 20:30:19 [012] 200 https://nuget.pkg.github.com:443/probit-io/index.json
  proxy | 2024/01/25 20:30:19 [016] GET https://nuget.pkg.github.com:443/probit-io/webgrease/index.json
  proxy | 2024/01/25 20:30:19 [016] * authenticating nuget feed request (host: nuget.pkg.github.com, basic auth)
  proxy | 2024/01/25 20:30:19 [016] 404 https://nuget.pkg.github.com:443/probit-io/webgrease/index.json
updater | 2024/01/25 20:30:19 INFO <job_778885900> Latest version is 
updater | 2024/01/25 20:30:19 INFO <job_778885900> Requirements to unlock all
updater | 2024/01/25 20:30:19 INFO <job_778885900> Requirements update strategy 
updater | Finding updated dependencies for WebGrease.
updater | 2024/01/25 20:30:19 INFO <job_778885900> [Transport] Sending envelope with items [event] 00b7727cb0564aea9f117c430a782256 to Sentry
  proxy | 2024/01/25 20:30:19 [021] POST https://sentry.io:443/api/1451818/envelope/
  proxy | 2024/01/25 20:30:19 [021] 200 https://sentry.io:443/api/1451818/envelope/
updater | 2024/01/25 20:30:19 ERROR <job_778885900> Error processing WebGrease (NoMethodError)
updater | 2024/01/25 20:30:19 ERROR <job_778885900> undefined method `fetch' for nil:NilClass
updater | 
updater |           latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s,
updater |                                                               ^^^^^^
updater | 2024/01/25 20:30:19 ERROR <job_778885900> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:47:in `updated_requirements'
updater | 2024/01/25 20:30:19 ERROR <job_778885900> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:101:in `updated_dependencies_after_full_unlock'
updater | 2024/01/25 20:30:19 ERROR <job_778885900> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:61:in `updated_dependencies'
updater | 2024/01/25 20:30:19 ERROR <job_778885900> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:99:in `check_and_create_pull_request'
updater | 2024/01/25 20:30:19 ERROR <job_778885900> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/25 20:30:19 ERROR <job_778885900> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/25 20:30:19 ERROR <job_778885900> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/25 20:30:19 ERROR <job_778885900> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/25 20:30:19 ERROR <job_778885900> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/01/25 20:30:19 ERROR <job_778885900> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/25 20:30:19 ERROR <job_778885900> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
updater | 2024/01/25 20:30:19 ERROR <job_778885900> bin/update_files.rb:24:in `<main>'`
```

**Comment by probitdavid** [comment]
@abdulapopoola New bug from #8759 conversation

**Comment by abdulapopoola** [comment]
@brettfo shipped another update today; could you confirm if that addressed the issue?

**Comment by probitdavid** [comment]
nope still the same this morning with a clean run
`
  proxy | 2024/01/26 08:12:41 proxy starting, commit: 07d59135734a484cdcd1b34f737c7bca281bcf94
  proxy | 2024/01/26 08:12:41 * authenticating nuget feed request (host: nuget.pkg.github.com, basic auth)
  proxy | 2024/01/26 08:12:41 Listening (:1080)
updater | 2024-01-26T08:12:41.652219151 [779089588:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-01-26T08:12:44Z" level=info msg="guest starting" commit=5265bc7c42825390c331713cef4ed23c69721bbb
updater | time="2024-01-26T08:12:44Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=779089588 updater_timeout=45m0s updater_version=a9a3a71cf17c47ad2c9eb95fe41a8f8b614bdff3-nuget
updater | 2024/01/26 08:12:48 INFO <job_779089588> Starting job processing
  proxy | 2024/01/26 08:12:48 [002] GET https://github.com:443/probit-io/aim4/info/refs?service=git-upload-pack
  proxy | 2024/01/26 08:12:48 [002] * authenticating git server request (host: github.com)
  proxy | 2024/01/26 08:12:49 [002] 200 https://github.com:443/probit-io/aim4/info/refs?service=git-upload-pack
  proxy | 2024/01/26 08:12:49 [004] POST https://github.com:443/probit-io/aim4/git-upload-pack
  proxy | 2024/01/26 08:12:49 [004] * authenticating git server request (host: github.com)
  proxy | 2024/01/26 08:12:49 [004] 200 https://github.com:443/probit-io/aim4/git-upload-pack
  proxy | 2024/01/26 08:12:49 [006] POST https://github.com:443/probit-io/aim4/git-upload-pack
  proxy | 2024/01/26 08:12:49 [006] * authenticating git server request (host: github.com)
  proxy | 2024/01/26 08:12:49 [006] 200 https://github.com:443/probit-io/aim4/git-upload-pack
updater | 2024/01/26 08:12:51 INFO <job_779089588> Finished job processing
updater | time="2024-01-26T08:12:51Z" level=info msg="task complete" container_id=job-779089588-file-fetcher exit_code=0 job_id=779089588 step=fetcher
updater | 2024/01/26 08:12:55 INFO <job_779089588> Starting job processing
updater | 2024/01/26 08:12:56 INFO <job_779089588> Starting update job for probit-io/aim4
updater | 2024/01/26 08:12:56 INFO <job_779089588> Checking all dependencies for version updates...
updater | 2024/01/26 08:12:56 INFO <job_779089588> Checking if System.Numerics.Vectors 4.5.0 needs updating
  proxy | 2024/01/26 08:12:56 [012] GET https://nuget.pkg.github.com:443/probit-io/index.json
  proxy | 2024/01/26 08:12:56 [012] * authenticating nuget feed request (host: nuget.pkg.github.com, basic auth)
  proxy | 2024/01/26 08:12:56 [012] 200 https://nuget.pkg.github.com:443/probit-io/index.json
  proxy | 2024/01/26 08:12:56 [016] GET https://nuget.pkg.github.com:443/probit-io/system.numerics.vectors/index.json
  proxy | 2024/01/26 08:12:56 [016] * authenticating nuget feed request (host: nuget.pkg.github.com, basic auth)
  proxy | 2024/01/26 08:12:56 [016] 404 https://nuget.pkg.github.com:443/probit-io/system.numerics.vectors/index.json
updater | 2024/01/26 08:12:56 INFO <job_779089588> Latest version is 
updater | 2024/01/26 08:12:56 INFO <job_779089588> Requirements to unlock all
updater | 2024/01/26 08:12:56 INFO <job_779089588> Requirements update strategy 
updater | Finding updated dependencies for System.Numerics.Vectors.
updater | 2024/01/26 08:12:56 INFO <job_779089588> [Transport] Sending envelope with items [event] 2b819323611f4f05815d4be68f7c8b4b to Sentry
updater | 2024/01/26 08:12:56 ERROR <job_779089588> Error processing System.Numerics.Vectors (NoMethodError)
updater | 2024/01/26 08:12:56 ERROR <job_779089588> undefined method `fetch' for nil:NilClass
updater | 
updater |           latest_version: preferred_resolvable_version_details.fetch(:version)&.to_s,
updater |                                                               ^^^^^^
updater | 2024/01/26 08:12:56 ERROR <job_779089588> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:47:in `updated_requirements'
updater | 2024/01/26 08:12:56 ERROR <job_779089588> /home/dependabot/nuget/lib/dependabot/nuget/update_checker.rb:101:in `updated_dependencies_after_full_unlock'
updater | 2024/01/26 08:12:56 ERROR <job_779089588> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:61:in `updated_dependencies'
updater | 2024/01/26 08:12:56 ERROR <job_779089588> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:99:in `check_and_create_pull_request'
updater | 2024/01/26 08:12:56 ERROR <job_779089588> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/26 08:12:56 ERROR <job_779089588> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/26 08:12:56 ERROR <job_779089588> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/26 08:12:56 ERROR <job_779089588> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/26 08:12:56 ERROR <job_779089588> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/01/26 08:12:56 ERROR <job_779089588> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/26 08:12:56 ERROR <job_779089588> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
updater | 2024/01/26 08:12:56 ERROR <job_779089588> bin/update_files.rb:24:in `<main>'`

**Comment by brettfo** [comment]
I believe all of the `undefined method 'fetch' for nil:NilClass` issues have been resolved, is this issue still occurring?
