### ISSUE TITLE
[Ruby] poetry_file_updater.rb throws "Content did not change" error for TOML file

### ISSUE THREAD

**Issue by PhilippWillms** [dependabot/dependabot-core#8931]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip

### Package manager version

poetry-core >= 1.8.0

### Language version

python = ">=3.8.1, <4.0.0"

### Manifest location and content before the Dependabot update

[tool.poetry]
name = "myPackage"
version = "0.5.6-dev"

[tool.poetry.dependencies]
python = ">=3.8.1, <4.0.0"
importlib_resources = {version = ">=6.0.0", python = ">=3.9"}
gymnasium = ">=0.26.3"
deprecated = "^1.2.13"
pandas = ">=1.3.0"
numpy = ">=1.18.0"
salabim = ">23.2.0"
Pillow = "^10.0.1"
kaleido = "0.2.1"
plotly = ">=5.8.0"
openpyxl = "^3.0.10"
PuLP = ">=2.6.0"
networkx = [
    {version = "^3.2.1", python = ">=3.9"},
    {version = "3.1", python = "<3.9"}
]
matplotlib = [
    {version = "^3.8.2", python = ">=3.9"},
    {version = "3.7.4", python = "<3.9"}
]
ordered-set = "^4.1.0"
sortedcontainers = "^2.4.0"

[tool.poetry.group.dev]
optional = true
[tool.poetry.group.dev.dependencies]
poetry = ">=1.4.2,<1.8.0"
pre-commit = "^3.5.0"
black = ">= 24.1.0"
reorder-python-imports = "^3.12.0"
flynt = ">= 0.71"
pydocstyle = "^6.3.0"
flake8 = "^6.1.0"
flake8-typing-imports = "^1.15.0"
flake8-black = "^0.3.6"
flake8-docstrings = "^1.7.0"
flake8-implicit-str-concat = "^0.4.0"
flake8-unused-arguments = "^0.0.13"

[tool.poetry.group.test]
optional = true
[tool.poetry.group.test.dependencies]
pytest = "^8.0.0"
pytest-cov = "^4.1.0"

[tool.poetry.group.docs]
optional = true
[tool.poetry.group.docs.dependencies]
Sphinx = ">=7.1.2"
sphinx-rtd-theme = "^2.0.0"
sphinx-autodoc-typehints = "^1.24.0"
sphinxcontrib-bibtex = "^2.5.0"
myst_parser = "^2.0.0"

[tool.semantic_release]
version_variable = "pyproject.toml:version" # version location
branch = "main"                             # branch to make releases of
changelog_file = "CHANGELOG.md"             # changelog file
build_command = "poetry build"              # build dists
dist_path = "dist/"                         # where to put dists
upload_to_release = false                   # auto-create GitHub release
upload_to_pypi = false                      # don't auto-upload to PyPI
remove_dist = false                         # don't remove dists
patch_without_tag = false                   # patch release by default

[build-system]
requires = ["poetry-core>=1.8.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "[CI] "
    open-pull-requests-limit: 10
    reviewers:
      - "PhilippWillms"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "[CI] "
    open-pull-requests-limit: 10
    reviewers:
      - "PhilippWillms"

### Updated dependency

pytest from ^7.2.0  to ^8.0.0
black from ^23.1.0 to ^24.1.1
flake8 from  ^6.1.10to 7.0.0

### What you expected to see, versus what you actually saw

The Sentry envelope sent back to GH Dependabot led into RunTime Error for the dependencies mentioned. It worked before fall 2023.

### Smallest manifest that reproduces the issue

updater | 2024/01/29 13:58:22 INFO <job_779935348> Checking if black  needs updating
  proxy | 2024/01/29 13:58:23 [936] GET https://pypi.org:443/simple/black/
  proxy | 2024/01/29 13:58:23 [936] 200 https://pypi.org:443/simple/black/
updater | 2024/01/29 13:58:23 INFO <job_779935348> Latest version is 24.1.1
  proxy | 2024/01/29 13:58:23 [938] GET https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:58:23 [938] 301 https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:58:23 [940] GET https://pypi.org:443/pypi/mypackage/json
  proxy | 2024/01/29 13:58:23 [940] 404 https://pypi.org:443/pypi/mypackage/json
  proxy | 2024/01/29 13:58:26 [942] GET https://pypi.org:443/pypi/black/24.1.1/json
  proxy | 2024/01/29 13:58:26 [942] 200 https://pypi.org:443/pypi/black/24.1.1/json
  proxy | 2024/01/29 13:58:26 [944] GET https://pypi.org:443/pypi/platformdirs/4.1.0/json
  proxy | 2024/01/29 13:58:26 [944] 200 https://pypi.org:443/pypi/platformdirs/4.1.0/json
  proxy | 2024/01/29 13:58:29 [946] GET https://pypi.org:443/pypi/poetry/1.7.0/json
  proxy | 2024/01/29 13:58:29 [946] 200 https://pypi.org:443/pypi/poetry/1.7.0/json
  proxy | 2024/01/29 13:58:29 [948] GET https://pypi.org:443/pypi/poetry/1.6.1/json
  proxy | 2024/01/29 13:58:29 [948] 200 https://pypi.org:443/pypi/poetry/1.6.1/json
  proxy | 2024/01/29 13:58:29 [950] GET https://pypi.org:443/pypi/poetry/1.6.0/json
  proxy | 2024/01/29 13:58:29 [950] 200 https://pypi.org:443/pypi/poetry/1.6.0/json
  proxy | 2024/01/29 13:58:29 [952] GET https://pypi.org:443/pypi/poetry/1.5.1/json
  proxy | 2024/01/29 13:58:29 [952] 200 https://pypi.org:443/pypi/poetry/1.5.1/json
  proxy | 2024/01/29 13:58:30 [954] GET https://pypi.org:443/pypi/poetry/1.5.0/json
  proxy | 2024/01/29 13:58:30 [954] 200 https://pypi.org:443/pypi/poetry/1.5.0/json
  proxy | 2024/01/29 13:58:30 [956] GET https://pypi.org:443/pypi/poetry/1.4.2/json
  proxy | 2024/01/29 13:58:30 [956] 200 https://pypi.org:443/pypi/poetry/1.4.2/json
  proxy | 2024/01/29 13:58:31 [958] GET https://pypi.org:443/pypi/urllib3/1.26.18/json
  proxy | 2024/01/29 13:58:31 [958] 200 https://pypi.org:443/pypi/urllib3/1.26.18/json
  proxy | 2024/01/29 13:59:02 [960] GET https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:02 [960] 301 https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:02 [962] GET https://pypi.org:443/pypi/mypackage/json
  proxy | 2024/01/29 13:59:02 [962] 404 https://pypi.org:443/pypi/mypackage/json
  proxy | 2024/01/29 13:59:02 [964] GET https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:02 [964] 301 https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:02 [966] GET https://pypi.org:443/pypi/mypackage/json
  proxy | 2024/01/29 13:59:02 [966] 404 https://pypi.org:443/pypi/mypackage/json
updater | 2024/01/29 13:59:02 INFO <job_779935348> Requirements to unlock own
  proxy | 2024/01/29 13:59:02 [968] GET https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:02 [968] 301 https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:02 [970] GET https://pypi.org:443/pypi/mypackage/json
  proxy | 2024/01/29 13:59:02 [970] 404 https://pypi.org:443/pypi/mypackage/json
updater | 2024/01/29 13:59:02 INFO <job_779935348> Requirements update strategy bump_versions
  proxy | 2024/01/29 13:59:03 [972] GET https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:03 [972] 301 https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:03 [974] GET https://pypi.org:443/pypi/mypackage/json
  proxy | 2024/01/29 13:59:03 [974] 404 https://pypi.org:443/pypi/mypackage/json
  proxy | 2024/01/29 13:59:03 [976] GET https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:03 [976] 301 https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:03 [978] GET https://pypi.org:443/pypi/mypackage/json
  proxy | 2024/01/29 13:59:03 [978] 404 https://pypi.org:443/pypi/mypackage/json
  proxy | 2024/01/29 13:59:03 [980] GET https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:03 [980] 301 https://pypi.org:443/pypi/mypackage/json/
  proxy | 2024/01/29 13:59:03 [982] GET https://pypi.org:443/pypi/mypackage/json
  proxy | 2024/01/29 13:59:03 [982] 404 https://pypi.org:443/pypi/mypackage/json
updater | 2024/01/29 13:59:03 INFO <job_779935348> Updating black from  to 24.1.1
updater | 2024/01/29 13:59:03 INFO <job_779935348> [Transport] Sending envelope with items [event] a54b4e754c0c474380da10d3b52aac53 to Sentry
  proxy | 2024/01/29 13:59:03 [985] POST https://sentry.io:443/api/1451818/envelope/
  proxy | 2024/01/29 13:59:03 [985] 200 https://sentry.io:443/api/1451818/envelope/
updater | 2024/01/29 13:59:03 ERROR <job_779935348> Error processing black (RuntimeError)
updater | 2024/01/29 13:59:03 ERROR <job_779935348> Content did not change!
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:74:in `updated_pyproject_content'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:48:in `fetch_updated_dependency_files'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:31:in `updated_dependency_files'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/python/lib/dependabot/python/file_updater.rb:101:in `updated_poetry_based_files'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/python/lib/dependabot/python/file_updater.rb:34:in `updated_dependency_files'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:91:in `generate_dependency_files'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:37:in `run'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:128:in `check_and_create_pull_request'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:60:in `check_and_create_pr_with_error_handling'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `block in perform'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `each'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:35:in `perform'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
updater | 2024/01/29 13:59:03 ERROR <job_779935348> bin/update_files.rb:24:in `<main>'

**Comment by abdulapopoola** [comment]
Tagging @JamieMagee in case he knows

**Comment by JamieMagee** [comment]
Did Sentry cause the error or is this log just Sentry sending telemetry about the error before it gets logged to stdout?

**Comment by PhilippWillms** [comment]
The extract I copy&pasted is from the "Update logs" from Dependabot job. As I am not familiar on technical details how Dependabot works internally, I cannot judge on this question. What I indeed recognize is that even in case the POST of Sentry envelops results in positive response (200), RuntimeError "Content did not change" occurs.

**Comment by JamieMagee** [comment]
Sentry is the monitoring platform that Dependabot uses. That log is saying that Sentry captured an exception and sent it to Sentry's API for processing. You can see where the log message comes from:

https://github.com/getsentry/sentry-ruby/blob/3135516e7b589ee6fda27c7cc2e9fd57ff817306/sentry-ruby/lib/sentry/transport.rb#L64

I don't think that Sentry caused the exception.

**Comment by PhilippWillms** [comment]
OK, looks reasonable. Then feel free to rename the issue appropriately. There must be some other reason within Dependabot.

**Comment by PhilippWillms** [comment]
I saw it working for another repository. Here the following TOML file is active:

> [tool.poetry]
> name = "anotherPackage"
> version = "0.3.0"
> authors = ["Philipp Willms"]
> license = "MIT"
> readme = "README.md"
> 
> [tool.poetry.dependencies]
> python = ">=3.8.1,<3.12"
> wandb = "^0.16.0"
> tqdm = "^4.65.0"
> deprecated = "^1.2.13"
> torch = ">=2.0"
> 
> [tool.poetry.group.dev]
> optional = true
> [tool.poetry.group.dev.dependencies]
> poetry = ">=1.4.2,<1.8.0"
> pre-commit = "^3.1.1"
> black = {extras = ["jupyter"], version = "^23.1.0"}
> reorder-python-imports = "^3.9.0"
> flynt = ">= 0.71"
> pydocstyle = "^6.1.1"
> flake8 = "^6.0.0"
> flake8-typing-imports = "^1.14.0"
> flake8-black = "^0.3.6"
> flake8-docstrings = "^1.7.0"
> flake8-implicit-str-concat = "^0.4.0"
> 
> [tool.poetry.group.test]
> optional = true
> [tool.poetry.group.test.dependencies]
> pytest = "^8.0.0"
> pytest-cov = "^4.0.0"
> 
> [tool.poetry.group.docs]
> optional = true
> [tool.poetry.group.docs.dependencies]
> Sphinx = "^7.1.2"
> sphinx-rtd-theme = "^2.0.0"
> sphinxcontrib-bibtex = "^2.5.0"
> myst_parser = "^2.0.0"
> sphinx-autodoc-typehints = "^1.23.0"
> 
> [tool.poetry.group.gpu]
> optional = true
> [tool.poetry.group.gpu.dependencies]
> gputil = "^1.4.0"
> 
> [tool.black]
> line-length = 88
> include = '\.pyi?$'
> exclude = '''
> /(
>     \.git
>   | \.hg
>   | \.mypy_cache
>   | \.tox
>   | \.venv
>   | _build
>   | buck-out
>   | build
>   | dist
> )/
> '''
> 
> [tool.semantic_release]
> version_variable = "pyproject.toml:version" # version location
> branch = "main"                             # branch to make releases of
> changelog_file = "CHANGELOG.md"             # changelog file
> build_command = "poetry build"              # build dists
> dist_path = "dist/"                         # where to put dists
> upload_to_release = false                   # auto-create GitHub release
> upload_to_pypi = false                      # don't auto-upload to PyPI
> remove_dist = false                         # don't remove dists
> patch_without_tag = false                    # patch release by default
> 
> [build-system]
> requires = ["poetry-core>=1.8.0"]
> build-backend = "poetry.core.masonry.api"
>

**Comment by PhilippWillms** [comment]
Any update on the topic? For another tepo, where I do not have the python version split in toml file it is working.

**Comment by PhilippWillms** [comment]
Any progress so far? I do not think that I am the only one affected by this issue. The type of `poetry` config mentioned above is quite common and recommended by them.

**Comment by edwardpeek-crown** [comment]
We have been triggering this same error with the root cause being dependencies with extras under a pip-tools setup. See https://github.com/dependabot/dependabot-core/issues/9902 for details.

**Comment by dlew** [comment]
I have run into this issue myself, but as far as I can tell, our `pyproject.toml` has no `extras` defined in it. So I'm not entirely convinced the issue has to do with `extras` in particular.

Here's an example stack trace from when an update fails (and it's failing for all updates):

```
updater | 2024/09/20 14:42:27 INFO <job_888262854> Updating pandas from 2.2.2 to 2.2.3
  proxy | 2024/09/20 14:42:27 [861] POST /update_jobs/888262854/record_update_job_unknown_error
  proxy | 2024/09/20 14:42:27 [861] 204 /update_jobs/888262854/record_update_job_unknown_error
  proxy | 2024/09/20 14:42:27 [863] POST /update_jobs/888262854/record_update_job_error
2024/09/20 14:42:27 [863] 204 /update_jobs/888262854/record_update_job_error
  proxy | 2024/09/20 14:42:27 [865] POST /update_jobs/888262854/increment_metric
  proxy | 2024/09/20 14:42:27 [865] 204 /update_jobs/888262854/increment_metric
  proxy | 2024/09/20 14:42:27 [867] POST /update_jobs/888262854/record_update_job_unknown_error
  proxy | 2024/09/20 14:42:27 [867] 204 /update_jobs/888262854/record_update_job_unknown_error
updater | 2024/09/20 14:42:27 ERROR <job_888262854> Error processing pandas (RuntimeError)
2024/09/20 14:42:27 ERROR <job_888262854> Content did not change!
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:76:in `updated_pyproject_content'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:50:in `fetch_updated_dependency_files'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/python/lib/dependabot/python/file_updater/poetry_file_updater.rb:33:in `updated_dependency_files'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/python/lib/dependabot/python/file_updater.rb:112:in `updated_poetry_based_files'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `block in create_validator_method_medium0'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/python/lib/dependabot/python/file_updater.rb:40:in `updated_dependency_files'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `block in create_validator_method_medium0'
updater | 2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:143:in `generate_dependency_files'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:919:in `block in create_validator_method_medium0'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:72:in `run'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:44:in `create_from'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:167:in `bind_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:175:in `create_change_for'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:1187:in `bind_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation_2_7.rb:1187:in `block in create_validator_method_medium4'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:100:in `block in compile_all_dependency_changes_for'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:62:in `each'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:62:in `compile_all_dependency_changes_for'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:97:in `dependency_change'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:61:in `perform'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:117:in `run_grouped_update_for'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:103:in `block in run_grouped_dependency_updates'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:102:in `each'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:102:in `run_grouped_dependency_updates'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:64:in `perform'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11444/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:44:in `block in perform_job'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `block in with_span'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/context.rb:87:in `with_value'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `with_span'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:18:in `perform_job'
2024/09/20 14:42:27 ERROR <job_888262854> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
2024/09/20 14:42:27 ERROR <job_888262854> bin/update_files.rb:46:in `<main>'
```
