### ISSUE TITLE
unknown_error in nuget Dependencies failed to update

### ISSUE THREAD

**Issue by johnsympatient** [dependabot/dependabot-core#8992]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Manifest location and content before the Dependabot update

``` "/Invirto/ContentServer/ContentServer.sln"
 "/Invirto/ContentServer/ContentServer/Backend/Core.csproj"
 "/Invirto/ContentServer/ContentServer/Backend/otherSubprojectsDependingOnCore/otherSubprojectsDependingOnCore.csproj"```

### dependabot.yml content

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Invirto/ContentServer"
    open-pull-requests-limit: 25
    schedule:
      interval: "monthly"
    groups:
      content-server-nuget-dependencies: # name of the group
        update-types: # group all updates for minor and patch versions into a single PR, major changes will be created as individual PRs
          - "minor"
          - "patch"

### Updated dependency

updater | +---------------------------------------------------------------+
updater | |              Changes to Dependabot Pull Requests              |
updater | +---------+-----------------------------------------------------+
updater | | created | Microsoft.NET.Sdk.Functions ( from 4.2.0 to 4.3.0 ) |
updater | +---------+-----------------------------------------------------+

### What you expected to see, versus what you actually saw

We got a nested multi project setup.
We got dependabot pointing to the sln file:
ContentServer/ContentServer.sln

In that directory we got a Core project where most of the general dependencies are installed.

ContentServer/Backend/Core/Core.csproj

We got services in the same sln file that got the Core project as dependency.

E.g. 
Contentserver/Backend/Service1/Servicee1.csproj <-- has the Core project as dependency.

if there is a dependency to be updated in the service itself (not installed in core) the pr is correctly created.

If there is a dependency that needs updating in Core, it fails to create the PR.

e.g. Microsoft.NET.Sdk.Functions is installed in a service and it updates fine.

Polly is installed in Core and fails to update.
I can see these errors in the log:

```
updater |   No dotnet-tools.json files found.
updater | Running for project [/home/dependabot/dependabot-updater/repo/Invirto/ContentServer/Web/Admin.Test/Admin.Test.csproj]
updater |   Updating [Invirto/ContentServer/global.json] file.
updater |     Dependency [Polly] not found.
updater |   Running for SDK-style project
updater |     Package [Polly] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/Invirto/ContentServer/Web/Admin.Test/Admin.Test.csproj].
updater | Update complete.
updater | 2024/02/05 16:26:46 INFO <job_783022848> [Transport] Sending envelope with items [event] e25c79f421a14ee9baa16ac78bf8bc63 to Sentry
  proxy | 2024/02/05 16:26:46 [862] POST https://sentry.io:443/api/1451818/envelope/
  proxy | 2024/02/05 16:26:46 [862] 200 https://sentry.io:443/api/1451818/envelope/
updater | 2024/02/05 16:26:46 ERROR <job_783022848> Error processing Polly (Dependabot::DependabotError)
updater | 2024/02/05 16:26:46 ERROR <job_783022848> FileUpdater failed
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:43:in `run'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:95:in `create_change_for'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:56:in `block in compile_all_dependency_changes_for'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `each'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `compile_all_dependency_changes_for'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:70:in `dependency_change'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:44:in `perform'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:119:in `run_update_for'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:101:in `block in run_grouped_dependency_updates'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:100:in `each'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:100:in `run_grouped_dependency_updates'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:47:in `perform'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
updater | 2024/02/05 16:26:46 ERROR <job_783022848> bin/update_files.rb:24:in `<main>'
```
Or this one:

```
updater |   No dotnet-tools.json files found.
updater | Running for project [/home/dependabot/dependabot-updater/repo/Invirto/ContentServer/Web/Admin.Test/Admin.Test.csproj]
updater |   Updating [Invirto/ContentServer/global.json] file.
updater |     Dependency [Microsoft.IdentityModel.Protocols.OpenIdConnect] not found.
updater |   Running for SDK-style project
updater |     Package [Microsoft.IdentityModel.Protocols.OpenIdConnect] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/Invirto/ContentServer/Web/Admin.Test/Admin.Test.csproj].
updater | Update complete.
updater | 2024/02/05 16:22:25 INFO <job_783022848> [Transport] Sending envelope with items [event] 4495ba163be34a3580939c9f7a51ce7e to Sentry
  proxy | 2024/02/05 16:22:25 [575] POST https://sentry.io:443/api/1451818/envelope/
  proxy | 2024/02/05 16:22:25 [575] 200 https://sentry.io:443/api/1451818/envelope/
updater | 2024/02/05 16:22:25 ERROR <job_783022848> Error processing Microsoft.IdentityModel.Protocols.OpenIdConnect (Dependabot::DependabotError)
updater | 2024/02/05 16:22:25 ERROR <job_783022848> FileUpdater failed
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:43:in `run'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:26:in `create_from'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:95:in `create_change_for'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:56:in `block in compile_all_dependency_changes_for'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `each'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:29:in `compile_all_dependency_changes_for'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:70:in `dependency_change'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:44:in `perform'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:119:in `run_update_for'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:101:in `block in run_grouped_dependency_updates'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:100:in `each'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:100:in `run_grouped_dependency_updates'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:47:in `perform'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
updater | 2024/02/05 16:22:25 ERROR <job_783022848> bin/update_files.rb:24:in `<main>'
```


updater | +---------------------------------------------------------------+
updater | |              Changes to Dependabot Pull Requests              |
updater | +---------+-----------------------------------------------------+
updater | | created | Microsoft.NET.Sdk.Functions ( from 4.2.0 to 4.3.0 ) |
updater | +---------+-----------------------------------------------------+
updater | Dependabot encountered '4' error(s) during execution, please check the logs for more details.
updater | +-----------------------------------------------------------------+
updater | |                  Dependencies failed to update                  |
updater | +-------------------------------------------------+---------------+
updater | | Microsoft.IdentityModel.Protocols.OpenIdConnect | unknown_error |
updater | | Polly                                           | unknown_error |
updater | | IronPdf.Native.Chrome.Linux                     | unknown_error |
updater | | IronPdf                                         | unknown_error |
updater | +-------------------------------------------------+---------------+

### Native package manager behavior

When using the native package manager command, it reports the outdated packages as usual

### Images of the diff or a link to the PR, issue, or logs

_No response_

### Smallest manifest that reproduces the issue

_No response_

**Comment by johnsympatient** [comment]
Some additional info that might help:
For the moment we switched back to adding each .csproj file to the dependabot config.

It produces this PR for one of our services:
```
Bumps the monitoring-nuget-dependencies group in /Invirto/ContentServer/Backend/MonitoringInvirto with 3 updates: [Microsoft.NET.Sdk.Functions](https://github.com/Azure/azure-functions-vs-build-sdk), [Microsoft.IdentityModel.Protocols.OpenIdConnect](https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet) and [Polly](https://github.com/App-vNext/Polly).

Updates Microsoft.NET.Sdk.Functions from 4.2.0 to 4.3.0

Release notes
Commits

Updates Microsoft.IdentityModel.Protocols.OpenIdConnect from 7.2.0 to 7.3.1

Release notes
Changelog
Commits

Updates Polly from 8.2.1 to 8.3.0

Release notes
Changelog
Commits

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting @dependabot rebase.
```

But in the changeset, only Polly, that is installed in the Core project is updated to 8.3.0.
OpenIdConnect and SDKFunctions is not included in the Core, but in the individual service and is not updated

**Comment by leonvandermeer** [comment]
I can reproduce same[^1]? issue. See Readme in a small [repository](https://github.com/leonvandermeer/DependabotErrorAnalysis). IMHO, NuGet updater must iterate all projects and update each for the changed reference. It seems that it stops iterating after the 1st. And when that project does not refer to the NuGet package, no files are changed. Dependabot detects no changed files and throws 'FileUpdater failed'.

[^1]: @johnsympatient Can you confirm that it is indeed the same issuq?

**Comment by johnsympatient** [comment]
@leonvandermeer Thanks for creating the reproduction repo. I can confirm that this is the exact issue I am getting

**Comment by joaorosado** [comment]
Any known workaround for this?
I'm getting it in a lot of repositories on Test projects. Also can't understand why some repositories with similar patterns do not fail.

My csproj files look like this (just some file and package names changed so I can post them):

MainProject:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
        <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
        <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
        <DefineConstants>DEBUG;TRACE</DefineConstants>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
      <PackageReference Include="GitVersion.MsBuild" Version="5.12.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="SomePackageName" Version="11.24.0" />
    </ItemGroup>

</Project>
```

Test Project:
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6;net461</TargetFrameworks>
    <IsTestProject>true</IsTestProject>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <!-- Package References -->
    <PackageReference Include="coverlet.msbuild" Version="6.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="GitVersion.MsBuild" Version="5.12.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <PackageReference Include="nunit" Version="3.14.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\MainProject\MainProject.csproj" />
  </ItemGroup>

</Project>
```

And the error:
```
updater |   No dotnet-tools.json files found.
updater | Running for project [/home/dependabot/dependabot-updater/repo/tests/UnitTests/MainProject.Tests/MainProject.Tests.csproj]
updater |   Running for SDK-style project
updater |     Package [SomePackageName] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/tests/UnitTests/MainProject.Tests/MainProject.Tests.csproj].
updater | Update complete.
updater | 2024/02/19 14:49:52 INFO <job_788842746> [Transport] Sending envelope with items [event] f1d6bcd3af3c40809ec7b89c008cf409 to Sentry
updater | 2024/02/19 14:49:52 ERROR <job_788842746> Error processing SomePackageName (Dependabot::DependabotError)
updater | 2024/02/19 14:49:52 ERROR <job_788842746> FileUpdater failed
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:69:in `run'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:42:in `create_from'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:114:in `create_change_for'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:72:in `block in compile_all_dependency_changes_for'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:38:in `each'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater/group_update_creation.rb:38:in `compile_all_dependency_changes_for'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:70:in `dependency_change'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_group_update_pull_request.rb:44:in `perform'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:119:in `run_update_for'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:101:in `block in run_grouped_dependency_updates'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:100:in `each'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:100:in `run_grouped_dependency_updates'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:47:in `perform'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `perform_job'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
updater | 2024/02/19 14:49:52 ERROR <job_788842746> bin/update_files.rb:24:in `<main>'
```

**Comment by leonvandermeer** [comment]
@JoeRobich @johnsympatient 
It looks like this issue is solved. Dependabot just worked on my [reproducing repository](https://github.com/leonvandermeer/DependabotErrorAnalysis):
| Job started at | Job id | Dependabot Core Version [^1] | Job Result |
|--------|--------|--------|--------|
| 2024/02/22 23:36:01 | [791091783](https://github.com/leonvandermeer/DependabotErrorAnalysis/network/updates/791091783) | [v0.244.0](https://github.com/dependabot/dependabot-core/releases/tag/v0.244.0) | unknown_error |
| 2024/02/23 23:13:29 | [791548322](https://github.com/leonvandermeer/DependabotErrorAnalysis/network/updates/791548322)  | [v0.245.0](https://github.com/dependabot/dependabot-core/releases/tag/v0.245.0)| [PR to update Octokit (from 9.1.1 to 10.0.0)](https://github.com/leonvandermeer/DependabotErrorAnalysis/pull/1)|

I compared the releases, browsed a bit an then concluded that [this](https://github.com/dependabot/dependabot-core/pull/9097/files/7eacd94983bc5af709ca5ef2136ab94fa26add50#r1498911775) most probably is the fix.

[^1]: At job's start time, this was the most recent release.

**Comment by johnsympatient** [comment]
@leonvandermeer @JoeRobich 
Hello thanks for notifying us. We tried it again and it al least doesnt error out/stop from completing anymore. In your exact case it works. But not in all cases.

We got this:

Core Project --> Core.Test project and Core2.Test project (Both test projects do have Core as Project Reference)

Nunit is included in both Core Test projects.
Another dependency only in Core.Test

I got an PR that suggests to update both, NUnit and the other dependency. (Group update)

But in the commit only the other dependency is updated.

But it should also be Nunit in both Core Test projects
