### ISSUE TITLE
Multi Directory Not Working for Helm Charts

### ISSUE THREAD

**Issue by jpinz** [dependabot/dependabot-core#9173]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

Docker/Helm

### dependabot.yml content

Don't want to share too much, but here are the relevant parts, note that it is multi-directory:
```
security-updates-only: false
grouped-update: true
 updating-a-pull-request: false
 source:
    directory: /
    directories:
    - /src/helmcharts/
    provider: azure
    repo: xxxx
    branch: main
 package-manager: docker
```

### What you expected to see, versus what you actually saw

Expected everything to work, instead got an error and stacktrace:

```
Starting job processing
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> No Dockerfile!
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/docker/lib/dependabot/docker/file_parser.rb:103:in 'check_required_files'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/common/lib/dependabot/file_parsers/base.rb:50:in 'initialize'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in 'bind_call'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in 'validate_call'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in 'block in _on_method_added'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/abstract/declare.rb:38:in 'new'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/abstract/declare.rb:38:in 'block in declare_abstract'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:196:in 'dependency_file_parser'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in 'bind_call'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in 'validate_call'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in 'block in _on_method_added'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:190:in 'parse_files!'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in 'bind_call'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in 'validate_call'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in 'block in _on_method_added'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:152:in 'block in initialize'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:150:in 'each'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:150:in 'initialize'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in 'bind_call'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in 'validate_call'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in 'block in _on_method_added'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:29:in 'new'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/lib/dependabot/dependency_snapshot.rb:29:in 'create_from_job_definition'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in 'bind_call'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in 'validate_call'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in 'block in _on_method_added'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:21:in 'perform_job'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in 'run'
updater | 2024/02/28 05:32:06 ERROR <job_b953c878-408a-4ca7-8487-b8a9449dbfd9> bin/update_files.rb:24:in '<main>'
```

### Images of the diff or a link to the PR, issue, or logs

I'm 99% sure it came from #8963 specifically the changes made in [updater/lib/dependabot/dependency_snapshot.rb](https://github.com/dependabot/dependabot-core/pull/8963/files#diff-8f100daee2d4df926e8ee83cfd59267a7f8894995e86f7c742eeb83b64591e62)

**Comment by jpinz** [comment]
@jakecoffman when you get a chance, would appreciate any feedback here.

**Comment by jpinz** [comment]
Appears that the issue here was due to setting `directory` to `/` when `directories` was present and not empty. Not setting `directory` appears to have fixed the issue.

**Comment by abdulapopoola** [comment]
This sounds like something customers will also run into; what are our plans for this?

Tagging @carogalvin

**Comment by abdulapopoola** [comment]
@jpinz , does this still repro?
