### ISSUE TITLE
Dependabot ran out of disk space during its update

### ISSUE THREAD

**Issue by dannyrb** [dependabot/dependabot-core#9265]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

npm

### Package manager version

lts

### Language version

lts

### Manifest location and content before the Dependabot update

`/package.json` (monorepo, with workspaces)

### dependabot.yml content

```yml
version: 2
updates:

  # `/cloudflare`
  - package-ecosystem: "npm"
    open-pull-requests-limit: 15
    directory: "/cloudflare"
    schedule:
      interval: "daily"
      time: "15:00"
    assignees:
      - teamupstart/fplat-upnext
    reviewers:
      - teamupstart/fplat-upnext
    registries:
      - npm-upstart
    labels:
      - "dependencies:npm"

  # `/e2e`
  - package-ecosystem: "npm"
    open-pull-requests-limit: 15
    directory: "/e2e"
    schedule:
      interval: "daily"
      time: "15:00"
    registries:
      - npm-upstart
    labels:
      - "dependencies:npm"  
  
  # GH Actions
  - package-ecosystem: github-actions
    open-pull-requests-limit: 10
    directory: /
    schedule:
      interval: "weekly"
    assignees:
      - teamupstart/fplat-upnext
    reviewers:
      - teamupstart/fplat-upnext
    registries:
      - github-teamupstart
    labels:
      - "dependencies:gh-action"
      - "service:ci-pipeline"

  # `/apps` and `/examples`
  - package-ecosystem: "npm"
    open-pull-requests-limit: 20
    directory: "/"
    schedule:
      interval: "daily"
      time: "15:00"
    registries:
      - npm-upstart
    labels:
      - "dependencies:npm"

registries:
  npm-upstart:
    type: npm-registry
    url: https://upstart.jfrog.io/artifactory/api/npm/local-npm/
    token: ${{ secrets.ARTIFACTORY_AUTH_TOKEN }}
  github-teamupstart:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{secrets.FPLAT_CI_TOKEN}}
```

### What you expected to see, versus what you actually saw

```bash
  proxy | 2024/03/11 15:16:43 Successfully posted metrics data via api client
  proxy | 2024/03/11 15:16:57 [031] GET https://repo.yarnpkg.com:443/3.5.0/packages/yarnpkg-cli/bin/yarn.js
  proxy | 2024/03/11 15:16:57 [031] 200 https://repo.yarnpkg.com:443/3.5.0/packages/yarnpkg-cli/bin/yarn.js
  proxy | 2024/03/11 15:17:16 [033] GET https://registry.yarnpkg.com:443/@mdx-js%2freact
  proxy | 2024/03/11 15:17:16 [033] 200 https://registry.yarnpkg.com:443/@mdx-js%2freact
  proxy | 2024/03/11 15:17:18 [035] GET https://registry.yarnpkg.com:443/@mdx-js%2freact/-/react-3.0.1.tgz
  proxy | 2024/03/11 15:17:18 [035] 200 https://registry.yarnpkg.com:443/@mdx-js%2freact/-/react-3.0.1.tgz
  proxy | 2024/03/11 15:17:43 Posting metrics to remote API endpoint
  proxy | 2024/03/11 15:17:43 Successfully posted metrics data via api client
updater | 2024/03/11 15:22:18 INFO <job_798473071> Requirements to unlock own
updater | 2024/03/11 15:22:18 INFO <job_798473071> Requirements update strategy bump_versions
updater | 2024/03/11 15:22:18 INFO <job_798473071> Updating @mdx-js/react from 1.6.22 to 3.0.1
updater | 2024/03/11 15:22:19 INFO <job_798473071> Finished job processing
updater | 2024/03/11 15:22:19 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------+
updater | |   Errors    |
updater | +-------------+
updater | | out_of_disk |
updater | +-------------+
updater | time="2024-03-11T15:22:19Z" level=info msg="task complete" container_id=job-798473071-updater exit_code=0 job_id=798473071 step=updater
```

**Comment by dannyrb** [comment]
Having trouble getting eyes on these closed issues:

- https://github.com/dependabot/dependabot-core/issues/8245
- https://github.com/dependabot/dependabot-core/issues/8613

I hate to bother folks, but I would appreciate it if @honeyankit or @jakecoffman could also opt these repositories into the "Dependabot on Action (private beta)":

- `teamupstart/typescript-platform`
- `teamupstart/upstart-web-frontend`

**Comment by dannyrb** [comment]
Note, these work correctly:

- `/cloudflare` is one workspace tree
- `/e2e` is another workspace tree

However, the primary workspace tree fails with this disk space issue:

- `/`

**Comment by honeyankit** [comment]
@dannyrb : Both the repos are onboarded to dependabot on actions (private beta)
```bash
teamupstart/typescript-platform
teamupstart/upstart-web-frontend
```

**Comment by honeyankit** [comment]
@dannyrb: If you wish, I can enroll you entire org. Once that is enabled, any new repos you create in that org, those repos will be automatically onboarded to Dependabot on Actions (private beta)?

**Comment by dannyrb** [comment]
@honeyankit unfortunately, this hasn't resolved our disk space issues and I'm stuck on how to proceed; but I understand if that's outside the scope of support you're able to offer.

**Security Update Example**
https://github.com/teamupstart/upstart-web-frontend/actions/runs/8255816735/job/22583121598

```
proxy | 2024/03/12 21:14:19 [061] 200 [https://registry.yarnpkg.com:443/turbo-linux-64/-/turbo-linux-64-1.10.14.tgz](https://registry.yarnpkg.com/turbo-linux-64/-/turbo-linux-64-1.10.14.tgz)
  proxy | 2024/03/12 21:14:24 Posting metrics to remote API endpoint
  proxy | 2024/03/12 21:14:24 Successfully posted metrics data via api client
  proxy | 2024/03/12 21:20:00 [063] POST /update_jobs/7991804[97](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8255816735/job/22583121598#step:3:99)/record_update_job_unknown_error
  proxy | 2024/03/12 21:20:00 [063] 204 /update_jobs/7[99](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8255816735/job/22583121598#step:3:101)180497/record_update_job_unknown_error
  proxy | 2024/03/12 21:20:00 [065] POST /update_jobs/799180497/record_update_job_error
  proxy | 2024/03/12 21:20:00 [065] 204 /update_jobs/799180497/record_update_job_error
  proxy | 2024/03/12 21:20:00 [067] POST /update_jobs/799180497/increment_metric
  proxy | 2024/03/12 21:20:00 [067] 204 /update_jobs/799180497/increment_metric
  proxy | 2024/03/12 21:20:00 [069] POST /update_jobs/799180497/record_update_job_unknown_error
  proxy | 2024/03/12 21:20:00 [069] 204 /update_jobs/799180497/record_update_job_unknown_error
updater | 2024/03/12 21:20:00 ERROR <job_799180497> Error processing axios (Dependabot::SharedHelpers::HelperSubprocessFailed)
2024/03/12 21:20:00 ERROR <job_799180497> ➤ YN0000: · Yarn 4.1.1
➤ YN0000: ┌ Resolution step
Resolution step
➤ YN0000: └ Completed in 1s 463ms
➤ YN0000: ┌ Post-resolution validation
Post-resolution validation
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
Fetch step
➤ YN0000: └ Completed in 1m 4s
➤ YN0000: ┌ Link step
Link step
➤ YN0001: Error: While cloning /home/dependabot/dependabot-updater/repo/apps/distribution/node_modules/@design-systems/utils -> /home/dependabot/dependabot-updater/repo/apps/top-of-the-funnel/node_modules/@design-systems/utils ENOSPC: no space left on device, copyfile '/home/dependabot/dependabot-updater/repo/apps/distribution/node_modules/@design-systems/utils/dist/cjs/utils/createSlots.js' -> '/home/dependabot/dependabot-updater/repo/apps/top-of-the-funnel/node_modules/@design-systems/utils/dist/cjs/utils/createSlots.js'
➤ YN0000: └ Completed in 4m 48s
➤ YN0000: · Failed with errors in 5m 52s
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/common/lib/dependabot/shared_helpers.rb:429:in `run_shell_command'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `bind_call'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `validate_call_skip_block_type'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:111:in `block in create_validator_slow_skip_block_type'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb:176:in `run_single_yarn_command'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/helpers.rb:166:in `run_yarn_command'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:155:in `run_yarn_berry_top_level_updater'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:112:in `block (2 levels) in run_yarn_updater'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:109:in `chdir'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:109:in `block in run_yarn_updater'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/common/lib/dependabot/shared_helpers.rb:265:in `with_git_configured'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:[108](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8255816735/job/22583121598#step:3:110):in `run_yarn_updater'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:81:in `run_current_yarn_update'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:62:in `block in updated_yarn_lock'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/common/lib/dependabot/shared_helpers.rb:58:in `block in in_a_temporary_repo_directory'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/common/lib/dependabot/shared_helpers.rb:58:in `chdir'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/common/lib/dependabot/shared_helpers.rb:58:in `in_a_temporary_repo_directory'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:58:in `updated_yarn_lock'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater/yarn_lockfile_updater.rb:34:in `updated_yarn_lock_content'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:[241](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8255816735/job/22583121598#step:3:247):in `updated_yarn_lock_content'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:172:in `yarn_lock_changed?'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:200:in `block in updated_lockfiles'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:199:in `each'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:199:in `updated_lockfiles'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/npm_and_yarn/lib/dependabot/npm_and_yarn/file_updater.rb:44:in `updated_dependency_files'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:135:in `generate_dependency_files'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:68:in `run'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:42:in `create_from'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:148:in `check_and_create_pull_request'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:64:in `check_and_create_pr_with_error_handling'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `block in perform'
updater | 2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `each'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/create_security_update_pull_request.rb:51:in `perform'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:43:in `block in perform_job'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `block in with_span'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/context.rb:87:in `with_value'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `with_span'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:17:in `perform_job'
2024/03/12 21:20:00 ERROR <job_799180497> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:36:in `run'
2024/03/12 21:20:00 ERROR <job_799180497> bin/update_files.rb:33:in `<main>'
  proxy | 2024/03/12 21:20:01 [071] PATCH /update_jobs/799180497/mark_as_processed
  proxy | 2024/03/12 21:20:01 [071] 204 /update_jobs/799180497/mark_as_processed
updater | 2024/03/12 21:20:01 INFO <job_799180497> Finished job processing
updater | 2024/03/12 21:20:01 INFO Results:
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+-------------------------------+
| Dependencies failed to update |
+---------------+---------------+
| axios         | unknown_error |
+---------------+---------------+
Failure running container 7f1b2ca0ec7a043b1715ab1775f85b974a8266cd25e5ec8405929bea391d4[256](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8255816735/job/22583121598#step:3:262)
  proxy | 2024/03/12 21:20:24 Posting metrics to remote API endpoint
  proxy | 2024/03/12 21:20:24 Successfully posted metrics data via api client
Cleaned up container 7f1b2ca0ec7a043b1715ab1775f85b974a8[266](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8255816735/job/22583121598#step:3:272)cd25e5ec8405929bea391d4256
  proxy | 2024/03/12 21:20:57 0/34 calls cached (0%)
(node:1436) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by dannyrb** [comment]
**Updater**

```
updater | 2024/03/11 21:11:31 INFO <job_798657872> Starting job processing
updater | 2024/03/11 21:11:31 INFO <job_798657872> Job definition: {"job":{"allowed-updates":[{"dependency-type":"direct","update-type":"all"}],"commit-message-options":{"prefix":null,"prefix-development":null,"include-scope":null},"credentials-metadata":[{"type":"npm_registry","registry":"upstart.jfrog.io/artifactory/api/npm/local-npm/"},{"type":"git_source","host":"github.com"}],"debug":null,"dependencies":null,"dependency-groups":[],"dependency-group-to-refresh":null,"existing-pull-requests":[],"existing-group-pull-requests":[],"experiments":{"record-ecosystem-versions":true,"record-update-job-unknown-error":true,"proxy-cached":true},"ignore-conditions":[],"lockfile-only":false,"max-updater-run-time":2700,"package-manager":"npm_and_yarn","proxy-log-response-body-on-auth-failure":true,"requirements-update-strategy":null,"reject-external-code":false,"security-advisories":[],"security-updates-only":false,"source":{"provider":"github","repo":"teamupstart/upstart-web-frontend","branch":null,"directory":"/.","api-endpoint":"https://api.github.com/","hostname":"github.com"},"updating-a-pull-request":false,"update-subdependencies":false,"vendor-dependencies":false,"repo-private":true}}
  proxy | 2024/03/11 21:11:32 [002] GET https://github.com:443/teamupstart/upstart-web-frontend/info/refs?service=git-upload-pack
  proxy | 2024/03/11 21:11:32 [002] * authenticating git server request (host: github.com)
  proxy | 2024/03/11 21:11:32 [002] 200 https://github.com:443/teamupstart/upstart-web-frontend/info/refs?service=git-upload-pack
  proxy | 2024/03/11 21:11:32 [004] POST https://github.com:443/teamupstart/upstart-web-frontend/git-upload-pack
2024/03/11 21:11:32 [004] * authenticating git server request (host: github.com)
  proxy | 2024/03/11 21:11:32 [004] 200 https://github.com:443/teamupstart/upstart-web-frontend/git-upload-pack
  proxy | 2024/03/11 21:11:32 [006] POST https://github.com:443/teamupstart/upstart-web-frontend/git-upload-pack
  proxy | 2024/03/11 21:11:32 [006] * authenticating git server request (host: github.com)
  proxy | 2024/03/11 21:11:33 [006] 200 https://github.com:443/teamupstart/upstart-web-frontend/git-upload-pack
  proxy | 2024/03/11 21:12:04 [008] GET https://repo.yarnpkg.com:443/3.5.0/packages/yarnpkg-cli/bin/yarn.js
  proxy | 2024/03/11 21:12:04 [008] 200 https://repo.yarnpkg.com:443/3.5.0/packages/yarnpkg-cli/bin/yarn.js
  proxy | 2024/03/11 21:12:04 [010] POST /update_jobs/798657872/record_ecosystem_versions
  proxy | 2024/03/11 21:12:04 [010] 204 /update_jobs/798657872/record_ecosystem_versions
updater | 2024/03/11 21:12:04 INFO <job_798657872> Finished job processing
updater | 2024/03/11 21:12:06 INFO <job_798657872> Starting job processing
  proxy | 2024/03/11 21:12:11 [013] POST /update_jobs/798657872/update_dependency_list
  proxy | 2024/03/11 21:12:11 [013] 204 /update_jobs/798657872/update_dependency_list
  proxy | 2024/03/11 21:12:11 [015] POST /update_jobs/798657872/increment_metric
  proxy | 2024/03/11 21:12:11 [015] 204 /update_jobs/798657872/increment_metric
updater | 2024/03/11 21:12:11 INFO <job_798657872> Starting update job for teamupstart/upstart-web-frontend
2024/03/11 21:12:11 INFO <job_798657872> Checking all dependencies for version updates...
updater | 2024/03/11 21:12:12 INFO <job_798657872> Checking if @types/lodash.debounce 4.0.9 needs updating
  proxy | 2024/03/11 21:12:12 [019] GET https://upstart.jfrog.io:443/artifactory/api/npm/local-npm/@types%2Flodash.debounce
  proxy | 2024/03/11 21:12:12 [019] * authenticating npm registry request (host: upstart.jfrog.io, token auth)
  proxy | 2024/03/11 21:12:12 [019] 404 https://upstart.jfrog.io:443/artifactory/api/npm/local-npm/@types%2Flodash.debounce
  proxy | 2024/03/11 21:12:12 [021] GET https://registry.npmjs.org:443/@types%2Flodash.debounce
  proxy | 2024/03/11 21:12:12 [021] 200 https://registry.npmjs.org:443/@types%2Flodash.debounce
  proxy | 2024/03/11 21:12:12 [023] HEAD https://registry.npmjs.org:443/@types/lodash.debounce/-/lodash.debounce-4.0.9.tgz
  proxy | 2024/03/11 21:12:12 [023] 200 https://registry.npmjs.org:443/@types/lodash.debounce/-/lodash.debounce-4.0.9.tgz
updater | 2024/03/11 21:12:12 INFO <job_798657872> Latest version is 4.0.9
updater | 2024/03/11 21:12:12 INFO <job_798657872> No update needed for @types/lodash.debounce 4.0.9
2024/03/11 21:12:12 INFO <job_798657872> Checking if dayjs 1.11.8 needs updating
  proxy | 2024/03/11 21:12:12 [025] GET https://upstart.jfrog.io:443/artifactory/api/npm/local-npm/dayjs
  proxy | 2024/03/11 21:12:12 [025] * authenticating npm registry request (host: upstart.jfrog.io, token auth)
  proxy | 2024/03/11 21:12:12 [025] 404 https://upstart.jfrog.io:443/artifactory/api/npm/local-npm/dayjs
  proxy | 2024/03/11 21:12:12 [0[27](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8239765036/job/22533730267#step:3:29)] GET https://registry.npmjs.org:443/dayjs
  proxy | 2024/03/11 21:12:12 [027] 200 https://registry.npmjs.org:443/dayjs
  proxy | 2024/03/11 21:12:13 [029] HEAD https://registry.npmjs.org:443/dayjs/-/dayjs-1.11.10.tgz
  proxy | 2024/03/11 21:12:13 [029] 200 https://registry.npmjs.org:443/dayjs/-/dayjs-1.11.10.tgz
updater | 2024/03/11 21:12:13 INFO <job_798657872> Latest version is 1.11.10
  proxy | 2024/03/11 21:12:[28](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8239765036/job/22533730267#step:3:30) Posting metrics to remote API endpoint
  proxy | 2024/03/11 21:12:28 Successfully posted metrics data via api client
updater | 2024/03/11 21:17:17 INFO <job_798657872> Requirements to unlock own
updater | 2024/03/11 21:17:17 INFO <job_798657872> Requirements update strategy bump_versions
updater | 2024/03/11 21:17:17 INFO <job_798657872> Updating dayjs from 1.11.8 to 1.11.10
  proxy | 2024/03/11 21:17:17 [0[31](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8239765036/job/22533730267#step:3:33)] POST /update_jobs/798657872/record_update_job_error
  proxy | 2024/03/11 21:17:17 [031] 204 /update_jobs/798657872/record_update_job_error
  proxy | 2024/03/11 21:17:17 [033] PATCH /update_jobs/798657872/mark_as_processed
  proxy | 2024/03/11 21:17:17 [033] 204 /update_jobs/798657872/mark_as_processed
updater | 2024/03/11 21:17:17 INFO <job_798657872> Finished job processing
updater | 2024/03/11 21:17:17 INFO Results:
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+-------------+
|   Errors    |
+-------------+
| out_of_disk |
+-------------+
Failure running container 51ee0934d0e552b92750fd9ff[32](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8239765036/job/22533730267#step:3:34)101ef4c75ddbc8b3b778c09fa0b6d98bffdab
  proxy | 2024/03/11 21:17:28 Posting metrics to remote API endpoint
  proxy | 2024/03/11 21:17:28 Successfully posted metrics data via api client
Cleaned up container 51ee09[34](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8239765036/job/22533730267#step:3:36)d0e552b92750fd9ff32101ef4c75ddbc8b3b778c09fa0b6d98bffdab
  proxy | 2024/03/11 21:18:[37](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8239765036/job/22533730267#step:3:39) 0/15 calls cached (0%)
(node:1508) [DEP01[47](https://github.com/teamupstart/upstart-web-frontend/actions/runs/8239765036/job/22533730267#step:3:49)] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: Dependabot encountered an error performing the update

Error: The updater encountered one or more errors.
```

**Comment by dannyrb** [comment]
@honeyankit, any chance that because these are on actions I can use an instance provisioned with more resources, or configure it in some other way that allows me to debug the issue(s) at play?

**Comment by honeyankit** [comment]
@dannyrb : Unfortunately no. We cannot change the disk size on the Action runners. It is possible for you to breakdown your repos into multi-directory. Something like below? This will run each directory in separate Action runner and might save the disk space. 

Example dependabot.yml
```yaml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/foo/first"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/foo/second"
    schedule:
      interval: "daily"
```

**Comment by dannyrb** [comment]
>  It is possible for you to breakdown your repos into multi-directory.

@honeyankit, I can give it a try and report back!

I am wondering if there is another less obvious issue that is being masked. This repository can restore all dependencies on default action instances without hitting disk issues, and we killed several hundred MB of cached dependencies to see if it would relieve enough pressure here to make a difference.

Given what I've read in other issues, splitting by directory isn't recommended when both directories are a part of the same workspace and share a lockfile. While a `dependabot.yml` file with an entry per directory directory is feasible, I'm hesitant to split the workspace, lockfile, etc. as it would impact a lot of our other monorepo tooling

> Another option of self-hosted runner might work

Ah, our enterprise organization does not yet have self-hosted runners setup. This does seem like a good option to push on if we're blocked here.

**Comment by NatoBoram** [comment]
@honeyankit splitting the Dependabot one ecosystem per package sounds like a great idea - but can we reuse groupings? For example, I have 82 lines of groupings. I wouldn't want to copy these groups 5 times for the 5 packages we have.

**Comment by ivopintodasilva** [comment]
@honeyankit i'm also running out of space during the update
is it possible to add `amieso/iosapp` to dependabot on actions (private beta)?

**Comment by v-thavaahariharangit** [comment]
At this moment this is the only possible solution we could provide

https://github.com/dependabot/dependabot-core/issues/9265#issuecomment-1993078282

closing the ticket with this note.
