### ISSUE TITLE
Strict Type Check for CodeCommit Client enforcing incorrect type

### ISSUE THREAD

**Issue by dwc0011** [dependabot/dependabot-core#9333]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

N/A

### What you expected to see, versus what you actually saw

Running Dependabot against a CodeCommit repo errors due to expected return type of "Aws::CodeCommit::Types::GetFolderOutput" when the Dependabot CodeCommit client calls the method "fetch_repo_contents" which calls the [AWS::CodeCommit::Client get_folder method](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CodeCommit/Client.html#get_folder-instance_method).

Actual return type from get_folder() is a response object of type [Seahorse::Client::Response](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Seahorse/Client/Response.html) as noted in the [AWS::CodeCommit::Client get_folder method api](https://docs.aws.amazon.com/sdk-for-ruby/v3/api/Aws/CodeCommit/Client.html#get_folder-instance_method).

### Smallest manifest that reproduces the issue

N/A

**Comment by dwc0011** [comment]
@abdulapopoola It not the ruby bundler per se, it is the dependabot codecommit client, not srue if there is a tag for that.

**Comment by JamieMagee** [comment]
@dwc0011 are you seeing a stack trace when running Dependabot against CodeCommit? Could you share that please?

**Comment by dwc0011** [comment]
First, I would like to mention that it any processing of a codecommit repo, regardless of ecosystem.  Below happens to be where it originates from the python file fetchers, but we have stack traces for every ecosystem that we process.  

If you test against any codecommit repo you will experience this error. I was able to recreate the issue using the .devcontainer (after some trial and error configuring it) and stepped it through the debugger as well.  The seahorse response is a wrapper, somehow sorbet needs to be made aware or it, if sorbet supports this, I could not find any definitive answer, but I have no experience with it and just a tad with Ruby.  See the error and stack blow.

Error:
`: Return value: Expected type Aws::CodeCommit::Types::GetFolderOutput, got type Seahorse::Client::Response with value #<struct Aws::CodeCommit::T...olic_links=[], sub_modules=[]>`

Stack (1 of many, comes from any of the file fetchers, this just happens to be the python one, but they all lead back to the Caller and Definition provided.
```
Caller: /dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.246.0/lib/dependabot/file_fetchers/base.rb:623
Definition: /dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.246.0/lib/dependabot/clients/codecommit.rb:87.

E, [2024-03-12T13:51:05.694386 #7] ERROR -- : ["/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/configuration.rb:296:in `call_validation_error_handler_default'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/configuration.rb:303:in `call_validation_error_handler'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:300:in `report_error'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:176:in `validate_call_skip_block_type'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.246.0/lib/dependabot/file_fetchers/base.rb:623:in `_codecommit_repo_contents'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation_2_7.rb:1102:in `bind_call'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation_2_7.rb:1102:in `block in create_validator_method_medium3'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.246.0/lib/dependabot/file_fetchers/base.rb:499:in `_fetch_repo_contents_fully_specified'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation_2_7.rb:1187:in `bind_call'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation_2_7.rb:1187:in `block in create_validator_method_medium4'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.246.0/lib/dependabot/file_fetchers/base.rb:460:in `_fetch_repo_contents'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:167:in `bind_call'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.246.0/lib/dependabot/file_fetchers/base.rb:302:in `repo_contents'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:167:in `bind_call'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.246.0/lib/dependabot/file_fetchers/base.rb:202:in `fetch_file_if_present'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:167:in `bind_call'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-python-0.246.0/lib/dependabot/python/file_fetcher.rb:150:in `pipfile'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-python-0.246.0/lib/dependabot/python/file_fetcher.rb:99:in `pipenv_files'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-python-0.246.0/lib/dependabot/python/file_fetcher.rb:75:in `fetch_files'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:270:in `bind_call'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation.rb:270:in `validate_call'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/dependabot-common-0.246.0/lib/dependabot/file_fetchers/base.rb:134:in `files'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'", 
"/dependabot-script/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11284/lib/types/private/methods/call_validation_2_7.rb:919:in `block in create_validator_method_medium0'", 
"/dependabot-script/updater.rb:86:in `update'", 
"./dependabot.rb:70:in `block (3 levels) in <main>'", 
"./dependabot.rb:67:in `each'", 
"./dependabot.rb:67:in `block (2 levels) in <main>'", 
"./dependabot.rb:58:in `each'", 
"./dependabot.rb:58:in `block in <main>'", 
"./dependabot.rb:34:in `each'", 
"./dependabot.rb:34:in `<main>'"]
```
