### ISSUE TITLE
Github API hitting rate limit when unauthenticated

### ISSUE THREAD

**Issue by lenntt** [dependabot/dependabot-core#942]
I'm using `dependabot-script` with GitHub Enterprise.
For some public dependencies, dependabot queries public GitHub.
But, GitHub doesn't like being queried without authentication.

Any suggestions, to make it either more robust, do less queries, or workarounds?

```
Traceback (most recent call last):
        30: from generic-update-script.rb:121:in `<main>'
        29: from generic-update-script.rb:121:in `each'
        28: from generic-update-script.rb:178:in `block in <main>'
        27: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/pull_request_creator.rb:56:in `create'
        26: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/pull_request_creator.rb:76:in `github_creator'
        25: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/pull_request_creator/message_builder.rb:56:in `pr_message'
        24: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/pull_request_creator/message_builder.rb:354:in `metadata_cascades'
        23: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/pull_request_creator/message_builder.rb:373:in `metadata_cascades_for_dep'
        22: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/pull_request_creator/message_builder.rb:454:in `commits_cascade'
        21: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/pull_request_creator/message_builder.rb:558:in `commits'
        20: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/metadata_finders/base.rb:96:in `commits'
        19: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/metadata_finders/base/commits_finder.rb:42:in `commits'
        18: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/metadata_finders/base/commits_finder.rb:158:in `fetch_github_commits'
        17: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/clients/github_with_retries.rb:86:in `method_missing'
        16: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/clients/github_with_retries.rb:109:in `retry_connection_failures'
        15: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/clients/github_with_retries.rb:89:in `block in method_missing'
        14: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/clients/github_with_retries.rb:89:in `public_send'
        13: from <myenv>/.rvm/gems/ruby-2.5.3/gems/octokit-4.13.0/lib/octokit/client/commits.rb:198:in `compare'
        12: from <myenv>/.rvm/gems/ruby-2.5.3/gems/octokit-4.13.0/lib/octokit/connection.rb:19:in `get'
        11: from <myenv>/.rvm/gems/ruby-2.5.3/gems/octokit-4.13.0/lib/octokit/connection.rb:156:in `request'
        10: from <myenv>/.rvm/gems/ruby-2.5.3/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
         9: from <myenv>/.rvm/gems/ruby-2.5.3/gems/faraday-0.15.4/lib/faraday/connection.rb:138:in `get'
         8: from <myenv>/.rvm/gems/ruby-2.5.3/gems/faraday-0.15.4/lib/faraday/connection.rb:387:in `run_request'
         7: from <myenv>/.rvm/gems/ruby-2.5.3/gems/faraday-0.15.4/lib/faraday/rack_builder.rb:143:in `build_response'
         6: from <myenv>/.rvm/gems/ruby-2.5.3/gems/faraday-0.15.4/lib/faraday/request/retry.rb:128:in `call'
         5: from <myenv>/.rvm/gems/ruby-2.5.3/gems/octokit-4.13.0/lib/octokit/middleware/follow_redirects.rb:61:in `call'
         4: from <myenv>/.rvm/gems/ruby-2.5.3/gems/octokit-4.13.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection'
         3: from <myenv>/.rvm/gems/ruby-2.5.3/gems/faraday-0.15.4/lib/faraday/response.rb:8:in `call'
         2: from <myenv>/.rvm/gems/ruby-2.5.3/gems/faraday-0.15.4/lib/faraday/response.rb:61:in `on_complete'
         1: from <myenv>/.rvm/gems/ruby-2.5.3/gems/faraday-0.15.4/lib/faraday/response.rb:9:in `block in call'
<myenv>/.rvm/gems/ruby-2.5.3/gems/octokit-4.13.0/lib/octokit/response/raise_error.rb:16:in `on_complete': GET https://api.github.com/repos/theintern/intern/compare/4.2.2...4.4.1: 403 - API rate limit exceeded for <myip>. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.) // See: https://developer.github.com/v3/#rate-limiting (Octokit::TooManyRequests)
```

**Comment by greysteil** [comment]
Hmmm, have you provided the script with an access token for public GitHub? Even one that only has access to public repos will get a *much* more generous rate limit.

**Comment by lenntt** [comment]
I secretly hoped I didn't need one as none of my sources are on public github, I provided one, expecting to work better now (didn't realize at first credentials was a list)

**Comment by greysteil** [comment]
Awesome. Do keep pinging me with any GHE issues - want to make the experience as good as possible using the script.

**Comment by GeorgiosGoniotakis** [comment]
Hello @greysteil For users which only want to use GHE, is there a way to completely disable interaction with GitHub.com?
