### ISSUE TITLE
invalid request to private npm repository

### ISSUE THREAD

**Issue by lenntt** [dependabot/dependabot-core#943]
I'm using a private npm repository for some packages within a specific scope. While public packages seem to work, I get an error for scoped packages, see below.

Note the url at the bottom looks weird (twice https, the second without a colon), 
I'set it correctly (afaik).
(I've obfuscated some parts between `<>`)

```
Traceback (most recent call last):
        23: from generic-update-script.rb:121:in `<main>'
        22: from generic-update-script.rb:121:in `each'
        21: from generic-update-script.rb:165:in `block in <main>'
        20: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:26:in `updated_dependency_files'
        19: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:97:in `updated_lockfiles'
        18: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:97:in `each'
        17: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:98:in `block in updated_lockfiles'
        16: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:69:in `package_lock_changed?'
        15: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn.rb:132:in `updated_package_lock_content'
        14: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:30:in`updated_lockfile_content'
        13: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/shared_helpers.rb:32:in `in_a_temporary_directory'
        12: from <myenv>/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/tmpdir.rb:89:in `mktmpdir'
        11: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/shared_helpers.rb:35:in `block in in_a_temporary_directory'
        10: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/shared_helpers.rb:35:in `chdir'
         9: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/shared_helpers.rb:35:in `block (2 levels) in in_a_temporary_directory'
         8: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:34:in`block in updated_lockfile_content'
         7: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:34:in`chdir'
         6: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:35:in`block (2 levels) in updated_lockfile_content'
         5: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:109:in `run_current_npm_update'
         4: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:131:in `run_npm_updater'
         3: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/shared_helpers.rb:112:in `with_git_configured'
         2: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:133:in `block in run_npm_updater'
         1: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/file_updaters/java_script/npm_and_yarn/npm_lockfile_updater.rb:145:in `run_npm_top_level_updater'
<myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/shared_helpers.rb:88:in `run_helper_subprocess': request to https://https//<urlpart1>.com:443/<urlpart2>/@scope%2fpack-age failed, reason: getaddrinfo ENOTFOUND https https:443 (Dependabot::SharedHelpers::HelperSubprocessFailed)
```

**Comment by greysteil** [comment]
Ah, for private npm registries you need to use the following format:

```
{
  "type"=>"npm_registry",
  "token"=> <redacted>,
  "registry"=>"npm.fontawesome.com"
}
```

Note that the registry URL *doesn't* start with its protocol.

Does it work if you use that format?

**Comment by lenntt** [comment]
Tried that too, but that fails earlier (at authentication):
```
Traceback (most recent call last):
        10: from generic-update-script.rb:125:in `<main>'
         9: from generic-update-script.rb:125:in `each'
         8: from generic-update-script.rb:142:in `block in <main>'
         7: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/update_checkers/base.rb:23:in `up_to_date?'
         6: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/update_checkers/base.rb:119:in `version_up_to_date?'
         5: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/update_checkers/base.rb:162:in `numeric_version_up_to_date?'
         4: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/update_checkers/java_script/npm_and_yarn.rb:22:in `latest_version'
         3: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/update_checkers/java_script/npm_and_yarn.rb:164:in `latest_version_details'
         2: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/update_checkers/java_script/npm_and_yarn/latest_version_finder.rb:27:in `latest_version_details_from_registry'
         1: from <myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/update_checkers/java_script/npm_and_yarn/latest_version_finder.rb:223:in `npm_details'
<myenv>/.rvm/gems/ruby-2.5.3/gems/dependabot-core-0.88.3/lib/dependabot/update_checkers/java_script/npm_and_yarn/latest_version_finder.rb:267:in `check_npm_response': The following source could not be reached as it requires authentication (and any provided details were invalid or lacked the required permissions): <myregistrywithouthttps> (Dependabot::PrivateSourceAuthenticationFailure)
```

**Comment by greysteil** [comment]
Hmmm, how are you providing the token? The logic Dependabot uses to convert it into an auth header is [here](https://github.com/dependabot/dependabot-core/blob/master/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker/registry_finder.rb#L73-L81).

Are you able to hit `https://#{registry}/#{dependency_name.gsub("/", "%2F")}` with that header and get an appropriate response?

**Comment by lenntt** [comment]
providing token like this:
``` 
credentials << {
  "type" => "npm_registry",
  "registry" => ENV["DEPENDENCY_REGISTRY"],
  "token" => ENV["DEPENDENCY_TOKEN"]
}
```

I removed the `https` from the url and put some `pp` in `auth_headers` and `dependency_url` in `registry_finder.rb`. the url seems fine, but the header is empty. I'll dig in a bit more, pointers are welcome

**Comment by lenntt** [comment]
With some more digging, I think im onto something

when inspecting `RegistryFinder#auth_token`, 
```
registry # =>with port number
known_registries.map { |cred| cred["registry"] } # same url, without port number
```
Any idea where this is coming from?

**Comment by greysteil** [comment]
Obvious question on this one: does `ENV["DEPENDENCY_REGISTRY"]` have the port number included? If not, does adding it fix this problem?

(I'll update the logic here, too, so that it can match regardless of port.)

**Comment by lenntt** [comment]
This might be an error on my end (I'm not entirely sure, as I thought I tried all combinations) - I seem to have ended up without protocol and without _port number_.
Added it, and its now failing at the same point as #945.

**Comment by wengjq** [comment]
> Ah, for private npm registries you need to use the following format:
> 
> ```
> {
>   "type"=>"npm_registry",
>   "token"=> <redacted>,
>   "registry"=>"npm.fontawesome.com"
> }
> ```
> 
> Note that the registry URL _doesn't_ start with its protocol.
> 
> Does it work if you use that format?

The registry address protocol is http, how to deal with this situation?
