### ISSUE TITLE
NuGet Package With wildcard version throws error

### ISSUE THREAD

**Issue by martin-shields-sage** [dependabot/dependabot-core#9442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

nuget

### Package manager version

latest

### Language version

.NET 6

### Manifest location and content before the Dependabot update

https://github.com/martin-shields-sage/TestProject/blob/master/TestProject.csproj

### dependabot.yml content

```
# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
```

### Updated dependency

https://www.nuget.org/packages/Newtonsoft.Json

12. -> 13.0.3

### What you expected to see, versus what you actually saw

I expect to get a PR for it to update newtonsoft.json to version 13...
(If i update my .csproj with `12.0.3` for example it will run successfully and provide the PR)
what I got was an error in dependabot and no PR made.

### Native package manager behavior

NuGet resolves 12.* to the latest version which at the time of writing is `12.0.3`

### Images of the diff or a link to the PR, issue, or logs

```
 proxy | 2024/04/05 13:15:18 proxy starting, commit: cf8623577dad71c128f219df2b27df6de35b909d
  proxy | 2024/04/05 13:15:18 Listening (:1080)
updater | 2024-04-05T13:15:19.275575323 [810630670:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-04-05T13:15:22Z" level=info msg="guest starting" commit=6d38d40701a6d7284d26225f78dd2c6b85c16229
updater | time="2024-04-05T13:15:22Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=810630670 updater_timeout=45m0s updater_version=5fcf148988e84e7e03871d44106032320cf7c61d-nuget
updater | 2024/04/05 13:15:27 INFO <job_810630670> Starting job processing
updater | 2024/04/05 13:15:27 INFO <job_810630670> Job definition: {"job":{"allowed-updates":[{"dependency-type":"direct","update-type":"all"}],"commit-message-options":{"include-scope":null,"prefix":null,"prefix-development":null},"credentials-metadata":[{"host":"github.com","type":"git_source"}],"debug":null,"dependencies":null,"dependency-group-to-refresh":null,"dependency-groups":[],"existing-group-pull-requests":[],"existing-pull-requests":[],"experiments":{"proxy-cached":true,"record-ecosystem-versions":true,"record-update-job-unknown-error":true},"ignore-conditions":[],"lockfile-only":false,"max-updater-run-time":2700,"package-manager":"nuget","proxy-log-response-body-on-auth-failure":true,"reject-external-code":false,"repo-private":false,"requirements-update-strategy":null,"security-advisories":[],"security-updates-only":false,"source":{"api-endpoint":"https://api.github.com/","branch":null,"directory":"/.","hostname":"github.com","provider":"github","repo":"martin-shields-sage/TestProject"},"update-subdependencies":false,"updating-a-pull-request":false,"vendor-dependencies":false}}
updater | 
  proxy | 2024/04/05 13:15:28 [002] GET https://github.com:443/martin-shields-sage/TestProject/info/refs?service=git-upload-pack
  proxy | 2024/04/05 13:15:28 [002] * authenticating git server request (host: github.com)
  proxy | 2024/04/05 13:15:28 [002] 200 https://github.com:443/martin-shields-sage/TestProject/info/refs?service=git-upload-pack
  proxy | 2024/04/05 13:15:28 [004] POST https://github.com:443/martin-shields-sage/TestProject/git-upload-pack
  proxy | 2024/04/05 13:15:28 [004] * authenticating git server request (host: github.com)
  proxy | 2024/04/05 13:15:28 [004] 200 https://github.com:443/martin-shields-sage/TestProject/git-upload-pack
  proxy | 2024/04/05 13:15:28 [006] POST https://github.com:443/martin-shields-sage/TestProject/git-upload-pack
  proxy | 2024/04/05 13:15:28 [006] * authenticating git server request (host: github.com)
  proxy | 2024/04/05 13:15:28 [006] 200 https://github.com:443/martin-shields-sage/TestProject/git-upload-pack
updater | 2024/04/05 13:15:28 INFO <job_810630670> Finished job processing
updater | time="2024-04-05T13:15:28Z" level=info msg="task complete" container_id=job-810630670-file-fetcher exit_code=0 job_id=810630670 step=fetcher
updater | 2024/04/05 13:15:31 INFO <job_810630670> Starting job processing
  proxy | 2024/04/05 13:15:32 [008] GET https://api.nuget.org:443/v3/registration5-gz-semver2/newtonsoft.json/index.json
  proxy | 2024/04/05 13:15:32 [008] 200 https://api.nuget.org:443/v3/registration5-gz-semver2/newtonsoft.json/index.json
updater | 2024/04/05 13:15:32 INFO <job_810630670> The following dependencies were found:
updater |   name: Newtonsoft.Json, version: 
updater |     file: TestProject.csproj, metadata: 
updater | 2024/04/05 13:15:32 INFO <job_810630670> Starting update job for martin-shields-sage/TestProject
updater | 2024/04/05 13:15:32 INFO <job_810630670> Checking all dependencies for version updates...
updater | 2024/04/05 13:15:32 INFO <job_810630670> Checking if Newtonsoft.Json  needs updating
updater | 2024/04/05 13:15:32 INFO <job_810630670> Latest version is 13.0.3
updater | 2024/04/05 13:15:32 INFO <job_810630670> Requirements to unlock own
updater | 2024/04/05 13:15:33 INFO <job_810630670> Requirements update strategy 
updater | 2024/04/05 13:15:33 ERROR <job_810630670> Error processing Newtonsoft.Json (ArgumentError)
updater | 2024/04/05 13:15:33 ERROR <job_810630670> blank strings must not be provided as versions
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/common/lib/dependabot/dependency.rb:357:in `check_values'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation_2_7.rb:652:in `bind_call'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation_2_7.rb:652:in `block in create_validator_procedure_fast0'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/common/lib/dependabot/dependency.rb:129:in `initialize'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `bind_call'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:169:in `validate_call_skip_block_type'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:111:in `block in create_validator_slow_skip_block_type'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:246:in `new'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:246:in `updated_dependency_with_own_req_unlock'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/common/lib/dependabot/update_checkers/base.rb:109:in `updated_dependencies'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `bind_call'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/call_validation.rb:272:in `validate_call'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/sorbet-runtime-0.5.11193/lib/types/private/methods/_methods.rb:272:in `block in _on_method_added'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:103:in `check_and_create_pull_request'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:64:in `check_and_create_pr_with_error_handling'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:39:in `block in perform'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:39:in `each'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:39:in `perform'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:44:in `block in perform_job'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `block in with_span'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/context.rb:87:in `with_value'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `with_span'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:18:in `perform_job'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/04/05 13:15:33 ERROR <job_810630670> bin/update_files.rb:44:in `<main>'
updater | 2024/04/05 13:15:33 INFO <job_810630670> Finished job processing
updater | 2024/04/05 13:15:33 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +---------------------------------+
updater | |  Dependencies failed to update  |
updater | +-----------------+---------------+
updater | | Newtonsoft.Json | unknown_error |
updater | +-----------------+---------------+
updater | time="2024-04-05T13:15:33Z" level=info msg="task complete" container_id=job-810630670-updater exit_code=0 job_id=810630670 step=updater
```

![image](https://github.com/dependabot/dependabot-core/assets/58210422/86f3c486-6d41-420d-86e7-c352be2e1003)
![image](https://github.com/dependabot/dependabot-core/assets/58210422/1e4d22e4-9c31-4c7b-adc9-296214022def)

### Smallest manifest that reproduces the issue

https://github.com/martin-shields-sage/TestProject

the project above is a simple c# console application using .NET6 and demonstrates the issue.

**Comment by martin-shields-sage** [comment]
Just to note, I originally saw this in one of my other repos and when I was able to run the CLI locally to see if I could figure out the issue I got these addtional logs:

```
updater |   Running for SDK-style project
updater |     Found unsupported version property [****] value [6.0.2.*] in [Directory.Build.props].
updater |     Found unsupported version property [****] value [6.0.1.*] in [Directory.Build.props].
```

I have *d out the property names due to those being private packages

**Comment by jchannon** [comment]
Any plans to support wildcards with nuget? Just came across this

**Comment by brettfo** [comment]
We're working on using the full MSBuild to evaluate dependencies.  That work is ongoing and won't be ready for a few more weeks, but it _does_ handle wildcard versions.

**Comment by mprice-gcmlp** [comment]
This was previously at least opening PR's for non-wild card packages which worked fine for us, but seems to have stopped doing even that and has effectively broken Dependabot entirely for any csproj that we have that contains a floating version.

The package 
```csproj
<PackageReference Include="AutoMapper" Version="13.*" />
<PackageReference Include="Highsoft.Highcharts" Version="10.3.3.1" />
```

```
updater | 2024/12/09 23:04:56 INFO <job_930109900> Updating Highsoft.Highcharts from 10.3.3.1 to 11.4.6.5
updater | running NuGet updater:
/opt/nuget/NuGetUpdater/NuGetUpdater.Cli update --job-path /home/dependabot/dependabot-updater/job.json --repo-root /home/dependabot/dependabot-updater/repo --solution-or-project /***/Infrastructure.csproj --dependency Highsoft.Highcharts --new-version 11.4.6.5 --previous-version 10.3.3.1 --result-output-path /tmp/update-result.json
  proxy | 2024/12/09 23:04:57 Posting metrics to remote API endpoint
  proxy | 2024/12/09 23:04:57 Successfully posted metrics data via api client
updater | 2024/12/09 23:04:56 INFO Temporarily removing `global.json` from `/home/dependabot/dependabot-updater/repo`.
2024/12/09 23:04:56 INFO Restoring `global.json` to `/home/dependabot/dependabot-updater/repo`.
2024/12/09 23:04:56 INFO   No dotnet-tools.json file found.
2024/12/09 23:04:56 INFO   Updating [global.json] file.
2024/12/09 23:04:56 INFO     Dependency [Highsoft.Highcharts] not found.
2024/12/09 23:04:56 INFO Running for project file [***/Infrastructure.csproj]
2024/12/09 23:04:56 INFO Updating project [/home/dependabot/dependabot-updater/repo/***/Infrastructure.csproj]
2024/12/09 23:04:56 INFO   Running 'PackageReference' project direct XML update
2024/12/09 23:04:58 WARN dotnet build in GetAllPackageDependenciesAsync failed. STDOUT:   Determining projects to restore...
/usr/local/dotnet/current/sdk/9.0.100/NuGet.targets(180,5): error : '[13.*]' is not a valid version string. [/tmp/package-dependency-resolution_4vtYqk/Project.csproj]

Build FAILED.

/usr/local/dotnet/current/sdk/9.0.100/NuGet.targets(180,5): error : '[13.*]' is not a valid version string. [/tmp/package-dependency-resolution_4vtYqk/Project.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.48

 STDERR: 

2024/12/09 23:04:58 INFO     Package [Highsoft.Highcharts] Does not exist as a dependency in [/home/dependabot/dependabot-updater/repo/***/Infrastructure.csproj].
2024/12/09 23:04:58 INFO Update complete.
2024/12/09 23:04:58 INFO   Writing update result to [/tmp/update-result.json].
updater | 2024/12/09 23:04:58 INFO <job_930109900> update result: {
  "ErrorType": null,
  "ErrorDetails": null
}
  proxy | 2024/12/09 23:04:58 [412] POST /update_jobs/930109900/record_update_job_error
  proxy | 2024/12/09 23:04:58 [412] 204 /update_jobs/930109900/record_update_job_error
updater | 2024/12/09 23:04:58 INFO <job_930109900> Handled error whilst updating Highsoft.Highcharts: update_not_possible {:dependencies=>["Highsoft.Highcharts"]}

...

+-------------------------------------------+
|       Dependencies failed to update       |
+---------------------+---------------------+
| Highsoft.Highcharts | update_not_possible |
+---------------------+---------------------+
```

**Comment by bkoelman** [comment]
@brettfo I've been experiencing the same issue for months now. Opened a GitHub support ticket back in August 2024, but this regression still has't been addressed.

Floating versions used to work properly before the large MSBuild refactoring. The problematic line is here: https://github.com/dependabot/dependabot-core/blob/167798e88feb5f50b3221807efad70ceed6ad603/nuget/helpers/lib/NuGetUpdater/NuGetUpdater.Core/Utilities/MSBuildHelper.cs#L723

The bug is that Dependabot surrounds the version with square brackets, which indicates a [NuGet version range](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort#version-ranges):

```
Version=\"[{p.Version}]\"
```

That's fine for explicit versions (such as "1.2.3"), but it can't be combined with a [NuGet wildcard version](https://learn.microsoft.com/en-us/nuget/concepts/package-versioning?tabs=semver20sort#references-in-project-files-packagereference) such as "1.2.*".

Therefore, the produced "[1.2.*]" is invalid and rejected by MSBuild, which explains the error.

I don't know why the square brackets are being added in the first place, but it shouldn't do so when there are wildcards in the version. This is a bug in the Dependabot updater. The change was introduced in https://github.com/dependabot/dependabot-core/commit/250c98a755d84453d3cfc2dd60d5f77fb094bfac (Nov 2023), part of https://github.com/dependabot/dependabot-core/pull/8179.

As a result, no PR is being opened for outdated versions of NuGet packages.

We're using floating versions in most places. As a result, Dependabot has become pretty useless since this bug was introduced.

**Comment by bkoelman** [comment]
Will wildcards also work in other places? In our case, the versions exist in multiple .props files.

Feel free to test with https://github.com/json-api-dotnet/JsonApiDotNetCore/blob/master/JsonApiDotNetCore.sln

**Comment by caspChristian** [comment]
@brettfo still seeing "error : '[*]' is not a valid version string" failing the full flow, if there is no real fix for the parsing, could you somehow make dependabot still complete run with warnings, and that way deal with all fully qualified versions?

Otherwise revert https://github.com/dependabot/dependabot-core/commit/250c98a755d84453d3cfc2dd60d5f77fb094bfac which seems to be the cause for this bug.

**Comment by brettfo** [comment]
I've created PR #11862 that allows one package to update when an unrelated dependency has a wildcard version.  Look at the unit test in that PR for an example.

For another scenario, I'm curious about the thoughts of everybody here, specifically:

If a dependency has a wildcard version like `<PackageReference Include="Newtonsoft.Json" Version="12.*" />` what would you think about dependabot updating that to a specific version?  Imagine you got a PR with the following changes:

``` diff
 ...
-<PackageReference Include="Newtonsoft.Json" Version="12.*" />
+<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
 ...
```

My initial thoughts are that it's a weird situation because by including a wildcard in the version, you seem to be indicating that you generally want _some_ version of a dependency, but you don't care which one in particular, but if dependabot made the above change, the project file now has a very specific dependency in mind which seems to go against your initial position.

Another option would be to keep a similar wildcard pattern and update the version to `13.0.*`.

Either of the above changes wouldn't likely be made any time soon because we're currently working on a big rewrite of the NuGet updater that we need to focus on, but I wanted to put this out there to get everybody thinking about the desired outcome.

**Comment by bkoelman** [comment]
Assuming 13.6.3 is the latest version, I would expect `12.*` to update to `13.*`, and `12.3.*` to `13.6.*`. We use the latter, based on the assumption that patch-level changes are always non-breaking.

Initially we only used wildcards in test projects, but with vulnerable dependencies being reported so often, we switched to using wildcards also for our published NuGet packages. This means each time we publish a new release, dependencies are updated to the latest patch versions of that moment.

**Comment by bkoelman** [comment]
Before the large MSBuild refactoring, Dependabot certainly was able to update wildcard versions, preserving the wildcards. Evidence at https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1400.

**Comment by Frulfump** [comment]
12.* to me means that I pin to major version 12 and accept any minor or patch version of it. So dependabot changing the pattern (or giving me a 13.x.y version unless I opt-in to semver-major updates but that might be the default? atleast preserving the pattern then is important) feels super weird.

**Comment by caspChristian** [comment]
Thanks for https://github.com/dependabot/dependabot-core/pull/11862 If that comes to production it would help a great deal!

One example NUnit 3.*
Testcases with `Assert.AreEqual` if this is updated to 4.* build will fail.
I wouldn't expect dependabot to succeed in doing this update.
And in other cases it could be runtime errors being caused by such a change.

Maybe consider adding separate options for how wildcards should be handled.
the 12.* -> 13.0.3 is also "acceptable" in terms of getting a PR and reviewing.
However if closed will/should it create a new PR for 13.0.4, or 13.1.0 or maybe only 14.0.0
And then we are back at this might need to be configurable, and maybe even per `PackageReference` declaration

**Comment by bkoelman** [comment]
@martin-shields-sage Yes, that's how I remember it too. It would bump the version number(s) at the left of the wildcard, while leaving the wildcard itself unmodified. It would never _move_, _delete_, or _insert_ a wildcard.

**Comment by bkoelman** [comment]
@brettfo In response to your comment at https://devblogs.microsoft.com/dotnet/the-new-dependabot-nuget-updater/?commentid=22272#comment-22272:

> The scenario that we don’t support, however, is performing an update while maintaining the wildcard, so in this example, we can’t update the Version attribute to “13.*”. We’re discussing this feature internally, but right now we’re leaning away from it because we’re targeting deterministic builds with well-known package version numbers and if the wildcard is kept at “13.*” then you might get different packages if you built on Monday and then again on Tuesday. We’re always open to feedback, so please let us know about your scenario, especially if I missed something important.

We _intentionally_ put a wildcard in the version at the patch level, so we're not _randomly_ bothered by vulnerability reports. We consider shipping with non-vulnerable dependencies _way more important_ than deterministic builds. Dependabot should respect that wildcard on update, as it has always done in the past. Otherwise, there's no point in us using a wildcard in the first place!

For example, we originally released a package version that depended on `https://www.nuget.org/packages/Microsoft.Extensions.Caching.Memory/8.0.0`, which was later marked as vulnerable. Today, we can release a new version of our package without worrying about that, because our package today depends on `https://www.nuget.org/packages/Microsoft.Extensions.Caching.Memory/8.0.1` (thanks to our wildcard), where the vulnerability has been fixed.

Isn't it obvious that if developers **choose** to use wildcards, it expresses that they **do not care** about deterministic builds?

**Comment by BadMagic100** [comment]
Our use case is to use wildcards to automatically update pre release versions when building locally. So we do want deterministic builds in general, and we get them by restoring in locked mode in ci. A more normal variant of this case would be upgrading X.Y.1 to X.Y.2, with the version X.Y.* requested. In such a case I think it would make sense to update the lock file but not the original package reference when the wildcard still matches after the update, even if you want to make the argument that replacing one wildcard with a different wildcard shouldn't be done.

Related pr where we observed this https://github.com/silksong-modding/Silksong.Prepatcher/pull/17/files

**Comment by JamieMagee** [comment]
Fixed. The updater now preserves wildcard versions like `1.0.*`. When it sees a `*` in the version string, it leaves the notation alone rather than wrapping it in `[version]` brackets. Handled in `MSBuildHelper.cs`.

**Comment by bkoelman** [comment]
@JamieMagee Can you confirm the fix hasn't been released to production yet? I'm asking because Dependabot still removes the wildcard. For example, https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1926/changes, which was opened yesterday.

**Comment by brettfo** [comment]
Thanks all for looking into this.  When the new XML writer was introduced it replaced all wildcard versions with a concrete version.  I've created a PR to retain the wildcard shape here: https://github.com/dependabot/dependabot-core/pull/14205

Let me know if that seems to cover your scenarios.  The new test in `FileWriterWorkerTests.cs` should give a good example of what will happen.

**Comment by brettfo** [comment]
The fix has just been deployed so any job with a start date after the time of this post will have the updated behavior.

**Comment by bkoelman** [comment]
Thanks, the wildcard is preserved now in the diff. I've run a `@dependabot recreate` on https://github.com/json-api-dotnet/JsonApiDotNetCore/pull/1925/changes. The diff changed, but the title didn't update likewise. Is that because a recreate always preserves the original title (so I need to wait for a new PR to verify), or is this another glitch?
