### ISSUE TITLE
Dependabot unable to update project with fuse-python==1.0.7 (pypi) package

### ISSUE THREAD

**Issue by glensc** [dependabot/dependabot-core#9515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

pip, pipenv

### Manifest location and content before the Dependabot update

- https://github.com/glensc/plex-fuse/blob/e2ecdd6faf6ba56ab92db08a94a76ac201c1a717/Pipfile.lock

### dependabot.yml content

- https://github.com/glensc/plex-fuse/blob/e2ecdd6faf6ba56ab92db08a94a76ac201c1a717/.github/dependabot.yml

### What you expected to see, versus what you actually saw

> Pipenv failed to install "fuse-python==1.0.7". This could be caused by missing system dependencies that can't be installed by Dependabot or required installation flags.

I'm guessing it could not install because wheel has not been built (and source dependencies not available), but what wheel is it searching? from logs I see only python version: `python3.11`.

If you could tell what wheel is needed, I could request it from the project:
- https://github.com/libfuse/python-fuse/issues/63

I see this in update logs:
- https://github.com/glensc/plex-fuse/network/updates
  - https://github.com/glensc/plex-fuse/network/updates/19222280/jobs
    - https://github.com/glensc/plex-fuse/network/updates/816023181

logs:

<details>

```
 Dependabot can't resolve your Python dependency files
Dependabot failed to update your dependencies because there was an error resolving your Python dependency files.

Dependabot encountered the following error:

Pipenv failed to install "fuse-python==1.0.7". This could be caused by missing system dependencies that can't be installed by Dependabot or required installation flags.

Error output from running "pipenv lock":
ERROR:pip.subprocessor:python setup.py egg_info exited with 1
Traceback (most recent call last):
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/operations/build/metadata_legacy.py", line 64, in generate_metadata
    call_subprocess(
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/utils/subprocess.py", line 224, in call_subprocess
    raise error
pipenv.patched.pip._internal.exceptions.InstallationSubprocessError: python setup.py egg_info exited with 1
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/utils/resolver.py", line 446, in resolve
    results = resolver.resolve(constraints, check_supported_wheels=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
                ^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
    self._link_candidate_cache = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 157, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/operations/prepare.py", line 71, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/distributions/sdist.py", line 67, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/req/req_install.py", line 584, in prepare_metadata
    self.metadata_directory = generate_metadata_legacy(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/.pyenv/versions/3.11.8/lib/python3.11/site-packages/pipenv/patched/pip/_internal/operations/build/metadata_legacy.py", line 71, in generate_metadata
    raise MetadataGenerationFailed(package_details=details) from error
pipenv.patched.pip._internal.exceptions.MetadataGenerationFailed: metadata generation failed
```

</details>

**Comment by glensc** [comment]
Upstream added needed wheel:
- https://github.com/libfuse/python-fuse/issues/71
