### ISSUE TITLE
Dependabot gets confused over a directory name

### ISSUE THREAD

**Issue by io7m** [dependabot/dependabot-core#9683]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Maven

### dependabot.yml content

https://github.com/io7m-com/xstructural/blob/develop/.github/dependabot.yml

### What you expected to see, versus what you actually saw

See https://github.com/io7m-com/xstructural

My project contains the following modules:

```
com.io7m.xstructural.api
com.io7m.xstructural.cmdline
com.io7m.xstructural.documentation
com.io7m.xstructural.maven_plugin
com.io7m.xstructural.tests
com.io7m.xstructural.vanilla
com.io7m.xstructural.xml
```

Each one of these modules is a directory with a Maven `pom.xml` file in it. So for example, there's a `com.io7m.xstructural.api/pom.xml` file, a `com.io7m.xstructural.cmdline/pom.xml` file, and so on.

Unfortunately, that last module seems to trip up Dependabot. It sees the filename `com.io7m.xstructural.xml`, apparently thinks "this is an XML file", tries to open it as a file, and immediately encounters an "is a directory" I/O error. This can be seen in the attached log output below.

This essentially causes Dependabot to fail to provide any updates to the repository.

### Images of the diff or a link to the PR, issue, or logs

```

  proxy | 2024/05/07 08:59:45 proxy starting, commit: d85fbd08cee81b78b7f408b09b558cac7a0cee5c
  proxy | 2024/05/07 08:59:45 Listening (:1080)
updater | 2024-05-07T08:59:45.781974503 [825006812:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-05-07T08:59:50Z" level=info msg="guest starting" commit=7ae3c8b6b9717f8ad3c56d9958b08ec3c5b6c903
updater | time="2024-05-07T08:59:50Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=825006812 updater_timeout=45m0s updater_version=4161311a41f0ff2f1f045cd92660a73051deb79f-maven
updater | /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/httparty-0.21.0/lib/httparty.rb:10: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of httparty-0.21.0 to add csv into its gemspec.
updater | 2024/05/07 09:00:01 INFO <job_825006812> Starting job processing
updater | 2024/05/07 09:00:01 INFO <job_825006812> Job definition: {"job":{"allowed-updates":[{"dependency-type":"direct","update-type":"all"}],"commit-message-options":{"include-scope":null,"prefix":null,"prefix-development":null},"credentials-metadata":[{"host":"github.com","type":"git_source"}],"debug":null,"dependencies":null,"dependency-group-to-refresh":null,"dependency-groups":[],"existing-group-pull-requests":[],"existing-pull-requests":[],"experiments":{"proxy-cached":true,"record-ecosystem-versions":true,"record-update-job-unknown-error":true},"ignore-conditions":[{"dependency-name":"*","source":".github/dependabot.yml","update-types":["version-update:semver-major"],"updated-at":"2024-05-05T20:58:11.000Z","version-requirement":null}],"lockfile-only":false,"max-updater-run-time":2700,"package-manager":"maven","proxy-log-response-body-on-auth-failure":true,"reject-external-code":false,"repo-private":false,"requirements-update-strategy":null,"security-advisories":[],"security-updates-only":false,"source":{"api-endpoint":"https://api.github.com/","branch":"develop","directory":"/.","hostname":"github.com","provider":"github","repo":"io7m-com/xstructural"},"update-subdependencies":false,"updating-a-pull-request":false,"vendor-dependencies":false}}
updater | 
  proxy | 2024/05/07 09:00:02 [002] GET https://github.com:443/io7m-com/xstructural/info/refs?service=git-upload-pack
  proxy | 2024/05/07 09:00:02 [002] * authenticating git server request (host: github.com)
  proxy | 2024/05/07 09:00:02 [002] 200 https://github.com:443/io7m-com/xstructural/info/refs?service=git-upload-pack
  proxy | 2024/05/07 09:00:02 [004] POST https://github.com:443/io7m-com/xstructural/git-upload-pack
  proxy | 2024/05/07 09:00:02 [004] * authenticating git server request (host: github.com)
  proxy | 2024/05/07 09:00:02 [004] 200 https://github.com:443/io7m-com/xstructural/git-upload-pack
  proxy | 2024/05/07 09:00:02 [006] POST https://github.com:443/io7m-com/xstructural/git-upload-pack
  proxy | 2024/05/07 09:00:02 [006] * authenticating git server request (host: github.com)
  proxy | 2024/05/07 09:00:02 [006] 200 https://github.com:443/io7m-com/xstructural/git-upload-pack
updater | 2024/05/07 09:00:03 ERROR <job_825006812> Error during file fetching; aborting: Is a directory @ io_fread - /home/dependabot/dependabot-updater/repo/com.io7m.xstructural.xml
updater | 2024/05/07 09:00:03 ERROR <job_825006812> Is a directory @ io_fread - /home/dependabot/dependabot-updater/repo/com.io7m.xstructural.xml
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/common/lib/dependabot/file_fetchers/base.rb:218:in `read'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/common/lib/dependabot/file_fetchers/base.rb:218:in `load_cloned_file_if_present'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation_2_7.rb:968:in `bind_call'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation_2_7.rb:968:in `block in create_validator_method_medium1'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/common/lib/dependabot/file_fetchers/base.rb:245:in `fetch_file_from_host'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:167:in `bind_call'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/maven/lib/dependabot/maven/file_fetcher.rb:76:in `block in recursively_fetch_child_poms'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/nokogiri-1.16.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:235:in `block in each'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/nokogiri-1.16.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `upto'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/nokogiri-1.16.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `each'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/maven/lib/dependabot/maven/file_fetcher.rb:65:in `flat_map'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/maven/lib/dependabot/maven/file_fetcher.rb:65:in `recursively_fetch_child_poms'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/maven/lib/dependabot/maven/file_fetcher.rb:49:in `child_poms'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/maven/lib/dependabot/maven/file_fetcher.rb:30:in `fetch_files'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/common/lib/dependabot/file_fetchers/base.rb:134:in `files'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:147:in `block in dependency_files'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:165:in `with_retries'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:147:in `dependency_files'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:36:in `block in perform_job'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `block in with_span'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/context.rb:87:in `with_value'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `with_span'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:22:in `perform_job'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/05/07 09:00:03 ERROR <job_825006812> bin/fetch_files.rb:37:in `<main>'
updater | 2024/05/07 09:00:03 INFO <job_825006812> Finished job processing
updater | 2024/05/07 09:00:03 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------+
updater | |       Errors       |
updater | +--------------------+
updater | | file_fetcher_error |
updater | +--------------------+
updater | time="2024-05-07T09:00:03Z" level=info msg="task complete" container_id=job-825006812-file-fetcher exit_code=0 job_id=825006812 step=fetcher
updater | time="2024-05-07T09:00:03Z" level=warning msg="failed during fetch, skipping updater" job_id=825006812
```

**Comment by io7m** [comment]
This same problem is occurring on a different repository:

https://github.com/io7m-com/quixote/network/updates/826262809

```

  proxy | 2024/05/09 22:50:57 proxy starting, commit: d85fbd08cee81b78b7f408b09b558cac7a0cee5c
  proxy | 2024/05/09 22:50:57 Listening (:1080)
updater | 2024-05-09T22:50:58.306707404 [826262809:main:WARN:src/devices/src/legacy/serial.rs:222] Detached the serial input due to peer close/error.
updater | time="2024-05-09T22:51:00Z" level=info msg="guest starting" commit=7ae3c8b6b9717f8ad3c56d9958b08ec3c5b6c903
updater | time="2024-05-09T22:51:00Z" level=info msg="starting job..." fetcher_timeout=10m0s job_id=826262809 updater_timeout=45m0s updater_version=6c1803521cfef2fcd4e5accda12fa4d1bcab0564-maven
updater | /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/httparty-0.21.0/lib/httparty.rb:10: warning: csv was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec. Also contact author of httparty-0.21.0 to add csv into its gemspec.
updater | 2024/05/09 22:51:08 INFO <job_826262809> Starting job processing
updater | 2024/05/09 22:51:08 INFO <job_826262809> Job definition: {"job":{"allowed-updates":[{"dependency-type":"direct","update-type":"all"}],"commit-message-options":{"include-scope":null,"prefix":null,"prefix-development":null},"credentials-metadata":[{"host":"github.com","type":"git_source"}],"debug":null,"dependencies":null,"dependency-group-to-refresh":null,"dependency-groups":[],"existing-group-pull-requests":[],"existing-pull-requests":[],"experiments":{"proxy-cached":true,"record-ecosystem-versions":true,"record-update-job-unknown-error":true},"ignore-conditions":[{"dependency-name":"*","source":".github/dependabot.yml","update-types":["version-update:semver-major"],"updated-at":"2024-05-05T20:57:55.000Z","version-requirement":null}],"lockfile-only":false,"max-updater-run-time":2700,"package-manager":"maven","proxy-log-response-body-on-auth-failure":true,"reject-external-code":false,"repo-private":false,"requirements-update-strategy":null,"security-advisories":[],"security-updates-only":false,"source":{"api-endpoint":"https://api.github.com/","branch":"develop","directory":"/.","hostname":"github.com","provider":"github","repo":"io7m-com/quixote"},"update-subdependencies":false,"updating-a-pull-request":false,"vendor-dependencies":false}}
updater | 
  proxy | 2024/05/09 22:51:08 [002] GET https://github.com:443/io7m-com/quixote/info/refs?service=git-upload-pack
  proxy | 2024/05/09 22:51:08 [002] * authenticating git server request (host: github.com)
  proxy | 2024/05/09 22:51:08 [002] 200 https://github.com:443/io7m-com/quixote/info/refs?service=git-upload-pack
  proxy | 2024/05/09 22:51:08 [004] POST https://github.com:443/io7m-com/quixote/git-upload-pack
  proxy | 2024/05/09 22:51:08 [004] * authenticating git server request (host: github.com)
  proxy | 2024/05/09 22:51:08 [004] 200 https://github.com:443/io7m-com/quixote/git-upload-pack
  proxy | 2024/05/09 22:51:08 [006] POST https://github.com:443/io7m-com/quixote/git-upload-pack
  proxy | 2024/05/09 22:51:08 [006] * authenticating git server request (host: github.com)
  proxy | 2024/05/09 22:51:09 [006] 200 https://github.com:443/io7m-com/quixote/git-upload-pack
updater | 2024/05/09 22:51:09 ERROR <job_826262809> Error during file fetching; aborting: Is a directory @ io_fread - /home/dependabot/dependabot-updater/repo/com.io7m.quixote.xml
updater | 2024/05/09 22:51:09 ERROR <job_826262809> Is a directory @ io_fread - /home/dependabot/dependabot-updater/repo/com.io7m.quixote.xml
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/common/lib/dependabot/file_fetchers/base.rb:218:in `read'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/common/lib/dependabot/file_fetchers/base.rb:218:in `load_cloned_file_if_present'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation_2_7.rb:968:in `bind_call'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation_2_7.rb:968:in `block in create_validator_method_medium1'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/common/lib/dependabot/file_fetchers/base.rb:245:in `fetch_file_from_host'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:167:in `bind_call'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/maven/lib/dependabot/maven/file_fetcher.rb:76:in `block in recursively_fetch_child_poms'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/nokogiri-1.16.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:235:in `block in each'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/nokogiri-1.16.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `upto'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/nokogiri-1.16.4-x86_64-linux/lib/nokogiri/xml/node_set.rb:234:in `each'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/maven/lib/dependabot/maven/file_fetcher.rb:65:in `flat_map'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/maven/lib/dependabot/maven/file_fetcher.rb:65:in `recursively_fetch_child_poms'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/maven/lib/dependabot/maven/file_fetcher.rb:49:in `child_poms'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/maven/lib/dependabot/maven/file_fetcher.rb:30:in `fetch_files'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/common/lib/dependabot/file_fetchers/base.rb:134:in `files'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:147:in `block in dependency_files'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:165:in `with_retries'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:147:in `dependency_files'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:36:in `block in perform_job'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `block in with_span'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/context.rb:87:in `with_value'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `with_span'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/lib/dependabot/file_fetcher_command.rb:22:in `perform_job'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/05/09 22:51:09 ERROR <job_826262809> bin/fetch_files.rb:37:in `<main>'
updater | 2024/05/09 22:51:09 INFO <job_826262809> Finished job processing
updater | 2024/05/09 22:51:09 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +--------------------+
updater | |       Errors       |
updater | +--------------------+
updater | | file_fetcher_error |
updater | +--------------------+
updater | time="2024-05-09T22:51:09Z" level=info msg="task complete" container_id=job-826262809-file-fetcher exit_code=0 job_id=826262809 step=fetcher
updater | time="2024-05-09T22:51:09Z" level=warning msg="failed during fetch, skipping updater" job_id=826262809

```

**Comment by snazy** [comment]
This issue still exists. This [breaks dependabot in Apache Karaf](https://github.com/apache/karaf/issues/1991), just because there's a directory called `specs/java.xml`.

**Comment by HaripriyaChintalapati** [comment]
Fixed by https://github.com/dependabot/dependabot-core/pull/15787 (merged 2026-08-07).

The Maven FileFetcher previously decided whether a <module> value was a pom file or a directory by a suffix guess (relative_path.end_with?(".xml")), so a module directory named com.io7m.xstructural.xml was mistaken for a pom file, read directly, and raised Errno::EISDIR — aborting the whole job with file_fetcher_error.

fetch_child_pom now resolves the module as a directory first (<module>/pom.xml) and only falls back to treating an .xml value as a custom-named pom file, rescuing both DependencyFileNotFound and Errno::EISDIR. Custom-named pom files (e.g. <module>sub/custom-pom.xml</module>) still resolve correctly, and git-submodule handling is unchanged. Regression tests and fixtures covering .xml- and pom.xml-suffixed module directories were added in the same PR.

Closing as resolved — thanks for the detailed logs, @io7m.
