### ISSUE TITLE
Nuget System.ArgumentException: Value cannot be null or an empty string. (Parameter 'value')

### ISSUE THREAD

**Issue by a-jackson** [dependabot/dependabot-core#9804]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Nuget

### Language version

.Net 8.0

### Updated dependency

QuestPDF from 2024.3.6 to 2024.3.7

### What you expected to see, versus what you actually saw

Expected a PR with the update but it throws an error. We're using central package management but it works with other dependencies. There's this and a couple of other packages have the same problem but everything else works.

### Images of the diff or a link to the PR, issue, or logs

<details><summary>Stack trace</summary>
<p>

```
updater | Updating project [/home/dependabot/dependabot-updater/repo/src/processor/services/Reporting/Reporting.csproj]
updater |   Running for SDK-style project
updater |     Found incorrect [PackageVersion] version attribute in [Directory.Packages.props].
updater | Unhandled exception: System.ArgumentException: Value cannot be null or an empty string. (Parameter 'value')
updater |    at NuGet.Versioning.NuGetVersion.Parse(String value) in /opt/nuget/lib/NuGet.Client/src/NuGet.Core/NuGet.Versioning/NuGetVersionFactory.cs:line 21
updater |    at NuGetUpdater.Core.SdkPackageUpdater.TryUpdateDependencyVersion(ImmutableArray`1 buildFiles, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Logger logger) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs:line 402
updater |    at NuGetUpdater.Core.SdkPackageUpdater.UpdateTopLevelDepdendency(String repoRootPath, ImmutableArray`1 buildFiles, String[] targetFrameworks, String dependencyName, String previousDependencyVersion, String newDependencyVersion, IDictionary`2 peerDependencies, Logger logger) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs:line 344
updater |    at NuGetUpdater.Core.SdkPackageUpdater.UpdateDependencyAsync(String repoRootPath, String projectPath, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Boolean isTransitive, Logger logger) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/SdkPackageUpdater.cs:line 44
updater |    at NuGetUpdater.Core.UpdaterWorker.RunUpdaterAsync(String repoRootPath, String projectPath, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Boolean isTransitive) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs:line 143
updater |    at NuGetUpdater.Core.UpdaterWorker.RunForProjectAsync(String repoRootPath, String projectPath, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Boolean isTransitive) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs:line 115
updater |    at NuGetUpdater.Core.UpdaterWorker.RunAsync(String repoRootPath, String workspacePath, String dependencyName, String previousDependencyVersion, String newDependencyVersion, Boolean isTransitive) in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Core/Updater/UpdaterWorker.cs:line 40
updater |    at NuGetUpdater.Cli.Commands.UpdateCommand.<>c__DisplayClass7_0.<<GetCommand>b__0>d.MoveNext() in /opt/nuget/lib/NuGetUpdater/NuGetUpdater.Cli/Commands/UpdateCommand.cs:line 37
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
updater |    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
updater | --- End of stack trace from previous location ---
updater |    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext():
```

</p>
</details>

**Comment by brettfo** [comment]
Could you share a repo/project or a log file that shows this error?

**Comment by abdulapopoola** [comment]
@a-jackson , a lot of improvements have been made to `nuget`, does this still repro for you? If not, can you please close this out? Thanks!
