### ISSUE TITLE
Error processing ubuntu (RuntimeError) (IMO, internal error)

### ISSUE THREAD

**Issue by claudioandre-br** [dependabot/dependabot-core#9834]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package ecosystem

Docker

### dependabot.yml content

---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /IDE/.devcontainer
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /cloud-tool
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /deploy/docker
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /CI/Dockerfiles
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /.clusterfuzzlite
    schedule:
      interval: "weekly"
      day: "sunday"

### Updated dependency

FROM ubuntu:24.04@sha256:3f85b7caad41a95462cf5b787d8a04604c8262cdcdf9a472b8c52ef83375fe15

To: whatever dependabot selects
- now it it sha256:3f85b7caad41a95462cf5b787d8a04604c8262cdcdf9a472b8c52ef83375fe15

Maybe there shouldn't be an error if there is no update. No wait, it doesn't fail for Fedora.

### What you expected to see, versus what you actually saw

I saw an internal error (Fedora works fine):
```
updater | 2024/05/23 07:03:42 INFO <job_832018320> Updating ubuntu from 24.04 to 24.04
updater | 2024/05/23 07:03:43 ERROR <job_832018320> Error processing ubuntu (RuntimeError)
updater | 2024/05/23 07:03:43 ERROR <job_832018320> No files changed!
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:43:in `updated_dependency_files'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:135:in `generate_dependency_files'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation_2_7.rb:919:in `bind_call'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation_2_7.rb:919:in `block in create_validator_method_medium0'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:68:in `run'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation_2_7.rb:59:in `bind_call'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation_2_7.rb:59:in `block in create_validator_method_fast0'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:42:in `create_from'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:167:in `bind_call'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:167:in `validate_call_skip_block_type'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11353/lib/types/private/methods/call_validation.rb:109:in `block in create_validator_slow_skip_block_type'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:132:in `check_and_create_pull_request'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:64:in `check_and_create_pr_with_error_handling'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:39:in `block in perform'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:39:in `each'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:39:in `perform'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:44:in `block in perform_job'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `block in with_span'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/context.rb:87:in `with_value'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `with_span'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:18:in `perform_job'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/05/23 07:03:43 ERROR <job_832018320> bin/update_files.rb:46:in `<main>'

```

Started two weeks ago:

```
Version update 826780281
Errored with the message "Dependabot encountered an unknown error"
No PRs affected 2 weeks ago 
[view logs](https://github.com/openwall/john-packages/network/updates/826780281)
```
```
Rebase update 826779933
Affected [#369 ](https://github.com/openwall/john-packages/pull/369)2 weeks ago 
[view logs](https://github.com/openwall/john-packages/network/updates/826779933)
```

**Comment by Smalls1652** [comment]
Seeing the same thing for a Kubernetes deployment YAML file for Redis going from `7.2.4-alpine` to `7.2.5-alpine`:

```
[...]
updater | 2024/06/25 00:53:12 INFO <job_846993282> Latest version is 7.2.5-alpine
updater | 2024/06/25 00:53:12 INFO <job_846993282> Requirements to unlock own
updater | 2024/06/25 00:53:12 INFO <job_846993282> Requirements update strategy 
updater | 2024/06/25 00:53:12 INFO <job_846993282> Updating library/redis from 7.2.4-alpine to 7.2.5-alpine
updater | 2024/06/25 00:53:12 ERROR <job_846993282> Error processing library/redis (RuntimeError)
updater | 2024/06/25 00:53:12 ERROR <job_846993282> Expected content to change!
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:167:in `updated_yaml_content'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:37:in `block in updated_dependency_files'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:31:in `each'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:31:in `updated_dependency_files'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:135:in `generate_dependency_files'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:68:in `run'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:42:in `create_from'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11415/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:132:in `check_and_create_pull_request'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:64:in `check_and_create_pr_with_error_handling'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:39:in `block in perform'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:39:in `each'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:39:in `perform'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:44:in `block in perform_job'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `block in with_span'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/context.rb:87:in `with_value'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace.rb:70:in `with_span'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.2.3/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:18:in `perform_job'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
updater | 2024/06/25 00:53:12 ERROR <job_846993282> bin/update_files.rb:46:in `<main>'
updater | 2024/06/25 00:53:12 INFO <job_846993282> Finished job processing
updater | 2024/06/25 00:53:12 INFO Results:
updater | Dependabot encountered '1' error(s) during execution, please check the logs for more details.
updater | +-------------------------------+
updater | | Dependencies failed to update |
updater | +---------------+---------------+
updater | | library/redis | unknown_error |
updater | +---------------+---------------+
updater | time="2024-06-25T00:53:12Z" level=info msg="task complete" container_id=job-846993282-updater exit_code=0 job_id=846993282 step=updater
```

**Comment by Smalls1652** [comment]
Mmmm strangely, in my case, changing the way I define images in my Kubernetes configs and Dockerfiles from including `docker.io` resolves it. So in my case I had two Kubernetes deployment `.yml` files that define images from Docker Hub:

* Changing from `docker.io/library/redis:7.2.4-alpine` to just `redis:7.2.4-alpine` successfully created a pull request.
* Changing from `docker.io/searxng/searxng:latest@sha256:867aa2f76602348296f8f416025ea87e53adb835391e0a6a115b3005e06a508e` to `searxng/searxng:latest@sha256:867aa2f76602348296f8f416025ea87e53adb835391e0a6a115b3005e06a508e` successfully created a pull request.

It didn't act that way before until fairly recently? I typically include `docker.io` in the image to help keep things consistent between the various different registries I'm pulling images from.

That being said... This isn't necessarily related to your issue @claudioandre-br. D: We just happened to get the same error message.

**Comment by fruch** [comment]
similar error happen to me as well:
https://github.com/scylladb/scylla-cluster-tests/actions/runs/12040015357/job/33569050808

I tried adding `docker.io`, it didn't helped

getting the exact traceback with this `Expected content to change!`

```
updater | 2024/11/26 22:23:52 ERROR <job_923209464> Error processing scylladb/hydra-loaders (RuntimeError)
2024/11/26 22:23:52 ERROR <job_923209464> Expected content to change!
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:167:in `updated_yaml_content'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
updater | 2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
updater | 2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:37:in `block in updated_dependency_files'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:31:in `each'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/docker/lib/dependabot/docker/file_updater.rb:31:in `updated_dependency_files'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:143:in `generate_dependency_files'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
updater | 2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:72:in `run'
updater | 2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/dependency_change_builder.rb:44:in `create_from'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:170:in `check_and_create_pull_request'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:94:in `check_and_create_pr_with_error_handling'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `block in perform'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `each'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/update_all_versions.rb:59:in `perform'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:137:in `block in run_ungrouped_dependency_updates'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:122:in `each'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:122:in `run_ungrouped_dependency_updates'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/updater/operations/group_update_all_versions.rb:[65](https://github.com/scylladb/scylla-cluster-tests/runs/33438371969?check_suite_focus=true#step:3:67):in `perform'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `bind_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/call_validation.rb:270:in `validate_call'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/sorbet-runtime-0.5.11577/lib/types/private/methods/_methods.rb:277:in `block in _on_method_added'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/updater.rb:45:in `run'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:44:in `block in perform_job'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.4.0/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.4.0/lib/opentelemetry/trace.rb:[70](https://github.com/scylladb/scylla-cluster-tests/runs/33438371969?check_suite_focus=true#step:3:72):in `block in with_span'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.4.0/lib/opentelemetry/context.rb:87:in `with_value'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.4.0/lib/opentelemetry/trace.rb:70:in `with_span'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/vendor/ruby/3.3.0/gems/opentelemetry-api-1.4.0/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/update_files_command.rb:18:in `perform_job'
2024/11/26 22:23:52 ERROR <job_923209464> /home/dependabot/dependabot-updater/lib/dependabot/base_command.rb:37:in `run'
2024/11/26 22:23:52 ERROR <job_923209464> bin/update_files.rb:46:in `<main>'
```
